Repository lobehub/lobe-chat, pull requests merged in 2024-09, with the labels that each got.

#3704 💄 style: add `*_MODEL_LIST` for Qwen and ZeroOne
  Dockerfile
  Dockerfile.database
  src/config/llm.ts
  src/server/globalConfig/index.ts
Labels: 💄 Design, size:M

#3705 💄 style: update Claude 3.5 Sonnet `maxOutput` vaule
  src/config/modelProviders/anthropic.ts
Labels: 💄 Design, size:XS

#3696 💄 style: fix model info
  src/config/modelProviders/qwen.ts
  src/config/modelProviders/stepfun.ts
Labels: 💄 Design, size:M

#3715 💄 style: update Novita AI model info & add `NOVITA_MODEL_LIST` support
  Dockerfile
  Dockerfile.database
  src/config/llm.ts
  src/config/modelProviders/novita.ts
  src/server/globalConfig/index.ts
Labels: 💄 Design, size:M

#3713 💄 style: update Together AI model list
  src/config/modelProviders/togetherai.ts
  src/libs/agent-runtime/togetherai/__snapshots__/index.test.ts.snap
Labels: 🐛 Bug, 💄 Design, size:L

#3716 💄 style: update Groq model list & add `GROQ_MODEL_LIST` support
  Dockerfile
  Dockerfile.database
  src/config/llm.ts
  src/config/modelProviders/groq.ts
  src/server/globalConfig/index.ts
Labels: 💄 Design, size:M

#3712 💄 style: Stepfun default enabled model
  src/config/modelProviders/stepfun.ts
Labels: 💄 Design, size:XS

#3719 📝 docs: Fix typo
  docs/self-hosting/server-database/docker-compose.mdx
  docs/self-hosting/server-database/docker-compose.zh-CN.mdx
Labels: 📝 Documentation, size:XS

#3743 💄 style: fix provider disabled title style
  src/app/(main)/settings/llm/components/ProviderConfig/index.tsx
Labels: 💄 Design, size:XS, lgtm

#3751 🐛 fix: fix speed and rag prompt
  .i18nrc.js
  src/chains/answerWithContext.ts
  src/services/upload.ts
  src/types/files/upload.ts
Labels: 🐛 Bug, size:S

#3754 ⚡️ perf: 优化长文本时的渲染性能
  src/app/(main)/profile/[[...slugs]]/Client.tsx
  src/app/webapi/tokenizer/index.test.ts
  src/app/webapi/tokenizer/route.ts
  src/database/server/models/session.ts
  src/hooks/useTokenCount.ts
  src/layout/AuthProvider/Clerk/useAppearance.ts
  src/server/context.ts
  src/server/routers/edge/index.ts
  src/services/user/client.ts
  src/types/worker.d.ts
  src/utils/fetch/__tests__/fetchSSE.test.ts
  src/utils/fetch/fetchSSE.ts
  src/utils/tokenizer.ts
  src/utils/tokenizer/client.ts
  src/utils/tokenizer/index.ts
  src/utils/tokenizer/server.ts
  src/utils/tokenizer/tokenizer.worker.ts
Labels: ⚡️ Performance, size:L

#3758 ⚡️ perf: improve stream smoothing
  src/utils/fetch/__tests__/fetchSSE.test.ts
  src/utils/fetch/fetchSSE.ts
Labels: ⚡️ Performance, size:M

#3767 💄 style: Update Stepfun models
  src/config/modelProviders/stepfun.ts
Labels: 💄 Design, size:XS

#3764 🐛 fix: fix typo in RAG prompt
  src/chains/answerWithContext.ts
Labels: 🐛 Bug, size:XS, lgtm

#3784 🔧 build: remove optimizePackageImports for shiki
  next.config.mjs
Labels: size:XS

#3787 ⚡️ perf: disable smoohting by default in `fetchSSE`
  src/config/modelProviders/google.ts
  src/services/chat.ts
  src/types/llm.ts
  src/utils/fetch/__tests__/fetchSSE.test.ts
  src/utils/fetch/fetchSSE.ts
Labels: ⚡️ Performance, size:M

#3769 💄 style: add `LLaVA 1.5 7B` model in Groq
  src/config/modelProviders/groq.ts
Labels: 💄 Design, size:XS

#3772 📝 docs: Update `server-database/repocloud`
  docs/self-hosting/server-database/repocloud.mdx
Labels: 📝 Documentation, size:S

#3797 📝docs: correct typo in 'openai api key' in .env example and documentation
  docker-compose/local/.env.example
  docker-compose/local/.env.zh-CN.example
  docker-compose/production/.env.example
  docker-compose/production/.env.zh-CN.example
  docs/self-hosting/server-database/docker-compose.mdx
  docs/self-hosting/server-database/docker-compose.zh-CN.mdx
  docs/self-hosting/server-database/docker.mdx
  docs/self-hosting/server-database/docker.zh-CN.mdx
Labels: 📝 Documentation, size:S, lgtm

#3795 🐛 fix: fix auth log
  src/libs/trpc/middleware/userAuth.ts
Labels: 🐛 Bug, size:XS

#3798 💄 style: support anthropic browser request
  package.json
  src/config/modelProviders/anthropic.ts
  src/libs/agent-runtime/anthropic/index.ts
  src/services/chat.ts
Labels: 💄 Design, size:XS

#3820 ⚡️ perf: fix large content render
  locales/ar/chat.json
  locales/ar/portal.json
  locales/bg-BG/chat.json
  locales/bg-BG/portal.json
  locales/de-DE/chat.json
  locales/de-DE/portal.json
  locales/en-US/chat.json
  locales/en-US/portal.json
  locales/es-ES/chat.json
  locales/es-ES/portal.json
  locales/fr-FR/chat.json
  locales/fr-FR/portal.json
  locales/it-IT/chat.json
  locales/it-IT/portal.json
  locales/ja-JP/chat.json
  locales/ja-JP/portal.json
  locales/ko-KR/chat.json
  locales/ko-KR/portal.json
  locales/nl-NL/chat.json
  locales/nl-NL/portal.json
  locales/pl-PL/chat.json
  locales/pl-PL/portal.json
  locales/pt-BR/chat.json
  locales/pt-BR/portal.json
  locales/ru-RU/chat.json
  locales/ru-RU/portal.json
  locales/tr-TR/chat.json
  locales/tr-TR/portal.json
  locales/vi-VN/chat.json
  locales/vi-VN/portal.json
  locales/zh-CN/chat.json
  locales/zh-CN/portal.json
  locales/zh-TW/chat.json
  locales/zh-TW/portal.json
  package.json
  src/app/(main)/chat/(workspace)/@portal/MessageDetail/Body/index.tsx
  src/app/(main)/chat/(workspace)/@portal/MessageDetail/Header.tsx
  src/app/(main)/chat/(workspace)/@portal/MessageDetail/index.ts
  src/app/(main)/chat/(workspace)/@portal/MessageDetail/useEnable.ts
  src/app/(main)/chat/(workspace)/@portal/router.tsx
  src/features/Conversation/Messages/User/MarkdownRender/ContentPreview.tsx
  src/features/Conversation/Messages/User/MarkdownRender/index.tsx
  src/features/Conversation/Messages/User/index.tsx
  src/features/Conversation/Messages/index.ts
  src/features/Conversation/components/ChatItem/index.tsx
  src/features/Conversation/types/index.tsx
  src/locales/default/chat.ts
  src/locales/default/portal.ts
  src/services/chat.ts
  src/store/chat/slices/portal/action.ts
  src/store/chat/slices/portal/initialState.ts
  src/store/chat/slices/portal/selectors.ts
  src/utils/tokenizer/tokenizer.worker.ts
Labels: ⚡️ Performance, size:M

#3824 ⚡️ perf: fix scrolling laggy in some chat list
  src/features/Conversation/components/VirtualizedList/index.tsx
Labels: ⚡️ Performance, size:XS

#3829 📝 docs: fix db name in docker
  docker-compose/production/.env.example
  docker-compose/production/.env.zh-CN.example
  docs/self-hosting/server-database/docker-compose.mdx
  docs/self-hosting/server-database/docker-compose.zh-CN.mdx
Labels: 🐛 Bug, size:XS

#3355 ♻️ refactor: temperature should from 0 to 2
  src/const/settings/agent.ts
  src/database/client/schemas/session.ts
  src/features/AgentSetting/AgentModal/index.tsx
  src/features/ChatInput/ActionBar/Temperature.tsx
  src/libs/agent-runtime/anthropic/index.test.ts
  src/libs/agent-runtime/anthropic/index.ts
  src/libs/agent-runtime/bedrock/index.test.ts
  src/libs/agent-runtime/bedrock/index.ts
  src/libs/agent-runtime/groq/index.test.ts
  src/libs/agent-runtime/groq/index.ts
  src/libs/agent-runtime/minimax/index.test.ts
  src/libs/agent-runtime/minimax/index.ts
  src/libs/agent-runtime/mistral/index.test.ts
  src/libs/agent-runtime/mistral/index.ts
  src/libs/agent-runtime/moonshot/index.ts
  src/libs/agent-runtime/ollama/index.test.ts
  src/libs/agent-runtime/ollama/index.ts
  src/libs/agent-runtime/perplexity/index.test.ts
  src/libs/agent-runtime/perplexity/index.ts
  src/libs/agent-runtime/qwen/index.test.ts
  src/libs/agent-runtime/qwen/index.ts
  src/libs/agent-runtime/taichu/index.test.ts
  src/libs/agent-runtime/taichu/index.ts
  src/libs/agent-runtime/types/chat.ts
  src/store/user/slices/settings/selectors/__snapshots__/settings.test.ts.snap
  src/types/llm.ts
  src/types/openai/chat.ts
Labels: size:L

#3757 💄 style: Update model display name & Remove Qwen preview model
  src/config/modelProviders/deepseek.ts
  src/config/modelProviders/novita.ts
  src/config/modelProviders/ollama.ts
  src/config/modelProviders/perplexity.ts
  src/config/modelProviders/qwen.ts
  src/config/modelProviders/siliconcloud.ts
  src/config/modelProviders/stepfun.ts
Labels: 💄 Design, size:L

#3831 ⚡️ perf: improving scrolling laggy
  src/features/Conversation/components/VirtualizedList/index.tsx
Labels: ⚡️ Performance, size:XS

#3833 💄 style：improve groq model tokens
  src/config/modelProviders/groq.ts
Labels: 💄 Design, size:XS, lgtm

#3841 💄 style: fix title in setting
  src/app/(main)/settings/about/features/Version.tsx
Labels: 💄 Design, size:XS

#3837 👷 build: fix DNS resolving issue in Docker
  Dockerfile
  Dockerfile.database
Labels: 🐛 Bug, size:S

#3836 💄 style: update perplexity model list
  src/config/modelProviders/perplexity.ts
Labels: 💄 Design, size:S

#3865 💄 style: add siliconcloud new model
  src/config/modelProviders/siliconcloud.ts
Labels: 💄 Design, size:S

#3356 🐛 fix: Update baichuan param
  src/libs/agent-runtime/baichuan/index.ts
Labels: size:S

#3370 🐛 fix: Gemini cannot input images when server database is enabled
  src/libs/agent-runtime/google/index.test.ts
  src/libs/agent-runtime/google/index.ts
  src/utils/imageToBase64.ts
Labels: size:L

#3870 🐛 fix: fix claude 3.5 image with s3 url
  src/libs/agent-runtime/anthropic/index.ts
  src/libs/agent-runtime/bedrock/index.ts
  src/libs/agent-runtime/utils/anthropicHelpers.test.ts
  src/libs/agent-runtime/utils/anthropicHelpers.ts
  src/utils/imageToBase64.test.ts
Labels: 🐛 Bug, size:L

#3871 🐛 fix: Baichuan should not introduce freequency_penality parameters
  src/libs/agent-runtime/baichuan/index.ts
Labels: 🐛 Bug, size:XS

#3872 🐛 fix: fix tools calling in some edge cases
  src/libs/agent-runtime/utils/streams/openai.test.ts
  src/libs/agent-runtime/utils/streams/openai.ts
Labels: 🐛 Bug, size:L

#3880 🐛 fix: `/etc/resolv.conf`edit permission
  Dockerfile
  Dockerfile.database
Labels: 🐛 Bug, size:XS

#3883 ♻️ refactor: change empty content stream behavior
  src/libs/agent-runtime/utils/streams/openai.test.ts
  src/libs/agent-runtime/utils/streams/openai.ts
Labels: size:M

#3098 ✨ feat: Add Spark model provider
  Dockerfile
  Dockerfile.database
  src/app/(main)/settings/llm/ProviderList/providers.tsx
  src/app/api/chat/agentRuntime.ts
  src/config/llm.ts
  src/config/modelProviders/index.ts
  src/config/modelProviders/spark.ts
  src/const/settings/llm.ts
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/spark/index.test.ts
  src/libs/agent-runtime/spark/index.ts
  src/libs/agent-runtime/types/type.ts
  src/server/globalConfig/index.ts
  src/types/user/settings/keyVaults.ts
Labels: size:L

#3392 ✨ feat: Add Fireworks AI Model Provider
  Dockerfile
  Dockerfile.database
  src/app/(main)/settings/llm/ProviderList/providers.tsx
  src/app/api/chat/agentRuntime.ts
  src/config/llm.ts
  src/config/modelProviders/fireworksai.ts
  src/config/modelProviders/index.ts
  src/const/settings/llm.ts
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/fireworksai/index.test.ts
  src/libs/agent-runtime/fireworksai/index.ts
  src/libs/agent-runtime/types/type.ts
  src/libs/agent-runtime/utils/streams/openai.test.ts
  src/libs/agent-runtime/utils/streams/openai.ts
  src/server/globalConfig/index.ts
  src/types/user/settings/keyVaults.ts
Labels: size:L

#3886 💄 style: Reorder the provider list
  src/app/(main)/settings/llm/ProviderList/providers.tsx
  src/config/modelProviders/index.ts
Labels: 💄 Design, size:M

#3885 💄 style: update spark check model to spark-lite & default disable useless model
  src/config/modelProviders/baichuan.ts
  src/config/modelProviders/minimax.ts
  src/config/modelProviders/spark.ts
Labels: 💄 Design, size:XS

#3890 💄 style: update Upstage model list
  src/config/modelProviders/upstage.ts
Labels: 💄 Design, size:S

#3887 🐛 fix: add `LLM_VISION_IMAGE_USE_BASE64` to support local s3 in vision model
  src/config/modelProviders/stepfun.ts
  src/libs/agent-runtime/google/index.test.ts
  src/libs/agent-runtime/google/index.ts
  src/libs/agent-runtime/utils/anthropicHelpers.test.ts
  src/libs/agent-runtime/utils/anthropicHelpers.ts
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.test.ts
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
  src/libs/agent-runtime/utils/openaiHelpers.test.ts
  src/libs/agent-runtime/utils/openaiHelpers.ts
  src/libs/agent-runtime/zhipu/index.ts
  src/utils/imageToBase64.test.ts
  src/utils/imageToBase64.ts
Labels: 🐛 Bug, vision, size:L

#3894 📝 docs: fix logto document
  docs/self-hosting/advanced/auth/next-auth/logto.zh-CN.mdx
Labels: 📝 Documentation, size:XS, lgtm

#3900 ⚡️ perf: add smoothing for some providers
  src/config/modelProviders/ai360.ts
  src/config/modelProviders/baichuan.ts
  src/config/modelProviders/minimax.ts
  src/config/modelProviders/moonshot.ts
  src/config/modelProviders/qwen.ts
  src/config/modelProviders/spark.ts
  src/config/modelProviders/stepfun.ts
Labels: ⚡️ Performance, size:S

#3905 🐛 fix: pin `next@14.2.8` to avoid 500 error
  package.json
Labels: 🐛 Bug, size:XS

#3697 💄 style: Optimize model token display method
  src/components/ModelSelect/index.tsx
  src/utils/format.test.ts
  src/utils/format.ts
Labels: 💄 Design, size:M

#3911 💄 style: improve models and add more info for providers and models
  src/config/modelProviders/ai360.ts
  src/config/modelProviders/anthropic.ts
  src/config/modelProviders/baichuan.ts
  src/config/modelProviders/bedrock.ts
  src/config/modelProviders/deepseek.ts
  src/config/modelProviders/fireworksai.ts
  src/config/modelProviders/google.ts
  src/config/modelProviders/groq.ts
  src/config/modelProviders/minimax.ts
  src/config/modelProviders/openai.ts
  src/const/discover.ts
  src/libs/agent-runtime/openai/__snapshots__/index.test.ts.snap
  src/server/routers/edge/config/__snapshots__/index.test.ts.snap
  src/server/routers/edge/config/index.test.ts
  src/types/llm.ts
  src/utils/parseModels.test.ts
Labels: Model Provider, size:XL

#3918 💄style: update claude model list sort and update groq model info
  src/config/modelProviders/anthropic.ts
  src/config/modelProviders/groq.ts
Labels: 💄 Design, size:M

#3920 💄 style: Add model and provider desc and url
  src/config/modelProviders/ai360.ts
  src/config/modelProviders/anthropic.ts
  src/config/modelProviders/azure.ts
  src/config/modelProviders/baichuan.ts
  src/config/modelProviders/bedrock.ts
  src/config/modelProviders/deepseek.ts
  src/config/modelProviders/fireworksai.ts
  src/config/modelProviders/google.ts
  src/config/modelProviders/groq.ts
  src/config/modelProviders/minimax.ts
  src/config/modelProviders/mistral.ts
  src/config/modelProviders/moonshot.ts
  src/config/modelProviders/novita.ts
  src/config/modelProviders/ollama.ts
  src/config/modelProviders/openai.ts
  src/config/modelProviders/openrouter.ts
  src/config/modelProviders/perplexity.ts
  src/config/modelProviders/qwen.ts
  src/config/modelProviders/siliconcloud.ts
  src/config/modelProviders/spark.ts
  src/config/modelProviders/stepfun.ts
  src/config/modelProviders/taichu.ts
  src/config/modelProviders/togetherai.ts
  src/config/modelProviders/upstage.ts
  src/config/modelProviders/zeroone.ts
  src/config/modelProviders/zhipu.ts
  src/types/llm.ts
Labels: size:XL

#3924 ✅ test: Update test for new provider info
  src/libs/agent-runtime/openai/__snapshots__/index.test.ts.snap
  src/migrations/FromV3ToV4/fixtures/ollama-output-v4.json
  src/server/routers/edge/config/__snapshots__/index.test.ts.snap
  src/server/routers/edge/config/index.test.ts
  src/store/user/slices/modelList/__snapshots__/action.test.ts.snap
  src/store/user/slices/modelList/action.test.ts
  src/utils/__snapshots__/parseModels.test.ts.snap
  src/utils/parseModels.test.ts
Labels: size:M

#3701 ♻️ refactor: Support Environment Variable Inference For NextAuth
  package.json
  src/config/__tests__/auth.test.ts
  src/config/auth.ts
  src/libs/next-auth/auth.config.ts
  src/libs/next-auth/sso-providers/auth0.ts
  src/libs/next-auth/sso-providers/authelia.ts
  src/libs/next-auth/sso-providers/authentik.ts
  src/libs/next-auth/sso-providers/azure-ad.ts
  src/libs/next-auth/sso-providers/cloudflare-zero-trust.ts
  src/libs/next-auth/sso-providers/generic-oidc.ts
  src/libs/next-auth/sso-providers/github.ts
  src/libs/next-auth/sso-providers/logto.ts
  src/libs/next-auth/sso-providers/zitadel.ts
Labels: size:L, lgtm

#3922 💄 style: default disable mistral provider useless models
  src/config/modelProviders/bedrock.ts
  src/config/modelProviders/mistral.ts
Labels: 💄 Design, size:M

#3774 🐛 fix: support webhooks for logto
  src/app/api/webhooks/logto/__tests__/route.test.ts
  src/app/api/webhooks/logto/route.ts
  src/app/api/webhooks/logto/validateRequest.ts
  src/config/auth.ts
  src/server/services/nextAuthUser/index.ts
Labels: 🌠 Feature Request, size:L

#3854 💄 style: Add sessionToken input for bedrock model
  docs/self-hosting/advanced/auth/next-auth/logto.zh-CN.mdx
  locales/ar/modelProvider.json
  locales/bg-BG/modelProvider.json
  locales/de-DE/modelProvider.json
  locales/en-US/modelProvider.json
  locales/es-ES/modelProvider.json
  locales/fr-FR/modelProvider.json
  locales/it-IT/modelProvider.json
  locales/ja-JP/modelProvider.json
  locales/ko-KR/modelProvider.json
  locales/nl-NL/modelProvider.json
  locales/pl-PL/modelProvider.json
  locales/pt-BR/modelProvider.json
  locales/ru-RU/modelProvider.json
  locales/tr-TR/modelProvider.json
  locales/vi-VN/modelProvider.json
  locales/zh-CN/modelProvider.json
  locales/zh-TW/modelProvider.json
  src/app/(main)/settings/llm/ProviderList/Bedrock/index.tsx
  src/app/api/chat/agentRuntime.test.ts
  src/app/api/chat/agentRuntime.ts
  src/config/llm.ts
  src/const/auth.ts
  src/features/Conversation/Error/APIKeyForm/Bedrock.tsx
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/baichuan/index.ts
  src/libs/agent-runtime/bedrock/index.ts
  src/libs/agent-runtime/qwen/index.test.ts
  src/libs/agent-runtime/qwen/index.ts
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
  src/locales/default/modelProvider.ts
  src/server/globalConfig/index.ts
  src/services/_auth.ts
  src/services/chat.ts
  src/types/user/settings/keyVaults.ts
  src/utils/format.ts
Labels: 🌠 Feature Request, size:L

#3927 💄 style: Remove brackets from model names with dates in OpenAI
  src/config/modelProviders/openai.ts
  src/libs/agent-runtime/openai/__snapshots__/index.test.ts.snap
  src/server/routers/edge/config/__snapshots__/index.test.ts.snap
Labels: 💄 Design, size:S

#3935 💄 style: Update siliconcloud model
  src/config/modelProviders/siliconcloud.ts
Labels: 💄 Design, size:S

#3465 💄 style(model): remove `OpenAI` deprecated model
  docs/usage/agents/model.mdx
  docs/usage/agents/model.zh-CN.mdx
  src/config/modelProviders/openai.ts
  src/libs/agent-runtime/openai/__snapshots__/index.test.ts.snap
  src/server/routers/edge/config/__snapshots__/index.test.ts.snap
  src/server/routers/edge/config/index.test.ts
Labels: size:M, lgtm

#3943 ✨ feat: support openai new OpenAI o1/o1-mini model
  src/config/modelProviders/openai.ts
  src/libs/agent-runtime/openai/index.ts
  src/store/user/slices/modelList/selectors/modelProvider.test.ts
Labels: 🌠 Feature Request, released, size:M

#3938 💄 style: Support Google Model List
  src/config/llm.ts
  src/server/globalConfig/index.ts
Labels: 💄 Design, size:S, lgtm

#3947 📝 docs: update deploy lobechat-database on zeabur
  README.md
  README.zh-CN.md
  docs/self-hosting/server-database/zeabur.mdx
  docs/self-hosting/server-database/zeabur.zh-CN.mdx
Labels: 📝 Documentation, size:L

#3949 💄 style: update zhipu model info
  src/config/modelProviders/zhipu.ts
Labels: 💄 Design, size:M

#3954 💄 style: update openrouter model list
  src/config/modelProviders/openrouter.ts
  src/server/routers/edge/config/__snapshots__/index.test.ts.snap
  src/server/routers/edge/config/index.test.ts
Labels: 💄 Design, size:L

#3957 🐛 fix: fix o1 model list
  package.json
  src/libs/agent-runtime/openai/index.ts
Labels: 🐛 Bug, size:S

#3958 💄 style: delete "-" in deepseek displayname
  src/config/modelProviders/deepseek.ts
  src/config/modelProviders/openrouter.ts
Labels: 💄 Design, size:XS, lgtm

#3948 💄 style: Update fullscreen loading style
  src/components/FullscreenLoading/index.tsx
Labels: 💄 Design, size:S

#3984 💄 style: Add MiniCPM-V 8B model entries to Ollama model providers
  src/config/modelProviders/ollama.ts
Labels: 🌠 Feature Request, size:S, lgtm

#3986 ♻️ refactor: rename artifacts to plugins in portal
  src/app/(main)/chat/(workspace)/@portal/Plugins/Body/ToolRender.tsx
  src/app/(main)/chat/(workspace)/@portal/Plugins/Body/index.tsx
  src/app/(main)/chat/(workspace)/@portal/Plugins/Footer.tsx
  src/app/(main)/chat/(workspace)/@portal/Plugins/Header.tsx
  src/app/(main)/chat/(workspace)/@portal/Plugins/index.ts
  src/app/(main)/chat/(workspace)/@portal/Plugins/useEnable.ts
  src/app/(main)/chat/(workspace)/@portal/router.tsx
  src/features/Conversation/Messages/Tool/Inspector/index.tsx
Labels: size:S

#3989 💄 style: Delete duplicate models in ollama
  src/config/modelProviders/ollama.ts
Labels: 💄 Design, size:XS

#3955 🐛 fix: fix a corner case of `tools_call` with empty object
  src/libs/agent-runtime/utils/streams/openai.test.ts
  src/libs/agent-runtime/utils/streams/openai.ts
Labels: 🐛 Bug, size:M, lgtm

#4008 👷 build: fix docker build
  .dockerignore
Labels: size:XS

#4011 🐛 fix: Fix InterceptingRoutes in discover
  package.json
  src/app/(main)/discover/(detail)/assistant/[slug]/features/InfoSidebar/index.tsx
  src/app/(main)/discover/(detail)/features/Back.tsx
  src/app/(main)/discover/(detail)/features/DetailLayout.tsx
  src/app/(main)/discover/(detail)/model/[...slugs]/features/InfoSidebar/index.tsx
  src/app/(main)/discover/(detail)/model/[...slugs]/features/ProviderList/ProviderItem.tsx
  src/app/(main)/discover/(detail)/plugin/[slug]/features/InfoSidebar/index.tsx
  src/app/(main)/discover/(detail)/provider/[slug]/features/InfoSidebar/index.tsx
  src/app/(main)/discover/(detail)/provider/[slug]/features/ModelList/ModelItem.tsx
  src/app/(main)/discover/(list)/(home)/features/AssistantList.tsx
  src/app/(main)/discover/(list)/(home)/features/ModelList.tsx
  src/app/(main)/discover/(list)/(home)/features/PluginList.tsx
  src/app/(main)/discover/(list)/assistants/features/List.tsx
  src/app/(main)/discover/(list)/models/features/List.tsx
  src/app/(main)/discover/(list)/plugins/features/List.tsx
  src/app/(main)/discover/(list)/providers/features/List.tsx
  src/app/(main)/discover/_layout/Desktop/index.tsx
  src/app/(main)/discover/_layout/Mobile/index.tsx
  src/app/@modal/(.)discover/assistant/[slug]/page.tsx
  src/app/@modal/(.)discover/layout.tsx
  src/app/@modal/(.)discover/loading.tsx
  src/app/@modal/(.)discover/model/[...slugs]/page.tsx
  src/app/@modal/(.)discover/plugin/[slug]/page.tsx
  src/app/@modal/(.)discover/provider/[slug]/page.tsx
  src/app/layout.tsx
  src/app/redirect/page.tsx
  src/components/InterceptingLink/index.tsx
  src/components/NProgress/index.tsx
  src/features/Conversation/components/InboxWelcome/AgentsSuggest.tsx
  src/hooks/useInterceptingRoutes.ts
Labels: 🐛 Bug, size:L

#3835 💄 style: improve open router tools calling metadata
  src/libs/agent-runtime/openrouter/__snapshots__/index.test.ts.snap
  src/libs/agent-runtime/openrouter/fixtures/models.json
  src/libs/agent-runtime/openrouter/index.ts
Labels: 🐛 Bug, 💄 Design, size:XS

#3869 ✨ feat: add Github Models provider
  locales/ar/error.json
  locales/ar/modelProvider.json
  locales/bg-BG/error.json
  locales/bg-BG/modelProvider.json
  locales/de-DE/error.json
  locales/de-DE/modelProvider.json
  locales/en-US/error.json
  locales/en-US/modelProvider.json
  locales/es-ES/error.json
  locales/es-ES/modelProvider.json
  locales/fr-FR/error.json
  locales/fr-FR/modelProvider.json
  locales/it-IT/error.json
  locales/it-IT/modelProvider.json
  locales/ja-JP/error.json
  locales/ja-JP/modelProvider.json
  locales/ko-KR/error.json
  locales/ko-KR/modelProvider.json
  locales/nl-NL/error.json
  locales/nl-NL/modelProvider.json
  locales/pl-PL/error.json
  locales/pl-PL/modelProvider.json
  locales/pt-BR/error.json
  locales/pt-BR/modelProvider.json
  locales/ru-RU/error.json
  locales/ru-RU/modelProvider.json
  locales/tr-TR/error.json
  locales/tr-TR/modelProvider.json
  locales/vi-VN/error.json
  locales/vi-VN/modelProvider.json
  locales/zh-CN/error.json
  locales/zh-CN/modelProvider.json
  locales/zh-TW/error.json
  locales/zh-TW/modelProvider.json
  src/app/(main)/settings/llm/ProviderList/Github/index.tsx
  src/app/(main)/settings/llm/ProviderList/providers.tsx
  src/app/api/chat/agentRuntime.ts
  src/config/llm.ts
  src/config/modelProviders/github.ts
  src/config/modelProviders/index.ts
  src/const/settings/llm.ts
  src/features/Conversation/Error/APIKeyForm/index.tsx
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/error.ts
  src/libs/agent-runtime/github/index.test.ts
  src/libs/agent-runtime/github/index.ts
  src/libs/agent-runtime/openrouter/__snapshots__/index.test.ts.snap
  src/libs/agent-runtime/types/type.ts
  src/locales/default/error.ts
  src/locales/default/modelProvider.ts
  src/server/globalConfig/index.ts
  src/types/user/settings/keyVaults.ts
Labels: Model Provider, size:L

#3727 ✨ feat: add Ai21Labs model provider
  Dockerfile
  Dockerfile.database
  src/app/(main)/settings/llm/ProviderList/providers.tsx
  src/app/api/chat/agentRuntime.ts
  src/config/llm.ts
  src/config/modelProviders/ai21.ts
  src/config/modelProviders/index.ts
  src/const/settings/llm.ts
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/ai21/index.test.ts
  src/libs/agent-runtime/ai21/index.ts
  src/libs/agent-runtime/types/type.ts
  src/server/globalConfig/index.ts
  src/types/user/settings/keyVaults.ts
Labels: 🌠 Feature Request, Model Provider, size:L

#4014 💄 style: add mistral provider new models
  src/config/modelProviders/mistral.ts
  src/config/modelProviders/upstage.ts
Labels: 💄 Design, size:M

#4020 💄 style: updata qwen model info & add qwen2.5 & reorder provider list
  src/app/(main)/settings/llm/ProviderList/providers.tsx
  src/config/modelProviders/index.ts
  src/config/modelProviders/qwen.ts
Labels: 💄 Design, size:M

#3926 👷 build: change base image from `musl` to `glibc`
  Dockerfile
  Dockerfile.database
Labels: size:M

#4012 ♻️ refactor: refactor the sitemap implement
  .gitignore
  next-sitemap.config.mjs
  next.config.mjs
  package.json
  scripts/buildSitemapIndex/index.ts
  src/app/(main)/discover/(detail)/assistant/[slug]/page.tsx
  src/app/(main)/discover/(detail)/model/[...slugs]/features/ProviderList/ProviderItem.tsx
  src/app/(main)/discover/(detail)/model/[...slugs]/page.tsx
  src/app/(main)/discover/(detail)/plugin/[slug]/page.tsx
  src/app/(main)/discover/(detail)/provider/[slug]/features/ModelList/ModelItem.tsx
  src/app/(main)/discover/(detail)/provider/[slug]/page.tsx
  src/app/(main)/discover/(list)/_layout/Desktop/Nav.tsx
  src/app/(main)/discover/_layout/Desktop/index.tsx
  src/app/page.tsx
  src/app/robots.tsx
  src/app/sitemap.tsx
  src/const/url.ts
  src/server/ld.test.ts
  src/server/ld.ts
  src/server/metadata.test.ts
  src/server/metadata.ts
  src/server/modules/AssistantStore/index.test.ts
  src/server/modules/AssistantStore/index.ts
  src/server/sitemap.test.ts
  src/server/sitemap.ts
  src/server/translation.test.ts
  src/server/utils/url.test.ts
  src/server/utils/url.ts
Labels: 🌠 Feature Request, size:XXL, lgtm

#4022 💄 style: enable functioncall for stepfun models
  src/config/modelProviders/stepfun.ts
Labels: 💄 Design, size:XS

#4026 💄 style: Update qwen models
  src/config/modelProviders/qwen.ts
Labels: 💄 Design, size:L

#4030 ♻️ refactor: refactor the tts route url
  src/app/api/openai/createBizOpenAI/index.ts
  src/app/webapi/stt/openai/route.ts
  src/app/webapi/tts/edge/route.ts
  src/app/webapi/tts/microsoft/route.ts
  src/app/webapi/tts/openai/route.ts
  src/const/fetch.ts
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/BaseAI.ts
  src/libs/agent-runtime/types/index.ts
  src/libs/agent-runtime/types/tts.ts
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
  src/services/_header.ts
  src/services/_url.ts
  src/store/file/slices/tts/action.ts
  src/store/file/slices/upload/action.ts
Labels: tts, size:M

#4024 💄 style: add siliconflow qwen2.5 model
  src/config/modelProviders/qwen.ts
  src/config/modelProviders/siliconcloud.ts
Labels: 💄 Design, size:L

#4033 💄 style: delete siliconflow outdated model & disable stepfun functioncall
  src/config/modelProviders/qwen.ts
  src/config/modelProviders/siliconcloud.ts
  src/config/modelProviders/stepfun.ts
Labels: 💄 Design, size:L

#4034 🐛 fix: fix a bug with server agent config when user not exist
  src/app/api/webhooks/clerk/route.ts
  src/server/routers/lambda/agent.ts
  src/server/services/user/index.ts
Labels: 🐛 Bug, size:XS

#4043 💄 style: add qwen2.5 math and coder model for siliconcloud provider
  src/config/modelProviders/siliconcloud.ts
Labels: 💄 Design, size:S

#4038 :bug: fix: custom model initialization not taking effect error
  src/server/globalConfig/index.ts
Labels: 🐛 Bug, size:XS, lgtm

#3942 💄 style: Support webhooks for casdoor
  src/app/api/webhooks/casdoor/__tests__/route.test.ts
  src/app/api/webhooks/casdoor/route.ts
  src/app/api/webhooks/casdoor/validateRequest.ts
  src/config/auth.ts
  src/libs/next-auth/sso-providers/casdoor.ts
  src/libs/next-auth/sso-providers/index.ts
Labels: 🌠 Feature Request, size:L

#4044 🐛 fix: try to implement better ssrf-protect
  package.json
  src/app/api/proxy/route.ts
  src/app/webapi/proxy/route.ts
  src/server/routers/lambda/user.ts
  src/services/_url.ts
  src/services/user/client.ts
Labels: 🐛 Bug, size:M

#4047 🐛 fix: pin `shiki@1.17.7` to fix code highlight
  package.json
Labels: 🐛 Bug, size:XS

#4049 💄 style: improve i18n in discover
  locales/ar/models.json
  locales/ar/providers.json
  locales/bg-BG/models.json
  locales/bg-BG/providers.json
  locales/de-DE/models.json
  locales/de-DE/providers.json
  locales/en-US/models.json
  locales/en-US/providers.json
  locales/es-ES/models.json
  locales/es-ES/providers.json
  locales/fr-FR/models.json
  locales/fr-FR/providers.json
  locales/it-IT/models.json
  locales/it-IT/providers.json
  locales/ja-JP/models.json
  locales/ja-JP/providers.json
  locales/ko-KR/models.json
  locales/ko-KR/providers.json
  locales/nl-NL/models.json
  locales/pl-PL/models.json
  locales/pt-BR/models.json
  locales/pt-BR/providers.json
  locales/ru-RU/models.json
  locales/ru-RU/providers.json
  locales/tr-TR/models.json
  locales/tr-TR/providers.json
  locales/vi-VN/models.json
  locales/zh-CN/models.json
  locales/zh-CN/providers.json
  locales/zh-TW/models.json
  locales/zh-TW/providers.json
Labels: 💄 Design, size:XXL

#4052 💄 style: improve i18n for discover and improve version check
  locales/it-IT/models.json
  locales/nl-NL/models.json
  locales/nl-NL/providers.json
  locales/pl-PL/providers.json
  src/libs/unstructured/__tests__/fixtures/table-parse/auto-partition-basic-output.json
  src/libs/unstructured/__tests__/fixtures/table-parse/auto-partition-basic-raw.json
  src/libs/unstructured/__tests__/index.test.ts
  src/store/global/action.test.ts
  src/store/global/action.ts
Labels: 💄 Design, size:XL

#4053 :bug: fix: `providerAccountId` not exist in provider
  src/libs/next-auth/sso-providers/auth0.ts
  src/libs/next-auth/sso-providers/authelia.ts
  src/libs/next-auth/sso-providers/authentik.ts
  src/libs/next-auth/sso-providers/azure-ad.ts
  src/libs/next-auth/sso-providers/casdoor.ts
  src/libs/next-auth/sso-providers/cloudflare-zero-trust.ts
  src/libs/next-auth/sso-providers/github.ts
  src/libs/next-auth/sso-providers/zitadel.ts
Labels: 🐛 Bug, size:XS

#4042 ⚡ perf: Use nextjs pwa feat to gen manifest file
  next.config.mjs
  public/manifest.json
  src/app/(main)/discover/(detail)/_layout/Desktop.tsx
  src/app/(main)/discover/(detail)/assistant/[slug]/page.tsx
  src/app/(main)/discover/(detail)/model/[...slugs]/page.tsx
  src/app/(main)/discover/(detail)/plugin/[slug]/page.tsx
  src/app/(main)/discover/(detail)/provider/[slug]/page.tsx
  src/app/manifest.ts
  src/features/PWAInstall/index.tsx
  src/server/manifest.test.ts
  src/server/manifest.ts
  src/server/metadata.ts
  src/server/services/discover/index.test.ts
  src/server/services/discover/index.ts
  vitest.config.ts
Labels: ⚡️ Performance, size:XL

#4055 :bug: fix: casdoor webhooks providerAccountId not found
  src/app/api/webhooks/casdoor/route.ts
  src/app/api/webhooks/logto/route.ts
  src/server/services/nextAuthUser/index.ts
Labels: 🐛 Bug, size:M

#4056 🐛 fix: fix Content-Security-Policy
  next.config.mjs
Labels: 🐛 Bug, size:S

#4061 ♻️ refactor: refactor to improve customization
  src/app/(main)/chat/features/PageTitle/index.tsx
  src/app/(main)/welcome/_layout/Desktop.tsx
  src/app/(main)/welcome/page.tsx
  src/components/BrandWatermark/index.tsx
  src/components/Branding/OrgBrand/index.tsx
  src/components/Branding/ProductLogo/Custom.tsx
  src/components/Branding/ProductLogo/index.tsx
  src/components/Branding/WelcomeLogo/Custom.tsx
  src/components/Branding/WelcomeLogo/LobeChat.tsx
  src/components/Branding/WelcomeLogo/index.tsx
  src/components/Branding/index.ts
  src/config/app.ts
  src/const/branding.ts
  src/const/meta.ts
  src/const/version.ts
  src/layout/GlobalProvider/AppTheme.tsx
  src/layout/GlobalProvider/index.tsx
Labels: size:L

#4070 🐛 fix: fix ollama model download panel
  src/features/Conversation/Error/OllamaBizError/InvalidOllamaModel/index.tsx
  src/features/Conversation/Error/OllamaBizError/index.tsx
Labels: 💄 Design, ollama, size:XS

#4071 💄 style: add spark max-32k model
  src/config/modelProviders/spark.ts
Labels: 💄 Design, size:S

#4096 🐛 fix: fix artifacts code language highlight
  src/app/(main)/chat/(workspace)/@portal/Artifacts/Body/index.tsx
  src/app/(main)/chat/(workspace)/@portal/Artifacts/Header.tsx
  src/features/Conversation/components/MarkdownElements/LobeArtifact/Render/index.tsx
  src/libs/unstructured/__tests__/index.test.ts
  src/store/chat/slices/portal/action.ts
  src/store/chat/slices/portal/initialState.ts
  src/store/chat/slices/portal/selectors.ts
  src/types/artifact.ts
Labels: 🐛 Bug, size:M

#4106 🐛 fix: add missing translations
  locales/ar/models.json
  locales/bg-BG/models.json
  locales/de-DE/models.json
  locales/en-US/models.json
  locales/es-ES/models.json
  locales/fr-FR/models.json
  locales/it-IT/models.json
  locales/ja-JP/models.json
  locales/ko-KR/models.json
  locales/nl-NL/models.json
  locales/pl-PL/models.json
  locales/pt-BR/models.json
  locales/ru-RU/models.json
  locales/tr-TR/models.json
  locales/vi-VN/models.json
  locales/vi-VN/providers.json
  locales/zh-CN/models.json
  locales/zh-TW/models.json
Labels: 🐛 Bug, size:L

#4108 💄 style: left sidebar has only assistants
  locales/ar/chat.json
  locales/bg-BG/chat.json
  locales/de-DE/chat.json
  locales/en-US/chat.json
  locales/es-ES/chat.json
  locales/fr-FR/chat.json
  locales/it-IT/chat.json
  locales/ja-JP/chat.json
  locales/ko-KR/chat.json
  locales/nl-NL/chat.json
  locales/pl-PL/chat.json
  locales/pt-BR/chat.json
  locales/ru-RU/chat.json
  locales/tr-TR/chat.json
  locales/vi-VN/chat.json
  locales/zh-CN/chat.json
  locales/zh-TW/chat.json
  src/app/(main)/chat/(workspace)/_layout/Desktop/ChatHeader/Main.tsx
  src/locales/default/chat.ts
Labels: 🐛 Bug, size:M

#4099 💄 style: add function call support for 360AI (`360gpt-pro`)
  src/config/modelProviders/ai360.ts
  src/libs/agent-runtime/ai360/index.ts
Labels: 💄 Design, size:S

#4090 📝 docs: update next-auth documents
  docs/self-hosting/advanced/auth/next-auth/auth0.mdx
  docs/self-hosting/advanced/auth/next-auth/auth0.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/authelia.mdx
  docs/self-hosting/advanced/auth/next-auth/authelia.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/authentik.mdx
  docs/self-hosting/advanced/auth/next-auth/authentik.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/cloudflare-zero-trust.mdx
  docs/self-hosting/advanced/auth/next-auth/cloudflare-zero-trust.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/github.mdx
  docs/self-hosting/advanced/auth/next-auth/github.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/logto.mdx
  docs/self-hosting/advanced/auth/next-auth/logto.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/microsoft-entra-id.mdx
  docs/self-hosting/advanced/auth/next-auth/microsoft-entra-id.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/zitadel.mdx
  docs/self-hosting/advanced/auth/next-auth/zitadel.zh-CN.mdx
Labels: 📝 Documentation, size:L, lgtm

#4072 :bug: fix: fix url config import after user state init
  src/layout/GlobalProvider/StoreInitialization.tsx
Labels: 🐛 Bug, size:S

#3475 💄 style: improve images display in chat messages
  src/components/GalleyGrid/index.tsx
Labels: size:S, lgtm

#4101 💄 style: add function call support for Stepfun
  src/config/modelProviders/stepfun.ts
  src/libs/agent-runtime/stepfun/index.ts
Labels: 💄 Design, size:S

#4114 💄 style: update taichu provider info & add taichu vision model
  src/app/(main)/settings/llm/ProviderList/providers.tsx
  src/config/modelProviders/index.ts
  src/config/modelProviders/taichu.ts
Labels: 💄 Design, size:S

#4117 💄 style: disable taichu2.0 functioncall & default disable taichu2.0v model
  src/config/modelProviders/taichu.ts
Labels: 💄 Design, size:XS

#4118 💄 style: add google gemini 1.5 002 series
  locales/ar/models.json
  locales/bg-BG/models.json
  locales/de-DE/models.json
  locales/en-US/models.json
  locales/es-ES/models.json
  locales/fr-FR/models.json
  locales/it-IT/models.json
  locales/ja-JP/models.json
  locales/ko-KR/models.json
  locales/nl-NL/models.json
  locales/pl-PL/models.json
  locales/pt-BR/models.json
  locales/ru-RU/models.json
  locales/tr-TR/models.json
  locales/vi-VN/models.json
  locales/zh-CN/models.json
  locales/zh-TW/models.json
  src/config/modelProviders/google.ts
  src/libs/agent-runtime/google/index.test.ts
  src/libs/agent-runtime/google/index.ts
Labels: 💄 Design, size:L

#4124 ⚡️ perf: refactor pwa implement to have better performance
  .gitignore
  next.config.mjs
  package.json
  src/app/(main)/chat/(workspace)/@conversation/features/ChatInput/Desktop/TextArea.test.tsx
  src/app/sw.ts
  src/features/FileViewer/Renderer/Image/index.tsx
  src/features/PWAInstall/Install.tsx
  src/features/PWAInstall/index.tsx
  src/server/services/discover/index.ts
  src/services/message/server.ts
  src/services/session/server.ts
  src/store/chat/slices/plugin/action.ts
  tsconfig.json
Labels: ⚡️ Performance, size:L

#4119 💄 style: add function call back for `taichu_llm`
  src/config/modelProviders/taichu.ts
Labels: 💄 Design, size:XS

#4129 💄 style: update google provider model info
  src/config/modelProviders/google.ts
Labels: 💄 Design, size:L

#4088 🐛 fix: MiniMax output long content interrupted by non-existent error
  src/libs/agent-runtime/minimax/index.test.ts
  src/libs/agent-runtime/minimax/index.ts
  src/libs/agent-runtime/utils/streams/minimax.test.ts
  src/libs/agent-runtime/utils/streams/minimax.ts
Labels: size:M

#4157 🔧 chore: update antd to version ^5.21
  package.json
Labels: dependencies, size:XS

#4161 🔨 chore: re-run i18n, eslint, and prettier
  docs/self-hosting/server-database/zeabur.mdx
  locales/ar/models.json
  locales/bg-BG/models.json
  locales/de-DE/models.json
  locales/en-US/models.json
  locales/es-ES/models.json
  locales/fr-FR/models.json
  locales/it-IT/models.json
  locales/ja-JP/models.json
  locales/ko-KR/models.json
  locales/nl-NL/models.json
  locales/pl-PL/models.json
  locales/pt-BR/models.json
  locales/ru-RU/models.json
  locales/tr-TR/models.json
  locales/vi-VN/models.json
  locales/zh-CN/models.json
  locales/zh-CN/providers.json
  locales/zh-TW/models.json
  src/config/modelProviders/mistral.ts
  src/config/modelProviders/ollama.ts
  src/config/modelProviders/siliconcloud.ts
  src/libs/agent-runtime/utils/streams/openai.test.ts
Labels: 🐛 Bug, size:L

#4127 💄 style: add o1-preview and o1-mini model to github model provider
  src/config/modelProviders/github.ts
  src/libs/agent-runtime/github/index.ts
Labels: 💄 Design, size:M, lgtm

#4151 💄 style: add llama3.2 model for openrouter provider
  src/config/modelProviders/openrouter.ts
  src/libs/agent-runtime/openrouter/__snapshots__/index.test.ts.snap
Labels: 💄 Design, size:M

#4147 ✨ feat: add Hunyuan(Tencent) model provider
  Dockerfile
  Dockerfile.database
  src/app/(main)/settings/llm/ProviderList/providers.tsx
  src/app/api/chat/agentRuntime.ts
  src/config/llm.ts
  src/config/modelProviders/hunyuan.ts
  src/config/modelProviders/index.ts
  src/const/settings/llm.ts
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/hunyuan/index.test.ts
  src/libs/agent-runtime/hunyuan/index.ts
  src/libs/agent-runtime/types/type.ts
  src/server/globalConfig/index.ts
  src/types/user/settings/keyVaults.ts
Labels: 🌠 Feature Request, size:L

#4025 👷 build: optimize image size under `glibc` env
  Dockerfile
  Dockerfile.database
  scripts/serverLauncher/startServer.js
Labels: size:L

#4175 👷 build: revert #4025
  Dockerfile
  Dockerfile.database
  scripts/serverLauncher/startServer.js
Labels: size:L

#4173 💄 style: add zhipu glm-4-flashx model
  src/config/modelProviders/siliconcloud.ts
  src/config/modelProviders/zhipu.ts
Labels: 💄 Design, size:M

#4181 📝 docs: update model-provider document
  docs/self-hosting/environment-variables/model-provider.mdx
  docs/self-hosting/environment-variables/model-provider.zh-CN.mdx
Labels: 📝 Documentation, size:M

#4188 📝 docs: add new configuration item of clerk singup
  docs/self-hosting/advanced/feature-flags.mdx
  docs/self-hosting/advanced/feature-flags.zh-CN.mdx
Labels: 📝 Documentation, size:XS

#4179 🐛 fix: improve delete orphan chunks when delete files
  src/database/server/models/chunk.ts
Labels: 🐛 Bug, size:S

#4081 📝 docs: Add deployment using ZITADEL authentication services
  docker-compose/local/zitadel/.env.example
  docker-compose/local/zitadel/.env.zh-CN.example
  docker-compose/local/zitadel/docker-compose.yml
  docker-compose/local/zitadel/zitadel-config.yaml
  docker-compose/local/zitadel/zitadel-init-steps.yaml
  docker-compose/production/zitadel/.env.example
  docker-compose/production/zitadel/.env.zh-CN.example
  docker-compose/production/zitadel/docker-compose.yml
  docker-compose/production/zitadel/zitadel-config.yaml
  docker-compose/production/zitadel/zitadel-init-steps.yaml
Labels: 📝 Documentation, size:L

#4085 ⚡ perf: remove some blur style to improve performance
  src/app/(main)/chat/(workspace)/_layout/Desktop/ChatHeader/index.tsx
  src/app/(main)/chat/(workspace)/_layout/Desktop/Portal.tsx
  src/app/(main)/chat/(workspace)/_layout/Desktop/TopicPanel.tsx
  src/app/(main)/chat/@session/features/SessionListContent/Modals/ConfigGroupModal/index.tsx
  src/components/DragUpload/index.tsx
  src/components/FunctionModal/style.tsx
  src/components/GuideModal/index.tsx
  src/features/Conversation/components/VirtualizedList/index.tsx
  src/layout/AuthProvider/Clerk/useAppearance.ts
Labels: ⚡️ Performance, 💄 Design, size:S

#4176 👷 build: optimize image size under glibc env
  Dockerfile
  Dockerfile.database
  scripts/serverLauncher/startServer.js
Labels: size:L

#4199 📝 docs: Update docker-compose to use new LOGTO env
  docs/self-hosting/server-database/docker-compose.mdx
  docs/self-hosting/server-database/docker-compose.zh-CN.mdx
Labels: 📝 Documentation, size:M, lgtm

#4211 📝 docs: Prevent '#' and its subsequent comments from affecting the URL of S3 configuration
  docs/self-hosting/server-database/docker.zh-CN.mdx
Labels: 🐛 Bug, size:XS

#4213 👷 build: fix zeabur build
  scripts/serverLauncher/startServer.js
Labels: size:S

#4195 💄 style: update groq model list
  src/config/modelProviders/groq.ts
Labels: 💄 Design, size:M, lgtm

#4215 💄 style: Update wenxin model and info
  src/app/(main)/settings/llm/ProviderList/providers.tsx
  src/config/modelProviders/index.ts
  src/config/modelProviders/wenxin.ts
Labels: 💄 Design, size:L

#4218 🔨 chore: upgrade `shiki` to 1.21.0
  package.json
Labels: dependencies, size:XS

#4219 👷 build: remove unnecessary SSL judgments
  scripts/serverLauncher/startServer.js
Labels: size:S

#4223 👷 build: enhance Self-host CA usage & remove TLS detection
  Dockerfile
  Dockerfile.database
  scripts/serverLauncher/startServer.js
Labels: 🌠 Feature Request, size:L
