Repository lobehub/lobe-chat, pull requests merged in 2024-12, with the labels that each got.

#4839 💄 style: update model list, add `qwq-32b-preview`
  src/config/modelProviders/fireworksai.ts
  src/config/modelProviders/qwen.ts
  src/config/modelProviders/siliconcloud.ts
  src/config/modelProviders/togetherai.ts
Labels: 💄 Design, size:L

#4842 💄 style: add `QWEN_PROXY_URL` support for Qwen
  Dockerfile
  Dockerfile.database
  src/config/modelProviders/qwen.ts
Labels: 💄 Design, size:XS

#4801 📝 docs: add langfuse in docs
  docs/self-hosting/environment-variables/analytics.mdx
Labels: 📝 Documentation, size:M

#3327 ✨ feat: support ollama tools use
  package.json
  src/config/modelProviders/ollama.ts
  src/libs/agent-runtime/ollama/index.ts
  src/libs/agent-runtime/utils/streams/ollama.test.ts
  src/libs/agent-runtime/utils/streams/ollama.ts
  src/server/modules/AgentRuntime/index.test.ts
  src/server/modules/AgentRuntime/index.ts
Labels: 🌠 Feature Request, ollama, size:L

#4850 📝 docs: update docs
  docs/changelog/2024-07-19-gpt-4o-mini.mdx
  docs/changelog/2024-07-19-gpt-4o-mini.zh-CN.mdx
  docs/changelog/2024-08-02-lobe-chat-database-docker.mdx
  docs/changelog/2024-08-02-lobe-chat-database-docker.zh-CN.mdx
  docs/changelog/2024-08-21-file-upload-and-knowledge-base.mdx
  docs/changelog/2024-08-21-file-upload-and-knowledge-base.zh-CN.mdx
  docs/changelog/2024-09-13-openai-o1-models.mdx
  docs/changelog/2024-09-20-artifacts.mdx
  docs/changelog/2024-09-20-artifacts.zh-CN.mdx
  docs/changelog/2024-10-27-pin-assistant.mdx
  docs/changelog/2024-10-27-pin-assistant.zh-CN.mdx
  docs/changelog/2024-11-06-share-text-json.mdx
  docs/changelog/2024-11-06-share-text-json.zh-CN.mdx
  docs/changelog/2024-11-25-november-providers.mdx
  docs/changelog/2024-11-25-november-providers.zh-CN.mdx
  docs/changelog/2024-11-27-forkable-chat.mdx
  docs/changelog/2024-11-27-forkable-chat.zh-CN.mdx
  docs/changelog/index.json
  docs/self-hosting/environment-variables/analytics.mdx
Labels: 📝 Documentation, size:L

#4853 💄 style: update ollama models
  locales/ar/models.json
  locales/bg-BG/models.json
  locales/de-DE/models.json
  locales/en-US/models.json
  locales/es-ES/models.json
  locales/fa-IR/models.json
  locales/fr-FR/models.json
  locales/it-IT/models.json
  locales/ja-JP/models.json
  locales/ko-KR/models.json
  locales/nl-NL/models.json
  locales/pl-PL/models.json
  locales/pt-BR/models.json
  locales/ru-RU/models.json
  locales/tr-TR/models.json
  locales/vi-VN/models.json
  locales/zh-CN/models.json
  locales/zh-TW/models.json
  src/config/modelProviders/ollama.ts
Labels: 💄 Design, ollama, size:XXL

#4857 💄 style: improve i18n
  docs/changelog/index.json
  locales/ar/modelProvider.json
  locales/bg-BG/modelProvider.json
  locales/de-DE/modelProvider.json
  locales/en-US/chat.json
  locales/en-US/modelProvider.json
  locales/es-ES/modelProvider.json
  locales/fr-FR/modelProvider.json
  locales/ja-JP/modelProvider.json
  locales/ko-KR/modelProvider.json
  locales/nl-NL/modelProvider.json
  locales/pl-PL/modelProvider.json
  locales/pt-BR/modelProvider.json
  locales/ru-RU/modelProvider.json
Labels: 💄 Design, size:L

#4855 💄 style: add gpt-4o-2024-11-20 model
  src/config/modelProviders/openai.ts
  src/store/user/slices/modelList/selectors/modelProvider.test.ts
Labels: 💄 Design, size:S

#4861 ⚡️ perf: update agent index url
  src/config/__tests__/app.test.ts
  src/config/app.ts
  src/server/modules/AssistantStore/index.test.ts
Labels: ⚡️ Performance, size:S

#4865 📝 docs: update provider docs
  docs/usage/providers/giteeai.mdx
  docs/usage/providers/giteeai.zh-CN.mdx
  docs/usage/providers/internlm.mdx
  docs/usage/providers/internlm.zh-CN.mdx
  docs/usage/providers/sensenova.mdx
  docs/usage/providers/sensenova.zh-CN.mdx
  docs/usage/providers/xai.mdx
  docs/usage/providers/xai.zh-CN.mdx
Labels: 📝 Documentation, size:XL

#4866 ♻️ refactor: deprecated the current client mode code
  src/database/_deprecated/core/__tests__/db-upgrade.test.ts
  src/database/_deprecated/core/__tests__/db.test.ts
  src/database/_deprecated/core/__tests__/model.test.ts
  src/database/_deprecated/core/db.ts
  src/database/_deprecated/core/index.ts
  src/database/_deprecated/core/migrations/migrateSettingsToUser/fixtures/input.json
  src/database/_deprecated/core/migrations/migrateSettingsToUser/fixtures/output.json
  src/database/_deprecated/core/migrations/migrateSettingsToUser/index.test.ts
  src/database/_deprecated/core/migrations/migrateSettingsToUser/index.ts
  src/database/_deprecated/core/migrations/migrateSettingsToUser/type.ts
  src/database/_deprecated/core/model.ts
  src/database/_deprecated/core/schemas.ts
  src/database/_deprecated/core/sync.ts
  src/database/_deprecated/core/types/db.ts
  src/database/_deprecated/models/__DEBUG.ts
  src/database/_deprecated/models/__tests__/file.test.ts
  src/database/_deprecated/models/__tests__/message.test.ts
  src/database/_deprecated/models/__tests__/plugin.test.ts
  src/database/_deprecated/models/__tests__/session.test.ts
  src/database/_deprecated/models/__tests__/sessionGroup.test.ts
  src/database/_deprecated/models/__tests__/topic.test.ts
  src/database/_deprecated/models/__tests__/user.test.ts
  src/database/_deprecated/models/file.ts
  src/database/_deprecated/models/message.ts
  src/database/_deprecated/models/plugin.ts
  src/database/_deprecated/models/session.ts
  src/database/_deprecated/models/sessionGroup.ts
  src/database/_deprecated/models/topic.ts
  src/database/_deprecated/models/user.ts
  src/database/_deprecated/schemas/files.ts
  src/database/_deprecated/schemas/message.ts
  src/database/_deprecated/schemas/plugin.ts
  src/database/_deprecated/schemas/session.ts
  src/database/_deprecated/schemas/sessionGroup.ts
  src/database/_deprecated/schemas/topic.ts
  src/database/_deprecated/schemas/user.ts
  src/services/__tests__/sync.test.ts
  src/services/debug.ts
  src/services/file/client.test.ts
  src/services/file/client.ts
  src/services/import/client.ts
  src/services/message/client.test.ts
  src/services/message/client.ts
  src/services/message/index.test.ts
  src/services/message/type.ts
  src/services/plugin/client.test.ts
  src/services/plugin/client.ts
  src/services/session/client.test.ts
  src/services/session/client.ts
  src/services/sync.ts
  src/services/topic/client.test.ts
  src/services/topic/client.ts
  src/services/upload.ts
  src/services/user/client.test.ts
  src/services/user/client.ts
  src/store/file/slices/chat/action.test.ts
  src/types/sync.ts
Labels: size:M

#4870 ♻️ refactor: add user server api key method in the server mode
  src/database/server/models/user.ts
Labels: size:M

#4867 💄 style: update HuggingFace model list, add `QwQ 32B Preview`
  src/config/modelProviders/huggingface.ts
Labels: 💄 Design, size:XS

#4875 👷 build: pin `@browserbasehq/stagehand@1.3.0` to fix pnpm install
  package.json
Labels: size:XS

#4876 👷 build: unpinned `@browserbasehq/stagehand`
  package.json
Labels: dependencies, size:XS

#4878 ♻️ refactor: refactor the server model implement
  src/app/(main)/repos/[id]/@menu/default.tsx
  src/app/(main)/repos/[id]/page.tsx
  src/database/schemas/topic.ts
  src/database/server/core/dbForTest.ts
  src/database/server/models/__tests__/_test_template.ts
  src/database/server/models/__tests__/agent.test.ts
  src/database/server/models/__tests__/asyncTask.test.ts
  src/database/server/models/__tests__/chunk.test.ts
  src/database/server/models/__tests__/file.test.ts
  src/database/server/models/__tests__/knowledgeBase.test.ts
  src/database/server/models/__tests__/message.test.ts
  src/database/server/models/__tests__/nextauth.test.ts
  src/database/server/models/__tests__/plugin.test.ts
  src/database/server/models/__tests__/session.test.ts
  src/database/server/models/__tests__/sessionGroup.test.ts
  src/database/server/models/__tests__/topic.test.ts
  src/database/server/models/__tests__/user.test.ts
  src/database/server/models/_template.ts
  src/database/server/models/agent.ts
  src/database/server/models/asyncTask.ts
  src/database/server/models/chunk.ts
  src/database/server/models/embedding.ts
  src/database/server/models/file.ts
  src/database/server/models/knowledgeBase.ts
  src/database/server/models/message.ts
  src/database/server/models/plugin.ts
  src/database/server/models/session.ts
  src/database/server/models/sessionGroup.ts
  src/database/server/models/thread.ts
  src/database/server/models/topic.ts
  src/database/server/models/user.ts
  src/database/type.ts
  src/libs/next-auth/adapter/index.ts
  src/libs/trpc/async/asyncAuth.ts
  src/server/routers/async/file.ts
  src/server/routers/async/ragEval.ts
  src/server/routers/lambda/_template.ts
  src/server/routers/lambda/agent.ts
  src/server/routers/lambda/chunk.ts
  src/server/routers/lambda/file.ts
  src/server/routers/lambda/knowledgeBase.ts
  src/server/routers/lambda/message.ts
  src/server/routers/lambda/plugin.ts
  src/server/routers/lambda/ragEval.ts
  src/server/routers/lambda/session.ts
  src/server/routers/lambda/sessionGroup.ts
  src/server/routers/lambda/thread.ts
  src/server/routers/lambda/topic.ts
  src/server/routers/lambda/user.ts
  src/server/services/chunk/index.ts
  src/server/services/nextAuthUser/index.ts
  src/server/services/user/index.ts
Labels: size:XXL

#4887 👷 build: pin `zustand@5.0.1` to fix bulid
  package.json
Labels: size:XS

#4576 📝 docs: support use custom `host` in docker-compose setup script & regenerate secrets
  docker-compose/local/init_data.json
  docker-compose/local/setup.sh
Labels: size:L

#4837 🐛 fix: fix typo of prompts
  src/prompts/systemRole/index.ts
Labels: size:XS

#4899 👷 build: pin `@type/react@18.3.13` to fix build
  package.json
Labels: dependencies, size:XS

#4904 ♻️ refactor: refactor page params to adapt next15 breaking change
  src/app/(main)/discover/(detail)/model/[...slugs]/page.tsx
  src/app/(main)/discover/(detail)/plugin/[slug]/page.tsx
  src/app/(main)/discover/(detail)/provider/[slug]/page.tsx
  src/app/(main)/discover/(list)/assistants/[slug]/page.tsx
  src/app/(main)/discover/(list)/models/[slug]/page.tsx
  src/app/(main)/discover/(list)/plugins/[slug]/page.tsx
  src/app/(main)/discover/search/page.tsx
  src/app/(main)/files/(content)/@modal/(.)[id]/page.tsx
  src/app/(main)/files/[id]/page.tsx
  src/app/(main)/repos/[id]/evals/dataset/page.tsx
  src/app/(main)/repos/[id]/evals/evaluation/page.tsx
  src/app/(main)/repos/[id]/evals/layout.tsx
  src/app/(main)/repos/[id]/evals/page.tsx
  src/app/(main)/repos/[id]/evals/type.ts
  src/app/(main)/repos/[id]/layout.tsx
  src/app/(main)/repos/[id]/page.tsx
  src/types/discover.ts
  src/types/next.ts
Labels: size:L

#4902 🔨 chore: improve server mode migration scripts
  scripts/migrateServerDB/errorHint.js
  scripts/migrateServerDB/index.ts
Labels: size:M

#4755 ✨ feat: add Higress ai model provider
  Dockerfile
  src/app/(main)/settings/llm/ProviderList/providers.tsx
  src/config/llm.ts
  src/config/modelProviders/higress.ts
  src/config/modelProviders/index.ts
  src/const/settings/llm.ts
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/higress/index.ts
  src/libs/agent-runtime/types/type.ts
  src/types/user/settings/keyVaults.ts
Labels: 🌠 Feature Request, Model Provider, size:XXL

#4909 💄 style: Add gemini-exp-1206 model
  src/config/modelProviders/google.ts
Labels: size:S

#4826 ♻️ refactor: Remove proxy url settings for NextAuth
  src/config/auth.ts
  src/libs/next-auth/auth.config.ts
Labels: size:XS

#4905 ♻️ refactor: refactor async params route to adapt next15 breaking change
  src/app/(backend)/middleware/auth/index.test.ts
  src/app/(backend)/middleware/auth/index.ts
  src/app/(backend)/webapi/assistant/[id]/route.ts
  src/app/(backend)/webapi/chat/[provider]/route.test.ts
  src/app/(backend)/webapi/chat/[provider]/route.ts
  src/app/(backend)/webapi/chat/anthropic/route.test.ts
  src/app/(backend)/webapi/chat/anthropic/route.ts
  src/app/(backend)/webapi/chat/google/route.test.ts
  src/app/(backend)/webapi/chat/google/route.ts
  src/app/(backend)/webapi/chat/minimax/route.test.ts
  src/app/(backend)/webapi/chat/minimax/route.ts
  src/app/(backend)/webapi/chat/models/[provider]/route.ts
  src/app/(backend)/webapi/chat/openai/route.test.ts
  src/app/(backend)/webapi/chat/openai/route.ts
  src/app/(backend)/webapi/chat/wenxin/route.test.ts
  src/app/(backend)/webapi/chat/wenxin/route.ts
  src/app/(backend)/webapi/text-to-image/[provider]/route.ts
Labels: size:M

#4915 ⚡️ perf: add react scan monitor
  package.json
  src/components/Analytics/ReactScan.tsx
  src/components/Analytics/index.tsx
  src/config/analytics.ts
Labels: ⚡️ Performance, size:S

#4934 🐛 fix: support request headers for chat
  src/libs/agent-runtime/types/chat.ts
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
  src/utils/clientIP.test.ts
  src/utils/clientIP.ts
Labels: 💄 Design, size:M

#4935 📝 docs: update changelog docs
  docs/changelog/2024-08-02-lobe-chat-database-docker.mdx
  docs/changelog/2024-08-02-lobe-chat-database-docker.zh-CN.mdx
  docs/changelog/2024-09-20-artifacts.mdx
  docs/changelog/2024-09-20-artifacts.zh-CN.mdx
Labels: 📝 Documentation, size:XS

#4941 👷 build: pin `re-resizable@6.10.1` to fix build
  package.json
Labels: dependencies, size:XS

#4919 🐛 fix: fix wrong email linking in next-auth db adapter
  src/database/server/models/__tests__/nextauth.test.ts
  src/libs/next-auth/adapter/index.ts
Labels: 🐛 Bug, size:M

#4942 💄 style: Update groq, add llama3.3
  src/config/modelProviders/groq.ts
Labels: 🌠 Feature Request, size:S

#4950 💄 style: Upgrade lobe-ui
  src/components/Branding/WelcomeLogo/LobeChat.tsx
  src/features/Conversation/Actions/Error.tsx
Labels: size:XS

#4964 🐛 fix: fix pricing with 0 digit
  package.json
  src/utils/format.test.ts
  src/utils/format.ts
Labels: 🐛 Bug, size:S

#4958 💄 style: add `GLM-4V-Flash` from Zhipu
  src/config/modelProviders/zhipu.ts
Labels: 💄 Design, size:S

#4965 ♻️ refactor: refactor the clerk user service implement
  locales/ar/models.json
  locales/ar/providers.json
  locales/bg-BG/models.json
  locales/bg-BG/providers.json
  locales/de-DE/models.json
  locales/de-DE/providers.json
  locales/en-US/models.json
  locales/en-US/providers.json
  locales/es-ES/models.json
  locales/es-ES/providers.json
  locales/fa-IR/models.json
  locales/fa-IR/providers.json
  locales/fr-FR/models.json
  locales/fr-FR/providers.json
  locales/it-IT/models.json
  locales/it-IT/providers.json
  locales/ja-JP/models.json
  locales/ja-JP/providers.json
  locales/ko-KR/models.json
  locales/ko-KR/providers.json
  locales/nl-NL/models.json
  locales/nl-NL/providers.json
  locales/pl-PL/modelProvider.json
  locales/pl-PL/models.json
  locales/pl-PL/providers.json
  locales/pt-BR/models.json
  locales/pt-BR/providers.json
  locales/ru-RU/models.json
  locales/ru-RU/providers.json
  locales/tr-TR/models.json
  locales/tr-TR/providers.json
  locales/vi-VN/models.json
  locales/vi-VN/providers.json
  locales/zh-CN/models.json
  locales/zh-CN/providers.json
  locales/zh-TW/models.json
  locales/zh-TW/providers.json
  src/app/(backend)/api/webhooks/clerk/route.ts
  src/server/services/user/index.test.ts
  src/server/services/user/index.ts
  vitest.config.ts
Labels: size:XXL

#4960 🐛 fix: nullptr errors in NextAuth adapter
  src/database/server/models/__tests__/nextauth.test.ts
  src/libs/next-auth/adapter/index.ts
Labels: 🐛 Bug, size:M

#4967 ♻️ refactor: clean the gpt-4-vision-preview models
  locales/ar/models.json
  locales/bg-BG/models.json
  locales/de-DE/models.json
  locales/en-US/models.json
  locales/es-ES/models.json
  locales/fa-IR/models.json
  locales/fr-FR/models.json
  locales/it-IT/models.json
  locales/ja-JP/models.json
  locales/ko-KR/models.json
  locales/nl-NL/models.json
  locales/pl-PL/models.json
  locales/pt-BR/models.json
  locales/ru-RU/models.json
  locales/tr-TR/models.json
  locales/vi-VN/models.json
  locales/zh-CN/models.json
  locales/zh-TW/models.json
  src/config/modelProviders/azure.ts
  src/config/modelProviders/higress.ts
  src/config/modelProviders/openai.ts
  src/libs/agent-runtime/openai/__snapshots__/index.test.ts.snap
  src/server/routers/edge/config/__snapshots__/index.test.ts.snap
  src/server/routers/edge/config/index.test.ts
  src/store/chat/slices/aiChat/actions/generateAIChat.ts
Labels: size:L

#4974 ♻️ refactor: refactor data importer to repos
  src/database/repositories/dataImporter/__tests__/fixtures/messages.json
  src/database/repositories/dataImporter/__tests__/index.test.ts
  src/database/repositories/dataImporter/index.ts
  src/server/routers/lambda/importer.ts
  vitest.config.ts
Labels: size:M

#4981 💄 style: Add Gemini 2.0 Flash Exp model
  src/config/modelProviders/google.ts
Labels: Gemini, size:S

#4977 📝 docs: Add docs for env `LLM_VISION_IMAGE_USE_BASE64`
  docs/self-hosting/environment-variables/s3.mdx
  docs/self-hosting/environment-variables/s3.zh-CN.mdx
Labels: 📝 Documentation, size:S

#4990 ♻️ refactor: refactor database file model to remove server env
  src/config/db.ts
  src/database/server/models/__tests__/file.test.ts
  src/database/server/models/_template.ts
  src/database/server/models/agent.ts
  src/database/server/models/asyncTask.ts
  src/database/server/models/chunk.ts
  src/database/server/models/embedding.ts
  src/database/server/models/file.ts
  src/database/server/models/knowledgeBase.ts
  src/database/server/models/message.ts
  src/database/server/models/session.ts
  src/database/server/models/sessionGroup.ts
  src/database/server/models/thread.ts
  src/database/server/models/topic.ts
  src/database/server/models/user.ts
  src/server/routers/async/file.ts
  src/server/routers/lambda/file.ts
Labels: size:M

#4997 💄 style: Enable googleSearch Tool for gemini-2.0-flash-exp
  src/libs/agent-runtime/google/index.ts
Labels: Gemini, size:XS

#4998 ♻️ refactor: refactor the file model method
  src/database/repositories/dataImporter/index.ts
  src/database/schemas/file.ts
  src/database/schemas/relations.ts
  src/database/server/models/__tests__/file.test.ts
  src/database/server/models/file.ts
  src/server/routers/lambda/file.ts
Labels: size:L

#5000 ⚡️ perf: downset tokenizer threshold to reduce browser memory usage
  src/utils/tokenizer/index.ts
Labels: ⚡️ Performance, size:XS

#5001 🐛 fix: fix Claude first message can not be assistant
  src/libs/agent-runtime/utils/anthropicHelpers.test.ts
  src/libs/agent-runtime/utils/anthropicHelpers.ts
Labels: 🐛 Bug, size:M

#5003 🐛 fix: Revert "Enable googleSearch Tool for gemini-2.0-flash-exp"
  src/libs/agent-runtime/google/index.ts
Labels: size:XS

#5002 🐛 fix: one of Gemini functionCall error
  src/libs/agent-runtime/google/index.ts
Labels: 🐛 Bug, size:XS

#5004 ⚡️ perf: remove welcome page to improve performance
  locales/ar/welcome.json
  locales/bg-BG/welcome.json
  locales/de-DE/welcome.json
  locales/en-US/welcome.json
  locales/es-ES/welcome.json
  locales/fa-IR/welcome.json
  locales/fr-FR/welcome.json
  locales/it-IT/welcome.json
  locales/ja-JP/welcome.json
  locales/ko-KR/welcome.json
  locales/nl-NL/welcome.json
  locales/pl-PL/welcome.json
  locales/pt-BR/welcome.json
  locales/ru-RU/welcome.json
  locales/tr-TR/welcome.json
  locales/vi-VN/welcome.json
  locales/zh-CN/welcome.json
  locales/zh-TW/welcome.json
  src/app/(main)/welcome/_layout/Desktop.tsx
  src/app/(main)/welcome/_layout/Mobile.tsx
  src/app/(main)/welcome/features/Actions.test.tsx
  src/app/(main)/welcome/features/Actions.tsx
  src/app/(main)/welcome/features/Hero.tsx
  src/app/(main)/welcome/layout.tsx
  src/app/(main)/welcome/page.tsx
  src/app/loading/Redirect.tsx
  src/components/Branding/WelcomeLogo/Custom.tsx
  src/components/Branding/WelcomeLogo/LobeChat.tsx
  src/components/Branding/WelcomeLogo/index.tsx
  src/components/Branding/index.ts
  src/locales/default/welcome.ts
  src/server/sitemap.ts
Labels: ⚡️ Performance, size:L

#5009 👷 build: upgrade nodejs version to 22
  Dockerfile
  Dockerfile.database
Labels: size:S

#4123 💄 style: support csv chunking
  src/libs/langchain/loaders/csv/__tests__/__snapshots__/index.test.ts.snap
  src/libs/langchain/loaders/csv/__tests__/demo.csv
  src/libs/langchain/loaders/csv/__tests__/index.test.ts
  src/libs/langchain/loaders/csv/index.ts
  src/libs/langchain/loaders/index.ts
  src/libs/langchain/types.ts
Labels: 🌠 Feature Request, size:M

#5010 🚨 ci: fix lint
  src/libs/langchain/loaders/csv/__tests__/index.test.ts
Labels: size:XS

#5019 ♻️ refactor: refactor file Url query in message model
  src/database/server/models/__tests__/message.test.ts
  src/database/server/models/message.ts
  src/server/routers/lambda/message.ts
Labels: size:S

#5013 💄 style: Add new grok models
  src/config/modelProviders/xai.ts
Labels: size:S

#5034 📝 docs: Update changelog
  docs/changelog/2023-09-09-plugin-system.mdx
  docs/changelog/2023-09-09-plugin-system.zh-CN.mdx
  docs/changelog/2023-11-14-gpt4-vision.mdx
  docs/changelog/2023-11-14-gpt4-vision.zh-CN.mdx
  docs/changelog/2023-11-19-tts-stt.mdx
  docs/changelog/2023-11-19-tts-stt.zh-CN.mdx
  docs/changelog/2023-12-22-dalle-3.mdx
  docs/changelog/2023-12-22-dalle-3.zh-CN.mdx
  docs/changelog/2024-02-08-sso-oauth.mdx
  docs/changelog/2024-02-08-sso-oauth.zh-CN.mdx
  docs/changelog/2024-02-14-ollama.mdx
  docs/changelog/2024-02-14-ollama.zh-CN.mdx
  docs/changelog/2024-06-19-lobe-chat-v1.mdx
  docs/changelog/2024-06-19-lobe-chat-v1.zh-CN.mdx
  docs/changelog/2024-07-19-gpt-4o-mini.mdx
  docs/changelog/2024-08-21-file-upload-and-knowledge-base.mdx
  docs/changelog/2024-09-20-artifacts.mdx
  docs/changelog/2024-09-20-artifacts.zh-CN.mdx
  docs/changelog/2024-10-27-pin-assistant.mdx
  docs/changelog/2024-10-27-pin-assistant.zh-CN.mdx
  docs/changelog/2024-11-06-share-text-json.mdx
  docs/changelog/2024-11-06-share-text-json.zh-CN.mdx
  docs/changelog/index.json
Labels: 📝 Documentation, size:L

#5041 💄 style: update models of Gitee AI provider
  src/config/modelProviders/giteeai.ts
Labels: 💄 Design, size:M

#5042 fix: add unique keys to `<ModelList>` children
  src/app/(main)/discover/(detail)/provider/[slug]/features/ModelList/index.tsx
Labels: 🐛 Bug, size:S

#5044 ⚡️ perf: improve loading performance by add a new state for loading page
  locales/ar/common.json
  locales/ar/models.json
  locales/bg-BG/common.json
  locales/bg-BG/models.json
  locales/de-DE/common.json
  locales/de-DE/models.json
  locales/en-US/common.json
  locales/en-US/models.json
  locales/es-ES/common.json
  locales/es-ES/models.json
  locales/fa-IR/common.json
  locales/fa-IR/models.json
  locales/fr-FR/common.json
  locales/fr-FR/models.json
  locales/it-IT/common.json
  locales/it-IT/models.json
  locales/ja-JP/common.json
  locales/ja-JP/models.json
  locales/ko-KR/common.json
  locales/ko-KR/models.json
  locales/nl-NL/common.json
  locales/nl-NL/models.json
  locales/pl-PL/common.json
  locales/pl-PL/models.json
  locales/pt-BR/common.json
  locales/pt-BR/models.json
  locales/ru-RU/common.json
  locales/ru-RU/models.json
  locales/tr-TR/common.json
  locales/tr-TR/models.json
  locales/vi-VN/common.json
  locales/vi-VN/models.json
  locales/zh-CN/common.json
  locales/zh-CN/models.json
  locales/zh-TW/common.json
  locales/zh-TW/models.json
  src/app/loading/Client.tsx
  src/app/loading/Content.tsx
  src/app/loading/Redirect.tsx
  src/app/loading/index.tsx
  src/locales/default/common.ts
  src/store/global/selectors.ts
Labels: ⚡️ Performance, size:XXL

#5045 🐛 fix: fix discover locale with different default lang
  src/const/locale.ts
  src/server/modules/AssistantStore/index.test.ts
  src/server/modules/PluginStore/index.test.ts
Labels: size:S

#5048 💄 style: improve page loading state
  locales/ar/common.json
  locales/bg-BG/common.json
  locales/de-DE/common.json
  locales/en-US/common.json
  locales/es-ES/common.json
  locales/fa-IR/common.json
  locales/fr-FR/common.json
  locales/it-IT/common.json
  locales/ja-JP/common.json
  locales/ko-KR/common.json
  locales/nl-NL/common.json
  locales/pl-PL/common.json
  locales/pt-BR/common.json
  locales/ru-RU/common.json
  locales/tr-TR/common.json
  locales/vi-VN/common.json
  locales/zh-CN/common.json
  locales/zh-TW/common.json
  next.config.mjs
  src/app/loading/Content.tsx
  src/app/loading/Redirect.tsx
  src/app/loading/index.tsx
  src/app/loading/type.ts
  src/components/FullscreenLoading/index.tsx
  src/layout/GlobalProvider/index.tsx
  src/locales/default/common.ts
Labels: 💄 Design, size:L

#5049 ♻️ refactor: refactor the data fetch with clientDB init check
  src/app/(main)/chat/(workspace)/@conversation/features/ChatList/Content.tsx
  src/app/(main)/chat/(workspace)/@conversation/features/ThreadHydration.tsx
  src/app/(main)/chat/@session/features/SessionListContent/DefaultMode.tsx
  src/app/(main)/discover/(detail)/plugin/[slug]/features/InstallPlugin.tsx
  src/database/server/models/plugin.ts
  src/database/server/models/session.ts
  src/features/AgentSetting/AgentPlugin/index.tsx
  src/features/ChatInput/ActionBar/Tools/Dropdown.tsx
  src/features/Portal/Thread/Chat/ChatList.tsx
  src/hooks/useCheckPluginsIsInstalled.ts
  src/hooks/useFetchInstalledPlugins.ts
  src/hooks/useFetchMessages.ts
  src/hooks/useFetchSessions.ts
  src/hooks/useFetchThreads.ts
  src/hooks/useFetchTopics.ts
  src/layout/GlobalProvider/StoreInitialization.tsx
  src/services/user/client.ts
  src/store/agent/slices/chat/action.test.ts
  src/store/chat/slices/aiChat/actions/__tests__/generateAIChat.test.ts
  src/store/chat/slices/builtinTool/action.ts
  src/store/chat/slices/message/action.test.ts
  src/store/chat/slices/message/action.ts
  src/store/chat/slices/thread/action.ts
  src/store/chat/slices/topic/action.test.ts
  src/store/chat/slices/topic/action.ts
  src/store/global/selectors.ts
  src/store/session/slices/session/action.ts
  src/store/session/slices/sessionGroup/action.test.ts
  src/store/tool/slices/plugin/action.ts
  src/store/tool/slices/store/action.ts
  src/store/user/slices/common/action.test.ts
Labels: size:L

#4779 📝docs: Update `docs/self-hosting/environment-variables/model-provider.mdx`
  docs/self-hosting/environment-variables/model-provider.mdx
Labels: 📝 Documentation, size:M

#5057 📝 docs: fix model providers docs
  docs/self-hosting/environment-variables/model-provider.mdx
  docs/self-hosting/environment-variables/model-provider.zh-CN.mdx
  docs/self-hosting/server-database/dokploy.zh-CN.mdx
Labels: 📝 Documentation, size:M

#5059 👷 build: fix vercel build by pin `bun@1.1.38`
  vercel.json
Labels: size:XS

#5058 ♻️ refactor: refactor the drizzle code style
  src/database/repositories/dataImporter/__tests__/index.test.ts
  src/database/repositories/dataImporter/index.ts
  src/database/server/models/__tests__/_test_template.ts
  src/database/server/models/__tests__/agent.test.ts
  src/database/server/models/__tests__/asyncTask.test.ts
  src/database/server/models/__tests__/chunk.test.ts
  src/database/server/models/__tests__/file.test.ts
  src/database/server/models/__tests__/knowledgeBase.test.ts
  src/database/server/models/__tests__/message.test.ts
  src/database/server/models/__tests__/nextauth.test.ts
  src/database/server/models/__tests__/session.test.ts
  src/database/server/models/__tests__/sessionGroup.test.ts
  src/database/server/models/__tests__/topic.test.ts
  src/database/server/models/__tests__/user.test.ts
  src/database/server/models/_template.ts
  src/database/server/models/agent.ts
  src/database/server/models/asyncTask.ts
  src/database/server/models/chunk.ts
  src/database/server/models/embedding.ts
  src/database/server/models/file.ts
  src/database/server/models/knowledgeBase.ts
  src/database/server/models/message.ts
  src/database/server/models/plugin.ts
  src/database/server/models/ragEval/dataset.ts
  src/database/server/models/ragEval/datasetRecord.ts
  src/database/server/models/ragEval/evaluation.ts
  src/database/server/models/ragEval/evaluationRecord.ts
  src/database/server/models/session.ts
  src/database/server/models/sessionGroup.ts
  src/database/server/models/thread.ts
  src/database/server/models/topic.ts
  src/database/server/models/user.ts
  src/libs/agent-runtime/utils/streams/azureOpenai.test.ts
  src/libs/next-auth/adapter/index.ts
  src/server/routers/lambda/chunk.ts
Labels: size:XL

#4645 🐛 fix: Fix GitHub model fetch
  src/config/modelProviders/github.ts
  src/libs/agent-runtime/github/index.test.ts
  src/libs/agent-runtime/github/index.ts
  src/libs/agent-runtime/togetherai/index.ts
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
Labels: size:L

#5071 🔧 chore: Update Readme Sync Workflow
  README.ja-JP.md
  README.md
  README.zh-CN.md
  locales/ar/models.json
  locales/ar/providers.json
  locales/bg-BG/models.json
  locales/bg-BG/providers.json
  locales/de-DE/models.json
  locales/de-DE/providers.json
  locales/en-US/models.json
  locales/en-US/providers.json
  locales/es-ES/models.json
  locales/es-ES/providers.json
  locales/fa-IR/models.json
  locales/fa-IR/providers.json
  locales/fr-FR/models.json
  locales/fr-FR/providers.json
  locales/it-IT/models.json
  locales/it-IT/providers.json
  locales/ja-JP/models.json
  locales/ja-JP/providers.json
  locales/ko-KR/models.json
  locales/ko-KR/providers.json
  locales/nl-NL/models.json
  locales/nl-NL/providers.json
  locales/pl-PL/models.json
  locales/pl-PL/providers.json
  locales/pt-BR/models.json
  locales/pt-BR/providers.json
  locales/ru-RU/models.json
  locales/ru-RU/providers.json
  locales/tr-TR/models.json
  locales/tr-TR/providers.json
  locales/vi-VN/models.json
  locales/vi-VN/providers.json
  locales/zh-CN/models.json
  locales/zh-CN/providers.json
  locales/zh-TW/models.json
  locales/zh-TW/providers.json
  scripts/readmeWorkflow/const.ts
  scripts/readmeWorkflow/index.ts
  scripts/readmeWorkflow/syncAgentIndex.ts
  scripts/readmeWorkflow/syncPluginIndex.ts
  scripts/readmeWorkflow/syncProviderIndex.ts
  scripts/readmeWorkflow/utlis.ts
  src/config/modelProviders/ai21.ts
  src/config/modelProviders/cloudflare.ts
  src/config/modelProviders/higress.ts
  src/config/modelProviders/sensenova.ts
  src/locales/default/models.ts
  src/locales/default/providers.ts
Labels: 📝 Documentation, size:XL

#5074 🐛 fix: fix pdf preview
  src/features/FileViewer/index.tsx
Labels: 🐛 Bug, size:XS

#5075 💄 style: improve home page loading for better UX
  locales/ar/common.json
  locales/bg-BG/common.json
  locales/de-DE/common.json
  locales/en-US/common.json
  locales/es-ES/common.json
  locales/fa-IR/common.json
  locales/fr-FR/common.json
  locales/it-IT/common.json
  locales/ja-JP/common.json
  locales/ko-KR/common.json
  locales/nl-NL/common.json
  locales/pl-PL/common.json
  locales/pt-BR/common.json
  locales/ru-RU/common.json
  locales/tr-TR/common.json
  locales/vi-VN/common.json
  locales/zh-CN/common.json
  locales/zh-TW/common.json
  src/app/loading/Client/Content.tsx
  src/app/loading/Client/Redirect.tsx
  src/app/loading/Client/index.tsx
  src/app/loading/Server/Content.tsx
  src/app/loading/Server/Redirect.tsx
  src/app/loading/Server/index.tsx
  src/app/loading/index.tsx
  src/app/loading/stage.ts
  src/app/loading/type.ts
  src/components/FullscreenLoading/index.tsx
  src/components/InitProgress/index.tsx
  src/features/MobileSwitchLoading/index.tsx
  src/layout/AuthProvider/NextAuth/UserUpdater.tsx
  src/locales/default/common.ts
Labels: 💄 Design, size:XL

#5076 ⚡️ perf: improve `getUserState` api performance
  src/database/server/models/message.ts
  src/database/server/models/session.ts
  src/server/routers/lambda/user.ts
Labels: ⚡️ Performance, size:M

#5090 👷 build: bump pdf dist version
  package.json
Labels: dependencies, size:XS

#5093 ♻️ refactor: refactor layout props
  package.json
  src/app/(main)/repos/[id]/evals/evaluation/page.tsx
  src/app/(main)/repos/[id]/evals/layout.tsx
Labels: size:S

#5097 ♻️ refactor: refactor to use async `headers()`
  src/app/(main)/(mobile)/me/(home)/page.tsx
  src/app/(main)/(mobile)/me/data/page.tsx
  src/app/(main)/(mobile)/me/profile/page.tsx
  src/app/(main)/(mobile)/me/settings/page.tsx
  src/app/(main)/chat/(workspace)/@conversation/default.tsx
  src/app/(main)/chat/(workspace)/@conversation/features/ChatInput/index.tsx
  src/app/(main)/chat/(workspace)/@portal/default.tsx
  src/app/(main)/chat/(workspace)/@topic/default.tsx
  src/app/(main)/chat/(workspace)/page.tsx
  src/app/(main)/discover/(detail)/assistant/[slug]/page.tsx
  src/app/(main)/discover/(detail)/model/[...slugs]/page.tsx
  src/app/(main)/discover/(detail)/plugin/[slug]/page.tsx
  src/app/(main)/discover/(detail)/provider/[slug]/page.tsx
  src/app/(main)/discover/(list)/assistants/[slug]/page.tsx
  src/app/(main)/discover/(list)/assistants/page.tsx
  src/app/(main)/discover/(list)/models/[slug]/page.tsx
  src/app/(main)/discover/(list)/models/page.tsx
  src/app/(main)/discover/(list)/plugins/[slug]/page.tsx
  src/app/(main)/discover/(list)/plugins/page.tsx
  src/app/(main)/discover/(list)/providers/page.tsx
  src/app/(main)/discover/search/page.tsx
  src/app/(main)/profile/[[...slugs]]/page.tsx
  src/app/(main)/profile/layout.tsx
  src/app/(main)/profile/loading.tsx
  src/app/(main)/settings/about/page.tsx
  src/app/(main)/settings/sync/page.tsx
  src/app/@modal/(.)settings/modal/page.tsx
  src/app/layout.tsx
  src/components/server/ServerLayout.tsx
  src/layout/GlobalProvider/index.tsx
  src/utils/server/responsive.ts
Labels: size:L

#5102 ♻️ refactor: seperate user keyvaults encrpyto from user model
  package.json
  src/database/schemas/user.ts
  src/database/server/models/__tests__/user.test.ts
  src/database/server/models/user.ts
  src/server/modules/KeyVaultsEncrypt/index.ts
  src/server/routers/lambda/user.ts
  src/server/services/user/index.ts
Labels: size:L

#5101 🔨 chore: add locale
  locales/ar/common.json
  locales/bg-BG/common.json
  locales/de-DE/common.json
  locales/en-US/common.json
  locales/es-ES/common.json
  locales/fa-IR/common.json
  locales/fr-FR/common.json
  locales/it-IT/common.json
  locales/ja-JP/common.json
  locales/ko-KR/common.json
  locales/nl-NL/common.json
  locales/pl-PL/common.json
  locales/pt-BR/common.json
  locales/ru-RU/common.json
  locales/tr-TR/common.json
  locales/vi-VN/common.json
  locales/zh-CN/common.json
  locales/zh-TW/common.json
  src/database/server/models/session.ts
  src/locales/default/common.ts
Labels: size:L

#5104 ♻️ refactor: upgrade react scan
  next.config.mjs
  package.json
  src/components/Analytics/ReactScan.tsx
Labels: size:S

#5099 🐛 fix: fix HUGGINGFACE endpoint url
  src/libs/agent-runtime/huggingface/index.ts
Labels: 🐛 Bug, size:XS

#5109 👷 build: upgrade bun version
  vercel.json
Labels: size:XS

#5103 💄 style: Add Gemini flash thinking model
  src/config/modelProviders/google.ts
Labels: size:S

#5114 📝 docs: add troubleshooting guides for logto
  docs/self-hosting/advanced/auth/next-auth/logto.mdx
  docs/self-hosting/advanced/auth/next-auth/logto.zh-CN.mdx
Labels: 📝 Documentation, size:M

#5110 💄 style: Add o1 model in GitHub models
  src/config/modelProviders/github.ts
Labels: Model Provider, size:S

#5111 ♻️ refactor: refactor upload method
  src/database/_deprecated/models/file.ts
  src/server/routers/lambda/file.ts
  src/services/__tests__/upload.test.ts
  src/services/file/ClientS3/index.test.ts
  src/services/file/ClientS3/index.ts
  src/services/file/client.test.ts
  src/services/file/client.ts
  src/services/upload.ts
  src/store/chat/slices/builtinTool/action.test.ts
  src/store/file/slices/upload/action.ts
  src/types/files/upload.ts
Labels: size:XL

#5127 🔨 chore: add init client db code
  src/services/session/client.ts
  src/store/chat/slices/builtinTool/action.test.ts
  src/store/session/slices/sessionGroup/reducer.test.ts
  src/types/clientDB.ts
  src/types/importer.ts
  src/types/meta.ts
  src/types/session/sessionGroup.ts
Labels: size:M

#5132 ♻️ refactor: refactor the client service to deprecated
  src/services/file/_deprecated.test.ts
  src/services/file/_deprecated.ts
  src/services/file/index.ts
  src/services/import/_deprecated.ts
  src/services/import/index.ts
  src/services/message/_deprecated.test.ts
  src/services/message/_deprecated.ts
  src/services/message/index.ts
  src/services/plugin/_deprecated.test.ts
  src/services/plugin/_deprecated.ts
  src/services/plugin/index.ts
  src/services/session/_deprecated.test.ts
  src/services/session/_deprecated.ts
  src/services/session/index.ts
  src/services/topic/_deprecated.ts
  src/services/topic/client.test.ts
  src/services/topic/index.ts
  src/services/user/_deprecated.test.ts
  src/services/user/_deprecated.ts
  src/services/user/index.ts
  src/store/chat/slices/builtinTool/action.test.ts
  src/store/user/slices/common/action.test.ts
Labels: size:M

#5133 ♻️ refactor: move pglite to client service
  locales/en-US/common.json
  src/services/file/client.test.ts
  src/services/file/client.ts
  src/services/file/index.ts
  src/services/import/client.test.ts
  src/services/import/client.ts
  src/services/import/index.ts
  src/services/message/client.test.ts
  src/services/message/client.ts
  src/services/message/index.ts
  src/services/plugin/client.test.ts
  src/services/plugin/client.ts
  src/services/plugin/index.ts
  src/services/session/client.test.ts
  src/services/session/client.ts
  src/services/session/index.ts
  src/services/topic/_deprecated.test.ts
  src/services/topic/client.ts
  src/services/topic/index.ts
  src/services/topic/pglite.test.ts
  src/services/user/client.test.ts
  src/services/user/client.ts
  src/services/user/index.ts
Labels: size:M

#5150 ✨ feat: support thread in client pglite
  src/const/version.ts
  src/features/Conversation/hooks/useChatListActionsBar.tsx
  src/locales/default/common.ts
  src/services/thread/client.ts
  src/services/thread/index.ts
  src/services/thread/server.ts
  src/services/thread/type.ts
  src/store/chat/slices/thread/action.ts
Labels: 🌠 Feature Request, size:L

#5167 🐛 fix: fix image input on pglite
  src/database/server/models/message.ts
  src/services/message/client.ts
Labels: 🐛 Bug, size:M

#5116 ♻️ refactor: refactor sensenova with LobeOpenAICompatibleFactory
  Dockerfile
  Dockerfile.database
  src/app/(main)/settings/llm/ProviderList/SenseNova/index.tsx
  src/app/(main)/settings/llm/ProviderList/providers.tsx
  src/config/llm.ts
  src/const/auth.ts
  src/features/Conversation/Error/APIKeyForm/SenseNova.tsx
  src/features/Conversation/Error/APIKeyForm/index.tsx
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/index.ts
  src/libs/agent-runtime/sensenova/authToken.test.ts
  src/libs/agent-runtime/sensenova/authToken.ts
  src/libs/agent-runtime/sensenova/index.test.ts
  src/libs/agent-runtime/sensenova/index.ts
  src/locales/default/modelProvider.ts
  src/server/modules/AgentRuntime/index.ts
  src/services/_auth.ts
  src/store/user/slices/modelList/selectors/keyVaults.ts
  src/store/user/slices/modelList/selectors/modelConfig.ts
  src/types/user/settings/keyVaults.ts
Labels: size:XL

#5165 💄 style: improve loading brand
  src/app/(main)/(mobile)/me/(home)/loading.tsx
  src/app/(main)/(mobile)/me/data/loading.tsx
  src/app/(main)/(mobile)/me/profile/loading.tsx
  src/app/(main)/(mobile)/me/settings/loading.tsx
  src/app/(main)/chat/(workspace)/@portal/default.tsx
  src/app/(main)/chat/(workspace)/@portal/loading.tsx
  src/app/(main)/chat/@session/default.tsx
  src/app/(main)/chat/loading.tsx
  src/app/(main)/chat/settings/loading.tsx
  src/app/(main)/discover/loading.tsx
  src/app/(main)/files/loading.tsx
  src/app/(main)/profile/loading.tsx
  src/app/(main)/repos/[id]/evals/dataset/page.tsx
  src/app/(main)/repos/[id]/evals/evaluation/page.tsx
  src/app/(main)/settings/@category/default.tsx
  src/app/(main)/settings/_layout/Desktop/SideBar.tsx
  src/app/(main)/settings/loading.tsx
  src/app/loading/Client/Content.tsx
  src/app/loading/Server/Content.tsx
  src/components/Loading/BrandTextLoading/LobeChatText/SVG.tsx
  src/components/Loading/BrandTextLoading/LobeChatText/index.tsx
  src/components/Loading/BrandTextLoading/LobeChatText/style.css
  src/components/Loading/BrandTextLoading/index.tsx
  src/components/Loading/CircleLoading/index.tsx
  src/components/Loading/FullscreenLoading/index.tsx
  src/components/Loading/SkeletonLoading/index.tsx
  src/features/FileViewer/Renderer/TXT/index.tsx
  src/features/Portal/FilePreview/Body/index.tsx
  src/features/Portal/Home/Body/Files/FileList/index.tsx
  src/features/Setting/Footer.tsx
  src/features/Setting/SettingContainer.tsx
Labels: 💄 Design, size:L

#5180 ♻️ refactor: Refactor services code style
  src/server/routers/lambda/agent.ts
  src/services/__tests__/chat.test.ts
  src/services/_auth.ts
  src/services/agent.ts
  src/services/chat.ts
  src/services/file/ClientS3/index.ts
  src/services/file/client.ts
  src/services/file/server.ts
  src/services/import/client.ts
  src/services/import/server.ts
  src/services/import/type.ts
  src/services/knowledgeBase.ts
  src/services/message/_deprecated.ts
  src/services/message/client.ts
  src/services/message/server.ts
  src/services/message/type.ts
  src/services/plugin/client.ts
  src/services/plugin/server.ts
  src/services/rag.ts
  src/services/ragEval.ts
  src/services/session/_deprecated.ts
  src/services/session/client.ts
  src/services/session/server.ts
  src/services/session/type.ts
  src/services/share.ts
  src/services/textToImage.ts
  src/services/thread/client.ts
  src/services/thread/server.ts
  src/services/topic/client.ts
  src/services/topic/server.ts
  src/services/trace.ts
  src/services/user/client.ts
  src/services/user/server.ts
  src/services/user/type.ts
  src/store/chat/slices/message/reducer.ts
  src/types/message/index.ts
Labels: size:XXL

#5183 🐛 fix: fix o1Models list
  src/libs/agent-runtime/openai/index.ts
Labels: 🐛 Bug, size:XS

#5178 💄 style: Support shortcut keys to open session settings
  src/app/(main)/chat/(workspace)/_layout/Desktop/HotKeys.tsx
  src/const/hotkeys.ts
Labels: 🌠 Feature Request, size:XS

#5189 🐛 fix: Fix changelog fetch fail (fix #5187)
  src/app/(main)/changelog/page.tsx
  src/app/@modal/(.)changelog/modal/page.tsx
  src/features/ChangelogModal/index.tsx
  src/features/User/UserPanel/useMenu.tsx
  src/server/services/changelog/index.ts
Labels: 🐛 Bug, size:S

#5190 🐛 fix: Fix changelog fetch fail ( #5187)
  src/server/services/changelog/index.test.ts
Labels: 🐛 Bug, size:XS

#5194 🐛 fix: fix promise error in changelog modal
  src/app/(main)/chat/(workspace)/features/ChangelogModal.tsx
  src/app/(main)/chat/(workspace)/page.tsx
  src/components/Loading/BrandTextLoading/index.tsx
  src/config/featureFlags/schema.ts
  src/server/services/changelog/index.test.ts
  src/server/services/changelog/index.ts
  src/store/serverConfig/selectors.test.ts
Labels: 🐛 Bug, size:M

#5199 💄 style: Update deepseek V3 model
  src/config/modelProviders/deepseek.ts
Labels: 💄 Design, size:S

#5216 ✨ feat: support white list for discover assistant
  src/app/(backend)/webapi/assistant/store/route.ts
  src/config/app.ts
  src/server/modules/AssistantStore/index.test.ts
  src/server/modules/AssistantStore/index.ts
  src/server/modules/EdgeConfig/index.ts
  src/server/services/discover/index.ts
  src/types/discover.ts
Labels: 🌠 Feature Request, size:L

#5195 ✨ feat(auth): add WeChat authentication support
  docs/self-hosting/advanced/auth/next-auth/wechat.mdx
  docs/self-hosting/advanced/auth/next-auth/wechat.zh-CN.mdx
  src/libs/next-auth/sso-providers/index.ts
  src/libs/next-auth/sso-providers/wechat.ts
Labels: 🌠 Feature Request, size:L

#5218 ⚡️ perf: improve setting page performance
  src/app/(main)/discover/(detail)/provider/[slug]/features/ProviderConfig.tsx
  src/app/@modal/(.)settings/modal/index.tsx
  src/app/@modal/(.)settings/modal/layout.tsx
  src/app/@modal/(.)settings/modal/loading.tsx
  src/app/@modal/(.)settings/modal/page.tsx
  src/features/MobileTabBar/index.tsx
  src/features/User/UserAvatar.tsx
  src/features/User/UserPanel/useMenu.tsx
  src/hooks/useInterceptingRoutes.test.ts
  src/hooks/useInterceptingRoutes.ts
Labels: ⚡️ Performance, size:L

#5039 ✨ feat: add custom stream handle support for LobeOpenAICompatibleFactory
  src/config/modelProviders/spark.ts
  src/libs/agent-runtime/qwen/index.test.ts
  src/libs/agent-runtime/qwen/index.ts
  src/libs/agent-runtime/spark/index.test.ts
  src/libs/agent-runtime/spark/index.ts
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.test.ts
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
  src/libs/agent-runtime/utils/streams/index.ts
  src/libs/agent-runtime/utils/streams/spark.test.ts
  src/libs/agent-runtime/utils/streams/spark.ts
Labels: 💄 Design, size:XL

#5226 🐛 fix: fix custom max_token not saved via customModelCards form
  src/app/(main)/settings/llm/components/ProviderModelList/ModelConfigModal/Form.tsx
Labels: 🐛 Bug, size:XS

#5250 ♻️ refactor: refactor the agent runtime payload
  next.config.ts
  src/app/(main)/settings/llm/components/ProviderModelList/ModelConfigModal/Form.tsx
  src/components/MaxTokenSlider.tsx
  src/components/ModelSelect/index.tsx
  src/components/NProgress/index.tsx
  src/const/auth.ts
  src/database/server/models/__tests__/user.test.ts
  src/database/server/models/user.ts
  src/libs/agent-runtime/AgentRuntime.test.ts
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/ollama/index.test.ts
  src/libs/agent-runtime/ollama/index.ts
  src/libs/agent-runtime/openai/__snapshots__/index.test.ts.snap
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
  src/locales/default/components.ts
  src/locales/default/setting.ts
  src/server/modules/AgentRuntime/index.test.ts
  src/server/modules/AgentRuntime/index.ts
  src/services/__tests__/_auth.test.ts
  src/services/__tests__/chat.test.ts
  src/services/_auth.ts
  src/services/chat.ts
  src/types/aiModel.ts
  src/types/aiProvider.ts
  src/types/llm.ts
  src/utils/merge.test.ts
  src/utils/merge.ts
Labels: size:XL

#5236 💄 style: Add o1 model in openai and openrouter models
  src/config/modelProviders/openai.ts
  src/config/modelProviders/openrouter.ts
  src/store/user/slices/modelList/selectors/modelProvider.test.ts
Labels: size:M
