Repository lobehub/lobe-chat, pull requests merged in 2024-08, with the labels that each got.

#3603 🐛 fix: fix multi file upload dupicate
  src/features/FileManager/FileList/EmptyStatus.tsx
  src/features/FileManager/Header/UploadFileButton.tsx
Labels: 🐛 Bug, size:S

#3604 🐛 fix: fix dayjs error in en-US language
  src/layout/GlobalProvider/Locale.tsx
  src/libs/trpc/index.ts
  src/libs/trpc/middleware/jwtPayload.test.ts
  src/libs/trpc/middleware/jwtPayload.ts
  src/libs/trpc/middleware/password.ts
Labels: 🐛 Bug, size:M

#3609 🐛 fix: Feature flag `knowledge_base` doesn't affect ActionBar
  src/features/ChatInput/ActionBar/Knowledge/index.tsx
  src/features/ChatInput/ActionBar/Upload/index.tsx
Labels: size:S

#3589 ✨ feat: Supports Authelia login
  docs/self-hosting/advanced/auth/next-auth/authelia.mdx
  docs/self-hosting/advanced/auth/next-auth/authelia.zh-CN.mdx
  docs/self-hosting/environment-variables/auth.mdx
  docs/self-hosting/environment-variables/auth.zh-CN.mdx
  src/config/auth.ts
  src/libs/next-auth/sso-providers/authelia.ts
  src/libs/next-auth/sso-providers/index.ts
Labels: size:L

#3626 💄 style: Update Qwen models
  src/config/modelProviders/qwen.ts
Labels: size:M

#3627 🐛 fix: bypass vercel deployment protection
  src/server/routers/async/caller.ts
Labels: 🐛 Bug, size:S

#3618 🐛 fix: fix can send message on uploading files
  package.json
  src/app/(main)/settings/_layout/Desktop/index.tsx
  src/components/ModelIcon/index.tsx
  src/database/server/models/__tests__/file.test.ts
  src/database/server/models/embedding.ts
  src/database/server/models/file.ts
  src/features/ChatInput/useSend.ts
  src/features/Setting/SettingContainer.tsx
  src/server/context.ts
  src/store/chat/slices/message/selectors.ts
  src/utils/format.ts
Labels: dependencies, size:L

#3630 ✨ Support logto provider
  src/config/auth.ts
  src/libs/next-auth/auth.config.ts
  src/libs/next-auth/sso-providers/index.ts
  src/libs/next-auth/sso-providers/logto.ts
Labels: 🌠 Feature Request, size:M

#3624 ✨ feat: Supports Cloudflare Zero Trust login
  docs/self-hosting/advanced/auth/next-auth/cloudflare-zero-trust.mdx
  docs/self-hosting/advanced/auth/next-auth/cloudflare-zero-trust.zh-CN.mdx
  docs/self-hosting/environment-variables/auth.mdx
  docs/self-hosting/environment-variables/auth.zh-CN.mdx
  src/config/auth.ts
  src/libs/next-auth/sso-providers/cloudflare-zero-trust.ts
  src/libs/next-auth/sso-providers/index.ts
Labels: 🌠 Feature Request, size:L

#3368 📝 docs: add Japanese README
  README.ja-JP.md
  README.md
  README.zh-CN.md
Labels: size:XL

#3635 💄 style: improve model zhipu config
  Dockerfile
  src/config/llm.ts
  src/config/modelProviders/zhipu.ts
  src/server/globalConfig/index.ts
Labels: 🌠 Feature Request, size:S

#3633 🐛 fix: fix agent setting
  docs/self-hosting/advanced/auth.mdx
  docs/self-hosting/advanced/auth.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/authentik.mdx
  docs/self-hosting/advanced/auth/next-auth/authentik.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/cloudflare-zero-trust.mdx
  docs/self-hosting/advanced/auth/next-auth/cloudflare-zero-trust.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/github.mdx
  docs/self-hosting/advanced/auth/next-auth/github.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/microsoft-entra-id.mdx
  docs/self-hosting/advanced/auth/next-auth/microsoft-entra-id.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/zitadel.mdx
  docs/self-hosting/advanced/auth/next-auth/zitadel.zh-CN.mdx
  locales/ar/chat.json
  locales/bg-BG/chat.json
  locales/de-DE/chat.json
  locales/en-US/chat.json
  locales/es-ES/chat.json
  locales/fr-FR/chat.json
  locales/it-IT/chat.json
  locales/ja-JP/chat.json
  locales/ko-KR/chat.json
  locales/nl-NL/chat.json
  locales/pl-PL/chat.json
  locales/pt-BR/chat.json
  locales/ru-RU/chat.json
  locales/tr-TR/chat.json
  locales/vi-VN/chat.json
  locales/zh-CN/chat.json
  locales/zh-TW/chat.json
  src/app/(main)/chat/settings/features/EditPage.tsx
  src/locales/default/chat.ts
  src/store/agent/slices/chat/selectors.ts
  src/store/chat/slices/message/selectors.ts
Labels: 📝 Documentation, size:M

#3607 📝 docs: Docker for database ver.
  docker-compose/.env.example
  docker-compose/.env.zh-CN.example
  docker-compose/docker-compose.yml
  docker-compose/minio-bucket.config.json
  docs/self-hosting/server-database/docker-compose.mdx
  docs/self-hosting/server-database/docker-compose.zh-CN.mdx
  docs/self-hosting/server-database/docker.zh-CN.mdx
  docs/usage/features/pwa.zh-CN.mdx
Labels: 📝 Documentation, size:XXL, lgtm

#3637 📝 docs: fix curl typo
  docs/self-hosting/server-database/docker-compose.mdx
  docs/self-hosting/server-database/docker.mdx
Labels: 📝 Documentation, size:S

#3638 🐛 fix: improve aysnc error type
  src/database/server/models/asyncTask.ts
  src/server/routers/async/caller.ts
  src/server/routers/async/file.ts
  src/server/services/chunk/index.ts
  src/types/asyncTask.ts
Labels: 🐛 Bug, size:L

#3641 📝 docs: Logto & fix typo.
  docker-compose/.env.example
  docker-compose/.env.zh-CN.example
  docs/self-hosting/advanced/auth/next-auth/github.mdx
  docs/self-hosting/advanced/auth/next-auth/github.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/logto.mdx
  docs/self-hosting/advanced/auth/next-auth/logto.zh-CN.mdx
  docs/self-hosting/environment-variables/auth.mdx
  docs/self-hosting/environment-variables/auth.zh-CN.mdx
  docs/self-hosting/server-database/docker-compose.mdx
  docs/self-hosting/server-database/docker-compose.zh-CN.mdx
Labels: 📝 Documentation, size:L, lgtm

#3634 💄 style: Move model and provider icon components to `@lobehub/icons`
  package.json
  src/app/(main)/chat/(workspace)/_layout/Desktop/ChatHeader/Tags.tsx
  src/app/(main)/chat/(workspace)/features/ShareButton/Preview.tsx
  src/app/(main)/chat/@session/features/SessionListContent/List/Item/index.tsx
  src/app/(main)/settings/llm/ProviderList/Azure/index.tsx
  src/app/(main)/settings/llm/ProviderList/Bedrock/index.tsx
  src/app/(main)/settings/llm/ProviderList/Ollama/index.tsx
  src/app/(main)/settings/llm/ProviderList/OpenAI/index.tsx
  src/app/(main)/settings/llm/ProviderList/providers.tsx
  src/app/(main)/settings/llm/components/ProviderConfig/index.tsx
  src/app/(main)/settings/llm/components/ProviderModelList/CustomModelOption.tsx
  src/app/(main)/settings/llm/components/ProviderModelList/Option.tsx
  src/app/(main)/settings/tts/features/const.tsx
  src/components/ModelIcon/index.tsx
  src/components/ModelProviderIcon/index.tsx
  src/components/ModelSelect/index.tsx
  src/components/ModelTag/ModelIcon.tsx
  src/components/ModelTag/index.tsx
  src/const/url.ts
  src/features/AgentSetting/AgentTTS/options.ts
  src/features/AgentSetting/AgentTTS/options.tsx
  src/features/Conversation/Extras/Assistant.tsx
Labels: 💄 Design, size:XL

#3649 🐛 fix: no user name if Cloudflare Zero Trust with onetimepin
  src/libs/next-auth/sso-providers/cloudflare-zero-trust.ts
Labels: 🐛 Bug, size:XS

#3651 📝 docs: Docker compose for local.
  docker-compose/local/.env.example
  docker-compose/local/.env.zh-CN.example
  docker-compose/local/docker-compose.yml
  docker-compose/production/.env.example
  docker-compose/production/.env.zh-CN.example
  docker-compose/production/docker-compose.yml
  docs/self-hosting/server-database/docker-compose.mdx
  docs/self-hosting/server-database/docker-compose.zh-CN.mdx
Labels: 📝 Documentation, size:L, lgtm

#3653 💄 style: Update Gemini models
  src/config/modelProviders/google.ts
Labels: 💄 Design, Gemini, size:M, lgtm

#3659 🐛 fix: disable ChatGPT-4o Tools Calling
  src/config/modelProviders/openai.ts
Labels: 🐛 Bug, size:XS

#3665 🐛 fix: Fix whisper-1 typo in tts options
  src/app/(main)/settings/tts/features/const.tsx
Labels: size:XS

#3661 📝 docs: improve docker-compose
  docker-compose/local/.env.example
  docker-compose/local/.env.zh-CN.example
  docker-compose/local/docker-compose.yml
  docs/self-hosting/server-database/docker-compose.mdx
  docs/self-hosting/server-database/docker-compose.zh-CN.mdx
Labels: 📝 Documentation, size:L

#3647 👷 build: support Generic OIDC auth
  docs/self-hosting/environment-variables/auth.mdx
  docs/self-hosting/environment-variables/auth.zh-CN.mdx
  src/config/auth.ts
  src/libs/next-auth/sso-providers/generic-oidc.ts
  src/libs/next-auth/sso-providers/index.ts
Labels: 🌠 Feature Request, size:L

#3676 🐛 fix: fix file relative chunks
  locales/en-US/components.json
  src/database/server/models/chunk.ts
Labels: 🐛 Bug, size:XS

#3677 💄 style：Update zhipu models
  src/config/modelProviders/zhipu.ts
Labels: Model Provider, size:S

#3680 💄 style：improve zhipu model tokens
  src/config/modelProviders/zhipu.ts
Labels: 💄 Design, size:XS

#3683 💄 style：improve qwen model tokens
  src/config/modelProviders/qwen.ts
Labels: 💄 Design, size:S

#3685 💄 style: Update Stepfun models info
  src/config/modelProviders/stepfun.ts
Labels: 💄 Design, size:S

#3686 💄 style: fix ms doc file preview
  locales/ar/file.json
  locales/bg-BG/file.json
  locales/de-DE/file.json
  locales/en-US/file.json
  locales/es-ES/file.json
  locales/fr-FR/file.json
  locales/it-IT/file.json
  locales/ja-JP/file.json
  locales/ko-KR/file.json
  locales/nl-NL/file.json
  locales/pl-PL/file.json
  locales/pt-BR/file.json
  locales/ru-RU/file.json
  locales/tr-TR/file.json
  locales/vi-VN/file.json
  locales/zh-CN/file.json
  locales/zh-TW/file.json
  src/components/FileParsingStatus/index.tsx
  src/const/url.ts
  src/features/FileViewer/NotSupport/index.tsx
  src/features/FileViewer/Renderer/MSDoc/index.tsx
  src/features/FileViewer/Renderer/PDF/HighlightLayer.tsx
  src/features/FileViewer/Renderer/PDF/index.tsx
  src/features/FileViewer/Renderer/PDF/style.ts
  src/features/FileViewer/Renderer/PDF/useResizeObserver.ts
  src/features/FileViewer/Renderer/TXT/index.tsx
  src/features/FileViewer/Renderer/index.ts
  src/features/FileViewer/index.tsx
  src/locales/default/file.ts
Labels: 💄 Design, size:L

#3688 💄 style: Update the sorting of each provider model
  src/config/modelProviders/moonshot.ts
  src/config/modelProviders/zeroone.ts
  src/config/modelProviders/zhipu.ts
Labels: 💄 Design, size:M

#3690 💄 style: add preview for image file
  src/features/FileViewer/Renderer/Image/index.tsx
  src/features/FileViewer/Renderer/index.ts
Labels: 💄 Design, size:M

#3670 ✨ feat: add Upstage model provider support
  Dockerfile
  Dockerfile.database
  src/app/(main)/settings/llm/ProviderList/providers.tsx
  src/app/api/chat/agentRuntime.ts
  src/config/llm.ts
  src/config/modelProviders/index.ts
  src/config/modelProviders/upstage.ts
  src/const/settings/llm.ts
  src/features/Conversation/Error/APIKeyForm/ProviderAvatar.tsx
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/types/type.ts
  src/libs/agent-runtime/upstage/index.test.ts
  src/libs/agent-runtime/upstage/index.ts
  src/server/globalConfig/index.ts
  src/types/user/settings/keyVaults.ts
Labels: 🌠 Feature Request, Model Provider, size:L

#3691 💄 style: improve style of file preview
  src/features/FileViewer/index.tsx
Labels: 💄 Design, size:S

#3689 💄 style: Update the sorting of each provider model
  src/config/modelProviders/baichuan.ts
  src/config/modelProviders/minimax.ts
  src/config/modelProviders/qwen.ts
Labels: 💄 Design, size:M

#3687 📝 docs: Docker Compose
  docker-compose/local/.env.example
  docker-compose/production/.env.example
  docker-compose/production/.env.zh-CN.example
  docs/self-hosting/advanced/auth/next-auth/authelia.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/authentik.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/cloudflare-zero-trust.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/github.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/logto.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/microsoft-entra-id.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/zitadel.zh-CN.mdx
  docs/self-hosting/advanced/knowledge-base.mdx
  docs/self-hosting/advanced/knowledge-base.zh-CN.mdx
  docs/self-hosting/advanced/model-list.mdx
  docs/self-hosting/advanced/model-list.zh-CN.mdx
  docs/self-hosting/advanced/s3.mdx
  docs/self-hosting/advanced/s3.zh-CN.mdx
  docs/self-hosting/advanced/s3/cloudflare-r2.zh-CN.mdx
  docs/self-hosting/advanced/s3/tencent-cloud.mdx
  docs/self-hosting/advanced/s3/tencent-cloud.zh-CN.mdx
  docs/self-hosting/environment-variables.mdx
  docs/self-hosting/environment-variables.zh-CN.mdx
  docs/self-hosting/environment-variables/model-provider.zh-CN.mdx
  docs/self-hosting/environment-variables/s3.mdx
  docs/self-hosting/environment-variables/s3.zh-CN.mdx
  docs/self-hosting/examples/azure-openai.mdx
  docs/self-hosting/examples/azure-openai.zh-CN.mdx
  docs/self-hosting/examples/ollama.zh-CN.mdx
  docs/self-hosting/platform/docker.zh-CN.mdx
  docs/self-hosting/platform/netlify.zh-CN.mdx
  docs/self-hosting/platform/vercel.zh-CN.mdx
  docs/self-hosting/server-database.mdx
  docs/self-hosting/server-database/docker-compose.mdx
  docs/self-hosting/server-database/docker-compose.zh-CN.mdx
  docs/self-hosting/server-database/docker.mdx
  docs/self-hosting/server-database/zeabur.mdx
  docs/self-hosting/server-database/zeabur.zh-CN.mdx
  docs/self-hosting/start.mdx
  docs/usage/agents/custom-agent.zh-CN.mdx
  docs/usage/features/local-llm.zh-CN.mdx
  docs/usage/features/multi-ai-providers.zh-CN.mdx
  docs/usage/features/plugin-system.mdx
  docs/usage/features/plugin-system.zh-CN.mdx
  docs/usage/foundation/basic.mdx
  docs/usage/foundation/basic.zh-CN.mdx
  docs/usage/foundation/text2image.mdx
  docs/usage/foundation/text2image.zh-CN.mdx
  docs/usage/plugins/custom-plugin.zh-CN.mdx
  docs/usage/providers/ollama/gemma.zh-CN.mdx
  docs/usage/providers/ollama/qwen.zh-CN.mdx
  docs/usage/tools-calling/openai.mdx
Labels: 📝 Documentation, size:XL, lgtm

#3693 💄 style: Update Qwen and Gemini models info
  src/config/modelProviders/google.ts
  src/config/modelProviders/qwen.ts
Labels: 💄 Design, size:S

#3700 🐛 fix: Typo
  docs/self-hosting/server-database/docker-compose.mdx
  docs/self-hosting/server-database/docker-compose.zh-CN.mdx
Labels: size:XS

#3702 📝 docs: add knowledge base in Readme
  README.md
  README.zh-CN.md
Labels: 📝 Documentation, size:M
