Repository lobehub/lobe-chat, pull requests merged in 2024-11, with the labels that each got.

#4254 ⚡️ perf: support to use signedUrl for S3 if bucket is not public-read
  src/config/file.ts
  src/database/server/models/message.ts
  src/server/modules/S3/index.ts
  src/server/routers/lambda/file.ts
  src/server/routers/lambda/ragEval.ts
  src/server/utils/files.test.ts
  src/server/utils/files.ts
Labels: size:M

#4579 🐛 fix: Fix MS Entra ID and Azure AD authorization
  src/libs/next-auth/sso-providers/azure-ad.ts
  src/libs/next-auth/sso-providers/microsoft-entra-id-helper.ts
  src/libs/next-auth/sso-providers/microsoft-entra-id.ts
Labels: 🐛 Bug, azure, size:M

#4596 🐛 fix: fix duplicate key value violates unique constraint "slug_user_id_unique" when create inbox session
  src/database/server/models/session.ts
Labels: 🐛 Bug, size:XS

#4153 💄 style: disable chunking button for unsupported files
  locales/ar/components.json
  locales/bg-BG/components.json
  locales/de-DE/components.json
  locales/en-US/components.json
  locales/es-ES/components.json
  locales/fr-FR/components.json
  locales/it-IT/components.json
  locales/ja-JP/components.json
  locales/ko-KR/components.json
  locales/nl-NL/components.json
  locales/pl-PL/components.json
  locales/pt-BR/components.json
  locales/ru-RU/components.json
  locales/tr-TR/components.json
  locales/vi-VN/components.json
  locales/zh-CN/components.json
  locales/zh-TW/components.json
  src/features/FileManager/FileList/FileListItem/index.tsx
  src/features/FileManager/FileList/ToolBar/index.tsx
  src/locales/default/components.ts
  src/store/file/slices/chat/action.ts
  src/utils/isChunkingUnsupported.test.ts
  src/utils/isChunkingUnsupported.ts
Labels: 💄 Design, size:M, lgtm

#4610 💄 style: improve group topic styles
  src/app/(main)/chat/(workspace)/@topic/features/TopicListContent/ByTimeMode/GroupItem.tsx
Labels: 💄 Design, size:S

#4607 🐛 fix: remove the 'resetConversation' hot key tip
  src/features/ChatInput/ActionBar/Clear.tsx
Labels: 🐛 Bug, size:XS, lgtm

#4608 💄 style: add claude 3.5 haiku model
  src/config/modelProviders/anthropic.ts
Labels: 💄 Design, size:S

#4626 🗃️ refactor: update database fields
  src/database/server/migrations/0010_add_accessed_at_and_clean_tables.sql
  src/database/server/migrations/meta/0010_snapshot.json
  src/database/server/migrations/meta/_journal.json
  src/database/server/models/__tests__/session.test.ts
  src/database/server/models/__tests__/topic.test.ts
  src/database/server/schemas/lobechat/_helpers.ts
  src/database/server/schemas/lobechat/agent.ts
  src/database/server/schemas/lobechat/asyncTask.ts
  src/database/server/schemas/lobechat/discover.ts
  src/database/server/schemas/lobechat/file.ts
  src/database/server/schemas/lobechat/index.ts
  src/database/server/schemas/lobechat/message.ts
  src/database/server/schemas/lobechat/rag.ts
  src/database/server/schemas/lobechat/ragEvals.ts
  src/database/server/schemas/lobechat/relations.ts
  src/database/server/schemas/lobechat/session.ts
  src/database/server/schemas/lobechat/topic.ts
  src/database/server/schemas/lobechat/user.ts
Labels: size:L

#4629 ♻️ refactor: refactor a few code
  src/app/(backend)/webapi/chat/anthropic/route.ts
  src/app/(backend)/webapi/chat/google/route.ts
  src/app/(backend)/webapi/chat/wenxin/route.ts
  src/app/(main)/settings/llm/components/ProviderConfig/index.tsx
  src/server/globalConfig/index.ts
  src/server/modules/AgentRuntime/index.ts
  src/types/llm.ts
Labels: size:M

#4631 ♻️ refactor: move portal code to features folder
  src/app/(main)/chat/(workspace)/@portal/default.tsx
  src/app/(main)/chat/(workspace)/@portal/features/Header.tsx
  src/features/Portal/Artifacts/Body/Renderer/HTML.tsx
  src/features/Portal/Artifacts/Body/Renderer/React/index.tsx
  src/features/Portal/Artifacts/Body/Renderer/React/template.ts
  src/features/Portal/Artifacts/Body/Renderer/SVG.tsx
  src/features/Portal/Artifacts/Body/Renderer/index.tsx
  src/features/Portal/Artifacts/Body/index.tsx
  src/features/Portal/Artifacts/Header.tsx
  src/features/Portal/Artifacts/index.ts
  src/features/Portal/Artifacts/useEnable.ts
  src/features/Portal/FilePreview/Body/index.tsx
  src/features/Portal/FilePreview/Header.tsx
  src/features/Portal/FilePreview/index.ts
  src/features/Portal/FilePreview/useEnable.ts
  src/features/Portal/Home/Body/Files/FileList/Item.tsx
  src/features/Portal/Home/Body/Files/FileList/index.tsx
  src/features/Portal/Home/Body/Files/index.tsx
  src/features/Portal/Home/Body/Plugins/ArtifactList/Item/index.tsx
  src/features/Portal/Home/Body/Plugins/ArtifactList/Item/style.ts
  src/features/Portal/Home/Body/Plugins/ArtifactList/index.tsx
  src/features/Portal/Home/Body/Plugins/index.tsx
  src/features/Portal/Home/Body/index.tsx
  src/features/Portal/Home/Header.tsx
  src/features/Portal/Home/index.ts
  src/features/Portal/MessageDetail/Body/index.tsx
  src/features/Portal/MessageDetail/Header.tsx
  src/features/Portal/MessageDetail/index.ts
  src/features/Portal/MessageDetail/useEnable.ts
  src/features/Portal/Plugins/Body/ToolRender.tsx
  src/features/Portal/Plugins/Body/index.tsx
  src/features/Portal/Plugins/Footer.tsx
  src/features/Portal/Plugins/Header.tsx
  src/features/Portal/Plugins/index.ts
  src/features/Portal/Plugins/useEnable.ts
  src/features/Portal/components/SkeletonLoading.tsx
  src/features/Portal/router.tsx
  src/features/Portal/type.ts
Labels: size:XS

#4638 Disable model fetch for GitHub
  src/config/modelProviders/github.ts
Labels: size:XS

#4641 ⚡️ perf: reduce server service bundle size by refactoring with constant fold
  src/services/file/index.ts
  src/services/import/index.ts
  src/services/message/index.ts
  src/services/plugin/index.ts
  src/services/session/index.ts
  src/services/topic/index.ts
  src/services/upload.ts
  src/services/user/index.ts
  src/store/user/slices/common/action.ts
  src/store/user/slices/sync/action.ts
Labels: ⚡️ Performance, size:M

#4651 🐛 fix: Fix env var of MS Entra ID
  src/libs/next-auth/sso-providers/microsoft-entra-id-helper.ts
Labels: 🐛 Bug, size:XS

#4655 🐛 fix: fix topic summary field
  src/database/server/models/topic.ts
  src/features/Portal/Artifacts/Body/Renderer/React/index.tsx
  src/server/routers/lambda/topic.ts
  src/store/chat/slices/aiChat/actions/memory.ts
  src/store/chat/slices/topic/selectors.ts
  src/types/topic.ts
Labels: 🐛 Bug, size:S

#4633 💄 style: allow users to disable SSRF or set a whitelist
  docs/self-hosting/environment-variables/basic.mdx
  docs/self-hosting/environment-variables/basic.zh-CN.mdx
  src/app/(backend)/webapi/proxy/route.ts
  src/config/app.ts
Labels: size:M, lgtm

#4656 🐛 fix: fix the display model of history summary
  src/store/chat/slices/aiChat/actions/memory.ts
Labels: 🐛 Bug, size:S

#4644 🐛 fix: disregard remoteModelCards when showModelFetcher is disabled
  src/store/user/slices/modelList/action.ts
Labels: size:S

#4664 🐛 fix: fix summary range
  src/app/loading/Client.tsx
  src/app/loading/Redirect.tsx
  src/app/loading/index.tsx
  src/app/page.tsx
  src/store/chat/slices/aiChat/actions/generateAIChat.ts
Labels: 🐛 Bug, size:M

#3402 ✨ feat: Support Cloudflare Workers AI
  .env.example
  locales/ar/modelProvider.json
  locales/bg-BG/modelProvider.json
  locales/de-DE/modelProvider.json
  locales/en-US/modelProvider.json
  locales/es-ES/modelProvider.json
  locales/fr-FR/modelProvider.json
  locales/it-IT/modelProvider.json
  locales/ja-JP/modelProvider.json
  locales/ko-KR/modelProvider.json
  locales/nl-NL/modelProvider.json
  locales/pl-PL/modelProvider.json
  locales/pt-BR/modelProvider.json
  locales/ru-RU/modelProvider.json
  locales/tr-TR/modelProvider.json
  locales/vi-VN/modelProvider.json
  locales/zh-CN/modelProvider.json
  locales/zh-TW/modelProvider.json
  package.json
  src/app/(main)/settings/llm/ProviderList/Cloudflare/index.tsx
  src/app/(main)/settings/llm/ProviderList/providers.tsx
  src/config/llm.ts
  src/config/modelProviders/cloudflare.ts
  src/config/modelProviders/index.ts
  src/const/auth.ts
  src/const/settings/llm.ts
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/cloudflare/index.test.ts
  src/libs/agent-runtime/cloudflare/index.ts
  src/libs/agent-runtime/types/type.ts
  src/libs/agent-runtime/utils/cloudflareHelpers.test.ts
  src/libs/agent-runtime/utils/cloudflareHelpers.ts
  src/locales/default/modelProvider.ts
  src/server/globalConfig/index.ts
  src/server/modules/AgentRuntime/index.ts
  src/services/_auth.ts
  src/services/chat.ts
  src/store/user/slices/modelList/selectors/keyVaults.ts
  src/store/user/slices/modelList/selectors/modelConfig.ts
  src/types/user/settings/keyVaults.ts
Labels: size:XXL

#4637 📝 docs: Update `docs/usage/features/database.zh-CN.mdx`
  docs/usage/features/database.zh-CN.mdx
Labels: 📝 Documentation, size:XS, lgtm

#4627 ✨ feat: add support xAI provider
  Dockerfile
  Dockerfile.database
  src/app/(main)/settings/llm/ProviderList/providers.tsx
  src/config/llm.ts
  src/config/modelProviders/index.ts
  src/config/modelProviders/xai.ts
  src/const/settings/llm.ts
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/types/type.ts
  src/libs/agent-runtime/xai/index.test.ts
  src/libs/agent-runtime/xai/index.ts
  src/server/globalConfig/index.ts
  src/server/modules/AgentRuntime/index.ts
  src/types/user/settings/keyVaults.ts
Labels: 🌠 Feature Request, size:L

#4502 💄 style: fix Windows always showing scrollbar
  src/app/(main)/chat/(workspace)/@conversation/features/ChatInput/Desktop/FilePreview/FileList.tsx
Labels: 🐛 Bug, size:XS

#4660 👷 build: support to ignore `\n` with `XXX_MODEL_LIST` env
  src/utils/__snapshots__/parseModels.test.ts.snap
  src/utils/parseModels.test.ts
  src/utils/parseModels.ts
Labels: size:S, lgtm

#4674 💄 style: Update deepseek model
  src/config/modelProviders/deepseek.ts
Labels: 💄 Design, size:XS, lgtm

#4649 ♻️ refactor: refactor `languageModel` & `DEFAULT_LLM_CONFIG` generate
  src/const/settings/llm.ts
  src/server/globalConfig/genServerLLMConfig.test.ts
  src/server/globalConfig/genServerLLMConfig.ts
  src/server/globalConfig/index.ts
  src/utils/genUserLLMConfig.test.ts
  src/utils/genUserLLMConfig.ts
Labels: size:XL, lgtm

#4672 💄 style: Fix Cloudflare Workers AI Sort
  src/config/modelProviders/index.ts
Labels: 💄 Design, size:XS

#4679 💄 style: update some provider modellist & fix ai360 baseurl
  src/config/modelProviders/baichuan.ts
  src/config/modelProviders/deepseek.ts
  src/config/modelProviders/qwen.ts
  src/config/modelProviders/siliconcloud.ts
  src/config/modelProviders/wenxin.ts
  src/libs/agent-runtime/ai360/index.test.ts
  src/libs/agent-runtime/ai360/index.ts
Labels: 💄 Design, size:L

#4684 🌐 chore: update models/provider locale
  locales/ar/models.json
  locales/ar/providers.json
  locales/bg-BG/models.json
  locales/bg-BG/providers.json
  locales/de-DE/models.json
  locales/de-DE/providers.json
  locales/en-US/models.json
  locales/en-US/providers.json
  locales/es-ES/models.json
  locales/es-ES/providers.json
  locales/fa-IR/modelProvider.json
  locales/fa-IR/models.json
  locales/fa-IR/providers.json
  locales/fr-FR/models.json
  locales/fr-FR/providers.json
  locales/it-IT/models.json
  locales/it-IT/providers.json
  locales/ja-JP/models.json
  locales/ja-JP/providers.json
  locales/ko-KR/models.json
  locales/ko-KR/providers.json
  locales/nl-NL/models.json
  locales/nl-NL/providers.json
  locales/pl-PL/models.json
  locales/pl-PL/providers.json
  locales/pt-BR/models.json
  locales/pt-BR/providers.json
  locales/ru-RU/models.json
  locales/ru-RU/providers.json
  locales/tr-TR/models.json
  locales/tr-TR/providers.json
  locales/vi-VN/models.json
  locales/vi-VN/providers.json
  locales/zh-CN/modelProvider.json
  locales/zh-CN/models.json
  locales/zh-CN/providers.json
  locales/zh-TW/models.json
  locales/zh-TW/providers.json
  src/config/modelProviders/cloudflare.ts
Labels: 💄 Design, size:XL

#4689 ♻️ refactor: refactor chat conversation
  src/app/(main)/chat/(workspace)/@conversation/default.tsx
  src/app/(main)/chat/(workspace)/@conversation/features/ChatInput/Desktop/Header/index.tsx
  src/app/(main)/chat/(workspace)/@conversation/features/ChatInput/Desktop/index.tsx
  src/app/(main)/chat/(workspace)/@conversation/features/ChatInput/Mobile/index.tsx
  src/app/(main)/chat/(workspace)/@conversation/features/ChatList/Content.tsx
  src/app/(main)/chat/(workspace)/@conversation/features/ChatList/index.tsx
  src/features/ChatInput/ActionBar/config.ts
  src/features/ChatInput/ActionBar/index.tsx
  src/features/ChatInput/types.ts
  src/features/Conversation/components/ChatItem/index.tsx
  src/features/Conversation/components/VirtualizedList/index.tsx
  src/features/Conversation/index.ts
  src/features/Conversation/index.tsx
Labels: size:L

#4685 📝 docs: add docs for cloudflare
  docs/usage/providers/cloudflare.mdx
  docs/usage/providers/cloudflare.zh-CN.mdx
Labels: 📝 Documentation, size:L

#4694 ♻️ refactor: `genServerLLMConfig` function, get *_MODEL_LIST from env
  Dockerfile
  Dockerfile.database
  src/config/llm.ts
  src/server/globalConfig/genServerLLMConfig.test.ts
  src/server/globalConfig/genServerLLMConfig.ts
Labels: 🐛 Bug, size:M

#4699 ♻️ refactor: move ChatInput to `@features/ChatInput`
  src/app/(main)/chat/(workspace)/@conversation/default.tsx
  src/app/(main)/chat/(workspace)/@conversation/features/ChatInput/index.tsx
  src/features/ChatInput/Desktop/FilePreview/FileItem/Content.tsx
  src/features/ChatInput/Desktop/FilePreview/FileItem/index.tsx
  src/features/ChatInput/Desktop/FilePreview/FileItem/style.ts
  src/features/ChatInput/Desktop/FilePreview/FileItem/utils.ts
  src/features/ChatInput/Desktop/FilePreview/FileList.tsx
  src/features/ChatInput/Desktop/FilePreview/index.tsx
  src/features/ChatInput/Desktop/Footer/SendMore.tsx
  src/features/ChatInput/Desktop/Footer/index.tsx
  src/features/ChatInput/Desktop/Header/index.tsx
  src/features/ChatInput/Desktop/TextArea.test.tsx
  src/features/ChatInput/Desktop/TextArea.tsx
  src/features/ChatInput/Desktop/__tests__/useAutoFocus.test.ts
  src/features/ChatInput/Desktop/index.tsx
  src/features/ChatInput/Desktop/useAutoFocus.ts
  src/features/ChatInput/Mobile/Files/FileItem/File.tsx
  src/features/ChatInput/Mobile/Files/FileItem/Image.tsx
  src/features/ChatInput/Mobile/Files/FileItem/index.tsx
  src/features/ChatInput/Mobile/Files/FileItem/style.ts
  src/features/ChatInput/Mobile/Files/index.tsx
  src/features/ChatInput/Mobile/InputArea/Container.tsx
  src/features/ChatInput/Mobile/InputArea/index.tsx
  src/features/ChatInput/Mobile/Send.tsx
  src/features/ChatInput/Mobile/index.tsx
  src/features/ChatInput/components/UploadDetail/UploadStatus.tsx
  src/features/ChatInput/components/UploadDetail/index.tsx
Labels: size:S

#4702 💄 style: Add gemini-exp-1114 model
  src/config/modelProviders/google.ts
Labels: Gemini, size:M

#4708 ⚡️ perf: refactor to improve chat performance
  src/app/(main)/chat/(workspace)/@conversation/features/ChatInput/Desktop/TextArea.test.tsx
  src/app/(main)/chat/(workspace)/@conversation/features/ChatInput/Desktop/TextArea.tsx
  src/app/(main)/chat/(workspace)/@conversation/features/ChatInput/Desktop/index.tsx
  src/app/(main)/chat/(workspace)/@conversation/features/ChatInput/index.tsx
  src/app/(main)/chat/(workspace)/@conversation/features/ChatList/Content.tsx
  src/const/message.ts
  src/features/ChatInput/Desktop/Footer/ShortcutHint.tsx
  src/features/ChatInput/Desktop/Footer/index.tsx
  src/features/ChatInput/Desktop/InputArea/index.tsx
  src/features/ChatInput/Desktop/index.tsx
  src/features/Conversation/Messages/index.ts
  src/features/Conversation/components/ChatItem/index.tsx
  src/features/Conversation/components/VirtualizedList/index.tsx
  src/features/Conversation/index.ts
  src/types/topic/index.ts
  src/types/topic/topic.ts
Labels: ⚡️ Performance, size:XL

#4719 🌐 chore: update i18n
  locales/ar/models.json
  locales/bg-BG/models.json
  locales/de-DE/models.json
  locales/en-US/models.json
  locales/es-ES/models.json
  locales/fa-IR/models.json
  locales/fr-FR/models.json
  locales/it-IT/models.json
  locales/ja-JP/models.json
  locales/ko-KR/models.json
  locales/nl-NL/models.json
  locales/pl-PL/models.json
  locales/pt-BR/models.json
  locales/ru-RU/models.json
  locales/tr-TR/models.json
  locales/vi-VN/models.json
  locales/zh-CN/models.json
  locales/zh-TW/models.json
Labels: size:L

#4720 🌐 chore: update i18n
  locales/ar/models.json
  locales/bg-BG/models.json
  locales/de-DE/models.json
  locales/en-US/models.json
  locales/es-ES/models.json
  locales/fa-IR/models.json
  locales/fr-FR/models.json
  locales/it-IT/models.json
  locales/ja-JP/models.json
  locales/ko-KR/models.json
  locales/nl-NL/models.json
  locales/pl-PL/models.json
  locales/pt-BR/models.json
  locales/ru-RU/models.json
  locales/tr-TR/models.json
  locales/vi-VN/models.json
  locales/zh-TW/models.json
Labels: size:M

#4722 🐛 fix: connection check logic
  locales/ar/error.json
  locales/bg-BG/error.json
  locales/de-DE/error.json
  locales/en-US/error.json
  locales/es-ES/error.json
  locales/fa-IR/error.json
  locales/fr-FR/error.json
  locales/it-IT/error.json
  locales/ja-JP/error.json
  locales/ko-KR/error.json
  locales/nl-NL/error.json
  locales/pl-PL/error.json
  locales/pt-BR/error.json
  locales/ru-RU/error.json
  locales/tr-TR/error.json
  locales/vi-VN/error.json
  locales/zh-CN/error.json
  locales/zh-TW/error.json
  src/app/(main)/settings/llm/components/Checker.tsx
  src/libs/agent-runtime/error.ts
  src/locales/default/error.ts
Labels: 🐛 Bug, size:M

#4711 ✨ feat: add support InternLM (书生浦语) provider
  Dockerfile
  Dockerfile.database
  src/app/(main)/settings/llm/ProviderList/providers.tsx
  src/config/llm.ts
  src/config/modelProviders/index.ts
  src/config/modelProviders/internlm.ts
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/internlm/index.test.ts
  src/libs/agent-runtime/internlm/index.ts
  src/libs/agent-runtime/types/type.ts
  src/server/modules/AgentRuntime/index.ts
  src/types/user/settings/keyVaults.ts
Labels: Model Provider, size:L

#4725 🐛 fix: keyword search for chat history & sessions
  src/database/server/models/__tests__/session.test.ts
  src/database/server/models/session.ts
  src/database/server/models/topic.ts
  src/store/chat/slices/topic/selectors.ts
Labels: 🐛 Bug, size:L

#4732 💄 style: support o1 models using streaming
  src/libs/agent-runtime/github/index.ts
  src/libs/agent-runtime/openai/index.ts
Labels: 💄 Design, size:XS

#4738 ⚡️ perf: fix slow delete file sql
  src/database/server/models/file.ts
  src/server/routers/lambda/file.ts
Labels: ⚡️ Performance, size:M

#4734 💄 style: Add grok-vision-beta model
  src/config/modelProviders/xai.ts
Labels: size:S

#4744 💄 style: update Mistral model list, add `pixtral-large-latest`
  src/config/modelProviders/mistral.ts
Labels: size:S

#4729 ♻️ refactor: refactor the default locale
  locales/ar/models.json
  locales/ar/providers.json
  locales/bg-BG/models.json
  locales/bg-BG/providers.json
  locales/de-DE/models.json
  locales/de-DE/providers.json
  locales/en-US/models.json
  locales/en-US/providers.json
  locales/es-ES/models.json
  locales/es-ES/providers.json
  locales/fa-IR/models.json
  locales/fa-IR/providers.json
  locales/fr-FR/models.json
  locales/fr-FR/providers.json
  locales/it-IT/models.json
  locales/it-IT/providers.json
  locales/ja-JP/models.json
  locales/ja-JP/providers.json
  locales/ko-KR/models.json
  locales/ko-KR/providers.json
  locales/nl-NL/models.json
  locales/nl-NL/providers.json
  locales/pl-PL/models.json
  locales/pl-PL/providers.json
  locales/pt-BR/models.json
  locales/pt-BR/providers.json
  locales/ru-RU/models.json
  locales/ru-RU/providers.json
  locales/tr-TR/models.json
  locales/tr-TR/providers.json
  locales/vi-VN/models.json
  locales/vi-VN/providers.json
  locales/zh-CN/models.json
  locales/zh-CN/providers.json
  locales/zh-TW/models.json
  locales/zh-TW/providers.json
  src/app/metadata.ts
  src/layout/GlobalProvider/index.tsx
  src/locales/resources.ts
  src/server/ld.ts
Labels: size:L

#4773 ♻️ refactor: refactor the main chat
  src/app/(main)/chat/(workspace)/@conversation/features/ChatList/ChatItem/index.tsx
  src/app/(main)/chat/(workspace)/@conversation/features/ChatList/Content.tsx
  src/app/(main)/chat/(workspace)/@conversation/features/ChatList/WelcomeChatItem/InboxWelcome/AgentsSuggest.tsx
  src/app/(main)/chat/(workspace)/@conversation/features/ChatList/WelcomeChatItem/InboxWelcome/QuestionSuggest.tsx
  src/app/(main)/chat/(workspace)/@conversation/features/ChatList/WelcomeChatItem/InboxWelcome/index.tsx
  src/app/(main)/chat/(workspace)/@conversation/features/ChatList/WelcomeChatItem/WelcomeMessage.tsx
  src/app/(main)/chat/(workspace)/@conversation/features/ChatList/WelcomeChatItem/index.tsx
  src/app/(main)/chat/(workspace)/@portal/features/Header.tsx
  src/components/BrandWatermark/index.tsx
  src/const/message.ts
  src/features/Conversation/components/ChatItem/ActionsBar.tsx
  src/features/Conversation/components/ChatItem/index.tsx
  src/features/Conversation/components/VirtualizedList/index.tsx
  src/features/Conversation/index.ts
  src/features/Portal/Artifacts/index.ts
  src/features/Portal/FilePreview/index.ts
  src/features/Portal/Home/Title.tsx
  src/features/Portal/Home/index.ts
  src/features/Portal/MessageDetail/index.ts
  src/features/Portal/Plugins/index.ts
  src/features/Portal/components/Header.tsx
  src/features/Portal/router.tsx
  src/features/Portal/type.ts
  src/features/ShareModal/ShareImage/ChatList/index.tsx
  src/features/ShareModal/ShareImage/Preview.tsx
  src/features/ShareModal/ShareJSON/index.tsx
  src/features/ShareModal/ShareText/index.tsx
  src/layout/GlobalProvider/Debug.tsx
  src/layout/GlobalProvider/index.tsx
  src/store/chat/slices/aiChat/actions/generateAIChat.ts
  src/store/chat/slices/message/action.ts
  src/store/chat/slices/message/selectors.test.ts
  src/store/chat/slices/message/selectors.ts
  src/store/chat/slices/plugin/action.test.ts
  src/store/chat/slices/plugin/action.ts
  src/store/chat/slices/topic/action.ts
Labels: size:XL

#4775 👷 build: pin `langfuse@3.29.1` to fix netlify build
  package.json
Labels: dependencies, size:XS

#4757 💄 style: 更新 HuggingFace 模型列表
  src/config/modelProviders/huggingface.ts
Labels: 💄 Design, size:S

#4776 🐛 fix: fix tool message display
  src/store/chat/slices/message/selectors.ts
Labels: 🐛 Bug, size:XS

#4747 ♻️ refactor: refactor `*_PROXY_URL`, get var from ENV
  Dockerfile
  Dockerfile.database
  src/app/(backend)/_deprecated/createBizOpenAI/createAzureOpenai.ts
  src/app/(backend)/_deprecated/createBizOpenAI/createOpenai.ts
  src/config/llm.ts
  src/config/modelProviders/moonshot.ts
  src/server/globalConfig/genServerLLMConfig.test.ts
  src/server/globalConfig/index.ts
  src/server/modules/AgentRuntime/index.ts
Labels: 🐛 Bug, size:L

#4260 💄 style: support to reset fetched models
  docs/self-hosting/platform/alibaba-cloud.mdx
  docs/self-hosting/platform/btpanel.mdx
  docs/self-hosting/platform/btpanel.zh-CN.mdx
  docs/self-hosting/server-database.mdx
  locales/ar/models.json
  locales/ar/setting.json
  locales/bg-BG/models.json
  locales/bg-BG/setting.json
  locales/de-DE/models.json
  locales/de-DE/setting.json
  locales/en-US/models.json
  locales/en-US/setting.json
  locales/es-ES/models.json
  locales/es-ES/setting.json
  locales/fa-IR/models.json
  locales/fa-IR/setting.json
  locales/fr-FR/models.json
  locales/fr-FR/setting.json
  locales/it-IT/models.json
  locales/it-IT/setting.json
  locales/ja-JP/models.json
  locales/ja-JP/setting.json
  locales/ko-KR/models.json
  locales/ko-KR/setting.json
  locales/nl-NL/models.json
  locales/nl-NL/setting.json
  locales/pl-PL/models.json
  locales/pl-PL/setting.json
  locales/pt-BR/models.json
  locales/pt-BR/setting.json
  locales/ru-RU/models.json
  locales/ru-RU/setting.json
  locales/tr-TR/models.json
  locales/tr-TR/setting.json
  locales/vi-VN/models.json
  locales/vi-VN/setting.json
  locales/zh-CN/models.json
  locales/zh-CN/setting.json
  locales/zh-TW/models.json
  locales/zh-TW/setting.json
  src/app/(main)/settings/llm/components/ProviderModelList/ModelFetcher.tsx
  src/app/layout.tsx
  src/locales/default/setting.ts
  src/store/user/slices/modelList/action.ts
Labels: 🌠 Feature Request, size:M

#4716 ✨ feat: add Gitee AI model provider
  Dockerfile
  Dockerfile.database
  src/app/(main)/settings/llm/ProviderList/providers.tsx
  src/config/llm.ts
  src/config/modelProviders/giteeai.ts
  src/config/modelProviders/index.ts
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/giteeai/index.test.ts
  src/libs/agent-runtime/giteeai/index.ts
  src/libs/agent-runtime/togetherai/__snapshots__/index.test.ts.snap
  src/libs/agent-runtime/types/type.ts
  src/server/globalConfig/index.ts
  src/server/modules/AgentRuntime/index.ts
  src/types/user/settings/keyVaults.ts
Labels: 🌠 Feature Request, Model Provider, size:L

#4783 💄 style: Add gemini-exp-1121 model
  src/config/modelProviders/google.ts
Labels: size:S

#4789 🐛 fix: fix tools calling
  src/store/chat/slices/aiChat/actions/generateAIChat.ts
  src/store/chat/slices/message/selectors.test.ts
Labels: 🐛 Bug, size:S

#4787 🐛 fix: fix `fetchOnClient` functional for Moonshot
  src/services/chat.ts
Labels: 🐛 Bug, size:S

#4799 🐛 fix: fix Qwen baseUrl calling
  src/server/modules/AgentRuntime/index.test.ts
  src/server/modules/AgentRuntime/index.ts
Labels: 🐛 Bug, size:S

#4813 🐛 fix: fix fallback behavior of default mode in AgentRuntime
  src/server/modules/AgentRuntime/index.test.ts
  src/server/modules/AgentRuntime/index.ts
Labels: 🐛 Bug, size:S

#4819 💄 style: improve i18n
  locales/ar/chat.json
  locales/bg-BG/chat.json
  locales/de-DE/chat.json
  locales/en-US/chat.json
  locales/es-ES/chat.json
  locales/fa-IR/chat.json
  locales/fr-FR/chat.json
  locales/it-IT/chat.json
  locales/ja-JP/chat.json
  locales/ko-KR/chat.json
  locales/nl-NL/chat.json
  locales/pl-PL/chat.json
  locales/pt-BR/chat.json
  locales/ru-RU/chat.json
  locales/tr-TR/chat.json
  locales/vi-VN/chat.json
  locales/zh-CN/chat.json
  locales/zh-TW/chat.json
  src/features/Conversation/components/History/index.tsx
  src/features/Portal/Thread/Header/index.tsx
  src/locales/default/chat.ts
Labels: 💄 Design, size:M

#4821 💄 style: Add Google LearnLM model
  src/config/modelProviders/google.ts
Labels: size:S

#4830 📝 docs: add changelog docs
  docs/changelog/2024-07-19-gpt-4o-mini.zh-CN.mdx
  docs/changelog/2024-08-02-lobe-chat-database-docker.zh-CN.mdx
  docs/changelog/2024-08-21-file-upload-and-knowledge-base.zh-CN.mdx
  docs/changelog/2024-09-13-openai-o1-models.zh-CN.mdx
  docs/changelog/2024-09-20-artifacts.zh-CN.mdx
  docs/changelog/2024-10-27-pin-assistant.zh-CN.mdx
  docs/changelog/2024-11-06-share-text-json.zh-CN.mdx
  docs/changelog/2024-11-27-forkable-chat.zh-CN.mdx
  docs/changelog/index.json
Labels: 📝 Documentation, size:L
