Repository lobehub/lobe-chat, pull requests merged in 2024-10, with the labels that each got.

#4229 💄 style: adjust Wenxin icon size
  src/app/(main)/settings/llm/ProviderList/Wenxin/index.tsx
Labels: 💄 Design, size:XS

#4231 👷 build: set `--dns-result-order=ipv4first` as default
  Dockerfile
  Dockerfile.database
Labels: size:XS

#4233 ♻️ refactor: `/api` to `/webapi`
  src/app/webapi/assistant/[id]/route.ts
  src/app/webapi/assistant/store/route.ts
  src/app/webapi/plugin/gateway/route.ts
  src/app/webapi/plugin/gateway/settings.test.ts
  src/app/webapi/plugin/gateway/settings.ts
  src/app/webapi/plugin/store/route.ts
  src/app/webapi/text-to-image/[provider]/route.ts
  src/app/webapi/trace/route.ts
  src/services/__tests__/assistant.test.ts
  src/services/__tests__/tool.test.ts
  src/services/_url.ts
Labels: size:M

#4245 🐛 fix: fix recharts deps in the Artifacts React Renderer
  src/app/(main)/chat/(workspace)/@portal/Artifacts/Body/Renderer/React.tsx
Labels: 🐛 Bug, size:XS

#4256 💄 style: support shadcn compoents in Artifacts
  src/app/(main)/chat/(workspace)/@portal/Artifacts/Body/Renderer/React.tsx
  src/app/(main)/chat/(workspace)/@portal/Artifacts/Body/Renderer/React/index.tsx
  src/app/(main)/chat/(workspace)/@portal/Artifacts/Body/Renderer/React/template.ts
Labels: 💄 Design, size:L

#4264 🐛 fix: fix txt-to-image api
  src/services/_url.ts
Labels: 🐛 Bug, size:XS

#4272 ♻️ refactor: refactor the text to image
  src/services/_url.ts
  src/services/textToImage.ts
Labels: size:XS

#4288 🐛 fix: fix auto rewrite query when user message is too long
  src/middleware.ts
  src/store/chat/slices/message/actions/rag.ts
Labels: 🐛 Bug, size:XS

#4283 💄 style: support yml in file chunk
  src/libs/langchain/file.ts
Labels: 🐛 Bug, size:XS

#4259 ♻️ refactor: Maintainable configurations for casdoor initialization
  docker-compose/local/init_data.json
  docker-compose/local/init_data.json.tar.gz
  docker-compose/local/setup.sh
Labels: size:XL

#4318 💄 style: updata gpt-4o model info
  src/config/modelProviders/openai.ts
  src/config/modelProviders/openrouter.ts
Labels: 💄 Design, size:XS, lgtm

#4319 🔨 chore: fix gpt-4o model ci
  src/libs/agent-runtime/openrouter/__snapshots__/index.test.ts.snap
  src/store/user/slices/modelList/selectors/modelProvider.test.ts
Labels: 🐛 Bug, size:XS

#4287 ♻️ refactor: refactor the backend code for better organization
  src/app/(backend)/_deprecated/createBizOpenAI/auth.test.ts
  src/app/(backend)/_deprecated/createBizOpenAI/auth.ts
  src/app/(backend)/_deprecated/createBizOpenAI/createAzureOpenai.ts
  src/app/(backend)/_deprecated/createBizOpenAI/createOpenai.ts
  src/app/(backend)/_deprecated/createBizOpenAI/index.ts
  src/app/(backend)/api/chat/[provider]/route.test.ts
  src/app/(backend)/api/chat/[provider]/route.ts
  src/app/(backend)/api/chat/models/[provider]/route.ts
  src/app/(backend)/middleware/auth/index.test.ts
  src/app/(backend)/middleware/auth/index.ts
  src/app/(backend)/middleware/auth/utils.test.ts
  src/app/(backend)/middleware/auth/utils.ts
  src/app/(backend)/webapi/plugin/gateway/route.ts
  src/app/(backend)/webapi/stt/openai/route.ts
  src/app/(backend)/webapi/text-to-image/[provider]/route.ts
  src/app/(backend)/webapi/tts/openai/route.ts
  src/libs/agent-runtime/AgentRuntime.test.ts
  src/libs/trpc/middleware/jwtPayload.test.ts
  src/libs/trpc/middleware/jwtPayload.ts
  src/libs/trpc/middleware/keyVaults.ts
  src/server/modules/AgentRuntime/apiKeyManager.test.ts
  src/server/modules/AgentRuntime/apiKeyManager.ts
  src/server/modules/AgentRuntime/index.test.ts
  src/server/modules/AgentRuntime/index.ts
  src/server/routers/async/file.ts
  src/server/routers/async/ragEval.ts
  src/server/routers/lambda/chunk.ts
  src/services/chat.ts
  src/services/ollama.ts
  src/store/chat/slices/message/actions/rag.ts
  src/utils/errorResponse.test.ts
  src/utils/errorResponse.ts
Labels: size:M

#4322 ♻️ refactor: refactor the jwt code
  src/app/(backend)/api/chat/[provider]/route.test.ts
  src/app/(backend)/middleware/auth/index.test.ts
  src/app/(backend)/middleware/auth/index.ts
  src/app/(backend)/middleware/auth/utils.test.ts
  src/app/(backend)/middleware/auth/utils.ts
  src/app/(backend)/webapi/plugin/gateway/route.ts
  src/libs/trpc/middleware/jwtPayload.test.ts
  src/libs/trpc/middleware/jwtPayload.ts
  src/libs/trpc/middleware/keyVaults.ts
  src/utils/server/jwt.test.ts
  src/utils/server/jwt.ts
Labels: size:L

#4323 ♻️ refactor: refactor the agent runtime implement
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/google/index.ts
  src/libs/agent-runtime/utils/streams/anthropic.ts
  src/libs/agent-runtime/utils/streams/azureOpenai.ts
  src/libs/agent-runtime/utils/streams/google-ai.ts
  src/libs/agent-runtime/utils/streams/ollama.ts
  src/libs/agent-runtime/utils/streams/openai.ts
  src/libs/agent-runtime/utils/streams/protocol.ts
  src/libs/agent-runtime/utils/streams/qwen.ts
  src/libs/agent-runtime/utils/streams/wenxin.test.ts
  src/libs/agent-runtime/utils/streams/wenxin.ts
  src/libs/agent-runtime/wenxin/index.ts
  src/libs/agent-runtime/zhipu/index.test.ts
  src/libs/agent-runtime/zhipu/index.ts
Labels: size:L

#4326 📝 docs: update docs for providers
  docs/usage/providers/ai21.mdx
  docs/usage/providers/ai21.zh-CN.mdx
  docs/usage/providers/ai360.mdx
  docs/usage/providers/ai360.zh-CN.mdx
  docs/usage/providers/fireworksai.mdx
  docs/usage/providers/fireworksai.zh-CN.mdx
  docs/usage/providers/github.mdx
  docs/usage/providers/github.zh-CN.mdx
  docs/usage/providers/hunyuan.mdx
  docs/usage/providers/hunyuan.zh-CN.mdx
  docs/usage/providers/siliconcloud.mdx
  docs/usage/providers/siliconcloud.zh-CN.mdx
  docs/usage/providers/spark.mdx
  docs/usage/providers/spark.zh-CN.mdx
  docs/usage/providers/upstage.mdx
  docs/usage/providers/upstage.zh-CN.mdx
  docs/usage/providers/wenxin.mdx
  docs/usage/providers/wenxin.zh-CN.mdx
  docs/usage/providers/zeroone.mdx
  docs/usage/providers/zeroone.zh-CN.mdx
Labels: 📝 Documentation, size:XXL

#4327 💄 style: fix artifacts render markdown
  src/app/(main)/chat/(workspace)/@portal/Artifacts/Body/Renderer/index.tsx
Labels: 💄 Design, size:XS

#4328 👷 build: fix netlify deployment failed
  netlify.toml
Labels: size:XS

#4329 💄styles: update siliconcloud models info (function_call)
  src/config/modelProviders/siliconcloud.ts
Labels: 💄 Design, size:XS

#4252 👷 build: Simplify custom builds for NEXT_PUBLIC vars
  Dockerfile
  Dockerfile.database
  docs/self-hosting/environment-variables.mdx
Labels: 🌠 Feature Request, size:L, lgtm

#4331 :memo: docs(self-hosting): Add deployment link for Alibaba Cloud
  README.zh-CN.md
Labels: 📝 Documentation, size:S, lgtm

#4333 📝 docs: update wenxin provider docs
  docs/usage/providers/wenxin.mdx
  docs/usage/providers/wenxin.zh-CN.mdx
Labels: 📝 Documentation, size:S, lgtm

#4335 🐛 fix: fix SiliconCloud function calling issue, disable stream when using tools
  src/libs/agent-runtime/siliconcloud/index.ts
Labels: 🐛 Bug, size:XS

#4338 📝docs: add casdoor docker compose document
  docker-compose/local/logto/.env.example
  docker-compose/local/logto/.env.zh-CN.example
  docker-compose/local/logto/docker-compose.yml
  docker-compose/local/setup.sh
  docker-compose/production/logto/.env.example
  docker-compose/production/logto/.env.zh-CN.example
  docker-compose/production/logto/docker-compose.yml
  docs/self-hosting/advanced/auth.mdx
  docs/self-hosting/advanced/auth.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/authentik.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/casdoor.mdx
  docs/self-hosting/advanced/auth/next-auth/casdoor.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/cloudflare-zero-trust.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/logto.mdx
  docs/self-hosting/advanced/auth/next-auth/logto.zh-CN.mdx
  docs/self-hosting/environment-variables/auth.mdx
  docs/self-hosting/environment-variables/auth.zh-CN.mdx
  docs/self-hosting/server-database/docker-compose.mdx
  docs/self-hosting/server-database/docker-compose.zh-CN.mdx
  docs/usage/providers/ai21.mdx
  docs/usage/providers/ai360.mdx
  docs/usage/providers/fireworksai.mdx
  docs/usage/providers/github.mdx
  docs/usage/providers/hunyuan.mdx
  docs/usage/providers/siliconcloud.mdx
  docs/usage/providers/spark.mdx
  docs/usage/providers/upstage.mdx
  docs/usage/providers/wenxin.mdx
  docs/usage/providers/zeroone.mdx
Labels: 📝 Documentation, size:XXL

#4349 📝docs: docker compose project name
  docker-compose/local/docker-compose.yml
  docker-compose/local/logto/docker-compose.yml
  docker-compose/local/setup.sh
  docker-compose/local/zitadel/docker-compose.yml
  docker-compose/production/logto/docker-compose.yml
  docker-compose/production/zitadel/docker-compose.yml
  docs/self-hosting/server-database/docker-compose.mdx
  docs/self-hosting/server-database/docker-compose.zh-CN.mdx
Labels: 📝 Documentation, size:L, lgtm

#4350 :bug: fix: allow use email as name in logto
  src/libs/next-auth/sso-providers/logto.ts
Labels: 🐛 Bug, size:XS

#4334 💄 style: support multi-window for PWA
  src/server/manifest.ts
Labels: size:XS, lgtm

#4359 ♻️ refactor: separate message slice and ai-chat slice
  src/features/ChatInput/useSend.ts
  src/store/chat/initialState.ts
  src/store/chat/slices/aiChat/action.test.ts
  src/store/chat/slices/aiChat/action.ts
  src/store/chat/slices/aiChat/actions/rag.ts
  src/store/chat/slices/aiChat/initialState.ts
  src/store/chat/slices/enchance/action.test.ts
  src/store/chat/slices/message/action.test.ts
  src/store/chat/slices/message/action.ts
  src/store/chat/slices/message/initialState.ts
  src/store/chat/slices/message/selectors.test.ts
  src/store/chat/slices/message/selectors.ts
  src/store/chat/slices/plugin/action.test.ts
  src/store/chat/slices/share/action.test.ts
  src/store/chat/slices/topic/action.test.ts
  src/store/chat/store.ts
  src/store/chat/utils/messageMapKey.ts
Labels: size:XXL

#4360 💄 style: Reorder github model list & updata info & add new model
  src/config/modelProviders/github.ts
  src/config/modelProviders/huggingface.ts
Labels: 💄 Design, size:L

#4361 🐛 fix: fix images not go in to chat context
  src/features/Conversation/components/SkeletonList.tsx
  src/store/chat/slices/aiChat/action.ts
  src/store/chat/slices/message/action.ts
  src/store/chat/utils/index.ts
Labels: 🐛 Bug, size:M

#4363 📝 docs: Update cloudflare-zero-trust.zh-CN
  docs/self-hosting/advanced/auth/next-auth/cloudflare-zero-trust.zh-CN.mdx
Labels: 📝 Documentation, size:XS

#4366 📝 docs: Typo Fix
  README.md
Labels: 📝 Documentation, size:XS, lgtm

#4369 📝docs: align variable names
  .env.example
  docker-compose/local/logto/.env.example
  docker-compose/local/logto/.env.zh-CN.example
  docker-compose/production/logto/.env.example
  docker-compose/production/logto/.env.zh-CN.example
  docs/self-hosting/advanced/auth/next-auth/cloudflare-zero-trust.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/logto.mdx
  docs/self-hosting/advanced/auth/next-auth/logto.zh-CN.mdx
  docs/self-hosting/environment-variables/auth.mdx
  docs/self-hosting/environment-variables/auth.zh-CN.mdx
  docs/self-hosting/server-database/docker-compose.mdx
  docs/self-hosting/server-database/docker-compose.zh-CN.mdx
  docs/self-hosting/server-database/docker.mdx
  docs/self-hosting/server-database/docker.zh-CN.mdx
  docs/self-hosting/server-database/zeabur.mdx
  docs/self-hosting/server-database/zeabur.zh-CN.mdx
Labels: 📝 Documentation, size:L, lgtm

#4376 📝docs: fix style tag bug
  docs/self-hosting/advanced/auth/next-auth/casdoor.mdx
  docs/self-hosting/advanced/auth/next-auth/casdoor.zh-CN.mdx
Labels: 📝 Documentation, size:S

#4380 💄 style: add qwen vision model & update qwen2.5 72b to 128k for siliconcloud
  src/config/modelProviders/huggingface.ts
  src/config/modelProviders/siliconcloud.ts
Labels: size:M

#4390 💄 style: Add Yi-Lightning model
  src/config/modelProviders/zeroone.ts
Labels: 💄 Design, size:M

#4394 💄 style: update Fireworks AI model list
  src/config/modelProviders/fireworksai.ts
Labels: 💄 Design, size:M

#4387 📝 docs: add Novita AI in zh-CN readme
  README.zh-CN.md
Labels: 📝 Documentation, size:XS

#4368 :memo: docs(self-hosting): Add deployment link for Alibaba Cloud international site
  README.md
  docs/self-hosting/platform/alibaba-cloud.mdx
  docs/self-hosting/platform/alibaba-cloud.zh-CN.mdx
  docs/self-hosting/start.mdx
  docs/self-hosting/start.zh-CN.mdx
Labels: 📝 Documentation, size:M, lgtm

#4423 👷 build: fix vercel build
  package.json
  src/libs/next-auth/sso-providers/azure-ad.ts
Labels: size:L

#4168 ♻️ refactor: refactor azure ad to ms entra id
  docs/self-hosting/advanced/auth.mdx
  docs/self-hosting/advanced/auth.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/microsoft-entra-id.mdx
  docs/self-hosting/advanced/auth/next-auth/microsoft-entra-id.zh-CN.mdx
  docs/self-hosting/environment-variables/auth.mdx
  docs/self-hosting/environment-variables/auth.zh-CN.mdx
  src/libs/next-auth/sso-providers/index.ts
  src/libs/next-auth/sso-providers/microsoft-entra-id.ts
Labels: 📝 Documentation, size:M, lgtm

#4424 💄 style: add Llama 3.1 Nemotron 70B model & reorder some provider model list
  src/config/modelProviders/moonshot.ts
  src/config/modelProviders/siliconcloud.ts
  src/config/modelProviders/stepfun.ts
  src/config/modelProviders/zeroone.ts
  src/config/modelProviders/zhipu.ts
Labels: 💄 Design, size:L

#4393 💄 style: update Together AI model list, add function call & vision
  src/config/modelProviders/github.ts
  src/config/modelProviders/togetherai.ts
Labels: 💄 Design, size:M

#4427 💄 style: add Ministral model
  src/config/modelProviders/hunyuan.ts
  src/config/modelProviders/mistral.ts
  src/config/modelProviders/zhipu.ts
Labels: 💄 Design, size:L

#4428 💄 style: update wenxin 4.0 turbo model to latest
  src/config/modelProviders/mistral.ts
  src/config/modelProviders/wenxin.ts
Labels: 💄 Design, size:XS

#4391 📝 docs: Update docker.zh-CN.mdx
  docs/self-hosting/server-database/docker.zh-CN.mdx
Labels: 📝 Documentation, size:XS

#4431 ♻️ refactor: Update format utils and shared layout
  src/components/server/MobileNavLayout.tsx
  src/features/Setting/SettingContainer.tsx
  src/utils/format.test.ts
  src/utils/format.ts
Labels: size:L

#4437 🌐 chore: update i18n
  locales/ar/models.json
  locales/bg-BG/models.json
  locales/de-DE/models.json
  locales/en-US/models.json
  locales/es-ES/models.json
  locales/fr-FR/models.json
  locales/it-IT/models.json
  locales/ja-JP/models.json
  locales/ko-KR/models.json
  locales/nl-NL/models.json
  locales/pl-PL/models.json
  locales/pt-BR/models.json
  locales/ru-RU/models.json
  locales/tr-TR/models.json
  locales/vi-VN/models.json
  locales/zh-CN/models.json
  locales/zh-CN/providers.json
  locales/zh-TW/models.json
Labels: size:XXL

#4438 🐛 fix: fix azure-ad
  src/libs/next-auth/sso-providers/azure-ad.ts
Labels: 🐛 Bug, size:XS

#4442 🎨 chore: clean deps
  package.json
Labels: size:XS

#4445 ♻️ refactor: fix dynamic import in rsc
  src/app/layout.tsx
  src/features/DebugUI/Content.tsx
  src/features/DebugUI/index.tsx
  src/layout/GlobalProvider/index.tsx
Labels: size:L

#4446 ⚡️ perf: try to use cssvar mode to improve performance
  package.json
  src/layout/GlobalProvider/AppTheme.tsx
Labels: ⚡️ Performance, size:M

#4447 :recycle: refactor: move responsive to server utils folder
  src/app/(main)/(mobile)/me/(home)/page.tsx
  src/app/(main)/(mobile)/me/data/page.tsx
  src/app/(main)/(mobile)/me/profile/page.tsx
  src/app/(main)/(mobile)/me/settings/page.tsx
  src/app/(main)/chat/(workspace)/@conversation/default.tsx
  src/app/(main)/chat/(workspace)/@portal/default.tsx
  src/app/(main)/chat/(workspace)/@topic/default.tsx
  src/app/(main)/chat/(workspace)/page.tsx
  src/app/(main)/discover/(detail)/assistant/[slug]/page.tsx
  src/app/(main)/discover/(detail)/model/[...slugs]/page.tsx
  src/app/(main)/discover/(detail)/plugin/[slug]/page.tsx
  src/app/(main)/discover/(detail)/provider/[slug]/page.tsx
  src/app/(main)/discover/(list)/assistants/[slug]/page.tsx
  src/app/(main)/discover/(list)/assistants/page.tsx
  src/app/(main)/discover/(list)/models/[slug]/page.tsx
  src/app/(main)/discover/(list)/models/page.tsx
  src/app/(main)/discover/(list)/plugins/[slug]/page.tsx
  src/app/(main)/discover/(list)/plugins/page.tsx
  src/app/(main)/discover/(list)/providers/page.tsx
  src/app/(main)/discover/search/page.tsx
  src/app/(main)/profile/[[...slugs]]/page.tsx
  src/app/(main)/profile/layout.tsx
  src/app/(main)/profile/loading.tsx
  src/app/(main)/settings/about/page.tsx
  src/app/(main)/settings/sync/page.tsx
  src/app/(main)/welcome/page.tsx
  src/app/@modal/(.)settings/modal/page.tsx
  src/app/layout.tsx
  src/components/server/ServerLayout.tsx
  src/layout/GlobalProvider/index.tsx
  src/utils/server/responsive.ts
Labels: size:M

#4452 💄 style: add new claude model
  src/config/modelProviders/anthropic.ts
Labels: 💄 Design, size:S

#4462 🌐 style: improve error i18n
  locales/ar/error.json
  locales/bg-BG/error.json
  locales/de-DE/error.json
  locales/en-US/error.json
  locales/es-ES/error.json
  locales/fr-FR/error.json
  locales/it-IT/error.json
  locales/ja-JP/error.json
  locales/ko-KR/error.json
  locales/nl-NL/error.json
  locales/pl-PL/error.json
  locales/pt-BR/error.json
  locales/ru-RU/error.json
  locales/tr-TR/error.json
  locales/vi-VN/error.json
  locales/zh-CN/error.json
  locales/zh-TW/error.json
  src/locales/default/error.ts
Labels: 💄 Design, size:L

#4463 ♻️ refactor: support `plugin` flag
  src/config/featureFlags/schema.ts
  src/features/AgentSetting/AgentSettings.tsx
  src/features/ChatInput/ActionBar/Tools/index.tsx
  src/store/serverConfig/selectors.test.ts
Labels: plugin, size:M

#4464 ♻️ refactor: remove unused user tables
  src/database/server/migrations/0009_remove_unused_user_tables.sql
  src/database/server/migrations/meta/0009_snapshot.json
  src/database/server/migrations/meta/_journal.json
  src/database/server/schemas/lobechat/user.ts
Labels: size:M

#4465 ♻️ refactor: fix some custom branding details
  src/app/(main)/discover/_layout/Desktop/Header.tsx
  src/app/(main)/settings/llm/index.tsx
  src/app/metadata.ts
  src/const/branding.ts
  src/layout/AuthProvider/Clerk/useAppearance.ts
Labels: 💄 Design, size:M

#4467 Update `docs/self-hosting/server-database.mdx`
  docs/self-hosting/server-database.mdx
Labels: 📝 Documentation, size:XS, lgtm

#4468 💄 style: add bedrock claude-3.5-sonnect-v2
  src/config/modelProviders/bedrock.ts
Labels: size:S

#4474 ✨ feat: support system agent config
  locales/ar/error.json
  locales/ar/setting.json
  locales/bg-BG/error.json
  locales/bg-BG/setting.json
  locales/de-DE/error.json
  locales/de-DE/setting.json
  locales/en-US/error.json
  locales/en-US/setting.json
  locales/es-ES/error.json
  locales/es-ES/setting.json
  locales/fr-FR/error.json
  locales/fr-FR/setting.json
  locales/it-IT/error.json
  locales/it-IT/setting.json
  locales/ja-JP/error.json
  locales/ja-JP/setting.json
  locales/ko-KR/error.json
  locales/ko-KR/setting.json
  locales/nl-NL/error.json
  locales/nl-NL/setting.json
  locales/pl-PL/error.json
  locales/pl-PL/setting.json
  locales/pt-BR/error.json
  locales/pt-BR/setting.json
  locales/ru-RU/error.json
  locales/ru-RU/setting.json
  locales/tr-TR/error.json
  locales/tr-TR/setting.json
  locales/vi-VN/error.json
  locales/vi-VN/setting.json
  locales/zh-CN/error.json
  locales/zh-CN/setting.json
  locales/zh-TW/error.json
  locales/zh-TW/setting.json
  package.json
  src/app/(main)/settings/system-agent/features/createForm.tsx
  src/app/(main)/settings/system-agent/index.tsx
  src/chains/rewriteQuery.ts
  src/components/TextArea/index.tsx
  src/const/settings/systemAgent.ts
  src/features/AgentSetting/AgentModal/ModelSelect.tsx
  src/features/ModelSelect/index.tsx
  src/features/User/UserPanel/useMenu.tsx
  src/locales/default/setting.ts
  src/server/globalConfig/parseSystemAgent.ts
  src/server/services/chunk/index.ts
  src/store/chat/slices/aiChat/actions/rag.ts
  src/store/user/slices/settings/action.ts
  src/types/user/settings/systemAgent.ts
Labels: 💄 Design, size:L

#4481 💄 style: add `*_MODEL_LIST` env to all models
  Dockerfile
  Dockerfile.database
  src/config/llm.ts
  src/server/globalConfig/index.ts
Labels: 💄 Design, size:L, lgtm

#4482 💄 style: update Spark model id & display name
  src/config/modelProviders/spark.ts
Labels: 💄 Design, size:S

#4389 🔧 chore: use dpdm-fast to make lint faster
  package.json
Labels: ⚡️ Performance, size:XS, lgtm

#4484 ♻️ refactor: refactor the Google AI implement
  package.json
  src/app/(main)/chat/(workspace)/_layout/Desktop/Portal.tsx
  src/const/layoutTokens.ts
  src/libs/agent-runtime/google/index.test.ts
  src/libs/agent-runtime/google/index.ts
Labels: size:L

#4495 💄 style: update Google Model list, add `gemini-1.5-flash-8b`
  src/config/modelProviders/google.ts
Labels: 💄 Design, size:S

#4496 ✨ feat: support ZEN mode
  .gitignore
  locales/ar/chat.json
  locales/ar/models.json
  locales/bg-BG/chat.json
  locales/bg-BG/models.json
  locales/de-DE/chat.json
  locales/de-DE/models.json
  locales/en-US/chat.json
  locales/en-US/models.json
  locales/es-ES/chat.json
  locales/es-ES/models.json
  locales/fr-FR/chat.json
  locales/fr-FR/models.json
  locales/it-IT/chat.json
  locales/it-IT/models.json
  locales/ja-JP/chat.json
  locales/ja-JP/models.json
  locales/ko-KR/chat.json
  locales/ko-KR/models.json
  locales/nl-NL/chat.json
  locales/nl-NL/models.json
  locales/pl-PL/chat.json
  locales/pl-PL/models.json
  locales/pt-BR/chat.json
  locales/pt-BR/models.json
  locales/ru-RU/chat.json
  locales/ru-RU/models.json
  locales/tr-TR/chat.json
  locales/tr-TR/models.json
  locales/vi-VN/chat.json
  locales/vi-VN/models.json
  locales/zh-CN/chat.json
  locales/zh-CN/models.json
  locales/zh-TW/chat.json
  locales/zh-TW/models.json
  src/app/(main)/@nav/_layout/Desktop/index.tsx
  src/app/(main)/chat/(workspace)/@conversation/default.tsx
  src/app/(main)/chat/(workspace)/@conversation/features/ZenModeToast/Toast.tsx
  src/app/(main)/chat/(workspace)/@conversation/features/ZenModeToast/index.tsx
  src/app/(main)/chat/(workspace)/_layout/Desktop/ChatHeader/index.tsx
  src/app/(main)/chat/(workspace)/_layout/Desktop/HotKeys.tsx
  src/app/(main)/chat/(workspace)/_layout/Desktop/TopicPanel.tsx
  src/app/(main)/chat/_layout/Desktop/index.tsx
  src/const/hotkeys.ts
  src/locales/default/chat.ts
  src/store/global/action.test.ts
  src/store/global/action.ts
  src/store/global/initialState.ts
  src/store/global/selectors.ts
Labels: 🌠 Feature Request, size:L

#4491 🐛 fix: fix `modelList` merge
  src/store/user/slices/modelList/action.ts
Labels: 🐛 Bug, size:S, lgtm

#4512 💄 style: Update stepfun models
  src/config/modelProviders/stepfun.ts
Labels: 💄 Design, size:XS

#4500 🐛 fix: fix the switch assistant portal not closing
  src/app/(main)/chat/@session/features/SessionListContent/useSwitchSession.ts
Labels: 🐛 Bug, size:XS

#4514 ✨ feat: experimentally support to pin assistant to sidebar
  src/app/(main)/@nav/_layout/Desktop/PinList/index.tsx
  src/app/(main)/@nav/_layout/Desktop/index.tsx
  src/app/(main)/chat/(workspace)/_layout/Desktop/ChatHeader/Main.tsx
  src/app/(main)/chat/_layout/Desktop/SessionPanel.tsx
  src/config/featureFlags/schema.ts
  src/store/serverConfig/selectors.test.ts
  src/store/session/slices/session/helpers.ts
Labels: 🌠 Feature Request, size:L

#4520 ♻️ refactor: refactor the plugin prompts
  src/prompts/plugin/index.test.ts
  src/prompts/plugin/index.ts
  src/prompts/plugin/tools.test.ts
  src/prompts/plugin/tools.ts
  src/services/__tests__/__snapshots__/chat.test.ts.snap
  src/services/__tests__/chat.test.ts
  src/store/tool/selectors/tool.ts
Labels: plugin, size:L

#4521 🐛 fix: fix page not switch when clicking on the pin assistant
  src/app/(main)/@nav/_layout/Desktop/PinList/index.tsx
  src/app/(main)/chat/@session/features/SessionListContent/Inbox/index.tsx
  src/app/(main)/chat/@session/features/SessionListContent/List/index.tsx
  src/hooks/useSwitchSession.ts
Labels: 🐛 Bug, size:S, lgtm

#4493 💄 style: remove SenseChat-Vision model, due to model limitation
  src/config/modelProviders/sensenova.ts
Labels: size:XS, lgtm

#4525 📝 docs: Remove repetitive word
  docs/usage/agents/model.mdx
Labels: 📝 Documentation, size:XS, lgtm

#4524 🐛 fix: fix Huggingface API interrupting when the output exceeds 140 tokens
  src/libs/agent-runtime/huggingface/index.ts
Labels: 🐛 Bug, size:XS, lgtm

#4526 🐛 fix: remove the 'resetConversation' hot key
  src/app/(main)/chat/(workspace)/_layout/Desktop/HotKeys.tsx
  src/const/hotkeys.ts
Labels: 🌠 Feature Request, size:S

#4531 💄 style: improve user guide when not login
  locales/ar/error.json
  locales/ar/models.json
  locales/bg-BG/error.json
  locales/bg-BG/models.json
  locales/de-DE/error.json
  locales/de-DE/models.json
  locales/en-US/error.json
  locales/en-US/models.json
  locales/es-ES/error.json
  locales/es-ES/models.json
  locales/fr-FR/error.json
  locales/fr-FR/models.json
  locales/it-IT/error.json
  locales/it-IT/models.json
  locales/ja-JP/error.json
  locales/ja-JP/models.json
  locales/ko-KR/error.json
  locales/ko-KR/models.json
  locales/nl-NL/error.json
  locales/nl-NL/models.json
  locales/pl-PL/error.json
  locales/pl-PL/models.json
  locales/pt-BR/error.json
  locales/pt-BR/models.json
  locales/ru-RU/error.json
  locales/ru-RU/models.json
  locales/tr-TR/error.json
  locales/tr-TR/models.json
  locales/vi-VN/error.json
  locales/vi-VN/models.json
  locales/zh-CN/error.json
  locales/zh-CN/models.json
  locales/zh-TW/error.json
  locales/zh-TW/models.json
  src/components/Error/Description.tsx
  src/components/Error/RedirectLogin.tsx
  src/components/Error/fetchErrorNotification.tsx
  src/components/Error/loginRequiredNotification.tsx
  src/features/User/UserInfo.tsx
  src/libs/trpc/client/lambda.ts
  src/locales/default/error.ts
  src/store/user/slices/auth/action.ts
Labels: 💄 Design, size:L

#4530 💄 style: add Qwen2.5-72B-Instruct model
  src/config/modelProviders/huggingface.ts
Labels: size:XS

#4532 🐛 fix: Remove PWA Install in Firefox and Arc
  src/app/manifest.ts
  src/features/PWAInstall/index.tsx
  src/hooks/usePWAInstall.test.ts
  src/hooks/usePWAInstall.ts
  src/hooks/usePlatform.test.ts
  src/hooks/usePlatform.ts
  src/utils/platform.test.ts
  src/utils/platform.ts
Labels: 🐛 Bug, size:L

#4523 🐛 fix: Update zhipu param process
  src/libs/agent-runtime/zhipu/index.test.ts
  src/libs/agent-runtime/zhipu/index.ts
Labels: 🐛 Bug, size:M, lgtm

#4541 ⚡️ perf: support more files and images meta info when upload files
  src/libs/langchain/file.ts
  src/prompts/files/file.ts
  src/prompts/files/image.ts
  src/prompts/files/index.ts
  src/services/__tests__/chat.test.ts
  src/services/chat.ts
Labels: ⚡️ Performance, size:L

#4542 ♻️ refactor: refactor the aiChat slice actions
  src/features/ChatInput/useSend.ts
  src/prompts/files/index.test.ts
  src/prompts/files/index.ts
  src/services/chat.ts
  src/store/chat/slices/aiChat/actions/__tests__/action.test.ts
  src/store/chat/slices/aiChat/actions/generateAIChat.ts
  src/store/chat/slices/aiChat/actions/index.ts
  src/store/chat/store.ts
  src/types/message/index.ts
Labels: size:L

#4544 ⚡️ perf: improve knowledge base RAG prompts
  src/database/server/models/chunk.ts
  src/prompts/knowledgeBaseQA/__snapshots__/index.test.ts.snap
  src/prompts/knowledgeBaseQA/chunk.ts
  src/prompts/knowledgeBaseQA/index.test.ts
  src/prompts/knowledgeBaseQA/index.ts
  src/prompts/knowledgeBaseQA/knowledge.ts
  src/prompts/knowledgeBaseQA/userQuery.ts
  src/store/chat/slices/aiChat/actions/__tests__/generateAIChat.test.ts
  src/store/chat/slices/aiChat/actions/__tests__/rag.test.ts
  src/store/chat/slices/aiChat/actions/generateAIChat.ts
  src/store/chat/slices/aiChat/actions/rag.ts
  src/types/chunk/index.ts
Labels: ⚡️ Performance, size:XL

#4548 🐛 fix: fix file image prompts in client mode
  src/services/__tests__/chat.test.ts
  src/services/chat.ts
Labels: 🐛 Bug, size:L

#4499 🐛 fix: fix the artifacts interface not scrolling
  src/app/(main)/chat/(workspace)/@portal/Artifacts/Body/Renderer/index.tsx
  src/app/(main)/chat/(workspace)/@portal/Plugins/Body/index.tsx
  src/app/(main)/chat/(workspace)/@portal/features/Body.tsx
Labels: 🐛 Bug, size:XS

#4554 🐛 fix: fix duplicate error when creating new user
  src/database/server/models/user.ts
  src/libs/langchain/loaders/index.ts
Labels: 🐛 Bug, size:XS

#4551 ♻️ refactor: refactor embedding as plain vector array
  src/libs/agent-runtime/BaseAI.ts
  src/libs/agent-runtime/types/embeddings.ts
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
  src/server/routers/async/file.ts
  src/server/routers/async/ragEval.ts
  src/server/routers/lambda/chunk.ts
Labels: size:M

#4528 📝 docs: add deployment on btpanel
  docs/self-hosting/platform/btpanel.mdx
  docs/self-hosting/platform/btpanel.zh-CN.mdx
Labels: 📝 Documentation, size:M, lgtm

#4556 🐛 fix: fix server `Network connection lost` error
  src/app/(backend)/webapi/assistant/store/route.ts
  src/database/server/schemas/lobechat/agent.ts
  src/database/server/utils/idGenerator.ts
Labels: 🐛 Bug, size:M

#4559 ♻️ refactor: improve server log on chat api
  src/app/(backend)/webapi/chat/[provider]/route.ts
  src/libs/agent-runtime/error.ts
Labels: size:S
