Repository lobehub/lobe-chat, pull requests merged in 2025-02, with the labels that each got.

#5601 🐛 fix: Multiple deepseek-reasoner request errors
  src/libs/agent-runtime/deepseek/index.test.ts
  src/libs/agent-runtime/deepseek/index.ts
Labels: 🐛 Bug, size:L

#5654 💄 style: support thinking for all non-official DeepSeek R1 models
  locales/ar/components.json
  locales/ar/providers.json
  locales/bg-BG/components.json
  locales/bg-BG/providers.json
  locales/de-DE/components.json
  locales/de-DE/providers.json
  locales/en-US/components.json
  locales/en-US/providers.json
  locales/es-ES/components.json
  locales/es-ES/providers.json
  locales/fa-IR/components.json
  locales/fa-IR/providers.json
  locales/fr-FR/components.json
  locales/fr-FR/providers.json
  locales/it-IT/components.json
  locales/it-IT/providers.json
  locales/ja-JP/components.json
  locales/ja-JP/providers.json
  locales/ko-KR/components.json
  locales/ko-KR/providers.json
  locales/nl-NL/components.json
  locales/nl-NL/providers.json
  locales/pl-PL/components.json
  locales/pl-PL/providers.json
  locales/pt-BR/components.json
  locales/pt-BR/providers.json
  locales/ru-RU/components.json
  locales/ru-RU/providers.json
  locales/tr-TR/components.json
  locales/tr-TR/providers.json
  locales/vi-VN/components.json
  locales/vi-VN/providers.json
  locales/zh-CN/components.json
  locales/zh-CN/providers.json
  locales/zh-TW/components.json
  locales/zh-TW/providers.json
  package.json
  src/components/Thinking/index.tsx
  src/const/plugin.ts
  src/features/Conversation/components/ChatItem/index.tsx
  src/features/Conversation/components/ChatItem/utils.ts
  src/features/Conversation/components/MarkdownElements/LobeArtifact/index.ts
  src/features/Conversation/components/MarkdownElements/LobeThinking/index.ts
  src/features/Conversation/components/MarkdownElements/Thinking/Render.tsx
  src/features/Conversation/components/MarkdownElements/Thinking/index.ts
  src/features/Conversation/components/MarkdownElements/Thinking/remarkPlugin.ts
  src/features/Conversation/components/MarkdownElements/index.ts
  src/features/Conversation/components/MarkdownElements/type.ts
  src/locales/default/components.ts
Labels: 💄 Design, size:L

#5647 💄 style: Update siliconcloud models
  src/config/aiModels/siliconcloud.ts
  src/config/modelProviders/siliconcloud.ts
Labels: 💄 Design, size:L

#5670 🐛 fix: fix `<think>` tag crash
  src/features/Conversation/components/MarkdownElements/Thinking/remarkPlugin.ts
Labels: 🐛 Bug, size:XS

#5671 🐛 fix: fix can not stop generating
  src/app/(main)/chat/(workspace)/@portal/_layout/Mobile.tsx
  src/app/(main)/chat/(workspace)/_layout/Desktop/Portal.tsx
  src/components/Thinking/index.tsx
  src/features/Conversation/components/MarkdownElements/LobeThinking/Render.tsx
  src/store/chat/slices/aiChat/actions/__tests__/generateAIChat.test.ts
  src/store/chat/slices/aiChat/actions/generateAIChat.ts
  src/store/chat/slices/aiChat/initialState.ts
  src/store/chat/slices/message/action.ts
  src/store/global/initialState.ts
  src/store/global/selectors.ts
Labels: size:L

#5667 💄 style: Check siliconcloud API-Key Balance
  src/config/modelProviders/siliconcloud.ts
  src/libs/agent-runtime/siliconcloud/index.ts
Labels: size:M

#5673 🔨 chore: unlock @clerk/next
  package.json
Labels: size:XS

#5174 🐛 fix: Optimize requests without historical messages
  src/store/chat/helpers.test.ts
  src/store/chat/helpers.ts
Labels: size:S

#5679 👷 build: fix pnpm cannot be installed via corepack due to key id mismatch
  Dockerfile
  Dockerfile.database
Labels: 🐛 Bug, size:XS

#5676 🐛 fix: fix provider update issue
  src/server/routers/lambda/aiProvider.ts
  src/types/aiProvider.ts
Labels: 🐛 Bug, size:XS

#5680 💄 style: update Fireworks check model and fix check error
  src/config/aiModels/fireworksai.ts
  src/config/modelProviders/fireworksai.ts
Labels: 🐛 Bug, 💄 Design, size:XL

#5624 💄 style: Update perplexity models
  src/config/aiModels/perplexity.ts
  src/config/modelProviders/perplexity.ts
  src/libs/agent-runtime/openrouter/__snapshots__/index.test.ts.snap
Labels: size:L

#5159 🐛 fix: Bind the selected group name in the rename modal.
  src/app/(main)/chat/@session/features/SessionListContent/Modals/RenameGroupModal.tsx
Labels: 🐛 Bug, size:XS

#5290 📝 docs: Refactor the `setup.sh` to make deployment much easier
  docker-compose/local/.env.example
  docker-compose/local/.env.zh-CN.example
  docker-compose/local/docker-compose.yml
  docker-compose/local/init_data.json
  docker-compose/local/s3_data.tar.gz
  docker-compose/local/setup.sh
  docker-compose/setup.sh
  docs/self-hosting/server-database/docker-compose.mdx
  docs/self-hosting/server-database/docker-compose.zh-CN.mdx
Labels: size:XXL

#5708 📝 docs: update sh in docker compose deploy
  docs/self-hosting/server-database/docker-compose.mdx
  docs/self-hosting/server-database/docker-compose.zh-CN.mdx
Labels: 📝 Documentation, size:L

#5719 📝 docs: only detect private ip in port mode
  docker-compose/setup.sh
Labels: 📝 Documentation, size:XS

#5714 🐛 fix: fix `o1` series calling issue
  src/libs/agent-runtime/github/index.ts
  src/libs/agent-runtime/openai/index.ts
Labels: 🐛 Bug, size:M

#5301 ⚡️perf: accelerating docker image builds: from 1 hour to 8 minutes
  .github/workflows/docker-database.yml
  .github/workflows/docker.yml
Labels: ⚡️ Performance, size:L

#5732 🐛 fix: fix invalid utf8 character
  src/database/repositories/dataImporter/index.ts
  src/libs/langchain/loaders/pdf/index.ts
  src/server/routers/async/file.ts
  src/utils/sanitizeUTF8.test.ts
  src/utils/sanitizeUTF8.ts
Labels: 📝 Documentation, size:M

#5691 📝 docs: Add `DEEPSEEK_PROXY_URL` configuration to environment variables
  .env.example
  docs/self-hosting/environment-variables/model-provider.mdx
  docs/self-hosting/environment-variables/model-provider.zh-CN.mdx
Labels: 🌠 Feature Request, size:S

#5736 📝 docs: add deepseek r1 changelog
  docs/changelog/2025-01-22-new-ai-provider.mdx
  docs/changelog/2025-02-02-deepseek-r1.mdx
  docs/changelog/2025-02-02-deepseek-r1.zh-CN.mdx
  docs/changelog/index.json
Labels: 📝 Documentation, size:M

#5683 💄 style: update GitHub Models
  src/config/aiModels/github.ts
  src/config/modelProviders/github.ts
Labels: 💄 Design, size:M

#5613 💄 style: Add/Update Aliyun Cloud Models
  src/config/aiModels/qwen.ts
  src/config/modelProviders/qwen.ts
Labels: 💄 Design, size:L

#5741 💄 style: fix `deepseek-v3` & `qvq` model tag fetch error from SiliconCloud
  src/libs/agent-runtime/siliconcloud/index.ts
Labels: 💄 Design, size:XS

#5739 🐛 fix: fix model ability missing
  src/utils/merge.test.ts
  src/utils/merge.ts
Labels: 🐛 Bug, size:M

#5684 ✨ feat: add reasoning tag support for custom models via UI or ENV
  locales/ar/modelProvider.json
  locales/bg-BG/modelProvider.json
  locales/de-DE/modelProvider.json
  locales/en-US/modelProvider.json
  locales/es-ES/modelProvider.json
  locales/fa-IR/modelProvider.json
  locales/fr-FR/modelProvider.json
  locales/it-IT/modelProvider.json
  locales/ja-JP/modelProvider.json
  locales/ko-KR/modelProvider.json
  locales/nl-NL/modelProvider.json
  locales/pl-PL/modelProvider.json
  locales/pt-BR/modelProvider.json
  locales/ru-RU/modelProvider.json
  locales/tr-TR/modelProvider.json
  locales/vi-VN/modelProvider.json
  locales/zh-CN/modelProvider.json
  locales/zh-TW/modelProvider.json
  src/app/(main)/settings/provider/features/ModelList/CreateNewModelModal/Form.tsx
  src/hooks/useModelSupportReasoning.ts
  src/locales/default/modelProvider.ts
  src/store/aiInfra/slices/aiModel/action.ts
  src/store/aiInfra/slices/aiModel/selectors.ts
  src/store/user/slices/modelList/selectors/modelProvider.ts
  src/types/aiModel.ts
  src/types/llm.ts
  src/utils/_deprecated/parseModels.test.ts
  src/utils/_deprecated/parseModels.ts
  src/utils/parseModels.test.ts
  src/utils/parseModels.ts
Labels: 💄 Design, size:L

#5752 ⚡️ perf: improve code of user panel
  next.config.ts
  src/app/(main)/_layout/Desktop/SideBar/Avatar.tsx
  src/app/(main)/repos/page.tsx
  src/features/User/UserInfo.tsx
  src/features/User/UserPanel/PanelContent.tsx
Labels: 💄 Design, size:M

#5759 🔧 chore: Log fetch cache info
  next.config.ts
Labels: size:XS

#5696 💄 style: update model list, add reasoning tag
  src/config/aiModels/ai360.ts
  src/config/aiModels/fireworksai.ts
  src/config/aiModels/giteeai.ts
  src/config/aiModels/github.ts
  src/config/aiModels/google.ts
  src/config/aiModels/groq.ts
  src/config/aiModels/huggingface.ts
  src/config/aiModels/internlm.ts
  src/config/aiModels/ollama.ts
  src/config/aiModels/openai.ts
  src/config/aiModels/perplexity.ts
  src/config/aiModels/qwen.ts
  src/config/aiModels/siliconcloud.ts
  src/config/aiModels/togetherai.ts
  src/config/aiModels/zhipu.ts
Labels: 💄 Design, size:L

#5764 💄 style: Add Cache, Metadata, FeatureFlag Viewer to DevPanel
  src/features/DevPanel/CacheViewer/DataTable/index.tsx
  src/features/DevPanel/CacheViewer/cacheProvider.tsx
  src/features/DevPanel/CacheViewer/getCacheEntries.ts
  src/features/DevPanel/CacheViewer/index.tsx
  src/features/DevPanel/CacheViewer/schema.ts
  src/features/DevPanel/FeatureFlagViewer/Form.tsx
  src/features/DevPanel/FeatureFlagViewer/index.tsx
  src/features/DevPanel/FloatPanel.tsx
  src/features/DevPanel/MetadataViewer/Ld.tsx
  src/features/DevPanel/MetadataViewer/MetaData.tsx
  src/features/DevPanel/MetadataViewer/Og.tsx
  src/features/DevPanel/MetadataViewer/index.tsx
  src/features/DevPanel/MetadataViewer/useHead.ts
  src/features/DevPanel/PostgresViewer/DataTable/TableCell.tsx
  src/features/DevPanel/PostgresViewer/DataTable/index.tsx
  src/features/DevPanel/PostgresViewer/SchemaSidebar/Columns.tsx
  src/features/DevPanel/PostgresViewer/SchemaSidebar/index.tsx
  src/features/DevPanel/PostgresViewer/index.tsx
  src/features/DevPanel/features/FloatPanel.tsx
  src/features/DevPanel/features/Header.tsx
  src/features/DevPanel/features/Table/TableCell.tsx
  src/features/DevPanel/features/Table/TooltipContent.tsx
  src/features/DevPanel/features/Table/index.tsx
  src/features/DevPanel/index.tsx
Labels: 🌠 Feature Request, size:XXL

#5729 ♻️ refactor: refactor Wenxin with LobeOpenAICompatibleFactory
  Dockerfile
  Dockerfile.database
  docs/usage/providers/wenxin.mdx
  docs/usage/providers/wenxin.zh-CN.mdx
  package.json
  src/app/(backend)/webapi/chat/wenxin/route.test.ts
  src/app/(backend)/webapi/chat/wenxin/route.ts
  src/app/(main)/settings/llm/ProviderList/Wenxin/index.tsx
  src/app/(main)/settings/llm/ProviderList/providers.tsx
  src/app/(main)/settings/provider/(detail)/wenxin/page.tsx
  src/config/aiModels/wenxin.ts
  src/config/llm.ts
  src/config/modelProviders/wenxin.ts
  src/const/auth.ts
  src/features/Conversation/Error/APIKeyForm/Wenxin.tsx
  src/features/Conversation/Error/APIKeyForm/index.tsx
  src/libs/agent-runtime/AgentRuntime.test.ts
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/utils/streams/wenxin.test.ts
  src/libs/agent-runtime/utils/streams/wenxin.ts
  src/libs/agent-runtime/wenxin/index.ts
  src/libs/agent-runtime/wenxin/type.ts
  src/locales/default/modelProvider.ts
  src/server/modules/AgentRuntime/index.test.ts
  src/services/_auth.ts
  src/store/user/slices/modelList/selectors/keyVaults.ts
  src/types/aiProvider.ts
  src/types/user/settings/keyVaults.ts
Labels: size:XXL

#5633 🐛 fix: Artifact Parsing and Rendering Bug Fix for Gemini 2.0 Flash
  .gitignore
  src/features/Conversation/components/ChatItem/utils.test.ts
  src/features/Conversation/components/ChatItem/utils.ts
  src/features/Conversation/components/MarkdownElements/LobeArtifact/rehypePlugin.test.ts
  src/store/chat/slices/portal/selectors.test.ts
  src/store/chat/slices/portal/selectors.ts
Labels: 🐛 Bug, size:XL

#5725 💄 style: Add siliconcloud models
  src/config/aiModels/siliconcloud.ts
  src/config/modelProviders/siliconcloud.ts
Labels: size:L

#5794 🐛 fix: try to fix discover pre-render error
  next.config.ts
  src/app/[variants]/(main)/discover/(detail)/model/[...slugs]/page.tsx
  src/app/[variants]/(main)/discover/(list)/models/[slug]/page.tsx
  src/app/[variants]/(main)/discover/features/StoreSearchBar.tsx
  src/app/[variants]/(main)/discover/layout.tsx
  src/app/[variants]/(main)/discover/search/page.tsx
Labels: 🐛 Bug, size:M

#5769 💄 style: Add Aliyun deepseek-r1 distill models
  src/config/aiModels/qwen.ts
Labels: size:L

#5768 ♻️ refactor: refactor model fetch method
  src/app/(backend)/webapi/chat/models/[provider]/route.ts
  src/libs/agent-runtime/ai360/index.ts
  src/libs/agent-runtime/anthropic/index.ts
  src/libs/agent-runtime/baichuan/index.ts
  src/libs/agent-runtime/cloudflare/index.test.ts
  src/libs/agent-runtime/cloudflare/index.ts
  src/libs/agent-runtime/deepseek/index.ts
  src/libs/agent-runtime/fireworksai/index.ts
  src/libs/agent-runtime/giteeai/index.ts
  src/libs/agent-runtime/github/index.test.ts
  src/libs/agent-runtime/github/index.ts
  src/libs/agent-runtime/google/index.ts
  src/libs/agent-runtime/groq/index.ts
  src/libs/agent-runtime/higress/index.ts
  src/libs/agent-runtime/huggingface/index.ts
  src/libs/agent-runtime/hunyuan/index.ts
  src/libs/agent-runtime/internlm/index.ts
  src/libs/agent-runtime/mistral/index.ts
  src/libs/agent-runtime/moonshot/index.ts
  src/libs/agent-runtime/novita/__snapshots__/index.test.ts.snap
  src/libs/agent-runtime/novita/index.ts
  src/libs/agent-runtime/openai/__snapshots__/index.test.ts.snap
  src/libs/agent-runtime/openai/index.ts
  src/libs/agent-runtime/openrouter/__snapshots__/index.test.ts.snap
  src/libs/agent-runtime/openrouter/index.ts
  src/libs/agent-runtime/qwen/index.ts
  src/libs/agent-runtime/sensenova/index.ts
  src/libs/agent-runtime/siliconcloud/index.ts
  src/libs/agent-runtime/stepfun/index.ts
  src/libs/agent-runtime/togetherai/__snapshots__/index.test.ts.snap
  src/libs/agent-runtime/togetherai/index.test.ts
  src/libs/agent-runtime/togetherai/index.ts
  src/libs/agent-runtime/utils/cloudflareHelpers.test.ts
  src/libs/agent-runtime/utils/cloudflareHelpers.ts
  src/libs/agent-runtime/xai/index.ts
  src/libs/agent-runtime/zeroone/index.ts
  src/libs/agent-runtime/zhipu/index.ts
Labels: Model Provider, size:L

#5800 💄 style: update edtion tag display and improve prerender
  locales/ar/common.json
  locales/ar/modelProvider.json
  locales/ar/models.json
  locales/bg-BG/common.json
  locales/bg-BG/modelProvider.json
  locales/bg-BG/models.json
  locales/de-DE/common.json
  locales/de-DE/modelProvider.json
  locales/de-DE/models.json
  locales/en-US/common.json
  locales/en-US/modelProvider.json
  locales/en-US/models.json
  locales/es-ES/common.json
  locales/es-ES/modelProvider.json
  locales/es-ES/models.json
  locales/fa-IR/common.json
  locales/fa-IR/modelProvider.json
  locales/fa-IR/models.json
  locales/fr-FR/common.json
  locales/fr-FR/modelProvider.json
  locales/fr-FR/models.json
  locales/it-IT/common.json
  locales/it-IT/modelProvider.json
  locales/it-IT/models.json
  locales/ja-JP/common.json
  locales/ja-JP/modelProvider.json
  locales/ja-JP/models.json
  locales/ko-KR/common.json
  locales/ko-KR/modelProvider.json
  locales/ko-KR/models.json
  locales/nl-NL/common.json
  locales/nl-NL/modelProvider.json
  locales/nl-NL/models.json
  locales/pl-PL/common.json
  locales/pl-PL/modelProvider.json
  locales/pl-PL/models.json
  locales/pt-BR/common.json
  locales/pt-BR/modelProvider.json
  locales/pt-BR/models.json
  locales/ru-RU/common.json
  locales/ru-RU/modelProvider.json
  locales/ru-RU/models.json
  locales/tr-TR/common.json
  locales/tr-TR/modelProvider.json
  locales/tr-TR/models.json
  locales/vi-VN/common.json
  locales/vi-VN/modelProvider.json
  locales/vi-VN/models.json
  locales/zh-CN/common.json
  locales/zh-CN/modelProvider.json
  locales/zh-CN/models.json
  locales/zh-TW/common.json
  locales/zh-TW/modelProvider.json
  locales/zh-TW/models.json
  src/app/[variants]/(main)/chat/_layout/Desktop/SessionPanel.tsx
  src/app/[variants]/(main)/chat/_layout/Mobile.tsx
  src/app/[variants]/(main)/chat/layout.ts
  src/app/[variants]/(main)/settings/provider/(detail)/[id]/page.tsx
  src/features/User/PlanTag.tsx
  src/locales/default/common.ts
Labels: 🐛 Bug, size:XXL

#5807 🐛 fix: fix provider 500 issue
  src/app/[variants]/(main)/settings/provider/(detail)/[id]/page.tsx
Labels: 🐛 Bug, size:M

#5812 🐛 fix: fix `/file/[id]` 500 issue
  src/app/[variants]/(main)/files/layout.tsx
  src/app/[variants]/(main)/settings/provider/(detail)/[id]/page.tsx
  src/app/[variants]/(main)/settings/provider/layout.tsx
Labels: size:M

#5813 🐛 fix: try to fix next-auth issue
  src/app/[variants]/(auth)/layout.tsx
  src/app/[variants]/(auth)/login/[[...login]]/page.tsx
  src/app/[variants]/(auth)/next-auth/error/AuthErrorPage.tsx
  src/app/[variants]/(auth)/next-auth/error/page.tsx
  src/app/[variants]/(auth)/signup/[[...signup]]/page.tsx
  src/app/[variants]/page.tsx
  src/layout/GlobalProvider/ImportSettings.tsx
  src/layout/GlobalProvider/StoreInitialization.tsx
  src/layout/GlobalProvider/index.tsx
Labels: 🐛 Bug, size:M

#5825 🐛 fix: Fix/next auth
  package.json
  src/app/[variants]/(main)/layout.tsx
  src/app/[variants]/layout.tsx
  src/app/[variants]/page.tsx
Labels: size:XS

#5829 ♻️ refactor: update changelog cache and upgrade anthropic sdk
  package.json
  src/const/cacheControl.ts
  src/libs/agent-runtime/utils/anthropicHelpers.ts
  src/server/services/changelog/index.ts
Labels: 🐛 Bug, size:S

#5831 🔨 chore: pin `lobe-chat-database@1.51.3` in docker-compose.yml to avoid one-click deploy error
  docker-compose/local/docker-compose.yml
Labels: size:XS

#5833 🐛 fix: fix home next auth error and update pnpm
  Dockerfile.database
  package.json
  src/config/auth.ts
Labels: size:XS

#5861 👷 build: netlify build error during the installation of dependencies
  package.json
Labels: size:XS

#5866 ✨ feat: refactor the auth condition in Next Auth
  .env.example
  Dockerfile.database
  next.config.ts
  src/app/[variants]/(main)/(mobile)/me/(home)/__tests__/UserBanner.test.tsx
  src/app/[variants]/(main)/(mobile)/me/(home)/__tests__/useCategory.test.tsx
  src/app/[variants]/(main)/(mobile)/me/(home)/features/UserBanner.tsx
  src/app/[variants]/(main)/(mobile)/me/(home)/features/useCategory.tsx
  src/app/[variants]/(main)/(mobile)/me/profile/features/Category.tsx
  src/app/[variants]/(main)/profile/(home)/Client.tsx
  src/app/[variants]/(main)/profile/hooks/useCategory.tsx
  src/app/[variants]/(main)/settings/_layout/Mobile/Header.tsx
  src/app/[variants]/page.tsx
  src/config/auth.ts
  src/const/auth.ts
  src/features/User/UserPanel/PanelContent.tsx
  src/features/User/UserPanel/useMenu.tsx
  src/features/User/__tests__/PanelContent.test.tsx
  src/layout/GlobalProvider/StoreInitialization.tsx
  src/libs/agent-runtime/togetherai/__snapshots__/index.test.ts.snap
  src/middleware.ts
  src/services/chat.ts
  src/store/user/slices/auth/action.test.ts
  src/store/user/slices/auth/action.ts
  src/store/user/slices/auth/initialState.ts
  src/store/user/slices/auth/selectors.ts
  src/store/user/slices/common/action.ts
Labels: size:L

#5874 🐛 fix: fix static relative issues
  src/app/[variants]/(main)/(mobile)/me/(home)/__tests__/useCategory.test.tsx
  src/app/[variants]/(main)/(mobile)/me/(home)/page.tsx
  src/app/[variants]/(main)/(mobile)/me/profile/page.tsx
  src/app/[variants]/(main)/(mobile)/me/settings/page.tsx
  src/app/[variants]/(main)/discover/search/page.tsx
  src/app/[variants]/(main)/layout.tsx
  src/app/[variants]/(main)/settings/layout.ts
  src/features/User/__tests__/useMenu.test.tsx
  src/layout/GlobalProvider/StoreInitialization.tsx
  src/layout/GlobalProvider/index.tsx
  src/server/routers/edge/config/index.test.ts
  src/server/routers/edge/config/index.ts
  src/services/__tests__/global.test.ts
  src/services/global.ts
  src/store/serverConfig/action.ts
  src/store/serverConfig/index.ts
  src/store/serverConfig/store.test.ts
  src/store/serverConfig/store.ts
  src/types/serverConfig.ts
Labels: 🐛 Bug, size:L

#5851 💄 style: Add siliconcloud pro models
  src/config/aiModels/siliconcloud.ts
  src/config/modelProviders/siliconcloud.ts
Labels: size:M

#5858 🐛 fix: Add Zhipu param limit
  src/libs/agent-runtime/zhipu/index.ts
Labels: size:XS

#5878 🐛 fix: Fix translation in variants mode
  src/app/[variants]/(auth)/login/[[...login]]/page.tsx
  src/app/[variants]/(auth)/signup/[[...signup]]/page.tsx
  src/app/[variants]/(main)/(mobile)/me/(home)/page.tsx
  src/app/[variants]/(main)/(mobile)/me/data/page.tsx
  src/app/[variants]/(main)/(mobile)/me/profile/page.tsx
  src/app/[variants]/(main)/(mobile)/me/settings/page.tsx
  src/app/[variants]/(main)/changelog/page.tsx
  src/app/[variants]/(main)/chat/(workspace)/page.tsx
  src/app/[variants]/(main)/discover/(detail)/assistant/[slug]/page.tsx
  src/app/[variants]/(main)/discover/(detail)/model/[...slugs]/page.tsx
  src/app/[variants]/(main)/discover/(detail)/plugin/[slug]/page.tsx
  src/app/[variants]/(main)/discover/(detail)/provider/[slug]/page.tsx
  src/app/[variants]/(main)/discover/(list)/(home)/page.tsx
  src/app/[variants]/(main)/discover/(list)/assistants/[slug]/page.tsx
  src/app/[variants]/(main)/discover/(list)/assistants/page.tsx
  src/app/[variants]/(main)/discover/(list)/models/[slug]/page.tsx
  src/app/[variants]/(main)/discover/(list)/models/page.tsx
  src/app/[variants]/(main)/discover/(list)/plugins/[slug]/page.tsx
  src/app/[variants]/(main)/discover/(list)/plugins/page.tsx
  src/app/[variants]/(main)/discover/(list)/providers/page.tsx
  src/app/[variants]/(main)/discover/search/page.tsx
  src/app/[variants]/(main)/profile/(home)/[[...slugs]]/page.tsx
  src/app/[variants]/(main)/profile/security/page.tsx
  src/app/[variants]/(main)/profile/stats/page.tsx
  src/app/[variants]/(main)/settings/about/page.tsx
  src/app/[variants]/(main)/settings/agent/page.tsx
  src/app/[variants]/(main)/settings/common/page.tsx
  src/app/[variants]/(main)/settings/llm/page.tsx
  src/app/[variants]/(main)/settings/provider/page.tsx
  src/app/[variants]/(main)/settings/sync/page.tsx
  src/app/[variants]/(main)/settings/system-agent/page.tsx
  src/app/[variants]/(main)/settings/tts/page.tsx
  src/app/[variants]/@modal/(.)changelog/modal/page.tsx
  src/app/[variants]/layout.tsx
  src/app/[variants]/metadata.ts
  src/middleware.ts
  src/server/translation.ts
  src/utils/server/routeVariants.ts
Labels: 🐛 Bug, size:XL

#5777 💄 style: Update Gemini 2.0 models
  src/config/aiModels/google.ts
  src/config/modelProviders/google.ts
Labels: Gemini, size:L

#5894 🐛 fix: fix changelog modal
  src/app/[variants]/(main)/changelog/error.tsx
  src/app/[variants]/(main)/changelog/modal/page.tsx
  src/app/[variants]/(main)/chat/(workspace)/@portal/error.tsx
  src/app/[variants]/(main)/chat/error.tsx
  src/app/[variants]/(main)/chat/settings/error.tsx
  src/app/[variants]/(main)/discover/(detail)/error.tsx
  src/app/[variants]/(main)/discover/(list)/error.tsx
  src/app/[variants]/(main)/discover/error.tsx
  src/app/[variants]/(main)/error.tsx
  src/app/[variants]/(main)/profile/error.tsx
  src/app/[variants]/(main)/profile/features/ClerkProfile.tsx
  src/app/[variants]/(main)/settings/error.tsx
  src/app/[variants]/@modal/error.tsx
  src/app/[variants]/error.tsx
  src/features/DevPanel/features/Table/TooltipContent.tsx
Labels: 🐛 Bug, size:M

#5906 🐛 fix: fix changelog modal
  src/app/[variants]/@modal/(.)changelog/modal/layout.tsx
  src/middleware.ts
  src/server/services/changelog/index.ts
Labels: size:S

#5904 💄 style: Update ZeroOne models
  src/config/aiModels/zeroone.ts
  src/config/modelProviders/zeroone.ts
Labels: 💄 Design, size:M

#5924 :memo: docs: add docs for webhooks configuration for logto & casdoor
  docs/self-hosting/advanced/auth/next-auth/casdoor.mdx
  docs/self-hosting/advanced/auth/next-auth/casdoor.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/logto.mdx
  docs/self-hosting/advanced/auth/next-auth/logto.zh-CN.mdx
Labels: 📝 Documentation, size:M

#5899 💄 style: Update Cloudflare models
  src/config/aiModels/cloudflare.ts
  src/config/modelProviders/cloudflare.ts
Labels: 💄 Design, size:M

#5910 🐛 fix: rewrite to local container in docker deployment mode
  Dockerfile
  Dockerfile.database
  package.json
  src/app/[variants]/(main)/(mobile)/me/data/page.tsx
  src/app/[variants]/(main)/settings/about/page.tsx
  src/app/[variants]/(main)/settings/sync/page.tsx
  src/config/app.ts
  src/middleware.ts
  src/utils/server/geo.ts
  src/utils/server/responsive.ts
Labels: 🐛 Bug, size:L

#5929 🔨 chore: add vercelIgnoredBuildStep
  scripts/vercelIgnoredBuildStep.js
Labels: size:M

#5919 💄 style: Update openrouter model list
  src/config/aiModels/openrouter.ts
  src/config/modelProviders/openrouter.ts
Labels: 💄 Design, size:L

#5920 💄 style: Update github model list
  src/config/aiModels/github.ts
  src/config/modelProviders/github.ts
Labels: 💄 Design, size:S

#5941 🐛 fix: fix changelog
  src/app/[variants]/(main)/changelog/page.tsx
Labels: 🐛 Bug, size:XS

#5943 👷 build: improve dockerfile of rewrite
  Dockerfile
  Dockerfile.database
  src/app/[variants]/(main)/changelog/modal/page.tsx
Labels: size:S

#5942 📝 docs: Add warnings to disable signup for casdoor
  docs/self-hosting/advanced/auth/next-auth/casdoor.mdx
  docs/self-hosting/advanced/auth/next-auth/casdoor.zh-CN.mdx
  docs/self-hosting/server-database/docker-compose.mdx
  docs/self-hosting/server-database/docker-compose.zh-CN.mdx
Labels: 📝 Documentation, size:M

#5947 💄 style: support Mermaid in Artifacts
  src/features/Portal/Artifacts/Body/Renderer/index.tsx
Labels: 💄 Design, size:XS

#5976 📝 docs: Update `docs/self-hosting/environment-variables/auth.zh-CN.mdx`
  docs/self-hosting/environment-variables/auth.zh-CN.mdx
Labels: 📝 Documentation, size:XS

#5970 🐛 fix: fix language incorrect on hydration
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatList/WelcomeChatItem/InboxWelcome/AgentsSuggest.tsx
  src/app/[variants]/(main)/chat/@session/features/SessionListContent/DefaultMode.tsx
  src/app/[variants]/(main)/chat/settings/features/SubmitAgentButton/SubmitAgentModal.tsx
  src/app/[variants]/(main)/settings/common/features/Theme/index.tsx
  src/chains/__tests__/summaryAgentName.test.ts
  src/chains/__tests__/summaryDescription.test.ts
  src/chains/__tests__/summaryHistory.test.ts
  src/chains/__tests__/summaryTags.test.ts
  src/chains/__tests__/summaryTitle.test.ts
  src/chains/summaryAgentName.ts
  src/chains/summaryDescription.ts
  src/chains/summaryTags.ts
  src/chains/summaryTitle.ts
  src/const/settings/common.ts
  src/features/AgentSetting/AgentMeta/AutoGenerateAvatar.tsx
  src/features/AgentSetting/AgentTTS/index.tsx
  src/features/ChatInput/STT/browser.tsx
  src/features/ChatInput/STT/openai.tsx
  src/features/Conversation/Extras/TTS/index.tsx
  src/features/PluginDevModal/LocalForm.tsx
  src/features/User/UserPanel/LangButton.tsx
  src/hooks/useTTS.ts
  src/layout/GlobalProvider/AppTheme.tsx
  src/middleware.ts
  src/services/__tests__/assistant.test.ts
  src/services/__tests__/tool.test.ts
  src/services/assistant.ts
  src/services/tool.ts
  src/store/global/actions/general.ts
  src/store/global/actions/workspacePane.ts
  src/store/global/helpers.ts
  src/store/global/initialState.ts
  src/store/global/selectors/general.test.ts
  src/store/global/selectors/general.ts
  src/store/global/selectors/index.ts
  src/store/global/selectors/systemStatus.ts
  src/store/global/store.ts
  src/store/user/helpers.ts
  src/store/user/slices/common/action.test.ts
  src/store/user/slices/common/action.ts
  src/store/user/slices/settings/action.ts
  src/store/user/slices/settings/selectors/general.test.ts
  src/store/user/slices/settings/selectors/general.ts
  src/types/user/settings/general.ts
  src/utils/client/cookie.test.ts
  src/utils/client/cookie.ts
  src/utils/client/switchLang.ts
  src/utils/cookie.ts
Labels: 🐛 Bug, size:L

#5985 :memo: docs: Add warning to caching in reverse proxy
  docs/self-hosting/platform/btpanel.mdx
  docs/self-hosting/platform/btpanel.zh-CN.mdx
  docs/self-hosting/server-database/docker-compose.mdx
  docs/self-hosting/server-database/docker-compose.zh-CN.mdx
Labels: 📝 Documentation, size:S

#5964 🐛 fix: fix Aliyun deepseek-r1 reasoning parsing with oneapi
  src/libs/agent-runtime/utils/streams/openai.test.ts
  src/libs/agent-runtime/utils/streams/openai.ts
Labels: 🐛 Bug, size:L

#5954 🐛 fix: Support Aliyun deepseek-r1 reasoning
  src/libs/agent-runtime/utils/streams/qwen.ts
Labels: size:S

#5987 🐛 fix: refactor agent settings modal
  src/app/[variants]/(main)/chat/(workspace)/features/AgentSettings/CategoryContent/index.tsx
  src/app/[variants]/(main)/chat/(workspace)/features/AgentSettings/CategoryContent/useCategory.tsx
  src/app/[variants]/(main)/chat/(workspace)/features/AgentSettings/index.tsx
  src/app/[variants]/(main)/chat/(workspace)/features/SettingButton.tsx
  src/app/[variants]/(main)/chat/settings/modal/page.tsx
  src/app/[variants]/@modal/chat/(.)settings/modal/layout.tsx
  src/app/[variants]/@modal/chat/(.)settings/modal/loading.tsx
  src/app/[variants]/@modal/chat/(.)settings/modal/page.tsx
  src/hooks/useChatSettingsTab.ts
  src/hooks/useInterceptingRoutes.test.ts
  src/hooks/useInterceptingRoutes.ts
  src/store/agent/slices/chat/initialState.ts
Labels: 🐛 Bug, size:L

#5952 💄 style: Optimized MaxToken Slider
  src/components/MaxTokenSlider.tsx
Labels: 💄 Design, size:S

#5926 :construction_worker: chore: Add configuration check for docker compose at setup.sh
  docker-compose/local/docker-compose.yml
  docs/self-hosting/advanced/auth/next-auth/casdoor.mdx
Labels: size:S

#6002 💄 style: support mistral proxy url
  src/config/modelProviders/mistral.ts
Labels: 💄 Design, size:XS

#5995 👷 build: improve Docker workflow
  .github/workflows/docker-database.yml
  .github/workflows/docker.yml
  .github/workflows/lighthouse.yml
Labels: size:L, Build Docker

#6020 👷 build: fix docker image
  .github/workflows/docker.yml
Labels: size:XS

#6025 ♻️ refactor: refactor the agent runtime test case
  src/libs/agent-runtime/hunyuan/index.test.ts
  src/libs/agent-runtime/providerTestUtils.ts
Labels: size:XL

#6030 💄 style: update i18n
  locales/ar/models.json
  locales/bg-BG/models.json
  locales/de-DE/models.json
  locales/en-US/models.json
  locales/es-ES/models.json
  locales/fa-IR/models.json
  locales/fr-FR/models.json
  locales/it-IT/models.json
  locales/ja-JP/models.json
  locales/ko-KR/models.json
  locales/nl-NL/models.json
  locales/pl-PL/models.json
  locales/pt-BR/models.json
  locales/ru-RU/models.json
  locales/tr-TR/models.json
  locales/vi-VN/models.json
  locales/zh-CN/models.json
  locales/zh-TW/models.json
  package.json
Labels: 💄 Design, size:XXL

#6029 ✨ feat: support tencent cloud
  src/config/aiModels/index.ts
  src/config/aiModels/tencentcloud.ts
  src/config/modelProviders/index.ts
  src/config/modelProviders/tencentcloud.ts
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/tencentcloud/index.test.ts
  src/libs/agent-runtime/tencentcloud/index.ts
  src/libs/agent-runtime/types/type.ts
  src/types/user/settings/keyVaults.ts
Labels: 🌠 Feature Request, size:L

#6031 💄 style: update provider i18n
  locales/ar/providers.json
  locales/bg-BG/providers.json
  locales/de-DE/providers.json
  locales/en-US/providers.json
  locales/es-ES/providers.json
  locales/fa-IR/providers.json
  locales/fr-FR/providers.json
  locales/it-IT/providers.json
  locales/ja-JP/providers.json
  locales/ko-KR/providers.json
  locales/nl-NL/providers.json
  locales/pl-PL/providers.json
  locales/pt-BR/providers.json
  locales/ru-RU/providers.json
  locales/tr-TR/providers.json
  locales/vi-VN/providers.json
  locales/zh-CN/providers.json
  locales/zh-TW/providers.json
Labels: 💄 Design, size:M

#5903 🐛 fix: fix reasoning output for OpenRouter reasoning models like deepseek-r1
  src/config/modelProviders/openrouter.ts
  src/libs/agent-runtime/openrouter/index.test.ts
  src/libs/agent-runtime/openrouter/index.ts
  src/libs/agent-runtime/utils/streams/openai.test.ts
  src/libs/agent-runtime/utils/streams/openai.ts
Labels: 🌠 Feature Request, size:L

#6043 🐛 fix: disable openrouter client fetch
  README.ja-JP.md
  README.md
  README.zh-CN.md
  README.zh-TW.md
  contributing/Others/Lighthouse.md
  contributing/Others/Lighthouse.zh-CN.md
  src/config/modelProviders/openrouter.ts
Labels: 📝 Documentation, size:L

#6058 🐛 fix: fix tencent cloud api issue
  .env.example
  Dockerfile
  Dockerfile.database
  src/config/llm.ts
  src/server/modules/AgentRuntime/index.ts
Labels: 🐛 Bug, size:S

#6060 🐛 fix: fix ai model abilities issue
  src/database/repositories/aiInfra/index.ts
  src/features/DevPanel/SystemInspector/AiProviderRuntimeConfig.tsx
  src/features/DevPanel/SystemInspector/JsonViewer.tsx
  src/features/DevPanel/SystemInspector/ServerConfig.tsx
  src/features/DevPanel/SystemInspector/index.tsx
  src/features/DevPanel/features/FloatPanel.tsx
  src/features/DevPanel/index.tsx
Labels: 🐛 Bug, size:L

#6063 🐛 fix: fix latex in thinking tag render
  src/features/Conversation/components/ChatItem/index.tsx
  src/features/Conversation/components/MarkdownElements/Thinking/index.ts
  src/features/Conversation/components/MarkdownElements/remarkPlugins/createRemarkCustomTagPlugin.ts
  src/features/Conversation/components/MarkdownElements/remarkPlugins/getNodeContent.test.ts
  src/features/Conversation/components/MarkdownElements/remarkPlugins/getNodeContent.ts
Labels: 🐛 Bug, size:L

#6070 📝 docs: update docs of next-auth in vercel deployment
  docs/self-hosting/environment-variables/auth.mdx
  docs/self-hosting/environment-variables/auth.zh-CN.mdx
Labels: 📝 Documentation, size:S

#6071 🐛 fix: fix not enable models correctly
  src/database/repositories/aiInfra/index.test.ts
  src/database/repositories/aiInfra/index.ts
Labels: 🐛 Bug, size:L

#6056 💄 style: Update model list
  src/config/aiModels/cloudflare.ts
  src/config/aiModels/huggingface.ts
  src/config/modelProviders/cloudflare.ts
  src/config/modelProviders/huggingface.ts
Labels: 💄 Design, size:S

#6080 🐛 fix: fix model fetch for spark
  locales/ar/modelProvider.json
  locales/bg-BG/modelProvider.json
  locales/de-DE/modelProvider.json
  locales/en-US/modelProvider.json
  locales/es-ES/modelProvider.json
  locales/fa-IR/modelProvider.json
  locales/fr-FR/modelProvider.json
  locales/it-IT/modelProvider.json
  locales/ja-JP/modelProvider.json
  locales/ko-KR/modelProvider.json
  locales/nl-NL/modelProvider.json
  locales/pl-PL/modelProvider.json
  locales/pt-BR/modelProvider.json
  locales/ru-RU/modelProvider.json
  locales/tr-TR/modelProvider.json
  locales/vi-VN/modelProvider.json
  locales/zh-CN/auth.json
  locales/zh-CN/changelog.json
  locales/zh-CN/chat.json
  locales/zh-CN/clerk.json
  locales/zh-CN/common.json
  locales/zh-CN/components.json
  locales/zh-CN/discover.json
  locales/zh-CN/error.json
  locales/zh-CN/file.json
  locales/zh-CN/knowledgeBase.json
  locales/zh-CN/metadata.json
  locales/zh-CN/migration.json
  locales/zh-CN/modelProvider.json
  locales/zh-CN/models.json
  locales/zh-CN/plugin.json
  locales/zh-CN/portal.json
  locales/zh-CN/providers.json
  locales/zh-CN/ragEval.json
  locales/zh-CN/setting.json
  locales/zh-CN/thread.json
  locales/zh-CN/tool.json
  locales/zh-CN/topic.json
  locales/zh-CN/welcome.json
  locales/zh-TW/modelProvider.json
  src/app/[variants]/(main)/settings/provider/features/ModelList/ModelItem.tsx
  src/app/[variants]/(main)/settings/provider/features/ModelList/ModelTitle/index.tsx
  src/app/[variants]/(main)/settings/provider/features/ModelList/ProviderSettingsContext.ts
  src/app/[variants]/(main)/settings/provider/features/ModelList/index.tsx
  src/config/modelProviders/spark.ts
  src/const/version.ts
  src/database/server/models/aiModel.ts
  src/locales/default/modelProvider.ts
  src/server/routers/lambda/aiModel.ts
  src/services/aiModel/client.ts
  src/services/aiModel/server.ts
  src/services/aiModel/type.ts
  src/store/aiInfra/slices/aiModel/action.ts
  src/types/aiProvider.ts
Labels: 🐛 Bug, Model Provider, size:L

#6076 docs: update custom model list instructions
  docs/self-hosting/advanced/model-list.mdx
  docs/self-hosting/advanced/model-list.zh-CN.mdx
Labels: 📝 Documentation, size:M

#6112 🐛 fix: fix api key input issue
  src/app/[variants]/(main)/settings/provider/(detail)/[id]/page.tsx
  src/features/Conversation/Error/APIKeyForm/LoadingContext.ts
  src/features/Conversation/Error/APIKeyForm/ProviderApiKeyForm.tsx
  src/features/Conversation/Error/APIKeyForm/index.tsx
  src/features/Conversation/Error/APIKeyForm/useApiKey.ts
Labels: size:L

#6115 🐛 fix: fix provider form api key
  locales/ar/modelProvider.json
  locales/bg-BG/modelProvider.json
  locales/de-DE/modelProvider.json
  locales/en-US/modelProvider.json
  locales/es-ES/modelProvider.json
  locales/fa-IR/modelProvider.json
  locales/fr-FR/modelProvider.json
  locales/it-IT/modelProvider.json
  locales/ja-JP/modelProvider.json
  locales/ko-KR/modelProvider.json
  locales/nl-NL/modelProvider.json
  locales/pl-PL/modelProvider.json
  locales/pt-BR/modelProvider.json
  locales/ru-RU/modelProvider.json
  locales/tr-TR/modelProvider.json
  locales/vi-VN/modelProvider.json
  locales/zh-CN/modelProvider.json
  locales/zh-TW/modelProvider.json
  src/app/[variants]/(main)/settings/provider/features/CreateNewProvider/index.tsx
  src/locales/default/modelProvider.ts
  src/server/manifest.ts
Labels: 🐛 Bug, size:M

#6055 ♻️ refactor: improve model fetch behavior
  src/config/aiModels/spark.ts
  src/libs/agent-runtime/ai360/index.ts
  src/libs/agent-runtime/anthropic/index.ts
  src/libs/agent-runtime/baichuan/index.ts
  src/libs/agent-runtime/cloudflare/index.ts
  src/libs/agent-runtime/deepseek/index.ts
  src/libs/agent-runtime/fireworksai/index.ts
  src/libs/agent-runtime/giteeai/index.ts
  src/libs/agent-runtime/github/index.test.ts
  src/libs/agent-runtime/github/index.ts
  src/libs/agent-runtime/google/index.ts
  src/libs/agent-runtime/groq/index.ts
  src/libs/agent-runtime/higress/index.ts
  src/libs/agent-runtime/huggingface/index.ts
  src/libs/agent-runtime/hunyuan/index.ts
  src/libs/agent-runtime/internlm/index.ts
  src/libs/agent-runtime/lmstudio/index.ts
  src/libs/agent-runtime/mistral/index.ts
  src/libs/agent-runtime/moonshot/index.ts
  src/libs/agent-runtime/novita/index.ts
  src/libs/agent-runtime/ollama/index.test.ts
  src/libs/agent-runtime/ollama/index.ts
  src/libs/agent-runtime/openai/__snapshots__/index.test.ts.snap
  src/libs/agent-runtime/openai/index.ts
  src/libs/agent-runtime/openrouter/__snapshots__/index.test.ts.snap
  src/libs/agent-runtime/openrouter/index.ts
  src/libs/agent-runtime/qwen/index.ts
  src/libs/agent-runtime/sensenova/index.ts
  src/libs/agent-runtime/siliconcloud/index.ts
  src/libs/agent-runtime/stepfun/index.ts
  src/libs/agent-runtime/tencentcloud/index.ts
  src/libs/agent-runtime/togetherai/index.ts
  src/libs/agent-runtime/xai/index.ts
  src/libs/agent-runtime/zeroone/index.ts
  src/libs/agent-runtime/zhipu/authToken.test.ts
  src/libs/agent-runtime/zhipu/authToken.ts
  src/libs/agent-runtime/zhipu/index.test.ts
  src/libs/agent-runtime/zhipu/index.ts
Labels: size:XXL

#6149 💄 style: improve advanced params settings
  locales/ar/modelProvider.json
  locales/ar/setting.json
  locales/bg-BG/modelProvider.json
  locales/bg-BG/setting.json
  locales/de-DE/modelProvider.json
  locales/de-DE/setting.json
  locales/en-US/modelProvider.json
  locales/en-US/setting.json
  locales/es-ES/modelProvider.json
  locales/es-ES/setting.json
  locales/fa-IR/modelProvider.json
  locales/fa-IR/setting.json
  locales/fr-FR/modelProvider.json
  locales/fr-FR/setting.json
  locales/it-IT/modelProvider.json
  locales/it-IT/setting.json
  locales/ja-JP/modelProvider.json
  locales/ja-JP/setting.json
  locales/ko-KR/modelProvider.json
  locales/ko-KR/setting.json
  locales/nl-NL/modelProvider.json
  locales/nl-NL/setting.json
  locales/pl-PL/modelProvider.json
  locales/pl-PL/setting.json
  locales/pt-BR/modelProvider.json
  locales/pt-BR/setting.json
  locales/ru-RU/modelProvider.json
  locales/ru-RU/setting.json
  locales/tr-TR/modelProvider.json
  locales/tr-TR/setting.json
  locales/vi-VN/modelProvider.json
  locales/vi-VN/setting.json
  locales/zh-CN/modelProvider.json
  locales/zh-CN/setting.json
  locales/zh-TW/modelProvider.json
  locales/zh-TW/setting.json
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatInput/Desktop/index.tsx
  src/components/InfoTooltip/index.tsx
  src/components/Loading/UpdateLoading/index.tsx
  src/features/ChatInput/ActionBar/Params/ParamsControls.tsx
  src/features/ChatInput/ActionBar/Params/index.tsx
  src/features/ChatInput/ActionBar/Temperature.tsx
  src/features/ChatInput/ActionBar/config.ts
  src/features/ChatInput/Mobile/index.tsx
  src/features/ModelParamsControl/FrequencyPenalty.tsx
  src/features/ModelParamsControl/PresencePenalty.tsx
  src/features/ModelParamsControl/Temperature.tsx
  src/features/ModelParamsControl/TopP.tsx
  src/features/ModelParamsControl/index.ts
  src/locales/default/setting.ts
Labels: 🌠 Feature Request, size:L

#6158 👷 build: update ai provider docs url
  README.ja-JP.md
  README.md
  README.zh-CN.md
  README.zh-TW.md
  docs/changelog/2024-11-25-november-providers.mdx
  docs/changelog/2024-11-25-november-providers.zh-CN.mdx
  docs/usage/features/multi-ai-providers.mdx
  docs/usage/features/multi-ai-providers.zh-CN.mdx
  src/const/url.ts
Labels: 📝 Documentation, size:M

#6154 ✨ feat: add vLLM provider support
  Dockerfile
  Dockerfile.database
  src/app/[variants]/(main)/settings/llm/ProviderList/providers.tsx
  src/config/aiModels/index.ts
  src/config/aiModels/vllm.ts
  src/config/llm.ts
  src/config/modelProviders/index.ts
  src/config/modelProviders/vllm.ts
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/types/type.ts
  src/libs/agent-runtime/vllm/index.ts
  src/types/user/settings/keyVaults.ts
Labels: 🌠 Feature Request, size:L

#6160 💄 style: update openrouter model list and descriptions
  src/config/aiModels/openrouter.ts
  src/config/modelProviders/openrouter.ts
Labels: 💄 Design, size:M

#6079 🐛 fix: fix Azure OpenAI O1 models and refactor the Azure OpenAI implement
  package.json
  src/libs/agent-runtime/AgentRuntime.test.ts
  src/libs/agent-runtime/azureOpenai/index.test.ts
  src/libs/agent-runtime/azureOpenai/index.ts
  src/libs/agent-runtime/utils/streams/azureOpenai.test.ts
  src/libs/agent-runtime/utils/streams/azureOpenai.ts
  src/libs/agent-runtime/utils/streams/index.ts
  src/server/modules/AgentRuntime/index.test.ts
Labels: 🐛 Bug, azure, size:XL

#4647 📝docs: add deployment on tencent cloud lighthouse
  docs/self-hosting/platform/tencentcloud-lighthouse.mdx
  docs/self-hosting/platform/tencentcloud-lighthouse.zh-CN.mdx
  docs/self-hosting/start.zh-CN.mdx
Labels: 📝 Documentation, size:M

#6168 📝 docs: update langfuse Chinese docs
  docs/changelog/2025-02-02-deepseek-r1.mdx
  docs/self-hosting/advanced/auth/next-auth/casdoor.mdx
  docs/self-hosting/advanced/auth/next-auth/casdoor.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/logto.mdx
  docs/self-hosting/advanced/auth/next-auth/logto.zh-CN.mdx
  docs/self-hosting/advanced/model-list.zh-CN.mdx
  docs/self-hosting/advanced/observability/langfuse.zh-CN.mdx
  docs/self-hosting/environment-variables/auth.mdx
  docs/self-hosting/environment-variables/auth.zh-CN.mdx
  docs/self-hosting/platform/btpanel.mdx
  docs/self-hosting/platform/btpanel.zh-CN.mdx
  docs/self-hosting/platform/tencentcloud-lighthouse.mdx
  docs/self-hosting/platform/tencentcloud-lighthouse.zh-CN.mdx
  docs/self-hosting/server-database.mdx
  docs/usage/providers/wenxin.mdx
  docs/usage/providers/wenxin.zh-CN.mdx
Labels: 📝 Documentation, size:L

#6153 🐛 fix: Avoid blank reasoning
  src/features/Conversation/Messages/Assistant/index.tsx
Labels: 🐛 Bug, size:XS

#6067 📝 docs: Updated broken hyperlink
  docs/self-hosting/server-database/docker-compose.mdx
Labels: 📝 Documentation, size:XS

#5850 💄 style: add deepseek r1 distill models for qwen series
  src/config/aiModels/qwen.ts
  src/config/modelProviders/qwen.ts
Labels: 🌠 Feature Request, Model Provider, size:L

#6176 💄 style: improve mobile params style
  package.json
  src/features/ChatInput/ActionBar/Params/ParamsControls.tsx
  src/features/ChatInput/ActionBar/Params/index.tsx
Labels: 💄 Design, 📱 Mobile Device, size:S

#5927 ✨ feat: Add configurable PDF processing method with Unstructured
  src/config/knowledge.ts
  src/server/modules/ContentChunk/index.ts
  src/server/modules/ContentChunk/rules.test.ts
  src/server/modules/ContentChunk/rules.ts
Labels: 🌠 Feature Request, size:L

#6189 🔨 chore: update vercel build ignore mode
  scripts/vercelIgnoredBuildStep.js
Labels: size:XS

#6185 📝 docs: Update README for 2025
  README.ja-JP.md
  README.md
  README.zh-CN.md
  README.zh-TW.md
  contributing/Others/Lighthouse.md
  contributing/Others/Lighthouse.zh-CN.md
  docs/self-hosting/advanced/auth/next-auth/casdoor.mdx
  docs/self-hosting/advanced/auth/next-auth/casdoor.zh-CN.mdx
  docs/self-hosting/server-database.mdx
  docs/self-hosting/server-database/docker-compose.zh-CN.mdx
  docs/usage/features/agent-market.mdx
  docs/usage/features/agent-market.zh-CN.mdx
  docs/usage/features/artifacts.mdx
  docs/usage/features/artifacts.zh-CN.mdx
  docs/usage/features/auth.mdx
  docs/usage/features/auth.zh-CN.mdx
  docs/usage/features/branching-conversations.mdx
  docs/usage/features/branching-conversations.zh-CN.mdx
  docs/usage/features/cot.mdx
  docs/usage/features/cot.zh-CN.mdx
  docs/usage/features/database.mdx
  docs/usage/features/database.zh-CN.mdx
  docs/usage/features/knowledge-base.mdx
  docs/usage/features/knowledge-base.zh-CN.mdx
  docs/usage/features/local-llm.mdx
  docs/usage/features/local-llm.zh-CN.mdx
  docs/usage/features/mobile.mdx
  docs/usage/features/mobile.zh-CN.mdx
  docs/usage/features/multi-ai-providers.mdx
  docs/usage/features/multi-ai-providers.zh-CN.mdx
  docs/usage/features/plugin-system.mdx
  docs/usage/features/plugin-system.zh-CN.mdx
  docs/usage/features/pwa.mdx
  docs/usage/features/pwa.zh-CN.mdx
  docs/usage/features/text-to-image.mdx
  docs/usage/features/text-to-image.zh-CN.mdx
  docs/usage/features/theme.mdx
  docs/usage/features/theme.zh-CN.mdx
  docs/usage/features/tts.mdx
  docs/usage/features/tts.zh-CN.mdx
  docs/usage/features/vision.mdx
  docs/usage/features/vision.zh-CN.mdx
  scripts/readmeWorkflow/syncAgentIndex.ts
  scripts/readmeWorkflow/syncPluginIndex.ts
  scripts/readmeWorkflow/syncProviderIndex.ts
Labels: 📝 Documentation, size:XXL

#6190 🐛 fix: fix inbox agent edit way in the new mode
  src/app/[variants]/(main)/chat/(workspace)/features/AgentSettings/CategoryContent/useCategory.tsx
  src/app/[variants]/(main)/chat/(workspace)/features/AgentSettings/index.tsx
  src/app/[variants]/(main)/chat/(workspace)/features/SettingButton.tsx
  src/hooks/useInterceptingRoutes.ts
Labels: 💄 Design, size:M

#6186 🐛 fix: fix inbox agent can not save config
  src/database/server/models/__tests__/session.test.ts
  src/database/server/models/session.ts
  src/database/server/models/user.ts
  src/features/DevPanel/features/Table/TableCell.tsx
  src/libs/next-auth/adapter/index.ts
  src/server/routers/lambda/agent.ts
  src/server/services/agent/index.test.ts
  src/server/services/agent/index.ts
  src/server/services/user/index.test.ts
  src/server/services/user/index.ts
  src/services/session/client.ts
Labels: 🐛 Bug, size:L

#6197 💄 style: improve inbox agent settings
  src/app/[variants]/(main)/chat/(workspace)/features/AgentSettings/CategoryContent/useCategory.tsx
  src/app/[variants]/(main)/chat/(workspace)/features/AgentSettings/index.tsx
  src/features/AgentSetting/AgentMeta/index.tsx
Labels: 💄 Design, size:S

#6199 🐛 fix: fix ai provider description not show correctly
  src/database/server/models/aiProvider.ts
Labels: 🐛 Bug, size:XS

#6198 🐛 fix: set max_completion_tokens to null for Azure OpenAI
  src/libs/agent-runtime/azureOpenai/index.ts
Labels: 🐛 Bug, size:XS

#6193 🐛 fix: match o1 series models more robust in Azure OpenAI provider
  src/libs/agent-runtime/azureOpenai/index.ts
Labels: 🐛 Bug, size:XS

#6202 🔨 chore: Update github issue
  .github/ISSUE_TEMPLATE/1_bug_report.yml
  .github/ISSUE_TEMPLATE/1_bug_report_cn.yml
Labels: size:S

#6140 ✨ feat: add Jina AI model provider support
  Dockerfile
  Dockerfile.database
  src/app/[variants]/(main)/settings/llm/ProviderList/providers.tsx
  src/config/aiModels/index.ts
  src/config/aiModels/jina.ts
  src/config/llm.ts
  src/config/modelProviders/index.ts
  src/config/modelProviders/jina.ts
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/jina/index.ts
  src/libs/agent-runtime/types/type.ts
  src/types/user/settings/keyVaults.ts
Labels: 🌠 Feature Request, Model Provider, size:L

#6203 💄 style: fix mobile agent settings not show correctly
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatInput/Mobile/Files/FileItem/File.tsx
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatInput/Mobile/Files/FileItem/Image.tsx
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatInput/Mobile/Files/FileItem/index.tsx
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatInput/Mobile/Files/FileItem/style.ts
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatInput/Mobile/Files/index.tsx
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatInput/Mobile/InputArea/Container.tsx
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatInput/Mobile/InputArea/index.tsx
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatInput/Mobile/Send.tsx
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatInput/Mobile/index.tsx
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatInput/index.tsx
  src/app/[variants]/(main)/chat/(workspace)/_layout/Desktop/ChatHeader/Main.tsx
  src/app/[variants]/(main)/chat/(workspace)/_layout/Mobile/ChatHeader/index.tsx
  src/app/[variants]/(main)/chat/(workspace)/features/AgentSettings/index.tsx
  src/app/[variants]/(main)/chat/settings/features/EditPage.tsx
  src/app/[variants]/(main)/chat/settings/page.tsx
  src/features/AgentSetting/AgentMeta/index.tsx
  src/features/AgentSetting/AgentPrompt/index.tsx
  src/features/AgentSetting/AgentSettings.tsx
  src/features/AgentSetting/AgentSettingsProvider.tsx
  src/features/AgentSetting/AgentSettingsStore.tsx
  src/features/AgentSetting/StoreUpdater.tsx
  src/features/AgentSetting/index.tsx
  src/features/AgentSetting/store/initialState.ts
  src/hooks/useInterceptingRoutes.test.ts
  src/hooks/useInterceptingRoutes.ts
  src/layout/GlobalProvider/StoreInitialization.tsx
  src/store/agent/slices/chat/action.test.ts
  src/store/agent/slices/chat/action.ts
Labels: 💄 Design, 📱 Mobile Device, size:L

#6213 📝 docs: files access denied in one-click deploy
  docker-compose/local/docker-compose.yml
Labels: 🐛 Bug, size:XS

#6221 ✨ feat: add volcengine as a new provider
  locales/ar/providers.json
  locales/bg-BG/providers.json
  locales/de-DE/providers.json
  locales/en-US/providers.json
  locales/es-ES/providers.json
  locales/fa-IR/modelProvider.json
  locales/fa-IR/providers.json
  locales/fr-FR/providers.json
  locales/it-IT/providers.json
  locales/ja-JP/providers.json
  locales/ko-KR/providers.json
  locales/nl-NL/providers.json
  locales/pl-PL/providers.json
  locales/pt-BR/providers.json
  locales/ru-RU/providers.json
  locales/tr-TR/modelProvider.json
  locales/tr-TR/providers.json
  locales/vi-VN/providers.json
  locales/zh-CN/models.json
  locales/zh-CN/providers.json
  locales/zh-TW/providers.json
  next.config.ts
  src/app/[variants]/(main)/settings/provider/(list)/ProviderGrid/index.tsx
  src/config/aiModels/index.ts
  src/config/aiModels/volcengine.ts
  src/config/llm.ts
  src/config/modelProviders/index.ts
  src/config/modelProviders/volcengine.ts
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/index.ts
  src/libs/agent-runtime/types/type.ts
  src/libs/agent-runtime/volcengine/index.ts
  src/services/chat.ts
  src/types/aiProvider.ts
  src/types/user/settings/keyVaults.ts
Labels: size:L

#6218 ✨ feat: add SambaNova provider support
  Dockerfile
  Dockerfile.database
  src/app/[variants]/(main)/settings/llm/ProviderList/providers.tsx
  src/config/aiModels/index.ts
  src/config/aiModels/sambanova.ts
  src/config/llm.ts
  src/config/modelProviders/index.ts
  src/config/modelProviders/sambanova.ts
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/sambanova/index.ts
  src/libs/agent-runtime/types/type.ts
  src/types/user/settings/keyVaults.ts
Labels: 🌠 Feature Request, size:L

#6243 💄 style: update Jina AI Provider name & model info
  src/config/aiModels/jina.ts
  src/config/modelProviders/jina.ts
Labels: 💄 Design, size:XS

#6240 🐛 fix: fix model list issue in client mode
  src/app/[variants]/(main)/settings/provider/(detail)/[id]/page.tsx
  src/config/aiModels/azure.ts
  src/database/repositories/aiInfra/index.ts
  src/libs/agent-runtime/openai/__snapshots__/index.test.ts.snap
  src/server/globalConfig/index.ts
  src/server/routers/lambda/aiModel.ts
  src/server/routers/lambda/aiProvider.ts
  src/services/aiModel/client.ts
  src/utils/merge.test.ts
  src/utils/merge.ts
  src/utils/parseModels.test.ts
Labels: size:XL

#6247 🐛 fix: user feedback for empty/long group names in create/edit group modals
  src/app/[variants]/(main)/chat/@session/features/SessionListContent/Modals/CreateGroupModal.tsx
  src/app/[variants]/(main)/chat/@session/features/SessionListContent/Modals/RenameGroupModal.tsx
Labels: 🐛 Bug, size:XS

#6252 🐛 fix: fix agent config not load correctly
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatInput/Mobile/index.tsx
  src/app/[variants]/(main)/chat/(workspace)/@topic/features/SystemRole/SystemRoleContent.tsx
  src/app/[variants]/(main)/chat/(workspace)/_layout/Desktop/ChatHeader/Main.tsx
  src/app/[variants]/(main)/chat/(workspace)/_layout/Desktop/ChatHeader/Tags.tsx
  src/app/[variants]/(main)/chat/(workspace)/features/AgentSettings/index.tsx
  src/app/[variants]/(main)/chat/settings/page.tsx
  src/features/AgentSetting/AgentPrompt/index.tsx
  src/features/AgentSetting/store/initialState.ts
  src/hooks/useInitAgentConfig.ts
  src/services/message/client.test.ts
  src/services/session/server.ts
  src/store/agent/slices/chat/action.test.ts
  src/store/agent/slices/chat/action.ts
  src/store/agent/slices/chat/initialState.ts
  src/store/agent/slices/chat/selectors.ts
Labels: 🐛 Bug, size:L

#6258 🐛 fix: fix loading on not login for db
  src/app/[variants]/(main)/chat/(workspace)/_layout/Desktop/ChatHeader/Tags.tsx
Labels: 🐛 Bug, size:XS

#6259 📝 docs: Add 2024 recap
  README.md
  README.zh-CN.md
  docs/usage/start.mdx
  docs/usage/start.zh-CN.mdx
Labels: 📝 Documentation, size:L

#6263 💄 style: add o1 vision metadata
  locales/ar/models.json
  locales/ar/providers.json
  locales/bg-BG/models.json
  locales/bg-BG/providers.json
  locales/de-DE/models.json
  locales/de-DE/providers.json
  locales/en-US/models.json
  locales/en-US/providers.json
  locales/es-ES/models.json
  locales/es-ES/providers.json
  locales/fa-IR/models.json
  locales/fa-IR/providers.json
  locales/fr-FR/models.json
  locales/fr-FR/providers.json
  locales/it-IT/models.json
  locales/it-IT/providers.json
  locales/ja-JP/models.json
  locales/ja-JP/providers.json
  locales/ko-KR/models.json
  locales/ko-KR/providers.json
  locales/nl-NL/models.json
  locales/nl-NL/providers.json
  locales/pl-PL/models.json
  locales/pl-PL/providers.json
  locales/pt-BR/models.json
  locales/pt-BR/providers.json
  locales/ru-RU/models.json
  locales/ru-RU/providers.json
  locales/tr-TR/models.json
  locales/tr-TR/providers.json
  locales/vi-VN/models.json
  locales/vi-VN/providers.json
  locales/zh-CN/models.json
  locales/zh-CN/providers.json
  locales/zh-TW/models.json
  locales/zh-TW/providers.json
  next.config.ts
  src/config/aiModels/openai.ts
Labels: 💄 Design, size:XL

#6270 💄 style: update MiniMax models
  src/config/aiModels/minimax.ts
Labels: 💄 Design, size:M

#6269 💄 style: remove deprecated models
  src/config/aiModels/google.ts
  src/config/modelProviders/google.ts
Labels: 💄 Design, size:L

#6278 📝 docs: Update docker image version
  README.md
  docs/self-hosting/platform/docker-compose.mdx
  docs/self-hosting/platform/docker-compose.zh-CN.mdx
  docs/self-hosting/platform/docker.mdx
  docs/self-hosting/platform/docker.zh-CN.mdx
  docs/self-hosting/server-database/docker-compose.mdx
  docs/self-hosting/server-database/docker-compose.zh-CN.mdx
  docs/self-hosting/server-database/docker.mdx
  docs/self-hosting/server-database/docker.zh-CN.mdx
Labels: 📝 Documentation, size:M

#6207 💄 style: sync chat limit
  src/features/AgentSetting/AgentChat/index.tsx
Labels: 💄 Design, size:XS

#6287 👷 build: add pglite docker image
  .github/ISSUE_TEMPLATE/1_bug_report.yml
  .github/ISSUE_TEMPLATE/1_bug_report_cn.yml
  .github/workflows/docker-pglite.yml
  Dockerfile.pglite
Labels: size:L

#6169 🐛 fix: try to fix pglite worker
  src/database/client/db.ts
Labels: 🐛 Bug, size:XS, Build Docker

#6299 💄 style: improve serveral error code
  locales/ar/error.json
  locales/bg-BG/error.json
  locales/de-DE/error.json
  locales/en-US/error.json
  locales/es-ES/error.json
  locales/fa-IR/error.json
  locales/fr-FR/error.json
  locales/it-IT/error.json
  locales/ja-JP/error.json
  locales/ko-KR/error.json
  locales/nl-NL/error.json
  locales/pl-PL/error.json
  locales/pt-BR/error.json
  locales/ru-RU/error.json
  locales/tr-TR/error.json
  locales/vi-VN/error.json
  locales/zh-CN/error.json
  locales/zh-TW/error.json
  src/app/(backend)/middleware/auth/index.ts
  src/features/Conversation/Error/OpenAiBizError.tsx
  src/features/Conversation/Error/index.tsx
  src/features/Conversation/Messages/User/MarkdownRender/ContentPreview.tsx
  src/libs/agent-runtime/error.ts
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
  src/locales/default/error.ts
  src/types/fetch.ts
  src/utils/errorResponse.test.ts
  src/utils/errorResponse.ts
Labels: 💄 Design, size:L

#6305 💄 style: improve error content and console error
  locales/ar/error.json
  locales/ar/models.json
  locales/bg-BG/error.json
  locales/bg-BG/models.json
  locales/de-DE/error.json
  locales/de-DE/models.json
  locales/en-US/error.json
  locales/en-US/models.json
  locales/es-ES/error.json
  locales/es-ES/models.json
  locales/fa-IR/error.json
  locales/fa-IR/models.json
  locales/fr-FR/error.json
  locales/fr-FR/models.json
  locales/it-IT/error.json
  locales/it-IT/models.json
  locales/ja-JP/error.json
  locales/ja-JP/models.json
  locales/ko-KR/error.json
  locales/ko-KR/models.json
  locales/nl-NL/error.json
  locales/nl-NL/models.json
  locales/pl-PL/error.json
  locales/pl-PL/models.json
  locales/pt-BR/error.json
  locales/pt-BR/models.json
  locales/ru-RU/error.json
  locales/ru-RU/models.json
  locales/tr-TR/error.json
  locales/tr-TR/models.json
  locales/vi-VN/error.json
  locales/vi-VN/models.json
  locales/zh-CN/error.json
  locales/zh-CN/models.json
  locales/zh-TW/error.json
  locales/zh-TW/models.json
  src/app/(backend)/middleware/auth/index.ts
  src/locales/default/error.ts
Labels: 💄 Design, size:L

#6307 💄 style: improve perplexity models
  locales/ar/models.json
  locales/bg-BG/models.json
  locales/de-DE/models.json
  locales/en-US/models.json
  locales/es-ES/models.json
  locales/fa-IR/models.json
  locales/fr-FR/models.json
  locales/it-IT/models.json
  locales/ja-JP/models.json
  locales/ko-KR/models.json
  locales/nl-NL/models.json
  locales/pl-PL/models.json
  locales/pt-BR/models.json
  locales/ru-RU/models.json
  locales/tr-TR/models.json
  locales/vi-VN/models.json
  locales/zh-CN/models.json
  locales/zh-TW/models.json
  src/config/aiModels/perplexity.ts
  src/config/modelProviders/perplexity.ts
  src/libs/agent-runtime/perplexity/index.test.ts
Labels: 💄 Design, size:L

#6304 :bug: fix: Casdoor webhooks error
  docs/self-hosting/advanced/auth/next-auth/casdoor.mdx
  docs/self-hosting/advanced/auth/next-auth/casdoor.zh-CN.mdx
  src/app/(backend)/api/webhooks/casdoor/route.ts
  src/app/(backend)/api/webhooks/casdoor/validateRequest.ts
  src/server/services/nextAuthUser/index.ts
Labels: 🐛 Bug, size:M

#6331 ✨ feat: support pplx search grounding
  locales/en-US/components.json
  package.json
  src/components/ModelSelect/index.tsx
  src/components/Thinking/index.tsx
  src/config/aiModels/jina.ts
  src/config/aiModels/perplexity.ts
  src/database/client/migrations.json
  src/database/migrations/0015_add_message_search_metadata.sql
  src/database/migrations/meta/0015_snapshot.json
  src/database/migrations/meta/_journal.json
  src/database/schemas/message.ts
  src/database/server/models/message.ts
  src/features/Conversation/components/ChatItem/index.tsx
  src/features/Conversation/components/MarkdownElements/Thinking/Render.tsx
  src/features/Conversation/components/MarkdownElements/remarkPlugins/createRemarkCustomTagPlugin.ts
  src/features/Conversation/components/MarkdownElements/remarkPlugins/getNodeContent.test.ts
  src/features/Conversation/components/MarkdownElements/remarkPlugins/getNodeContent.ts
  src/libs/agent-runtime/perplexity/index.test.ts
  src/libs/agent-runtime/utils/streams/anthropic.ts
  src/libs/agent-runtime/utils/streams/bedrock/claude.ts
  src/libs/agent-runtime/utils/streams/bedrock/llama.ts
  src/libs/agent-runtime/utils/streams/google-ai.ts
  src/libs/agent-runtime/utils/streams/ollama.ts
  src/libs/agent-runtime/utils/streams/openai.ts
  src/libs/agent-runtime/utils/streams/protocol.ts
  src/libs/agent-runtime/utils/streams/vertex-ai.ts
  src/locales/default/components.ts
  src/store/chat/slices/aiChat/actions/generateAIChat.ts
  src/store/chat/slices/message/action.ts
  src/types/aiModel.ts
  src/types/message/base.ts
  src/types/message/chat.ts
  src/utils/fetch/fetchSSE.ts
Labels: 🌠 Feature Request, Gemini, size:XL

#6346 :bug: fix: Azure AI env var configuration issue.
  src/config/llm.ts
Labels: 🐛 Bug, size:XS

#6256 🔨 chore: Update issue template
  .github/ISSUE_TEMPLATE/1_bug_report_cn.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: size:S

#6348 🐛 fix: add sambanova proxy url
  locales/ar/components.json
  locales/bg-BG/components.json
  locales/de-DE/components.json
  locales/en-US/components.json
  locales/es-ES/components.json
  locales/fa-IR/components.json
  locales/fr-FR/components.json
  locales/it-IT/components.json
  locales/ja-JP/components.json
  locales/ko-KR/components.json
  locales/nl-NL/components.json
  locales/pl-PL/components.json
  locales/pt-BR/components.json
  locales/ru-RU/components.json
  locales/tr-TR/components.json
  locales/vi-VN/components.json
  locales/zh-CN/components.json
  locales/zh-TW/components.json
  src/config/modelProviders/sambanova.ts
Labels: 🐛 Bug, size:S

#6222 🐛 fix: update message roles for specific Azure OpenAI models
  src/libs/agent-runtime/azureOpenai/index.ts
Labels: 🐛 Bug, size:S

#6354 🐛 fix: fix a feature flag
  locales/ar/error.json
  locales/bg-BG/error.json
  locales/de-DE/error.json
  locales/en-US/error.json
  locales/es-ES/error.json
  locales/fa-IR/error.json
  locales/fr-FR/error.json
  locales/it-IT/error.json
  locales/ja-JP/error.json
  locales/ko-KR/error.json
  locales/nl-NL/error.json
  locales/pl-PL/error.json
  locales/pt-BR/error.json
  locales/ru-RU/error.json
  locales/tr-TR/error.json
  locales/vi-VN/error.json
  locales/zh-CN/error.json
  locales/zh-TW/error.json
  src/app/[variants]/(main)/(mobile)/me/settings/features/useCategory.tsx
  src/features/Conversation/Error/index.tsx
  src/libs/agent-runtime/error.ts
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
  src/locales/default/error.ts
  src/utils/errorResponse.ts
Labels: 🐛 Bug, size:M

#6363 🐛 fix: fix hotkeys of open agent settings
  src/app/[variants]/(main)/chat/(workspace)/_layout/Desktop/HotKeys.tsx
Labels: 🐛 Bug, size:XS

#6377 💄 style: add some error types
  locales/ar/error.json
  locales/bg-BG/error.json
  locales/de-DE/error.json
  locales/en-US/error.json
  locales/es-ES/error.json
  locales/fa-IR/error.json
  locales/fr-FR/error.json
  locales/it-IT/error.json
  locales/ja-JP/error.json
  locales/ko-KR/error.json
  locales/nl-NL/error.json
  locales/pl-PL/error.json
  locales/pt-BR/error.json
  locales/ru-RU/error.json
  locales/tr-TR/error.json
  locales/vi-VN/error.json
  locales/zh-CN/error.json
  locales/zh-TW/error.json
  package.json
  src/features/Conversation/Error/index.tsx
  src/locales/default/error.ts
  src/types/fetch.ts
  src/utils/errorResponse.ts
Labels: 💄 Design, size:M

#6393 🐛 fix: fix default agent loading
  package.json
  src/app/[variants]/(main)/settings/agent/index.tsx
  src/features/Conversation/components/ChatItem/index.tsx
Labels: size:XS

#6390 💄 style: refactor the plugin render style
  locales/ar/plugin.json
  locales/bg-BG/plugin.json
  locales/de-DE/plugin.json
  locales/en-US/plugin.json
  locales/es-ES/plugin.json
  locales/fa-IR/plugin.json
  locales/fr-FR/plugin.json
  locales/it-IT/plugin.json
  locales/ja-JP/plugin.json
  locales/ko-KR/plugin.json
  locales/nl-NL/plugin.json
  locales/pl-PL/plugin.json
  locales/pt-BR/plugin.json
  locales/ru-RU/plugin.json
  locales/tr-TR/plugin.json
  locales/vi-VN/plugin.json
  locales/zh-CN/plugin.json
  locales/zh-TW/plugin.json
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatInput/Desktop/index.tsx
  src/database/server/models/aiProvider.ts
  src/database/server/models/topic.ts
  src/features/Conversation/Messages/Assistant/Tool/Inspector/Debug.tsx
  src/features/Conversation/Messages/Assistant/Tool/Inspector/Loader.tsx
  src/features/Conversation/Messages/Assistant/Tool/Inspector/PluginResultJSON.tsx
  src/features/Conversation/Messages/Assistant/Tool/Inspector/Settings.tsx
  src/features/Conversation/Messages/Assistant/Tool/Inspector/index.tsx
  src/features/Conversation/Messages/Assistant/Tool/Render/Arguments.tsx
  src/features/Conversation/Messages/Assistant/Tool/Render/CustomRender.tsx
  src/features/Conversation/Messages/Assistant/Tool/Render/index.tsx
  src/features/Conversation/Messages/Assistant/Tool/index.tsx
  src/features/Conversation/Messages/Assistant/ToolCallItem/Inspector/index.tsx
  src/features/Conversation/Messages/Assistant/ToolCallItem/Inspector/style.ts
  src/features/Conversation/Messages/Assistant/ToolCallItem/index.tsx
  src/features/Conversation/Messages/Assistant/ToolCallItem/style.ts
  src/features/Conversation/Messages/Assistant/index.tsx
  src/features/Conversation/Messages/components/Arguments.tsx
  src/features/InitClientDB/PGliteIcon.tsx
  src/features/PluginsUI/Render/index.tsx
  src/locales/default/plugin.ts
  src/styles/loading.ts
  src/tools/dalle/Render/GalleyGrid.tsx
  src/tools/dalle/Render/index.tsx
Labels: size:XL

#6397 📝 docs: Add volcengine environment variables
  docs/self-hosting/environment-variables/model-provider.mdx
  docs/self-hosting/environment-variables/model-provider.zh-CN.mdx
Labels: 📝 Documentation, size:M

#6399 📝 docs:(deploy): update Sealos deployment docs and links
  README.md
  README.zh-CN.md
  docs/self-hosting/platform/sealos.mdx
  docs/self-hosting/platform/sealos.zh-CN.mdx
  docs/self-hosting/server-database/sealos.mdx
  docs/self-hosting/server-database/sealos.zh-CN.mdx
  docs/self-hosting/start.zh-CN.mdx
Labels: 📝 Documentation, size:L

#6368 💄 style: Add Volcano Ark models
  src/config/aiModels/volcengine.ts
Labels: size:L

#6400 Update Node to 22 (lts/jod) in .nvmrc
  .nvmrc
Labels: dependencies, size:XS

#6408 👷 docs: Fix the issue that the communication with the casdoor server is not available due to the port change
  docker-compose/local/docker-compose.yml
Labels: 🐛 Bug, size:XS
