Repository lobehub/lobe-chat, pull requests merged in 2025-04, with the labels that each got.

#7253 ⚡️ perf: fix delete file chunk timeout
  src/app/[variants]/(main)/repos/[id]/@menu/default.tsx
  src/components/Loading/BrandTextLoading/index.tsx
  src/database/models/file.ts
  src/libs/agent-runtime/openrouter/__snapshots__/index.test.ts.snap
  src/server/routers/lambda/file.ts
Labels: ⚡️ Performance, size:L

#7255 ♻️ refactor: refactor the db mode to async init
  src/database/core/db-adaptor.ts
  src/database/models/__tests__/aiProvider.test.ts
  src/database/models/session.ts
  src/database/models/user.ts
  src/database/server/index.ts
  src/libs/trpc/async/index.ts
  src/libs/trpc/lambda/index.ts
  src/libs/trpc/lambda/serverDatabase.ts
  src/server/routers/async/file.ts
  src/server/routers/async/ragEval.ts
  src/server/routers/lambda/_template.ts
  src/server/routers/lambda/agent.ts
  src/server/routers/lambda/aiModel.ts
  src/server/routers/lambda/aiProvider.test.ts
  src/server/routers/lambda/aiProvider.ts
  src/server/routers/lambda/chunk.ts
  src/server/routers/lambda/exporter.ts
  src/server/routers/lambda/file.ts
  src/server/routers/lambda/importer.ts
  src/server/routers/lambda/knowledgeBase.ts
  src/server/routers/lambda/message.ts
  src/server/routers/lambda/plugin.ts
  src/server/routers/lambda/ragEval.ts
  src/server/routers/lambda/session.ts
  src/server/routers/lambda/sessionGroup.ts
  src/server/routers/lambda/thread.ts
  src/server/routers/lambda/topic.ts
  src/server/routers/lambda/user.ts
  src/server/services/nextAuthUser/index.test.ts
Labels: size:L

#7261 🔨 chore: add desktop pre-code to validate build process
  next.config.ts
  package.json
  packages/electron-client-ipc/README.md
  packages/electron-client-ipc/package.json
  packages/electron-client-ipc/src/events/devtools.ts
  packages/electron-client-ipc/src/events/index.ts
  packages/electron-client-ipc/src/index.ts
  packages/electron-client-ipc/src/types/dispatch.ts
  packages/electron-client-ipc/src/types/index.ts
  packages/electron-server-ipc/README.md
  pnpm-workspace.yaml
  src/app/desktop/devtools/page.tsx
  src/app/desktop/layout.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/const/desktop.ts
  src/const/version.ts
  src/database/client/db.ts
  src/database/models/drizzleMigration.ts
  src/database/models/user.ts
  src/features/DevPanel/features/FloatPanel.tsx
  src/features/User/UserPanel/index.tsx
  src/libs/trpc/middleware/userAuth.ts
  src/server/routers/tools/__tests__/search.test.ts
  src/services/electron/devtools.ts
  src/styles/electron.ts
  src/types/electron.ts
  src/utils/electron/dispatch.ts
  tsconfig.json
Labels: size:L

#7265 ♻️ refactor: add desktop-release workflow and improve code
  .github/scripts/pr-comment.js
  .github/scripts/pr-release-body.js
  .github/workflows/release-desktop.yml
  .github/workflows/test.yml
  package.json
  scripts/setup-test-postgres-db.sh
  src/database/models/__tests__/message.test.ts
  src/database/models/__tests__/session.test.ts
  src/database/models/message.ts
  src/server/translation.test.ts
  src/server/translation.ts
  src/tools/web-browsing/Portal/Search/ResultList/SearchItem/index.tsx
  src/tools/web-browsing/Render/Search/SearchResult/ShowMore.tsx
  vitest.config.ts
  vitest.server.config.ts
Labels: size:XL

#7270 🐛 fix: add `SEARCH1API_CRAWL_API_KEY` env
  packages/web-crawler/src/crawImpl/search1api.ts
Labels: 🐛 Bug, size:M

#7011 💄 style: Auto refresh TokenTag count
  src/features/ChatInput/ActionBar/Token/TokenTag.tsx
Labels: 💄 Design, size:S

#7251 💄 style(web-crawler): add special support for YouTube,Reddit and WeChat links
  packages/web-crawler/src/urlRules.ts
Labels: 🌠 Feature Request, size:S

#7258 💄 style: Add QVQ-Max model
  src/config/aiModels/novita.ts
  src/config/aiModels/qwen.ts
  src/libs/agent-runtime/novita/__snapshots__/index.test.ts.snap
  src/libs/agent-runtime/openrouter/__snapshots__/index.test.ts.snap
Labels: size:M

#7285 🐛 fix(web-crawler): remove unnecessary urlTransform for YouTube links
  packages/web-crawler/src/urlRules.ts
Labels: 🐛 Bug, size:XS

#7288 🐛 fix: fix fetch issue in offline mode and make jina crawler first
  packages/web-crawler/src/crawler.ts
  src/app/(backend)/webapi/assistant/store/route.ts
  src/app/(backend)/webapi/plugin/store/route.ts
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatList/WelcomeChatItem/InboxWelcome/AgentsSuggest.tsx
  src/features/Conversation/Error/index.tsx
  src/libs/agent-runtime/error.ts
  src/libs/agent-runtime/ollama/index.ts
  src/server/modules/AssistantStore/index.ts
  src/utils/errorResponse.ts
Labels: 🐛 Bug, size:M

#7304 📝 docs: Update `PROXY_URL` and `ENABLE_PROXY_DNS`
  docs/self-hosting/environment-variables/basic.mdx
  docs/self-hosting/environment-variables/basic.zh-CN.mdx
Labels: 📝 Documentation, size:S

#7289 💄 style: fix QVQ Max model
  src/config/aiModels/google.ts
  src/config/aiModels/novita.ts
  src/config/aiModels/qwen.ts
Labels: 💄 Design, size:M

#7296 💄 style: support default config for system agent and pre-merge some desktop code
  .github/scripts/pr-comment.js
  .gitignore
  docs/self-hosting/environment-variables/basic.mdx
  docs/self-hosting/environment-variables/basic.zh-CN.mdx
  scripts/migrateServerDB/index.ts
  src/app/[variants]/(main)/settings/provider/features/ProviderConfig/index.tsx
  src/app/desktop/devtools/page.tsx
  src/config/aiModels/ollama.ts
  src/features/DevPanel/PostgresViewer/SchemaSidebar/index.tsx
  src/features/User/UserPanel/index.tsx
  src/features/User/__tests__/PanelContent.test.tsx
  src/libs/trpc/index.ts
  src/libs/trpc/middleware/userAuth.ts
  src/server/globalConfig/parseSystemAgent.test.ts
  src/server/globalConfig/parseSystemAgent.ts
  src/server/services/changelog/index.test.ts
  src/server/services/changelog/index.ts
  src/services/electron/devtools.ts
  src/utils/electron/dispatch.ts
Labels: size:L

#7311 🐛 fix: fix data not show correctly in 1.77.11
  src/libs/trpc/index.ts
Labels: size:XS

#7302 💄 style: add `ernie-x1-32k-preview` support for Wenxin
  src/config/aiModels/wenxin.ts
Labels: 💄 Design, size:XS

#7313 🔨 chore: Correcting the env example url
  docs/self-hosting/server-database/docker-compose.mdx
Labels: 📝 Documentation, size:XS

#7314 ♻️ refactor: improve public procedure implement
  src/libs/trpc/index.ts
Labels: size:XS

#7323 ♻️ refactor: refactor the file service
  src/server/routers/async/file.ts
  src/server/routers/lambda/file.ts
  src/server/routers/lambda/importer.ts
  src/server/routers/lambda/message.ts
  src/server/routers/lambda/ragEval.ts
  src/server/services/file/impls/index.ts
  src/server/services/file/impls/s3.test.ts
  src/server/services/file/impls/s3.ts
  src/server/services/file/impls/type.ts
  src/server/services/file/index.ts
  src/server/utils/files.test.ts
  src/server/utils/files.ts
Labels: files, size:L

#7332 💄 style: improve ollama desktop setup guide
  locales/ar/components.json
  locales/bg-BG/components.json
  locales/de-DE/components.json
  locales/en-US/components.json
  locales/es-ES/components.json
  locales/fa-IR/components.json
  locales/fr-FR/components.json
  locales/it-IT/components.json
  locales/ja-JP/components.json
  locales/ko-KR/components.json
  locales/nl-NL/components.json
  locales/pl-PL/components.json
  locales/pt-BR/components.json
  locales/ru-RU/components.json
  locales/tr-TR/components.json
  locales/vi-VN/components.json
  locales/zh-CN/components.json
  locales/zh-TW/components.json
  src/components/FormAction/index.tsx
  src/features/Conversation/Error/OllamaDesktopSetupGuide/index.tsx
  src/features/Conversation/Error/index.tsx
  src/libs/agent-runtime/openrouter/__snapshots__/index.test.ts.snap
  src/libs/agent-runtime/openrouter/fixtures/frontendModels.json
  src/libs/agent-runtime/openrouter/fixtures/models.json
  src/libs/agent-runtime/openrouter/index.test.ts
  src/libs/agent-runtime/openrouter/index.ts
  src/locales/default/components.ts
Labels: 💄 Design, ollama, size:L

#7335 📝 docs: improve contributing docs
  contributing/Basic/Architecture.md
  contributing/Basic/Architecture.zh-CN.md
  contributing/Basic/Chat-API.md
  contributing/Basic/Chat-API.zh-CN.md
  contributing/Basic/Contributing-Guidelines.md
  contributing/Basic/Contributing-Guidelines.zh-CN.md
  contributing/Home.md
  contributing/State-Management/State-Management-Intro.md
  contributing/State-Management/State-Management-Intro.zh-CN.md
  src/helpers/url.ts
Labels: 📝 Documentation, size:XL

#7342 ✨ feat: Add Keycloak SSO provider support
  docs/self-hosting/advanced/auth.mdx
  docs/self-hosting/advanced/auth.zh-CN.mdx
  docs/self-hosting/advanced/auth/next-auth/keycloak.mdx
  docs/self-hosting/advanced/auth/next-auth/keycloak.zh-CN.mdx
  src/libs/next-auth/sso-providers/index.ts
  src/libs/next-auth/sso-providers/keycloak.ts
Labels: 🌠 Feature Request, size:L

#7349 📝 docs: move contributing docs to docs/development and deploy to lobehub
  .github/workflows/wiki-sync.yml
  contributing/Home.md
  contributing/Upstream-Sync.md
  contributing/Upstream-Sync.zh-CN.md
  contributing/_Footer.md
  contributing/_Sidebar.md
  docs/development/basic/add-new-authentication-providers.mdx
  docs/development/basic/add-new-authentication-providers.zh-CN.mdx
  docs/development/basic/architecture.mdx
  docs/development/basic/architecture.zh-CN.mdx
  docs/development/basic/chat-api.mdx
  docs/development/basic/chat-api.zh-CN.mdx
  docs/development/basic/contributing-guidelines.mdx
  docs/development/basic/contributing-guidelines.zh-CN.mdx
  docs/development/basic/feature-development-frontend.mdx
  docs/development/basic/feature-development-frontend.zh-CN.mdx
  docs/development/basic/feature-development.mdx
  docs/development/basic/feature-development.zh-CN.mdx
  docs/development/basic/folder-structure.mdx
  docs/development/basic/folder-structure.zh-CN.mdx
  docs/development/basic/resources.mdx
  docs/development/basic/resources.zh-CN.mdx
  docs/development/basic/setup-development.mdx
  docs/development/basic/setup-development.zh-CN.mdx
  docs/development/basic/test.mdx
  docs/development/basic/test.zh-CN.mdx
  docs/development/internationalization/add-new-locale.mdx
  docs/development/internationalization/add-new-locale.zh-CN.mdx
  docs/development/internationalization/internationalization-implementation.mdx
  docs/development/internationalization/internationalization-implementation.zh-CN.mdx
  docs/development/others/lighthouse.mdx
  docs/development/others/lighthouse.zh-CN.mdx
  docs/development/start.mdx
  docs/development/start.zh-CN.mdx
  docs/development/state-management/state-management-intro.mdx
  docs/development/state-management/state-management-intro.zh-CN.mdx
  docs/development/state-management/state-management-selectors.mdx
  docs/development/state-management/state-management-selectors.zh-CN.mdx
  src/locales/default/tool.ts
  src/server/modules/SearXNG.ts
  src/server/routers/tools/search.ts
  src/services/search.ts
  src/store/chat/slices/builtinTool/actions/searXNG.test.ts
  src/store/chat/slices/builtinTool/actions/searXNG.ts
  src/tools/web-browsing/components/CategoryAvatar.tsx
  src/tools/web-browsing/components/SearchBar.tsx
  src/tools/web-browsing/const.ts
  src/tools/web-browsing/index.ts
  src/types/tool/search.ts
Labels: 📝 Documentation, size:L

#7352 Some final work of contributing docs migration
  .github/workflows/sync-database-schema.yml
  .github/workflows/wiki-sync.yml
  docs/development/basic/add-new-authentication-providers.mdx
  docs/development/basic/add-new-authentication-providers.zh-CN.mdx
  docs/development/basic/architecture.mdx
  docs/development/basic/architecture.zh-CN.mdx
  docs/development/basic/chat-api.mdx
  docs/development/basic/chat-api.zh-CN.mdx
  docs/development/basic/contributing-guidelines.mdx
  docs/development/basic/contributing-guidelines.zh-CN.mdx
  docs/development/basic/feature-development-frontend.mdx
  docs/development/basic/feature-development-frontend.zh-CN.mdx
  docs/development/basic/feature-development.mdx
  docs/development/basic/feature-development.zh-CN.mdx
  docs/development/basic/resources.mdx
  docs/development/basic/resources.zh-CN.mdx
  docs/development/basic/setup-development.mdx
  docs/development/basic/setup-development.zh-CN.mdx
  docs/development/basic/test.mdx
  docs/development/basic/test.zh-CN.mdx
  docs/development/database-schema.dbml
  docs/development/internationalization/add-new-locale.mdx
  docs/development/internationalization/add-new-locale.zh-CN.mdx
  docs/development/internationalization/internationalization-implementation.mdx
  docs/development/internationalization/internationalization-implementation.zh-CN.mdx
  docs/development/others/lighthouse.mdx
  docs/development/others/lighthouse.zh-CN.mdx
  docs/development/start.mdx
  docs/development/start.zh-CN.mdx
  docs/development/state-management/state-management-intro.mdx
  docs/development/state-management/state-management-intro.zh-CN.mdx
  docs/wiki/HOME.md
  package.json
  scripts/dbmlWorkflow/index.ts
Labels: 📝 Documentation, size:L

#7353 🐛 fix: fix xAI API calling, not support `stream_options`
  src/libs/agent-runtime/xai/index.test.ts
  src/libs/agent-runtime/xai/index.ts
Labels: 🐛 Bug, size:XS

#7354 🐛 fix: fix env for Tencent Cloud & remove `deepseek-v3` series fc tag
  src/config/aiModels/tencentcloud.ts
  src/libs/agent-runtime/tencentcloud/index.ts
  src/server/globalConfig/index.ts
Labels: 🐛 Bug, size:S

#7359 🔨 chore: upgrade `nextjs@15.3.0`
  package.json
Labels: dependencies, size:XS

#7361 👷 build: add desktop workflow code
  .env.desktop
  .github/scripts/pr-release-body.js
  package.json
  packages/electron-client-ipc/src/events/file.ts
  packages/electron-client-ipc/src/events/index.ts
  packages/electron-client-ipc/src/events/shortcut.ts
  packages/electron-client-ipc/src/events/system.ts
  packages/electron-client-ipc/src/events/update.ts
  packages/electron-client-ipc/src/events/windows.ts
  packages/electron-client-ipc/src/index.ts
  packages/electron-client-ipc/src/types/file.ts
  packages/electron-client-ipc/src/types/index.ts
  packages/electron-client-ipc/src/types/route.ts
  packages/electron-client-ipc/src/types/shortcut.ts
  packages/electron-client-ipc/src/types/update.ts
  packages/electron-client-ipc/src/useWatchBroadcast.ts
  packages/electron-server-ipc/src/events/database.ts
  packages/electron-server-ipc/src/events/file.ts
  packages/electron-server-ipc/src/events/index.ts
  packages/electron-server-ipc/src/events/storagePath.ts
  packages/electron-server-ipc/src/index.ts
  packages/electron-server-ipc/src/ipcClient.test.ts
  packages/electron-server-ipc/src/ipcClient.ts
  packages/electron-server-ipc/src/ipcServer.ts
  packages/electron-server-ipc/src/types/event.ts
  packages/electron-server-ipc/src/types/file.ts
  packages/electron-server-ipc/src/types/index.ts
  scripts/electronWorkflow/buildElectron.ts
  scripts/electronWorkflow/moveNextStandalone.ts
  scripts/electronWorkflow/setDesktopVersion.ts
  scripts/prebuild.mts
  src/prompts/files/file.ts
  src/prompts/files/image.ts
  src/prompts/files/index.test.ts
  src/prompts/files/index.ts
  src/services/chat.ts
  src/store/global/actions/general.ts
Labels: size:XL

#7355 🐛 fix: Remove Azure AI o3-mini unsupported parameters
  src/libs/agent-runtime/azureai/index.ts
Labels: 🐛 Bug, azure, size:XS

#7360 💄 style: Update Grok 3 models
  src/config/aiModels/xai.ts
Labels: 💄 Design, size:M

#7367 🐛 fix: fix langfuse intergation
  package.json
  src/app/(backend)/webapi/chat/[provider]/route.ts
  src/app/(backend)/webapi/plugin/gateway/route.ts
  src/app/(backend)/webapi/trace/route.ts
  src/const/trace.ts
  src/database/models/__tests__/_util.ts
  src/libs/agent-runtime/AgentRuntime.test.ts
  src/libs/agent-runtime/helpers/index.ts
  src/libs/agent-runtime/helpers/parseToolCalls.test.ts
  src/libs/agent-runtime/helpers/parseToolCalls.ts
  src/libs/agent-runtime/index.ts
  src/libs/agent-runtime/types/chat.ts
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.test.ts
  src/libs/agent-runtime/utils/streams/anthropic.test.ts
  src/libs/agent-runtime/utils/streams/bedrock/llama.test.ts
  src/libs/agent-runtime/utils/streams/google-ai.test.ts
  src/libs/agent-runtime/utils/streams/ollama.test.ts
  src/libs/agent-runtime/utils/streams/openai.test.ts
  src/libs/agent-runtime/utils/streams/protocol.ts
  src/libs/agent-runtime/utils/streams/qwen.test.ts
  src/libs/agent-runtime/utils/streams/spark.test.ts
  src/libs/agent-runtime/utils/streams/vertex-ai.test.ts
  src/libs/agent-runtime/zhipu/index.test.ts
  src/server/modules/AgentRuntime/index.ts
  src/server/modules/AgentRuntime/trace.ts
  src/store/chat/slices/aiChat/actions/generateAIChat.ts
  src/utils/fetch/fetchSSE.ts
Labels: 🐛 Bug, size:XL

#7365 📝 docs: add online-search documents
  docs/self-hosting/advanced/online-search.zh-CN.mdx
Labels: 📝 Documentation, size:M

#7371 🐛 fix: fix `grok-3-mini` series calling
  src/libs/agent-runtime/xai/index.ts
Labels: 🐛 Bug, size:S

#7374 ♻️ refactor: refactor hotkey import to avoid db generate error
  src/const/hotkeys.ts
  src/types/hotkey.ts
Labels: size:M

#7385 🐛 fix: fix Azure OpenAI unable to process image messages in local s3
  src/libs/agent-runtime/azureOpenai/index.ts
Labels: 🐛 Bug, size:XS

#7412 ♻️ refactor: refactor trpc to have a clear obligation
  src/app/(backend)/trpc/async/[trpc]/route.ts
  src/app/(backend)/trpc/edge/[trpc]/route.ts
  src/app/(backend)/trpc/lambda/[trpc]/route.ts
  src/app/(backend)/trpc/tools/[trpc]/route.ts
  src/app/[variants]/(main)/files/[id]/page.tsx
  src/libs/trpc/async/context.ts
  src/libs/trpc/async/init.ts
  src/libs/trpc/edge/context.ts
  src/libs/trpc/edge/index.ts
  src/libs/trpc/edge/init.ts
  src/libs/trpc/edge/middleware/jwtPayload.test.ts
  src/libs/trpc/edge/middleware/jwtPayload.ts
  src/libs/trpc/lambda/context.ts
  src/libs/trpc/lambda/index.ts
  src/libs/trpc/lambda/init.ts
  src/libs/trpc/lambda/middleware/index.ts
  src/libs/trpc/lambda/middleware/keyVaults.ts
  src/libs/trpc/lambda/middleware/serverDatabase.ts
  src/libs/trpc/middleware/userAuth.test.ts
  src/libs/trpc/middleware/userAuth.ts
  src/libs/trpc/mock.ts
  src/server/mock.ts
  src/server/routers/edge/appStatus.ts
  src/server/routers/edge/config/index.test.ts
  src/server/routers/edge/config/index.ts
  src/server/routers/edge/index.ts
  src/server/routers/edge/upload.ts
  src/server/routers/lambda/_template.ts
  src/server/routers/lambda/agent.ts
  src/server/routers/lambda/aiModel.ts
  src/server/routers/lambda/aiProvider.ts
  src/server/routers/lambda/chunk.ts
  src/server/routers/lambda/exporter.ts
  src/server/routers/lambda/file.ts
  src/server/routers/lambda/importer.ts
  src/server/routers/lambda/index.ts
  src/server/routers/lambda/knowledgeBase.ts
  src/server/routers/lambda/message.ts
  src/server/routers/lambda/plugin.ts
  src/server/routers/lambda/ragEval.ts
  src/server/routers/lambda/session.ts
  src/server/routers/lambda/sessionGroup.ts
  src/server/routers/lambda/thread.ts
  src/server/routers/lambda/topic.ts
  src/server/routers/lambda/user.ts
  src/server/routers/tools/__tests__/search.test.ts
  src/server/routers/tools/index.ts
  src/server/routers/tools/search.ts
Labels: size:L

#7410 💄 style: Add GPT-4.1 models
  src/config/aiModels/openai.ts
Labels: size:L

#7414 💄 style: make gpt-4.1-mini default model
  locales/ar/models.json
  locales/bg-BG/models.json
  locales/de-DE/models.json
  locales/en-US/models.json
  locales/es-ES/models.json
  locales/fa-IR/models.json
  locales/fr-FR/models.json
  locales/it-IT/models.json
  locales/ja-JP/models.json
  locales/ko-KR/models.json
  locales/nl-NL/models.json
  locales/pl-PL/models.json
  locales/pt-BR/models.json
  locales/ru-RU/models.json
  locales/tr-TR/models.json
  locales/vi-VN/models.json
  locales/zh-CN/models.json
  locales/zh-TW/models.json
  src/config/modelProviders/openai.ts
  src/const/settings/llm.ts
  src/server/routers/tools/search.ts
  src/services/chat.ts
  src/store/agent/slices/chat/selectors/__snapshots__/agent.test.ts.snap
  src/store/user/slices/modelList/selectors/modelProvider.test.ts
  src/store/user/slices/settings/selectors/__snapshots__/settings.test.ts.snap
Labels: 💄 Design, size:L

#7382 ✨ feat: agent opening settings
  .gitignore
  docs/development/basic/feature-development-new.mdx
  docs/development/basic/feature-development-new.zh-CN.mdx
  docs/development/database-schema.dbml
  locales/ar/setting.json
  locales/bg-BG/setting.json
  locales/de-DE/setting.json
  locales/en-US/setting.json
  locales/es-ES/setting.json
  locales/fa-IR/setting.json
  locales/fr-FR/setting.json
  locales/it-IT/setting.json
  locales/ja-JP/setting.json
  locales/ko-KR/setting.json
  locales/nl-NL/setting.json
  locales/pl-PL/setting.json
  locales/pt-BR/setting.json
  locales/ru-RU/setting.json
  locales/tr-TR/setting.json
  locales/vi-VN/setting.json
  locales/zh-CN/setting.json
  locales/zh-TW/setting.json
  scripts/generate-oidc-jwk.mjs
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatList/WelcomeChatItem/OpeningQuestions.tsx
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatList/WelcomeChatItem/WelcomeMessage.tsx
  src/app/[variants]/(main)/chat/(workspace)/features/AgentSettings/CategoryContent/useCategory.tsx
  src/app/[variants]/(main)/chat/(workspace)/features/AgentSettings/index.tsx
  src/const/settings/agent.ts
  src/database/_deprecated/schemas/session.ts
  src/database/client/migrations.json
  src/database/migrations/0021_add_agent_opening_settings.sql
  src/database/migrations/meta/0021_snapshot.json
  src/database/migrations/meta/_journal.json
  src/database/repositories/dataImporter/deprecated/__tests__/fixtures/messages.json
  src/database/repositories/dataImporter/deprecated/__tests__/index.test.ts
  src/database/schemas/agent.ts
  src/features/AgentSetting/AgentOpening/OpeningMessage.tsx
  src/features/AgentSetting/AgentOpening/OpeningQuestions.tsx
  src/features/AgentSetting/AgentOpening/index.tsx
  src/features/AgentSetting/store/selectors.ts
  src/locales/default/setting.ts
  src/migrations/FromV5ToV6/types/v6.ts
  src/server/routers/lambda/session.ts
  src/services/import/client.test.ts
  src/services/session/server.test.ts
  src/store/agent/slices/chat/selectors/__snapshots__/agent.test.ts.snap
  src/store/agent/slices/chat/selectors/agent.ts
  src/store/global/initialState.ts
  src/store/user/slices/settings/selectors/__snapshots__/settings.test.ts.snap
  src/types/agent/index.ts
Labels: 🌠 Feature Request, size:XXL

#7420 💄 style: add `step-r1` & `glm-z1` model fetch support
  src/libs/agent-runtime/stepfun/index.ts
  src/libs/agent-runtime/zhipu/index.ts
Labels: 💄 Design, size:M

#7387 🐛 fix: fix model support file and image logic
  src/features/ChatInput/ActionBar/Upload/ClientMode.tsx
  src/hooks/useModelSupportFiles.ts
  src/store/aiInfra/slices/aiModel/selectors.ts
Labels: size:M

#7345 💄 style: Add Llama 4 & other latest models
  src/config/aiModels/azure.ts
  src/config/aiModels/azureai.ts
  src/config/aiModels/google.ts
  src/config/aiModels/groq.ts
  src/config/aiModels/hunyuan.ts
  src/config/aiModels/moonshot.ts
  src/config/aiModels/novita.ts
  src/config/aiModels/siliconcloud.ts
  src/config/aiModels/stepfun.ts
  src/config/aiModels/tencentcloud.ts
  src/config/aiModels/volcengine.ts
  src/config/aiModels/zhipu.ts
  src/utils/parseModels.test.ts
Labels: 💄 Design, size:XL

#7426 🔨 chore: add oidc auth for lambda route
  src/app/[variants]/oauth/consent/[uid]/Client.tsx
  src/app/[variants]/oauth/consent/[uid]/page.tsx
  src/libs/oidc-provider/config.ts
  src/libs/trpc/edge/index.ts
  src/libs/trpc/lambda/context.ts
  src/libs/trpc/lambda/index.ts
  src/libs/trpc/lambda/middleware/oidcAuth.ts
  src/libs/trpc/middleware/userAuth.ts
  src/server/services/oidc/index.ts
  src/utils/server/__tests__/auth.test.ts
  src/utils/server/auth.ts
Labels: size:L

#7425 🐛 fix: default file embedding provider
  src/const/settings/knowledge.ts
Labels: 🐛 Bug, size:XS

#7430 🔨 chore: fix oidc provider proxy issue with host deployment
  next.config.ts
  src/libs/oidc-provider/adapter.ts
  src/libs/oidc-provider/provider.ts
Labels: size:S

#7448 💄 style: Add o3/o4-mini models
  src/config/aiModels/azure.ts
  src/config/aiModels/azureai.ts
  src/config/aiModels/cohere.ts
  src/config/aiModels/github.ts
  src/config/aiModels/groq.ts
  src/config/aiModels/openai.ts
  src/config/aiModels/openrouter.ts
  src/config/aiModels/volcengine.ts
Labels: size:XL

#7443 💄 style: update 360 AI & Taichu & AI21 model list
  src/config/aiModels/ai21.ts
  src/config/aiModels/ai360.ts
  src/config/aiModels/stepfun.ts
  src/config/aiModels/taichu.ts
  src/config/aiModels/volcengine.ts
  src/config/modelProviders/ai21.ts
  src/database/repositories/aiInfra/index.test.ts
Labels: 💄 Design, size:L

#7449 ✨ feat: support search1api as search provider
  packages/electron-client-ipc/src/events/index.ts
  packages/electron-client-ipc/src/events/remoteServer.ts
  packages/electron-client-ipc/src/types/index.ts
  packages/electron-client-ipc/src/types/remoteServer.ts
  packages/electron-server-ipc/package.json
  packages/electron-server-ipc/src/ipcClient.ts
  packages/electron-server-ipc/src/ipcServer.ts
  packages/web-crawler/src/crawImpl/__tests__/search1api.test.ts
  packages/web-crawler/src/crawImpl/search1api.ts
  packages/web-crawler/src/index.ts
  packages/web-crawler/src/urlRules.ts
  src/config/tools.ts
  src/features/Conversation/Messages/Assistant/Tool/Inspector/Debug.tsx
  src/features/Conversation/Messages/Assistant/Tool/Inspector/PluginState.tsx
  src/features/Conversation/Messages/Assistant/Tool/Render/Arguments.tsx
  src/locales/default/plugin.ts
  src/server/routers/tools/__tests__/search.test.ts
  src/server/routers/tools/search.test.ts
  src/server/routers/tools/search.ts
  src/server/services/search/impls/index.ts
  src/server/services/search/impls/search1api/index.ts
  src/server/services/search/impls/search1api/type.ts
  src/server/services/search/impls/searxng/client.ts
  src/server/services/search/impls/searxng/fixtures/searXNG.ts
  src/server/services/search/impls/searxng/index.test.ts
  src/server/services/search/impls/searxng/index.ts
  src/server/services/search/impls/type.ts
  src/server/services/search/index.ts
  src/store/chat/slices/builtinTool/actions/index.ts
  src/store/chat/slices/builtinTool/actions/search.test.ts
  src/store/chat/slices/builtinTool/actions/search.ts
  src/tools/web-browsing/Portal/Search/Footer.tsx
  src/tools/web-browsing/Portal/Search/ResultList/SearchItem/TitleExtra.tsx
  src/tools/web-browsing/Portal/Search/ResultList/SearchItem/Video.tsx
  src/tools/web-browsing/Portal/Search/ResultList/SearchItem/index.tsx
  src/tools/web-browsing/Portal/Search/ResultList/index.tsx
  src/tools/web-browsing/Portal/Search/index.tsx
  src/tools/web-browsing/Portal/index.tsx
  src/tools/web-browsing/Render/Search/SearchQuery/SearchView.tsx
  src/tools/web-browsing/Render/Search/SearchQuery/index.tsx
  src/tools/web-browsing/Render/Search/SearchResult/SearchResultItem.tsx
  src/tools/web-browsing/Render/Search/SearchResult/index.tsx
  src/tools/web-browsing/Render/Search/index.tsx
  src/tools/web-browsing/Render/index.tsx
  src/tools/web-browsing/components/SearchBar.tsx
  src/tools/web-browsing/index.ts
  src/tools/web-browsing/systemRole.ts
  src/types/tool/search.ts
  src/types/tool/search/index.ts
Labels: 🌠 Feature Request, size:XXL

#7439 💄 style: add `SenseNova-V6` series & `SenseChat-Vision` support
  src/config/aiModels/sensenova.ts
  src/libs/agent-runtime/sensenova/index.ts
  src/libs/agent-runtime/utils/sensenovaHelpers.test.ts
  src/libs/agent-runtime/utils/sensenovaHelpers.ts
Labels: 💄 Design, size:L

#7421 💄 style: Allow folding SystemRole box
  src/app/[variants]/(main)/chat/(workspace)/@topic/features/SystemRole/SystemRoleContent.tsx
  src/app/[variants]/(main)/chat/(workspace)/@topic/features/SystemRole/style.ts
  src/components/SidebarHeader/index.tsx
  src/store/global/actions/workspacePane.ts
  src/store/global/initialState.ts
  src/store/global/selectors/systemStatus.ts
Labels: 💄 Design, size:M

#7456 💄 style: Update Google models
  src/config/aiModels/google.ts
Labels: size:S

#7453 💄 style: Update GitHub & Cloudflare models
  src/config/aiModels/cloudflare.ts
  src/config/aiModels/github.ts
Labels: 💄 Design, size:L

#7463 🐛 fix: Gemini error `Tool use with function calling is unsupported`
  src/libs/agent-runtime/google/index.ts
Labels: size:XS

#7488 🔨 chore: add file-loaders modules
  .eslintrc.js
  .github/workflows/release.yml
  .github/workflows/test.yml
  locales/ar/models.json
  locales/bg-BG/models.json
  locales/de-DE/models.json
  locales/en-US/models.json
  locales/es-ES/models.json
  locales/fa-IR/models.json
  locales/fr-FR/models.json
  locales/it-IT/models.json
  locales/ja-JP/models.json
  locales/ko-KR/models.json
  locales/nl-NL/models.json
  locales/pl-PL/models.json
  locales/pt-BR/models.json
  locales/ru-RU/models.json
  locales/tr-TR/models.json
  locales/vi-VN/models.json
  locales/zh-CN/models.json
  locales/zh-TW/models.json
  packages/file-loaders/README.md
  packages/file-loaders/package.json
  packages/file-loaders/src/index.ts
  packages/file-loaders/src/loadFile.ts
  packages/file-loaders/src/loaders/docx/__snapshots__/index.test.ts.snap
  packages/file-loaders/src/loaders/docx/fixtures/test.docx
  packages/file-loaders/src/loaders/docx/index.test.ts
  packages/file-loaders/src/loaders/docx/index.ts
  packages/file-loaders/src/loaders/excel/__snapshots__/index.test.ts.snap
  packages/file-loaders/src/loaders/excel/fixtures/test.xlsx
  packages/file-loaders/src/loaders/excel/index.test.ts
  packages/file-loaders/src/loaders/excel/index.ts
  packages/file-loaders/src/loaders/index.ts
  packages/file-loaders/src/loaders/pdf/__snapshots__/index.test.ts.snap
  packages/file-loaders/src/loaders/pdf/fixtures/test.pdf
  packages/file-loaders/src/loaders/pdf/index.test.ts
  packages/file-loaders/src/loaders/pdf/index.ts
  packages/file-loaders/src/loaders/pptx/__snapshots__/index.test.ts.snap
  packages/file-loaders/src/loaders/pptx/fixtures/test.pptx
  packages/file-loaders/src/loaders/pptx/index.test.ts
  packages/file-loaders/src/loaders/pptx/index.ts
  packages/file-loaders/src/loaders/text/__snapshots__/index.test.ts.snap
  packages/file-loaders/src/loaders/text/fixtures/test.txt
  packages/file-loaders/src/loaders/text/index.test.ts
  packages/file-loaders/src/loaders/text/index.ts
  packages/file-loaders/src/types.ts
  packages/file-loaders/src/utils/isTextReadableFile.ts
  packages/file-loaders/src/utils/parser-utils.ts
  packages/file-loaders/test/__snapshots__/loaders.test.ts.snap
  packages/file-loaders/test/fixtures/test.csv
  packages/file-loaders/test/fixtures/test.docx
  packages/file-loaders/test/fixtures/test.epub
  packages/file-loaders/test/fixtures/test.md
  packages/file-loaders/test/fixtures/test.pptx
  packages/file-loaders/test/fixtures/test.txt
  packages/file-loaders/test/loaders.test.ts
Labels: size:L

#7491 :pushpin: chore: lock nextauth to beta.25 to prevent build failed
  package.json
Labels: size:XS

#7494 🔨 chore: add mcp client modules
  package.json
  src/server/modules/MCPClient/__tests__/__snapshots__/index.test.ts.snap
  src/server/modules/MCPClient/__tests__/index.test.ts
  src/server/modules/MCPClient/index.ts
Labels: size:L

#7498 🐛 fix: together.ai fetch model list
  src/libs/agent-runtime/togetherai/index.ts
  src/libs/agent-runtime/togetherai/type.ts
Labels: 🐛 Bug, size:M

#6959 💄 style: show token generate performance
  locales/ar/chat.json
  locales/bg-BG/chat.json
  locales/de-DE/chat.json
  locales/en-US/chat.json
  locales/es-ES/chat.json
  locales/fa-IR/chat.json
  locales/fr-FR/chat.json
  locales/it-IT/chat.json
  locales/ja-JP/chat.json
  locales/ko-KR/chat.json
  locales/nl-NL/chat.json
  locales/pl-PL/chat.json
  locales/pt-BR/chat.json
  locales/ru-RU/chat.json
  locales/tr-TR/chat.json
  locales/vi-VN/chat.json
  locales/zh-CN/chat.json
  locales/zh-TW/chat.json
  src/features/Conversation/Extras/Usage/UsageDetail/index.tsx
  src/features/Conversation/Extras/Usage/index.tsx
  src/libs/agent-runtime/anthropic/index.ts
  src/libs/agent-runtime/perplexity/index.test.ts
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
  src/libs/agent-runtime/utils/streams/anthropic.test.ts
  src/libs/agent-runtime/utils/streams/anthropic.ts
  src/libs/agent-runtime/utils/streams/openai.ts
  src/libs/agent-runtime/utils/streams/protocol.test.ts
  src/libs/agent-runtime/utils/streams/protocol.ts
  src/locales/default/chat.ts
  src/store/chat/slices/aiChat/actions/generateAIChat.ts
  src/types/message/base.ts
  src/utils/fetch/fetchSSE.ts
Labels: 💄 Design, size:L

#7517 💄 style: improve mcp server type select and fix refresh mcp manifest issue
  .github/scripts/pr-comment.js
  locales/ar/plugin.json
  locales/bg-BG/plugin.json
  locales/de-DE/plugin.json
  locales/en-US/plugin.json
  locales/es-ES/plugin.json
  locales/fa-IR/plugin.json
  locales/fr-FR/plugin.json
  locales/it-IT/plugin.json
  locales/ja-JP/plugin.json
  locales/ko-KR/plugin.json
  locales/nl-NL/plugin.json
  locales/pl-PL/plugin.json
  locales/pt-BR/plugin.json
  locales/ru-RU/plugin.json
  locales/tr-TR/plugin.json
  locales/vi-VN/plugin.json
  locales/zh-CN/plugin.json
  locales/zh-TW/plugin.json
  src/features/PluginDevModal/MCPManifestForm/ArgsInput.tsx
  src/features/PluginDevModal/MCPManifestForm/MCPTypeSelect.tsx
  src/features/PluginDevModal/MCPManifestForm/index.tsx
  src/libs/mcp/__tests__/__snapshots__/index.test.ts.snap
  src/locales/default/plugin.ts
  src/server/routers/tools/mcp.ts
  src/server/services/mcp/index.ts
  src/services/mcp.ts
  src/store/tool/slices/customPlugin/action.ts
Labels: 🐛 Bug, size:XXL

#7524 💄 style: Update the id of some OpenAI models in OpenRouter
  src/config/aiModels/openrouter.ts
Labels: size:S

#7529 💄 style: improve stdio mcp form
  locales/ar/plugin.json
  locales/bg-BG/plugin.json
  locales/de-DE/plugin.json
  locales/en-US/plugin.json
  locales/es-ES/plugin.json
  locales/fa-IR/plugin.json
  locales/fr-FR/plugin.json
  locales/it-IT/plugin.json
  locales/ja-JP/plugin.json
  locales/ko-KR/plugin.json
  locales/nl-NL/plugin.json
  locales/pl-PL/plugin.json
  locales/pt-BR/plugin.json
  locales/ru-RU/plugin.json
  locales/tr-TR/plugin.json
  locales/vi-VN/plugin.json
  locales/zh-CN/plugin.json
  locales/zh-TW/plugin.json
  src/features/PluginDevModal/MCPManifestForm/ArgsInput.tsx
  src/features/PluginDevModal/MCPManifestForm/index.tsx
  src/features/PluginDevModal/MCPManifestForm/utils.test.ts
  src/features/PluginDevModal/MCPManifestForm/utils.ts
  src/features/PluginDevModal/index.tsx
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
  src/locales/default/plugin.ts
  src/server/services/mcp/index.ts
Labels: size:XXL

#7523 🐛 fix: fix openai tools calling
  src/libs/agent-runtime/utils/streams/openai.test.ts
  src/libs/agent-runtime/utils/streams/openai.ts
Labels: 🐛 Bug, size:L

#7535 🐛 fix: fix hydration error
  src/app/layout.tsx
  src/app/not-found.tsx
  src/database/_deprecated/models/message.ts
  src/database/_deprecated/schemas/message.ts
Labels: 🐛 Bug, size:S

#7450 🐛 fix: Improve stability of Cloudflare Workers AI
  src/libs/agent-runtime/utils/cloudflareHelpers.ts
Labels: 🐛 Bug, size:XS

#7521 🐛 fix: pwa-install cause mobile infinity scroll
  src/features/PWAInstall/index.tsx
Labels: 🐛 Bug, 📱 Mobile Device, size:S

#7558 🐛 fix: fix oidc redirect urls
  src/libs/oidc-provider/config.ts
Labels: 🐛 Bug, size:S

#7550 ♻️ refactor: improve categories selection via SearXNG
  src/tools/web-browsing/index.ts
  src/tools/web-browsing/systemRole.ts
Labels: size:M

#7545 🐛 fix(http-adapter): extract protocol from base URL and add headers
  src/libs/oidc-provider/http-adapter.ts
Labels: 🐛 Bug, size:S

#7563 💄 style: improve oidc OAuth workflow
  locales/ar/models.json
  locales/ar/oauth.json
  locales/bg-BG/models.json
  locales/bg-BG/oauth.json
  locales/de-DE/models.json
  locales/de-DE/oauth.json
  locales/en-US/models.json
  locales/en-US/oauth.json
  locales/es-ES/models.json
  locales/es-ES/oauth.json
  locales/fa-IR/models.json
  locales/fa-IR/oauth.json
  locales/fr-FR/models.json
  locales/fr-FR/oauth.json
  locales/it-IT/models.json
  locales/it-IT/oauth.json
  locales/ja-JP/models.json
  locales/ja-JP/oauth.json
  locales/ko-KR/models.json
  locales/ko-KR/oauth.json
  locales/nl-NL/models.json
  locales/nl-NL/oauth.json
  locales/pl-PL/models.json
  locales/pl-PL/oauth.json
  locales/pt-BR/models.json
  locales/pt-BR/oauth.json
  locales/ru-RU/models.json
  locales/ru-RU/oauth.json
  locales/tr-TR/models.json
  locales/tr-TR/oauth.json
  locales/vi-VN/models.json
  locales/vi-VN/oauth.json
  locales/zh-CN/models.json
  locales/zh-CN/oauth.json
  locales/zh-TW/models.json
  locales/zh-TW/oauth.json
  src/app/(backend)/oidc/consent/route.ts
  src/app/[variants]/oauth/consent/[uid]/Consent.tsx
  src/app/[variants]/oauth/consent/[uid]/Login.tsx
  src/app/[variants]/oauth/consent/[uid]/components/OAuthApplicationLogo.tsx
  src/app/[variants]/oauth/consent/[uid]/page.tsx
  src/app/[variants]/oauth/handoff/Client.tsx
  src/app/[variants]/oauth/handoff/page.tsx
  src/locales/default/oauth.ts
  src/middleware.ts
Labels: size:XL

#7504 💄 style: support `ernie-x1` & `ernie-4.5` series from Wenxin
  src/config/aiModels/wenxin.ts
Labels: 💄 Design, size:L

#7577 👷 build: fix beta publish
  .github/workflows/release-desktop-beta.yml
Labels: size:S

#7582 👷 build: fix beta release
  apps/desktop/package.json
Labels: 🐛 Bug, size:XS

#7585 👷 build: fix desktop beta release issue
  .github/workflows/release-desktop-beta.yml
  apps/desktop/package.json
Labels: size:S

#7588 🐛 fix: fix cloud connection issue
  src/features/ElectronTitlebar/Connection/ConnectionMode.tsx
  src/store/electron/actions/sync.ts
Labels: 🐛 Bug, size:XS

#7589 🐛 fix: fix desktop beta redirect uris
  src/libs/oidc-provider/config.ts
Labels: 🐛 Bug, size:XS

#7591 🐛 fix: fix desktop cloud sync issue
  .github/workflows/release-desktop-beta.yml
  apps/desktop/electron-builder.js
  apps/desktop/electron.vite.config.ts
  apps/desktop/src/main/controllers/AuthCtr.ts
Labels: 🐛 Bug, size:S

#7593 📝 docs: add desktop docs
  apps/desktop/src/main/controllers/RemoteServerSyncCtr.ts
  docs/self-hosting/advanced/desktop.mdx
  docs/self-hosting/advanced/desktop.zh-CN.mdx
Labels: 📝 Documentation, size:L

#7478 💄 style: fix `doubao-1-5-thinking-pro-vision` endpoint calling
  src/config/aiModels/volcengine.ts
Labels: 💄 Design, size:XS

#7599 💄 style: improve hotkey for delete messages
  src/const/hotkeys.ts
Labels: 💄 Design, size:XS

#7613 💄 style(mcp): support stdio env params
  .env.desktop
  locales/ar/models.json
  locales/ar/plugin.json
  locales/bg-BG/models.json
  locales/bg-BG/plugin.json
  locales/de-DE/models.json
  locales/de-DE/plugin.json
  locales/en-US/models.json
  locales/en-US/plugin.json
  locales/es-ES/models.json
  locales/es-ES/plugin.json
  locales/fa-IR/models.json
  locales/fa-IR/plugin.json
  locales/fr-FR/models.json
  locales/fr-FR/plugin.json
  locales/it-IT/models.json
  locales/it-IT/plugin.json
  locales/ja-JP/models.json
  locales/ja-JP/plugin.json
  locales/ko-KR/models.json
  locales/ko-KR/plugin.json
  locales/nl-NL/models.json
  locales/nl-NL/plugin.json
  locales/pl-PL/models.json
  locales/pl-PL/plugin.json
  locales/pt-BR/models.json
  locales/pt-BR/plugin.json
  locales/ru-RU/models.json
  locales/ru-RU/plugin.json
  locales/tr-TR/models.json
  locales/tr-TR/plugin.json
  locales/vi-VN/models.json
  locales/vi-VN/plugin.json
  locales/zh-CN/models.json
  locales/zh-CN/plugin.json
  locales/zh-TW/models.json
  locales/zh-TW/plugin.json
  src/app/[variants]/(main)/_layout/Desktop/SideBar/index.tsx
  src/features/ModelSwitchPanel/index.tsx
  src/features/PluginDevModal/MCPManifestForm/EnvEditor.tsx
  src/features/PluginDevModal/MCPManifestForm/index.tsx
  src/locales/default/plugin.ts
  src/server/globalConfig/index.ts
Labels: 🌠 Feature Request, size:L, Build Desktop

#7586 🐛 fix: Remove `gpt-4o-search-preview` unsupported parameters
  src/libs/agent-runtime/openai/index.ts
Labels: size:S

#7618 🐛 fix: Fix mobile agent settings and textarea scroll
  package.json
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatInput/Mobile/InputArea/index.tsx
  src/app/[variants]/(main)/chat/settings/page.tsx
  src/app/[variants]/(main)/settings/_layout/Desktop/Header.tsx
  src/app/[variants]/(main)/settings/_layout/Mobile/Header.tsx
  src/app/[variants]/(main)/settings/agent/_layout/Desktop.tsx
  src/app/[variants]/(main)/settings/agent/_layout/Mobile.tsx
  src/app/[variants]/(main)/settings/agent/index.tsx
  src/app/[variants]/(main)/settings/common/features/Common.tsx
  src/app/[variants]/(main)/settings/provider/features/ModelList/index.tsx
  src/app/[variants]/(main)/settings/storage/Advanced.tsx
  src/features/ChatInput/ActionBar/Params/ParamsControls.tsx
  src/hooks/useHotkeys/chatScope.ts
  src/hooks/useHotkeys/filesScope.ts
Labels: 🐛 Bug, 📱 Mobile Device, size:L

#7621 💄 style: improve stdio mcp server install experience
  locales/ar/plugin.json
  locales/bg-BG/plugin.json
  locales/de-DE/plugin.json
  locales/en-US/plugin.json
  locales/es-ES/plugin.json
  locales/fa-IR/plugin.json
  locales/fr-FR/plugin.json
  locales/it-IT/plugin.json
  locales/ja-JP/plugin.json
  locales/ko-KR/plugin.json
  locales/nl-NL/plugin.json
  locales/pl-PL/plugin.json
  locales/pt-BR/plugin.json
  locales/ru-RU/plugin.json
  locales/tr-TR/plugin.json
  locales/vi-VN/plugin.json
  locales/zh-CN/plugin.json
  locales/zh-TW/plugin.json
  package.json
  src/features/PluginDevModal/MCPManifestForm/index.tsx
  src/features/PluginDevModal/PluginPreview.tsx
  src/features/PluginDevModal/PluginPreview/ApiVisualizer.tsx
  src/features/PluginDevModal/PluginPreview/EmptyState.tsx
  src/features/PluginDevModal/PluginPreview/index.tsx
  src/features/PluginDevModal/index.tsx
  src/locales/default/plugin.ts
Labels: size:XXL, Build Desktop

#7628 💄 style: Add Qwen3 models
  src/config/aiModels/openrouter.ts
  src/config/aiModels/qwen.ts
  src/libs/agent-runtime/qwen/index.ts
Labels: size:L

#7632 💄 style: improve mcp stdio style
  locales/ar/error.json
  locales/ar/plugin.json
  locales/bg-BG/error.json
  locales/bg-BG/plugin.json
  locales/de-DE/error.json
  locales/de-DE/plugin.json
  locales/en-US/error.json
  locales/en-US/plugin.json
  locales/es-ES/error.json
  locales/es-ES/plugin.json
  locales/fa-IR/error.json
  locales/fa-IR/plugin.json
  locales/fr-FR/error.json
  locales/fr-FR/plugin.json
  locales/it-IT/error.json
  locales/it-IT/plugin.json
  locales/ja-JP/error.json
  locales/ja-JP/plugin.json
  locales/ko-KR/error.json
  locales/ko-KR/plugin.json
  locales/nl-NL/error.json
  locales/nl-NL/plugin.json
  locales/pl-PL/error.json
  locales/pl-PL/plugin.json
  locales/pt-BR/error.json
  locales/pt-BR/plugin.json
  locales/ru-RU/error.json
  locales/ru-RU/plugin.json
  locales/tr-TR/error.json
  locales/tr-TR/plugin.json
  locales/vi-VN/error.json
  locales/vi-VN/plugin.json
  locales/zh-CN/error.json
  locales/zh-CN/plugin.json
  locales/zh-TW/error.json
  locales/zh-TW/plugin.json
  src/features/PluginDevModal/MCPManifestForm/index.tsx
  src/features/PluginDevModal/PluginPreview/ApiVisualizer.tsx
  src/features/PluginDevModal/PluginPreview/EmptyState.tsx
  src/libs/mcp/types.ts
  src/locales/default/error.ts
  src/locales/default/plugin.ts
  src/server/routers/desktop/mcp.ts
  src/server/routers/tools/mcp.ts
  src/server/services/mcp/index.ts
  src/services/mcp.ts
  src/types/tool/plugin.ts
Labels: size:L

#7638 💄 style: Fix OpenRouter models config
  src/config/aiModels/openrouter.ts
Labels: 💄 Design, size:L

#7645 🐛 fix: fix custom provider crash
  apps/desktop/Development.md
  apps/desktop/README.md
  src/app/[variants]/(main)/repos/[id]/@menu/default.tsx
  src/app/[variants]/(main)/repos/[id]/_layout/Desktop/index.tsx
  src/app/[variants]/(main)/repos/[id]/_layout/Mobile.tsx
  src/app/[variants]/(main)/repos/[id]/_layout/type.ts
  src/app/[variants]/(main)/repos/[id]/features/Menu/Head/index.tsx
  src/app/[variants]/(main)/repos/[id]/features/Menu/Menu/index.tsx
  src/app/[variants]/(main)/repos/[id]/features/Menu/index.tsx
  src/app/[variants]/(main)/repos/[id]/page.tsx
  src/app/[variants]/(main)/settings/provider/(detail)/[id]/page.tsx
  src/libs/trpc/client/helpers/desktopRemoteRPCFetch.ts
Labels: size:XL

#7648 🐛 fix: fix stdio mcp server env issue
  apps/desktop/src/main/controllers/SystemCtr.ts
  apps/desktop/src/preload/routeInterceptor.ts
  packages/electron-client-ipc/src/events/system.ts
  src/features/PluginDevModal/MCPManifestForm/index.tsx
  src/libs/mcp/client.ts
  src/server/routers/desktop/mcp.ts
  src/server/services/mcp/index.ts
  src/services/mcp.ts
  src/types/tool/plugin.ts
Labels: 🐛 Bug, size:M

#7641 🐛 fix: Embeddings Format Issue with OpenAI API when using Ollama
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
Labels: ollama, size:XS

#7650 💄 style: update ollama checker
  apps/desktop/electron.vite.config.ts
  src/app/[variants]/(main)/settings/provider/(detail)/ollama/CheckError.tsx
  src/app/[variants]/(main)/settings/provider/(detail)/ollama/Container.tsx
  src/features/Conversation/Error/OllamaBizError/SetupGuide.tsx
  src/features/Conversation/Error/OllamaBizError/index.tsx
  src/features/Conversation/Error/index.tsx
  src/features/OllamaSetupGuide/Desktop.tsx
  src/features/OllamaSetupGuide/index.tsx
  src/utils/server/auth.ts
Labels: 💄 Design, ollama, size:L, Build Desktop

#7651 💄 style: Arrange model tags neatly
  src/components/ModelSelect/index.tsx
Labels: 💄 Design, size:XS

#7631 💄 style: Add Gemini 2.5 Pro Experimental model
  src/config/modelProviders/google.ts
Labels: size:S

#7664 💄 style: Allow copy/edit when generate error
  src/features/Conversation/Actions/Error.tsx
Labels: 🌠 Feature Request, size:S

#7643 💄 style: Support Qwen3 `thinking_budget` param
  src/config/aiModels/qwen.ts
  src/libs/agent-runtime/qwen/index.ts
Labels: size:M
