Repository lobehub/lobe-chat, pull requests merged in 2025-08, with the labels that each got.

#8634 feat: add mobile router
  apps/mobile/app/(auth)/login/index.tsx
  apps/mobile/package.json
  apps/mobile/src/services/_auth/trpc.ts
  apps/mobile/src/services/session.ts
  apps/mobile/src/store/session/index.ts
  src/app/(backend)/trpc/mobile/[trpc]/route.ts
  src/server/routers/mobile/__tests__/file.test.ts
  src/server/routers/mobile/__tests__/importer.test.ts
  src/server/routers/mobile/__tests__/message.test.ts
  src/server/routers/mobile/_template.ts
  src/server/routers/mobile/agent.test.ts
  src/server/routers/mobile/agent.ts
  src/server/routers/mobile/aiModel.test.ts
  src/server/routers/mobile/aiModel.ts
  src/server/routers/mobile/aiProvider.test.ts
  src/server/routers/mobile/aiProvider.ts
  src/server/routers/mobile/chunk.ts
  src/server/routers/mobile/config/__snapshots__/index.test.ts.snap
  src/server/routers/mobile/config/index.test.ts
  src/server/routers/mobile/config/index.ts
  src/server/routers/mobile/document.ts
  src/server/routers/mobile/exporter.ts
  src/server/routers/mobile/file.ts
  src/server/routers/mobile/generation.test.ts
  src/server/routers/mobile/generation.ts
  src/server/routers/mobile/generationBatch.test.ts
  src/server/routers/mobile/generationBatch.ts
  src/server/routers/mobile/generationTopic.test.ts
  src/server/routers/mobile/generationTopic.ts
  src/server/routers/mobile/image.ts
  src/server/routers/mobile/importer.ts
  src/server/routers/mobile/index.ts
  src/server/routers/mobile/knowledgeBase.ts
  src/server/routers/mobile/market/index.ts
  src/server/routers/mobile/message.ts
  src/server/routers/mobile/plugin.ts
  src/server/routers/mobile/ragEval.ts
  src/server/routers/mobile/session.ts
  src/server/routers/mobile/sessionGroup.ts
  src/server/routers/mobile/thread.ts
  src/server/routers/mobile/topic.ts
  src/server/routers/mobile/user.test.ts
  src/server/routers/mobile/user.ts
Labels: 🌠 Feature Request, 📱 Mobile Device, size:XXL

#8633 🐛 fix(desktop): settings window can't exit when fullscreen
  apps/desktop/src/main/core/browser/Browser.ts
Labels: 🐛 Bug, size:S

#8654 🐛 fix: aihubmix request header
  src/config/modelProviders/index.ts
  src/libs/model-runtime/RouterRuntime/createRuntime.ts
  src/libs/model-runtime/aihubmix/index.ts
  src/libs/model-runtime/anthropic/index.ts
  src/libs/model-runtime/google/index.ts
Labels: 🐛 Bug, size:M

#8661 Revert "fix: when s3 files not exist , global files should delete"
  packages/types/src/files/index.ts
  src/config/aiModels/giteeai.ts
  src/config/aiModels/hunyuan.ts
  src/config/aiModels/minimax.ts
  src/config/aiModels/qwen.ts
  src/config/aiModels/sensenova.ts
  src/config/aiModels/volcengine.ts
  src/config/aiModels/wenxin.ts
  src/config/aiModels/zhipu.ts
  src/const/imageGeneration.ts
  src/database/models/file.ts
  src/libs/model-runtime/minimax/createImage.test.ts
  src/libs/model-runtime/minimax/createImage.ts
  src/libs/model-runtime/moonshot/index.ts
  src/libs/model-runtime/qwen/createImage.ts
  src/libs/model-runtime/qwen/index.ts
  src/libs/model-runtime/sensenova/index.ts
  src/libs/model-runtime/utils/usageConverter.test.ts
  src/libs/model-runtime/utils/usageConverter.ts
  src/server/modules/ModelRuntime/index.test.ts
  src/server/routers/lambda/document.ts
  src/server/services/document/index.ts
  src/server/services/file/__tests__/index.test.ts
  src/server/services/file/index.ts
  src/services/rag.ts
  src/store/discover/slices/mcp/action.ts
  src/store/file/slices/chat/action.ts
Labels: files, size:L

#8657 💄 style: update models
  src/config/aiModels/aihubmix.ts
Labels: 💄 Design, size:XS, lgtm

#8658 feat: sidebar implementation
  apps/mobile/.gitignore
  apps/mobile/.npmrc
  apps/mobile/app/(main)/chat/(components)/StopLoadingIcon/index.tsx
  apps/mobile/app/(main)/chat/(components)/StopLoadingIcon/style.ts
  apps/mobile/app/(main)/chat/index.tsx
  apps/mobile/eas.json
  apps/mobile/jest.config.json
  apps/mobile/locales/en-US/chat.json
  apps/mobile/pnpm-lock.yaml
  apps/mobile/src/components/GithubAvatar/__tests__/GitHubAvatar.test.tsx
  apps/mobile/src/components/ListItem/index.tsx
  apps/mobile/src/components/ListItem/style.ts
  apps/mobile/src/features/SideBar/components/Footer/index.tsx
  apps/mobile/src/features/SideBar/components/Footer/styles.ts
  apps/mobile/src/features/SideBar/components/Header/index.tsx
  apps/mobile/src/features/SideBar/components/Header/style.ts
  apps/mobile/src/features/SideBar/components/SessionList/Inbox.tsx
  apps/mobile/src/features/SideBar/components/SessionList/SessionItem.tsx
  apps/mobile/src/features/SideBar/components/SessionList/index.tsx
  apps/mobile/src/features/SideBar/components/SessionList/style.ts
  apps/mobile/src/features/SideBar/index.tsx
  apps/mobile/src/features/SideBar/style.ts
  apps/mobile/src/services/_auth/trpc.ts
  apps/mobile/src/services/session.ts
  apps/mobile/src/store/session/index.ts
  src/app/[variants]/oauth/consent/[uid]/Consent.tsx
Labels: size:L

#8627 🐛 fix: Break line for Gemini Artifacts
  src/features/Conversation/components/ChatItem/utils.test.ts
  src/features/Conversation/components/ChatItem/utils.ts
  src/tools/artifacts/systemRole.ts
Labels: 🐛 Bug, size:M, lgtm

#8677 🔨 chore: desktop trpc log
  src/app/(backend)/trpc/desktop/[trpc]/route.ts
Labels: 🐛 Bug, size:XS

#8555 💄 style: Update mask style
  src/styles/antdOverride.ts
Labels: 💄 Design, size:XS

#8673 🐛 fix: avatar in desktop version
  src/features/User/UserAvatar.tsx
Labels: 🐛 Bug, size:S

#8672 🔨 chore: Add ga4 analytics provider
  package.json
  src/components/Analytics/LobeAnalyticsProvider.tsx
  src/components/Analytics/LobeAnalyticsProviderWrapper.tsx
Labels: 🌠 Feature Request, size:M, lgtm

#8682 ✨ feat: support gpt-oss in Ollama
  src/config/aiModels/ollama.ts
Labels: ollama, size:S

#8683 💄 style: Add Claude Opus 4.1 model
  src/config/aiModels/aihubmix.ts
  src/config/aiModels/anthropic.ts
  src/config/aiModels/groq.ts
  src/config/aiModels/qwen.ts
  src/libs/model-runtime/anthropic/index.ts
  src/libs/model-runtime/utils/modelParse.ts
Labels: size:XL

#8680 ✨ feat: support mcp plugin install from web
  .cursor/rules/i18n.mdc
  apps/desktop/electron-builder.js
  apps/desktop/src/main/controllers/McpInstallCtr.ts
  apps/desktop/src/main/controllers/index.ts
  apps/desktop/src/main/core/App.ts
  apps/desktop/src/main/core/infrastructure/IoCContainer.ts
  apps/desktop/src/main/core/infrastructure/ProtocolManager.ts
  apps/desktop/src/main/types/protocol.ts
  apps/desktop/src/main/utils/__tests__/protocol.test.ts
  apps/desktop/src/main/utils/protocol.ts
  locales/ar/plugin.json
  locales/bg-BG/plugin.json
  locales/de-DE/plugin.json
  locales/en-US/plugin.json
  locales/es-ES/plugin.json
  locales/fa-IR/plugin.json
  locales/fr-FR/plugin.json
  locales/it-IT/plugin.json
  locales/ja-JP/plugin.json
  locales/ko-KR/plugin.json
  locales/nl-NL/plugin.json
  locales/pl-PL/plugin.json
  locales/pt-BR/plugin.json
  locales/ru-RU/plugin.json
  locales/tr-TR/plugin.json
  locales/vi-VN/plugin.json
  locales/zh-CN/plugin.json
  locales/zh-TW/plugin.json
  package.json
  packages/electron-client-ipc/src/events/index.ts
  packages/electron-client-ipc/src/events/protocol.ts
  packages/electron-client-ipc/src/types/index.ts
  packages/electron-client-ipc/src/types/mcpInstall.ts
  packages/types/src/plugins/mcp.ts
  packages/types/src/plugins/protocol.ts
  src/app/[variants]/(main)/chat/_layout/Desktop/index.tsx
  src/app/[variants]/(main)/discover/(detail)/mcp/[slug]/features/Sidebar/ActionButton/index.tsx
  src/components/KeyValueEditor/index.tsx
  src/features/MCP/MCPInstallProgress/index.tsx
  src/features/PluginDevModal/MCPManifestForm/index.tsx
  src/features/PluginStore/McpList/List/Item.tsx
  src/features/ProtocolUrlHandler/InstallPlugin/ConfigDisplay.tsx
  src/features/ProtocolUrlHandler/InstallPlugin/CustomPluginInstallModal.tsx
  src/features/ProtocolUrlHandler/InstallPlugin/OfficialPluginInstallModal/Detail.tsx
  src/features/ProtocolUrlHandler/InstallPlugin/OfficialPluginInstallModal/index.tsx
  src/features/ProtocolUrlHandler/InstallPlugin/index.tsx
  src/features/ProtocolUrlHandler/InstallPlugin/types.ts
  src/features/ProtocolUrlHandler/index.tsx
  src/locales/default/plugin.ts
  src/store/tool/slices/mcpStore/action.ts
  src/store/tool/slices/mcpStore/initialState.ts
  src/store/tool/slices/mcpStore/selectors.ts
Labels: 🌠 Feature Request, size:XXL, Build Desktop

#8688 🐛 fix: fix remote avatar broken in desktop again
  src/features/ChatItem/index.tsx
Labels: 🐛 Bug, size:S

#8691 💄 style: add context menu for desktop
  apps/desktop/src/main/controllers/MenuCtr.ts
  apps/desktop/src/main/locales/default/menu.ts
  apps/desktop/src/main/menus/impls/linux.ts
  apps/desktop/src/main/menus/impls/macOS.ts
  apps/desktop/src/main/menus/impls/windows.ts
  packages/electron-client-ipc/src/events/menu.ts
  src/features/ChatInput/Desktop/InputArea/index.tsx
  src/features/Conversation/components/ChatItem/index.tsx
  src/services/electron/system.ts
Labels: 💄 Design, size:L

#8694 🔨 chore: update author github url
  src/server/ld.ts
Labels: size:XS

#8699 ♻️ refactor: refactor trace type
  packages/types/package.json
  packages/types/src/aiProvider.ts
  packages/types/src/importer.ts
  packages/types/src/index.ts
  packages/types/src/llm.ts
  packages/types/src/rag.ts
  packages/types/src/serverConfig.ts
  packages/types/src/share.ts
  packages/types/src/trace/action.ts
  packages/types/src/trace/enum.ts
  packages/types/src/trace/index.ts
  packages/types/src/user/index.ts
  src/app/(backend)/_deprecated/createBizOpenAI/auth.ts
  src/app/(backend)/_deprecated/createBizOpenAI/createAzureOpenai.ts
  src/app/(backend)/_deprecated/createBizOpenAI/createOpenai.ts
  src/app/(backend)/_deprecated/createBizOpenAI/index.ts
  src/app/(backend)/middleware/auth/index.test.ts
  src/app/(backend)/middleware/auth/index.ts
  src/app/(backend)/middleware/auth/utils.ts
  src/app/(backend)/webapi/chat/[provider]/route.test.ts
  src/app/(backend)/webapi/chat/[provider]/route.ts
  src/app/(backend)/webapi/models/[provider]/pull/route.ts
  src/app/(backend)/webapi/models/[provider]/route.ts
  src/app/(backend)/webapi/plugin/gateway/route.ts
  src/app/(backend)/webapi/text-to-image/[provider]/route.ts
  src/app/(backend)/webapi/trace/route.ts
  src/app/[variants]/(main)/settings/llm/components/Checker.tsx
  src/app/[variants]/(main)/settings/provider/features/ProviderConfig/Checker.tsx
  src/const/trace.ts
  src/features/AgentSetting/store/action.ts
  src/features/Conversation/Error/index.tsx
  src/features/Portal/Artifacts/Header.tsx
  src/libs/model-runtime/ModelRuntime.test.ts
  src/libs/model-runtime/ModelRuntime.ts
  src/libs/traces/event.test.ts
  src/libs/traces/event.ts
  src/server/modules/ModelRuntime/trace.ts
  src/services/__tests__/chat.test.ts
  src/services/chat.ts
  src/store/chat/slices/aiChat/actions/generateAIChat.ts
  src/store/chat/slices/aiChat/actions/memory.ts
  src/store/chat/slices/message/action.test.ts
  src/store/chat/slices/message/action.ts
  src/store/chat/slices/plugin/action.ts
  src/store/chat/slices/topic/action.ts
  src/store/chat/slices/translate/action.ts
  src/types/locale.ts
  src/utils/errorResponse.test.ts
  src/utils/errorResponse.ts
  src/utils/fetch/__tests__/parseError.test.ts
  src/utils/fetch/fetchSSE.ts
  src/utils/fetch/parseError.ts
Labels: size:L

#8489 🐛 fix: Optimize Gemini error message display & Filter empty messages
  src/libs/model-runtime/google/index.ts
  src/libs/model-runtime/utils/googleErrorParser.test.ts
  src/libs/model-runtime/utils/googleErrorParser.ts
Labels: Gemini, size:XL

#8705 ⚡️ perf: support no animation mode
  locales/ar/setting.json
  locales/bg-BG/setting.json
  locales/de-DE/setting.json
  locales/en-US/setting.json
  locales/es-ES/setting.json
  locales/fa-IR/setting.json
  locales/fr-FR/setting.json
  locales/it-IT/setting.json
  locales/ja-JP/setting.json
  locales/ko-KR/setting.json
  locales/nl-NL/setting.json
  locales/pl-PL/setting.json
  locales/pt-BR/setting.json
  locales/ru-RU/setting.json
  locales/tr-TR/setting.json
  locales/vi-VN/setting.json
  locales/zh-CN/setting.json
  locales/zh-TW/setting.json
  package.json
  packages/types/src/user/settings/general.ts
  src/app/[variants]/(main)/settings/common/features/Common.tsx
  src/const/settings/common.ts
  src/layout/GlobalProvider/AppTheme.tsx
  src/locales/default/setting.ts
  src/server/routers/lambda/agent.ts
  src/server/services/user/index.ts
  src/store/user/slices/settings/selectors/general.test.ts
  src/store/user/slices/settings/selectors/general.ts
Labels: ⚡️ Performance, size:L

#8710 🐛 fix: missing languages it-IT, pl-PL, nl-NL
  src/locales/resources.ts
  src/server/sitemap.test.ts
Labels: size:S

#8711 ✨ feat: add GPT-5 series models
  src/config/aiModels/aihubmix.ts
  src/config/aiModels/openai.ts
  src/config/modelProviders/openai.ts
  src/const/models.ts
  src/const/settings/llm.ts
  src/libs/model-runtime/openai/index.ts
  src/services/chat.ts
  src/store/agent/slices/chat/selectors/__snapshots__/agent.test.ts.snap
  src/store/user/slices/modelList/selectors/modelProvider.test.ts
  src/store/user/slices/settings/selectors/__snapshots__/settings.test.ts.snap
Labels: 🌠 Feature Request, size:L

#8678 💄 style: Add descriptions for the FLUX.1 Krea and Qwen Image
  src/config/aiModels/fal.ts
  src/libs/model-runtime/fal/index.ts
Labels: 💄 Design, size:M

#8719 💄 style: improve thinking auto scroll style
  src/components/Thinking/index.tsx
Labels: 💄 Design, size:M

#8729 💄 style: Add mask effect to thinking scroll
  src/components/Thinking/index.tsx
Labels: 💄 Design, size:S

#8746 👷 build: pin `swr@2.3.4` to fix next build
  package.json
Labels: dependencies, size:XS

#8704 🐛 fix: Solve the cache problem caused by the same dom id when sharing image
  src/features/Conversation/components/ChatItem/ShareMessageModal/ShareImage/Preview.tsx
  src/features/Conversation/components/ChatItem/ShareMessageModal/ShareImage/index.tsx
  src/features/Conversation/components/ChatItem/ShareMessageModal/index.tsx
Labels: 🐛 Bug, size:L

#8707 💄 style: improve Gemini error with promptFeedback
  locales/de-DE/error.json
  locales/en-US/error.json
  locales/fr-FR/error.json
  locales/ja-JP/error.json
  locales/ko-KR/error.json
  locales/zh-TW/error.json
  packages/model-runtime/src/utils/streams/google-ai.test.ts
  packages/model-runtime/src/utils/streams/google-ai.ts
  src/locales/default/error.ts
Labels: 🐛 Bug, Gemini, size:L

#8772 💄 style: Adjust near bottom size on thinking scroll
  src/components/Thinking/index.tsx
Labels: size:XS

#8764 ✨ chore: update some models pricing
  packages/model-runtime/src/utils/openaiCompatibleFactory/index.test.ts
  src/config/aiModels/anthropic.ts
  src/config/aiModels/fal.ts
  src/config/aiModels/google.ts
  src/config/aiModels/qwen.ts
  src/config/aiModels/zhipu.ts
Labels: 🌠 Feature Request, size:L

#8777 📝 docs: fix eslint irregular whitespace issues positioning
  docs/development/state-management/state-management-intro.mdx
  docs/development/state-management/state-management-intro.zh-CN.mdx
Labels: 📝 Documentation, size:XS

#8644 💄 style: Update Mistral AI models & Optimize many model providers fetching
  packages/model-runtime/src/RouterRuntime/createRuntime.ts
  packages/model-runtime/src/ai302/index.ts
  packages/model-runtime/src/aihubmix/index.ts
  packages/model-runtime/src/anthropic/index.ts
  packages/model-runtime/src/giteeai/index.ts
  packages/model-runtime/src/github/index.ts
  packages/model-runtime/src/modelscope/index.ts
  packages/model-runtime/src/moonshot/index.ts
  packages/model-runtime/src/novita/__snapshots__/index.test.ts.snap
  packages/model-runtime/src/novita/index.ts
  packages/model-runtime/src/nvidia/index.ts
  packages/model-runtime/src/openai/__snapshots__/index.test.ts.snap
  packages/model-runtime/src/openai/index.ts
  packages/model-runtime/src/openrouter/__snapshots__/index.test.ts.snap
  packages/model-runtime/src/openrouter/index.ts
  packages/model-runtime/src/qiniu/index.ts
  packages/model-runtime/src/qwen/index.ts
  packages/model-runtime/src/siliconcloud/index.ts
  packages/model-runtime/src/utils/modelParse.test.ts
  packages/model-runtime/src/utils/modelParse.ts
  packages/model-runtime/src/utils/streams/openai/openai.ts
  packages/model-runtime/src/v0/index.ts
  packages/model-runtime/src/volcengine/index.ts
  packages/model-runtime/src/xai/index.ts
  packages/model-runtime/src/zhipu/index.ts
  src/config/aiModels/aihubmix.ts
  src/config/aiModels/anthropic.ts
  src/config/aiModels/groq.ts
  src/config/aiModels/hunyuan.ts
  src/config/aiModels/mistral.ts
  src/config/aiModels/moonshot.ts
  src/config/aiModels/openai.ts
  src/config/aiModels/qwen.ts
  src/config/aiModels/sensenova.ts
  src/config/aiModels/siliconcloud.ts
  src/config/aiModels/stepfun.ts
  src/config/aiModels/zhipu.ts
  src/config/modelProviders/aihubmix.ts
  src/config/modelProviders/mistral.ts
  src/config/modelProviders/openai.ts
  src/config/modelProviders/qwen.ts
  src/config/modelProviders/v0.ts
  src/config/modelProviders/volcengine.ts
Labels: Model Provider, size:XL

#8782 🐛 fix: update gpt-5, gpt-5-nano imageOutput
  src/config/aiModels/aihubmix.ts
  src/config/aiModels/openai.ts
Labels: 🐛 Bug, size:XS

#8797 ✨ feat(feature-flags): add ai_image flag to control AI painting UI
  src/app/[variants]/(main)/_layout/Desktop/SideBar/TopActions.test.tsx
  src/app/[variants]/(main)/_layout/Desktop/SideBar/TopActions.tsx
  src/config/featureFlags/schema.test.ts
  src/config/featureFlags/schema.ts
  src/store/serverConfig/selectors.test.ts
Labels: 🌠 Feature Request, size:M

#8805 💄 style: improve auth sign in loading
  src/app/[variants]/(auth)/next-auth/signin/AuthSignInBox.tsx
Labels: 💄 Design, size:XS

#8765 ♻️ refactor: 重构ArgsInput组件
  locales/en-US/components.json
  locales/zh-CN/components.json
  src/features/PluginDevModal/MCPManifestForm/ArgsInput.tsx
  src/locales/default/components.ts
Labels: size:L, Build Desktop

#8827 🐛 fix: improve mcp tracing with user config
  src/app/[variants]/(main)/chat/(workspace)/features/TelemetryNotification.tsx
  src/app/[variants]/(main)/settings/about/index.tsx
  src/server/routers/lambda/market/index.ts
  src/services/discover.ts
  src/services/mcp.ts
Labels: 🐛 Bug, size:S

#8806 ✨ feat(provider): add BFL provider support for image generation
  .vscode/settings.json
  package.json
  packages/const/src/image.ts
  packages/model-runtime/src/bfl/createImage.test.ts
  packages/model-runtime/src/bfl/createImage.ts
  packages/model-runtime/src/bfl/index.test.ts
  packages/model-runtime/src/bfl/index.ts
  packages/model-runtime/src/bfl/types.ts
  packages/model-runtime/src/index.ts
  packages/model-runtime/src/qwen/createImage.ts
  packages/model-runtime/src/runtimeMap.ts
  packages/model-runtime/src/utils/asyncifyPolling.test.ts
  packages/model-runtime/src/utils/asyncifyPolling.ts
  src/app/[variants]/(main)/image/@menu/features/ConfigPanel/index.tsx
  src/config/aiModels/bfl.ts
  src/config/aiModels/index.ts
  src/config/llm.ts
  src/config/modelProviders/bfl.ts
  src/config/modelProviders/index.ts
  src/store/image/slices/generationConfig/hooks.ts
Labels: 🌠 Feature Request, size:XXL

#8830 🐛 fix(db): desktop local db can't vectorization
  src/app/(backend)/api/webhooks/casdoor/route.ts
  src/app/(backend)/api/webhooks/clerk/route.ts
  src/app/(backend)/api/webhooks/logto/route.ts
  src/app/(backend)/webapi/user/avatar/[id]/[image]/route.ts
  src/database/server/models/ragEval/dataset.ts
  src/database/server/models/ragEval/datasetRecord.ts
  src/database/server/models/ragEval/evaluation.ts
  src/database/server/models/ragEval/evaluationRecord.ts
  src/server/routers/async/file.ts
  src/server/routers/async/ragEval.ts
  src/server/routers/lambda/chunk.ts
  src/server/routers/lambda/ragEval.ts
  src/server/routers/lambda/user.ts
  src/server/services/chunk/index.ts
  src/server/services/nextAuthUser/index.test.ts
  src/server/services/nextAuthUser/index.ts
  src/server/services/user/index.test.ts
  src/server/services/user/index.ts
Labels: 🐛 Bug, size:L

#8844 🐛 chore: fix provider data fetch time
  src/app/[variants]/(main)/settings/provider/(detail)/[id]/index.tsx
  src/app/[variants]/(main)/settings/provider/features/ProviderConfig/index.tsx
Labels: 🐛 Bug, size:S

#8838 fix: image models support for aihubmix
  packages/model-runtime/src/RouterRuntime/createRuntime.ts
  packages/model-runtime/src/openai/__snapshots__/index.test.ts.snap
  packages/model-runtime/src/utils/modelParse.ts
  packages/types/src/aiModel.ts
  packages/types/src/llm.ts
  src/store/aiInfra/slices/aiProvider/__tests__/action.test.ts
Labels: 🐛 Bug, size:M

#8851 ✨ feat(models): Add Qwen Image Edit model
  src/config/aiModels/fal.ts
Labels: Model Provider, size:S

#8808 🔨 chore: update github workflow
  .github/workflows/claude-code-review.yml
  .github/workflows/docker-database.yml
  .github/workflows/docker-pglite.yml
  .github/workflows/docker.yml
  .github/workflows/release.yml
  .github/workflows/wiki-sync.yml
  packages/model-runtime/src/utils/modelParse.ts
Labels: size:L

#8885 💄 style: Update mistral model vision ability
  src/config/aiModels/mistral.ts
Labels: vision, size:XS

#8900 🐛 fix(files): remove force-static rendering to enable session access
  .prettierignore
  .vscode/settings.json
  package.json
  src/app/[variants]/(main)/files/[id]/page.tsx
Labels: size:L

#8934 📝 docs(workflow): optimize documentation structure and development setup
  .cursor/rules/add-provider-doc.mdc
  .cursor/rules/debug.mdc
  .github/workflows/release.yml
  .github/workflows/test.yml
  CLAUDE.md
  docs/development/basic/setup-development.mdx
  docs/development/basic/setup-development.zh-CN.mdx
Labels: 📝 Documentation, size:L

#8940 feat: add gemini 2.5 flash image model
  packages/model-runtime/src/google/index.ts
  packages/model-runtime/src/utils/streams/google-ai.ts
  packages/types/src/aiModel.ts
  src/config/aiModels/google.ts
Labels: Gemini, size:M

#8946 🔨 chore: Revert model specification
  .github/workflows/claude.yml
Labels: size:XS

#8962 🐛 fix: fix desktop route error
  apps/desktop/package.json
  src/app/(backend)/trpc/desktop/[trpc]/route.ts
  src/app/(backend)/trpc/trpc.test.ts
  src/app/desktop/devtools/page.tsx
  src/app/desktop/layout.tsx
Labels: 🐛 Bug, size:L

#8972 🔨 chore: update workflow
  .github/workflows/release.yml
Labels: size:XS

#8973 🔨 chore: upgrade `xlsx` to latest
  packages/file-loaders/package.json
Labels: dependencies, size:XS

#8971 📝 docs: add agents md
  AGENTS.md
Labels: 📝 Documentation, size:L, lgtm

#8848 :bug: fix: Restore internet capability icon in chat interface after LLM changes
  packages/model-runtime/src/ollama/index.ts
  packages/types/src/aiModel.ts
Labels: 🐛 Bug, size:XS

#8987 💄 style: fix chat session part theme issue
  src/app/[variants]/(main)/chat/_layout/Desktop/SessionPanel.tsx
Labels: 💄 Design, size:XS

#8989 💄 style: fix clerk scrollBox style
  src/app/[variants]/(main)/profile/features/ClerkProfile.tsx
Labels: 💄 Design, size:XS

#8878 💄 style: update DeepSeek V3.1 & Gemini 2.5 Flash Image Preview models
  packages/model-bank/src/aiModels/aihubmix.ts
  packages/model-bank/src/aiModels/deepseek.ts
  packages/model-bank/src/aiModels/modelscope.ts
  packages/model-bank/src/aiModels/novita.ts
  packages/model-bank/src/aiModels/openrouter.ts
  packages/model-bank/src/aiModels/qwen.ts
  packages/model-bank/src/aiModels/siliconcloud.ts
  packages/model-bank/src/aiModels/vertexai.ts
  packages/model-bank/src/aiModels/volcengine.ts
  packages/model-bank/src/aiModels/xai.ts
  packages/model-runtime/src/deepseek/index.ts
  packages/model-runtime/src/google/index.ts
  packages/model-runtime/src/utils/modelParse.ts
  packages/model-runtime/src/utils/streams/google-ai.ts
  packages/model-runtime/src/volcengine/index.ts
  src/config/modelProviders/modelscope.ts
Labels: 💄 Design, size:L

#8898 ✨ feat: Added support for Azure OpenAI Image Generation
  packages/model-bank/src/aiModels/azure.ts
  packages/model-runtime/src/azureOpenai/index.test.ts
  packages/model-runtime/src/azureOpenai/index.ts
Labels: 🌠 Feature Request, azure, size:L

#8998 🔨 chore(model-runtime): add ChatMethods ChatMethodOptions merge helper
  packages/model-runtime/src/helpers/index.ts
  packages/model-runtime/src/helpers/mergeChatMethodOptions.test.ts
  packages/model-runtime/src/helpers/mergeChatMethodOptions.ts
Labels: size:L

#9000 🔨 chore: Optimized model owner parse
  packages/model-runtime/src/utils/modelParse.test.ts
  packages/model-runtime/src/utils/modelParse.ts
Labels: Model Provider, size:S

#8999 🐛fix: Qwen & SiliconCloud DeepSeek V3.1 Model Ability
  packages/model-bank/src/aiModels/qwen.ts
  packages/model-bank/src/aiModels/siliconcloud.ts
  packages/model-runtime/src/qwen/index.ts
  packages/model-runtime/src/siliconcloud/index.ts
Labels: 🐛 Bug, size:S
