Repository lobehub/lobe-chat, pull requests merged in 2025-01, with the labels that each got.

#5268 ♻️ refactor: refactor provider info and improve settings side bar loading
  package.json
  src/app/(main)/settings/_layout/Desktop/SideBar.tsx
  src/config/modelProviders/ai21.ts
  src/config/modelProviders/ai360.ts
  src/config/modelProviders/anthropic.ts
  src/config/modelProviders/azure.ts
  src/config/modelProviders/baichuan.ts
  src/config/modelProviders/bedrock.ts
  src/config/modelProviders/cloudflare.ts
  src/config/modelProviders/deepseek.ts
  src/config/modelProviders/fireworksai.ts
  src/config/modelProviders/giteeai.ts
  src/config/modelProviders/github.ts
  src/config/modelProviders/google.ts
  src/config/modelProviders/groq.ts
  src/config/modelProviders/higress.ts
  src/config/modelProviders/huggingface.ts
  src/config/modelProviders/hunyuan.ts
  src/config/modelProviders/internlm.ts
  src/config/modelProviders/minimax.ts
  src/config/modelProviders/mistral.ts
  src/config/modelProviders/moonshot.ts
  src/config/modelProviders/novita.ts
  src/config/modelProviders/ollama.ts
  src/config/modelProviders/openai.ts
  src/config/modelProviders/openrouter.ts
  src/config/modelProviders/perplexity.ts
  src/config/modelProviders/qwen.ts
  src/config/modelProviders/sensenova.ts
  src/config/modelProviders/siliconcloud.ts
  src/config/modelProviders/spark.ts
  src/config/modelProviders/stepfun.ts
  src/config/modelProviders/taichu.ts
  src/config/modelProviders/togetherai.ts
  src/config/modelProviders/upstage.ts
  src/config/modelProviders/wenxin.ts
  src/config/modelProviders/xai.ts
  src/config/modelProviders/zeroone.ts
  src/config/modelProviders/zhipu.ts
  src/features/ModelSelect/index.tsx
  src/features/ModelSwitchPanel/index.tsx
  src/hooks/useEnabledChatModels.ts
  src/store/user/slices/modelList/selectors/modelProvider.ts
  src/types/aiModel.ts
  src/types/aiProvider.ts
  src/types/llm.ts
Labels: Model Provider, size:L

#5266 🐛 fix: fix topic mobile view ui error
  src/app/(main)/chat/(workspace)/_layout/Mobile/TopicModal.tsx
Labels: 🐛 Bug, 📱 Mobile Device, size:XS

#5272 ♻️ refactor: fix zero-sized element in topic list
  package.json
  src/app/(main)/chat/(workspace)/@topic/features/TopicListContent/ByTimeMode/index.tsx
Labels: size:S

#5275 🔨 chore: improve server error log
  src/server/modules/AssistantStore/index.ts
Labels: size:XS

#5279 🔨 chore: fix changelog index.json
  docs/changelog/index.json
Labels: size:XS

#5280 🐛 fix: fix chat page error
  src/server/services/changelog/index.ts
Labels: 🐛 Bug, size:XS

#5283 🐛 fix: fix stats data query issue
  locales/ar/auth.json
  locales/bg-BG/auth.json
  locales/de-DE/auth.json
  locales/en-US/auth.json
  locales/es-ES/auth.json
  locales/fa-IR/auth.json
  locales/fr-FR/auth.json
  locales/it-IT/auth.json
  locales/ja-JP/auth.json
  locales/ko-KR/auth.json
  locales/nl-NL/auth.json
  locales/pl-PL/auth.json
  locales/pt-BR/auth.json
  locales/ru-RU/auth.json
  locales/tr-TR/auth.json
  locales/vi-VN/auth.json
  locales/zh-CN/auth.json
  locales/zh-TW/auth.json
  src/app/(main)/profile/stats/features/ModelsRank.tsx
  src/app/(main)/profile/stats/features/TopicsRank.tsx
  src/app/(main)/profile/stats/features/Welcome.tsx
  src/database/server/models/session.ts
  src/database/server/models/topic.ts
  src/locales/default/auth.ts
Labels: size:L

#5289 🐛 fix: Fix heatmap and manifest
  docs/changelog/index.json
  src/app/manifest.ts
  src/database/server/models/__tests__/message.test.ts
  src/database/server/models/message.ts
Labels: 🐛 Bug, size:S

#5287 ⚡️ perf: improve auth page performance
  src/app/(main)/profile/@category/default.tsx
  src/app/(main)/profile/_layout/Desktop/SideBar.tsx
Labels: ⚡️ Performance, size:S

#5291 ♻️ refactor: upgrade `@clerk/nextjs` to v6
  package.json
  src/layout/AuthProvider/Clerk/index.tsx
  src/middleware.ts
  src/utils/server/auth.ts
Labels: size:XS

#5294 🐛 fix: fix format short number
  next.config.ts
  src/features/User/DataStatistics.tsx
  src/utils/format.test.ts
  src/utils/format.ts
Labels: size:M

#5319 💄 style: Fix style warning in antd 5.23.0 and some error logs
  next.config.ts
  package.json
  src/app/(main)/chat/features/Migration/Failed.tsx
  src/app/(main)/discover/(detail)/assistant/[slug]/features/InfoSidebar/index.tsx
  src/app/(main)/discover/(detail)/assistant/[slug]/page.tsx
  src/app/(main)/discover/(detail)/model/[...slugs]/features/InfoSidebar/index.tsx
  src/app/(main)/discover/(detail)/model/[...slugs]/page.tsx
  src/app/(main)/discover/(detail)/plugin/[slug]/features/InfoSidebar/SuggestionItem.tsx
  src/app/(main)/discover/(detail)/plugin/[slug]/features/InfoSidebar/index.tsx
  src/app/(main)/discover/(detail)/plugin/[slug]/page.tsx
  src/app/(main)/discover/(detail)/provider/[slug]/features/InfoSidebar/index.tsx
  src/app/(main)/discover/(list)/assistants/features/Card.tsx
  src/app/(main)/discover/(list)/models/features/Card.tsx
  src/app/(main)/discover/(list)/plugins/features/Card.tsx
  src/app/(main)/discover/(list)/providers/features/Card.tsx
  src/app/(main)/discover/(list)/providers/features/List.tsx
  src/app/(main)/discover/components/VirtuosoGridList/index.tsx
  src/app/(main)/discover/features/ModelFeatureTags.tsx
  src/app/(main)/settings/llm/components/ProviderModelList/ModelFetcher.tsx
  src/app/(main)/settings/llm/components/ProviderModelList/Option.tsx
  src/components/FileParsingStatus/EmbeddingStatus.tsx
  src/components/FileParsingStatus/index.tsx
  src/components/ModelSelect/index.tsx
  src/components/TipGuide/index.tsx
  src/features/ChatInput/ActionBar/Clear.tsx
  src/features/ChatInput/ActionBar/Token/TokenTag.tsx
  src/features/FileManager/FileList/FileListItem/index.tsx
  src/features/User/UserPanel/LangButton.tsx
  src/features/User/UserPanel/ThemeButton.tsx
  src/features/User/UserPanel/index.tsx
Labels: 💄 Design, size:L

#5322 🐛 fix: fix portal suspense error when first open
  src/app/(main)/chat/(workspace)/_layout/Desktop/index.tsx
Labels: 🐛 Bug, size:XS

#5310 📝 docs: fix incorrect casdoor password information in self-hosting guide
  docs/self-hosting/server-database/docker-compose.mdx
Labels: 📝 Documentation, size:XS

#5330 🐛 fix: fix model select not auto update and sort issue
  next.config.ts
  src/components/ModelSelect/index.tsx
  src/database/repositories/aiInfra/index.ts
  src/database/server/models/aiModel.ts
  src/features/ModelSelect/index.tsx
  src/features/ModelSwitchPanel/index.tsx
  src/store/aiInfra/slices/aiProvider/action.ts
  src/store/user/slices/modelList/selectors/modelProvider.ts
  src/types/aiModel.ts
  src/types/aiProvider.ts
Labels: 🐛 Bug, size:M

#5336 🐛 fix: add provider id validate
  locales/ar/modelProvider.json
  locales/bg-BG/modelProvider.json
  locales/de-DE/modelProvider.json
  locales/en-US/modelProvider.json
  locales/es-ES/modelProvider.json
  locales/fa-IR/modelProvider.json
  locales/fr-FR/modelProvider.json
  locales/it-IT/modelProvider.json
  locales/ja-JP/modelProvider.json
  locales/ko-KR/modelProvider.json
  locales/nl-NL/modelProvider.json
  locales/pl-PL/modelProvider.json
  locales/pt-BR/modelProvider.json
  locales/ru-RU/modelProvider.json
  locales/tr-TR/modelProvider.json
  locales/vi-VN/modelProvider.json
  locales/zh-CN/modelProvider.json
  locales/zh-TW/modelProvider.json
  src/app/(main)/settings/provider/features/CreateNewProvider/index.tsx
  src/app/(main)/settings/provider/features/ProviderConfig/Checker.tsx
  src/app/(main)/settings/provider/features/ProviderConfig/index.tsx
  src/config/aiModels/siliconcloud.ts
  src/locales/default/modelProvider.ts
  src/store/aiInfra/slices/aiProvider/action.ts
  src/store/aiInfra/slices/aiProvider/initialState.ts
  src/store/aiInfra/slices/aiProvider/selectors.ts
Labels: 🐛 Bug, size:L

#5357 🐛 fix: fix remark gfm regex breaks in Safari versions < 16.4
  next.config.ts
  package.json
Labels: 🐛 Bug, size:XS

#5360 💄 style: Update siliconcloud model list
  src/config/aiModels/siliconcloud.ts
  src/config/modelProviders/siliconcloud.ts
Labels: 💄 Design, size:L

#5361 🐛 fix: fix provider known issues
  src/app/(main)/discover/(detail)/provider/[slug]/features/ProviderConfig.tsx
  src/database/repositories/aiInfra/index.ts
  src/database/server/models/__tests__/aiModel.test.ts
  src/database/server/models/aiModel.ts
Labels: 🐛 Bug, size:M

#5370 🐛 fix: Revert dependencies
  package.json
Labels: 🐛 Bug, size:XS

#5391 🐛 fix: fix released at for undefined condition
  locales/ar/modelProvider.json
  locales/bg-BG/modelProvider.json
  locales/de-DE/modelProvider.json
  locales/en-US/modelProvider.json
  locales/es-ES/modelProvider.json
  locales/fa-IR/modelProvider.json
  locales/fr-FR/modelProvider.json
  locales/it-IT/modelProvider.json
  locales/ja-JP/modelProvider.json
  locales/ko-KR/modelProvider.json
  locales/nl-NL/modelProvider.json
  locales/pl-PL/modelProvider.json
  locales/pt-BR/modelProvider.json
  locales/ru-RU/modelProvider.json
  locales/tr-TR/modelProvider.json
  locales/vi-VN/modelProvider.json
  locales/zh-CN/modelProvider.json
  locales/zh-TW/modelProvider.json
  src/app/(main)/settings/provider/features/CreateNewProvider/index.tsx
  src/libs/agent-runtime/openai/__snapshots__/index.test.ts.snap
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.test.ts
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
  src/locales/default/modelProvider.ts
Labels: 🐛 Bug, size:L

#5434 🐛 fix: refactor dynamic import in RSC
  src/app/(main)/changelog/not-found.tsx
  src/app/(main)/chat/not-found.tsx
  src/app/(main)/chat/settings/not-found.tsx
  src/app/(main)/discover/(detail)/not-found.tsx
  src/app/(main)/discover/(list)/not-found.tsx
  src/app/(main)/discover/not-found.tsx
  src/app/(main)/discover/search/page.tsx
  src/app/(main)/not-found.tsx
  src/app/(main)/profile/not-found.tsx
  src/app/(main)/profile/security/page.tsx
  src/app/(main)/repos/[id]/not-found.tsx
  src/app/(main)/settings/not-found.tsx
  src/app/not-found.tsx
Labels: 🐛 Bug, size:M

#5436 🐛 fix: fix docker package manager
  Dockerfile
  Dockerfile.database
Labels: 🐛 Bug, size:XS

#5397 📝 docs: Update deepseek model to v3 in README.
  README.ja-JP.md
  README.md
Labels: 📝 Documentation, size:XS

#5297 🐛 fix: fix `enable_search` parameter intro condition in Qwen
  src/libs/agent-runtime/qwen/index.ts
Labels: 🐛 Bug, size:S

#5438 💄 style: improve model config modal
  locales/ar/modelProvider.json
  locales/bg-BG/modelProvider.json
  locales/de-DE/modelProvider.json
  locales/en-US/modelProvider.json
  locales/es-ES/modelProvider.json
  locales/fa-IR/modelProvider.json
  locales/fr-FR/modelProvider.json
  locales/it-IT/modelProvider.json
  locales/ja-JP/modelProvider.json
  locales/ko-KR/modelProvider.json
  locales/nl-NL/modelProvider.json
  locales/pl-PL/modelProvider.json
  locales/pt-BR/modelProvider.json
  locales/ru-RU/modelProvider.json
  locales/tr-TR/modelProvider.json
  locales/vi-VN/modelProvider.json
  locales/zh-CN/modelProvider.json
  locales/zh-TW/modelProvider.json
  scripts/serverLauncher/startServer.js
  src/app/(main)/settings/provider/features/ModelList/CreateNewModelModal/Form.tsx
  src/app/(main)/settings/provider/features/ModelList/CreateNewModelModal/index.tsx
  src/app/(main)/settings/provider/features/ModelList/DisabledModels.tsx
  src/app/(main)/settings/provider/features/ModelList/ModelConfigModal/Form.tsx
  src/app/(main)/settings/provider/features/ModelList/ModelConfigModal/index.tsx
  src/config/aiModels/bedrock.ts
  src/locales/default/modelProvider.ts
Labels: Model Provider, size:XL

#5083 ♻️ refactor(plugin): update plugin prompt
  src/prompts/plugin/index.test.ts
  src/prompts/plugin/index.ts
  src/prompts/plugin/tools.test.ts
  src/prompts/plugin/tools.ts
  src/services/__tests__/__snapshots__/chat.test.ts.snap
  src/services/__tests__/chat.test.ts
Labels: size:M

#4818 📝 docs: add Langfuse observability to documentation
  docs/self-hosting/advanced/observability/langfuse.mdx
Labels: 📝 Documentation, size:M

#5442 ♻️ refactor: improve ai provider code
  src/app/(main)/settings/provider/(detail)/[id]/page.tsx
  src/config/modelProviders/index.ts
Labels: size:M

#5325 ♻️ refactor: refactor Minimax with LobeOpenAICompatibleFactory
  src/app/(backend)/webapi/chat/minimax/route.test.ts
  src/app/(backend)/webapi/chat/minimax/route.ts
  src/config/aiModels/minimax.ts
  src/libs/agent-runtime/minimax/index.test.ts
  src/libs/agent-runtime/minimax/index.ts
  src/libs/agent-runtime/utils/streams/index.ts
  src/libs/agent-runtime/utils/streams/minimax.test.ts
  src/libs/agent-runtime/utils/streams/minimax.ts
Labels: size:XL

#4483 ✨ feat: add lm studio
  locales/ar/providers.json
  locales/bg-BG/providers.json
  locales/de-DE/providers.json
  locales/en-US/providers.json
  locales/es-ES/providers.json
  locales/fa-IR/providers.json
  locales/fr-FR/providers.json
  locales/it-IT/providers.json
  locales/ja-JP/providers.json
  locales/ko-KR/providers.json
  locales/nl-NL/providers.json
  locales/pl-PL/providers.json
  locales/pt-BR/providers.json
  locales/ru-RU/providers.json
  locales/tr-TR/providers.json
  locales/vi-VN/providers.json
  locales/zh-CN/providers.json
  locales/zh-TW/providers.json
  src/app/(main)/settings/provider/(detail)/[id]/index.tsx
  src/config/aiModels/index.ts
  src/config/aiModels/lmstudio.ts
  src/config/modelProviders/index.ts
  src/config/modelProviders/lmstudio.ts
  src/const/settings/llm.ts
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/lmstudio/index.test.ts
  src/libs/agent-runtime/lmstudio/index.ts
  src/libs/agent-runtime/types/type.ts
  src/types/user/settings/keyVaults.ts
Labels: 🌠 Feature Request, Model Provider, size:L

#5177 ✨ feat: support to customize Embedding model with env
  .env.example
  docs/self-hosting/advanced/knowledge-base.mdx
  docs/self-hosting/advanced/knowledge-base.zh-CN.mdx
  src/config/knowledge.ts
  src/const/settings/knowledge.ts
  src/const/settings/llm.ts
  src/database/schemas/ragEvals.ts
  src/libs/agent-runtime/bedrock/index.ts
  src/libs/agent-runtime/ollama/index.ts
  src/server/globalConfig/index.ts
  src/server/globalConfig/parseFilesConfig.test.ts
  src/server/globalConfig/parseFilesConfig.ts
  src/server/routers/async/file.ts
  src/server/routers/lambda/chunk.ts
  src/types/knowledgeBase/index.ts
  src/types/user/settings/filesConfig.ts
Labels: 🌠 Feature Request, size:L

#5304 💄 style: add auth support for `PROXY_URL`
  scripts/serverLauncher/startServer.js
Labels: 🌠 Feature Request, size:S

#5312 📝 docs: add zh-TW readme
  README.ja-JP.md
  README.md
  README.zh-CN.md
  README.zh-TW.md
Labels: 📝 Documentation, size:XXL

#5449 👷 build: Node.js command line arguments use hyphens (-) as word separators
  netlify.toml
Labels: size:XS

#5448 🐛 fix: fix azure in new ai provider
  package.json
  src/services/_auth.ts
  src/types/user/settings/keyVaults.ts
Labels: 🐛 Bug, size:XS

#5453 📝 docs: fix plugin usage link
  docs/usage/features/plugin-system.mdx
  docs/usage/features/plugin-system.zh-CN.mdx
Labels: 📝 Documentation, size:XS

#5462 ♻️ refactor: refactor some implement for the next perfomance improvement
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/[[...login]]/page.tsx
  src/app/(auth)/next-auth/error/AuthErrorPage.tsx
  src/app/(auth)/next-auth/error/page.tsx
  src/app/(auth)/signup/[[...signup]]/page.tsx
  src/app/(backend)/api/auth/error/page.tsx
  src/app/(main)/chat/(workspace)/@conversation/features/ChatInput/Desktop/Footer/index.tsx
  src/app/(main)/chat/@session/features/SessionListContent/DefaultMode.tsx
  src/app/(main)/discover/(list)/assistants/features/Card.tsx
  src/app/(main)/files/[id]/page.tsx
  src/app/(main)/profile/stats/features/ShareButton/Preview.tsx
  src/app/(main)/profile/stats/features/Welcome.tsx
  src/app/(main)/repos/[id]/evals/evaluation/CreateEvaluation/index.tsx
  src/features/InitClientDB/PGliteIcon.tsx
  src/layout/GlobalProvider/ReactScan.tsx
  src/layout/GlobalProvider/index.tsx
  src/libs/next-auth/auth.config.ts
  src/utils/locale.test.ts
  src/utils/locale.ts
Labels: size:L

#5467 📝 docs: Fix docs typo
  docs/self-hosting/server-database/vercel.zh-CN.mdx
Labels: 📝 Documentation, size:XS

#5473 👷 build: vercel build OOM error
  vercel.json
Labels: 🐛 Bug, size:XS

#5477 🐛 fix: Gemini models HarmBlockThreshold
  src/libs/agent-runtime/google/index.ts
Labels: 🐛 Bug, size:S

#5479 🐛 fix: temporarily disable S3 client integrity check for Cloudflare R2
  src/server/modules/S3/index.ts
Labels: 🐛 Bug, size:XS

#5454 🐛 fix: improve validation for provider and model in parseFilesConfig
  src/const/settings/knowledge.ts
  src/server/globalConfig/parseFilesConfig.test.ts
  src/server/globalConfig/parseFilesConfig.ts
  src/types/knowledgeBase/index.ts
  src/types/user/settings/filesConfig.ts
Labels: 🐛 Bug, size:L

#5488 ✨ feat: support new ai provider in client pglite
  package.json
  src/app/(main)/discover/(detail)/provider/[slug]/features/ProviderConfig.tsx
  src/app/(main)/settings/hooks/useCategory.tsx
  src/app/(main)/settings/provider/(detail)/[id]/ClientMode.tsx
  src/app/(main)/settings/provider/(detail)/[id]/page.tsx
  src/app/(main)/settings/provider/ProviderMenu/SortProviderModal/index.tsx
  src/database/client/migrations.json
  src/database/repositories/tableViewer/index.test.ts
  src/database/repositories/tableViewer/index.ts
  src/database/server/models/aiProvider.ts
  src/features/DebugUI/Content.tsx
  src/features/DebugUI/index.tsx
  src/features/DevPanel/FloatPanel.tsx
  src/features/DevPanel/PostgresViewer/DataTable/Table.tsx
  src/features/DevPanel/PostgresViewer/DataTable/TableCell.tsx
  src/features/DevPanel/PostgresViewer/DataTable/index.tsx
  src/features/DevPanel/PostgresViewer/Schema.tsx
  src/features/DevPanel/PostgresViewer/TableColumns.tsx
  src/features/DevPanel/PostgresViewer/index.tsx
  src/features/DevPanel/PostgresViewer/useTableColumns.ts
  src/features/DevPanel/index.tsx
  src/features/ModelSwitchPanel/index.tsx
  src/hooks/useEnabledChatModels.ts
  src/hooks/useModelContextWindowTokens.ts
  src/hooks/useModelHasContextWindowToken.ts
  src/hooks/useModelSupportToolUse.ts
  src/hooks/useModelSupportVision.ts
  src/layout/GlobalProvider/index.tsx
  src/services/_auth.ts
  src/services/aiModel.ts
  src/services/aiModel/client.ts
  src/services/aiModel/index.test.ts
  src/services/aiModel/index.ts
  src/services/aiModel/server.ts
  src/services/aiModel/type.ts
  src/services/aiProvider.ts
  src/services/aiProvider/client.ts
  src/services/aiProvider/index.test.ts
  src/services/aiProvider/index.ts
  src/services/aiProvider/server.ts
  src/services/aiProvider/type.ts
  src/services/chat.ts
  src/services/tableViewer/client.ts
  src/services/tableViewer/index.ts
  src/store/aiInfra/slices/aiProvider/action.ts
  src/types/serverConfig.ts
  src/types/tableViewer.ts
  tests/utils.tsx
Labels: 🌠 Feature Request, size:XXL

#5497 👷 build: fix migration
  vercel.json
Labels: size:XS

#5498 🐛 fix: fix api key in api key form
  src/features/Conversation/Error/APIKeyForm/ProviderApiKeyForm.tsx
  src/features/Conversation/Error/APIKeyForm/useApiKey.ts
  src/store/aiInfra/slices/aiProvider/selectors.ts
  src/types/aiProvider.ts
Labels: 🐛 Bug, size:M

#5502 🐛 fix: fix hydration error
  package.json
  src/hooks/useInterceptingRoutes.ts
  src/libs/trpc/client/lambda.ts
Labels: 🐛 Bug, size:S

#5500 ⚡️ perf: move pglite into web worker
  next.config.ts
  src/database/client/db.ts
  src/database/client/pglite.ts
  src/database/client/pglite.worker.ts
  src/database/client/type.ts
Labels: ⚡️ Performance, size:L

#5514 ♻️ refactor: refactor ai provider detail
  src/app/(main)/settings/provider/ProviderMenu/Item.tsx
  src/app/(main)/settings/provider/features/ProviderConfig/EnableSwitch.tsx
  src/app/(main)/settings/provider/features/ProviderConfig/index.tsx
Labels: size:M

#5516 ♻️ refactor: refactor provider code
  src/app/(main)/settings/provider/(detail)/[id]/index.tsx
  src/app/(main)/settings/provider/(list)/ProviderGrid/Card.tsx
  src/app/(main)/settings/provider/(list)/ProviderGrid/style.ts
  src/types/llm.ts
Labels: size:L

#5267 ♻️ refactor: Remove redundant payload remapping in client-fetch
  src/services/__tests__/_auth.test.ts
  src/services/_auth.ts
  src/services/chat.ts
Labels: size:L

#5522 🔨 chore: Create devcontainer.json for codespaces
  .devcontainer/devcontainer.json
Labels: size:XS

#5520 💄 style: Add deepseek r1 model
  src/config/aiModels/deepseek.ts
  src/config/modelProviders/deepseek.ts
  src/libs/agent-runtime/deepseek/index.ts
Labels: 💄 Design, size:M

#5525 ♻️ refactor: improve error code
  src/database/schemas/user.ts
  src/server/globalConfig/genServerAiProviderConfig.ts
Labels: size:XS

#5527 💄 style: support assistant blacklist
  src/app/(backend)/webapi/revalidate/route.ts
  src/server/modules/AssistantStore/index.ts
  src/server/modules/EdgeConfig/index.ts
  src/types/requestCache.ts
Labels: 💄 Design, size:M

#5532 ♻️ refactor: improve code for provider
  src/app/(main)/settings/modal/page.tsx
  src/app/(main)/settings/provider/(list)/ProviderGrid/Card.tsx
  src/app/(main)/settings/provider/(list)/ProviderGrid/EnableSwitch.tsx
  src/app/(main)/settings/provider/(list)/ProviderGrid/index.tsx
  src/app/(main)/settings/provider/ProviderMenu/SkeletonList.tsx
  src/app/(main)/settings/provider/ProviderMenu/index.tsx
Labels: size:M

#5533 💄 style: refactor `@nav` layout and improve pin list style
  src/app/(main)/@nav/default.tsx
  src/app/(main)/_layout/Desktop/SideBar/Avatar.test.tsx
  src/app/(main)/_layout/Desktop/SideBar/Avatar.tsx
  src/app/(main)/_layout/Desktop/SideBar/BottomActions.tsx
  src/app/(main)/_layout/Desktop/SideBar/PinList/index.tsx
  src/app/(main)/_layout/Desktop/SideBar/TopActions.test.tsx
  src/app/(main)/_layout/Desktop/SideBar/TopActions.tsx
  src/app/(main)/_layout/Desktop/SideBar/index.tsx
  src/app/(main)/_layout/Desktop/index.tsx
  src/app/(main)/_layout/Mobile/NavBar.tsx
  src/app/(main)/_layout/Mobile/index.tsx
  src/app/(main)/_layout/type.ts
  src/app/(main)/layout.tsx
  src/layout/GlobalProvider/StoreInitialization.tsx
Labels: 💄 Design, size:L

#5316 💄 style: add `ModelFetcher` for supported provider
  src/config/aiModels/ai360.ts
  src/config/aiModels/giteeai.ts
  src/config/aiModels/minimax.ts
  src/config/aiModels/moonshot.ts
  src/config/aiModels/taichu.ts
  src/config/aiModels/upstage.ts
  src/config/aiModels/zhipu.ts
  src/config/modelProviders/ai21.ts
  src/config/modelProviders/ai360.ts
  src/config/modelProviders/anthropic.ts
  src/config/modelProviders/giteeai.ts
  src/config/modelProviders/google.ts
  src/config/modelProviders/hunyuan.ts
  src/config/modelProviders/mistral.ts
  src/config/modelProviders/moonshot.ts
  src/config/modelProviders/spark.ts
  src/config/modelProviders/taichu.ts
  src/config/modelProviders/upstage.ts
  src/config/modelProviders/zeroone.ts
  src/config/modelProviders/zhipu.ts
  src/libs/agent-runtime/ai360/index.ts
  src/libs/agent-runtime/anthropic/index.ts
  src/libs/agent-runtime/baichuan/index.ts
  src/libs/agent-runtime/deepseek/index.ts
  src/libs/agent-runtime/fireworksai/index.ts
  src/libs/agent-runtime/giteeai/index.ts
  src/libs/agent-runtime/google/index.ts
  src/libs/agent-runtime/groq/index.ts
  src/libs/agent-runtime/huggingface/index.ts
  src/libs/agent-runtime/internlm/index.ts
  src/libs/agent-runtime/minimax/index.ts
  src/libs/agent-runtime/mistral/index.ts
  src/libs/agent-runtime/moonshot/index.ts
  src/libs/agent-runtime/qwen/index.ts
  src/libs/agent-runtime/sensenova/index.ts
  src/libs/agent-runtime/siliconcloud/index.ts
  src/libs/agent-runtime/stepfun/index.ts
  src/libs/agent-runtime/xai/index.ts
  src/libs/agent-runtime/zeroone/index.ts
  src/libs/agent-runtime/zhipu/index.ts
Labels: 💄 Design, size:XL

#5540 💄 style: support model list with model fetcher settings
  locales/ar/models.json
  locales/bg-BG/models.json
  locales/de-DE/models.json
  locales/en-US/common.json
  locales/en-US/models.json
  locales/es-ES/models.json
  locales/fa-IR/models.json
  locales/fr-FR/models.json
  locales/it-IT/models.json
  locales/ja-JP/models.json
  locales/ko-KR/models.json
  locales/nl-NL/models.json
  locales/pl-PL/models.json
  locales/pt-BR/models.json
  locales/ru-RU/models.json
  locales/tr-TR/models.json
  locales/vi-VN/models.json
  locales/zh-CN/models.json
  locales/zh-TW/models.json
  package.json
  src/app/(main)/settings/provider/(detail)/[id]/index.tsx
  src/app/(main)/settings/provider/features/ModelList/ModelTitle/index.tsx
  src/app/(main)/settings/provider/features/ModelList/index.tsx
  src/server/globalConfig/genServerAiProviderConfig.ts
  src/server/globalConfig/index.ts
  src/services/chat.ts
  src/types/aiProvider.ts
Labels: 💄 Design, size:L

#5544 💄 style: improve discover model page
  src/app/(main)/discover/(detail)/model/[...slugs]/features/Header.tsx
  src/app/(main)/discover/(detail)/model/[...slugs]/features/InfoSidebar/SuggestionItem.tsx
  src/app/(main)/discover/(detail)/model/[...slugs]/features/ParameterList/index.tsx
  src/app/(main)/discover/(detail)/model/[...slugs]/features/ProviderList/index.tsx
  src/features/DevPanel/PostgresViewer/DataTable/Table.tsx
  src/features/DevPanel/PostgresViewer/DataTable/index.tsx
  src/features/DevPanel/PostgresViewer/Schema.tsx
  src/features/DevPanel/PostgresViewer/TableColumns.tsx
  src/features/DevPanel/PostgresViewer/usePgTable.ts
  src/features/DevPanel/PostgresViewer/useTableColumns.ts
  src/services/config.ts
Labels: 💄 Design, size:L

#5546 💄 style: Add gemini new model
  src/config/aiModels/google.ts
  src/config/modelProviders/google.ts
Labels: Gemini, size:M

#5551 ♻️ refactor: move hooks and component
  src/app/(main)/chat/(workspace)/_layout/Desktop/ChatHeader/Tags.tsx
  src/app/(main)/chat/(workspace)/_layout/Mobile/TopicModal.tsx
  src/app/(main)/chat/(workspace)/features/ShareButton/index.tsx
  src/features/ChatInput/ActionBar/Tools/Dropdown.tsx
  src/features/PluginTag/PluginStatus.tsx
  src/features/PluginTag/index.tsx
  src/features/ShareModal/ShareImage/Preview.tsx
  src/hooks/useWorkspaceModal.tsx
Labels: size:S

#5553 🐛 fix: upgrade `react-i18next` to ^15
  package.json
Labels: size:XS

#5557 🐛 fix: fix debounce issue of provider config
  locales/ar/modelProvider.json
  locales/ar/models.json
  locales/bg-BG/modelProvider.json
  locales/bg-BG/models.json
  locales/de-DE/modelProvider.json
  locales/de-DE/models.json
  locales/en-US/modelProvider.json
  locales/en-US/models.json
  locales/es-ES/modelProvider.json
  locales/es-ES/models.json
  locales/fa-IR/modelProvider.json
  locales/fa-IR/models.json
  locales/fr-FR/modelProvider.json
  locales/fr-FR/models.json
  locales/it-IT/modelProvider.json
  locales/it-IT/models.json
  locales/ja-JP/modelProvider.json
  locales/ja-JP/models.json
  locales/ko-KR/modelProvider.json
  locales/ko-KR/models.json
  locales/nl-NL/modelProvider.json
  locales/nl-NL/models.json
  locales/pl-PL/modelProvider.json
  locales/pl-PL/models.json
  locales/pt-BR/modelProvider.json
  locales/pt-BR/models.json
  locales/ru-RU/modelProvider.json
  locales/ru-RU/models.json
  locales/tr-TR/modelProvider.json
  locales/tr-TR/models.json
  locales/vi-VN/modelProvider.json
  locales/vi-VN/models.json
  locales/zh-CN/modelProvider.json
  locales/zh-CN/models.json
  locales/zh-TW/modelProvider.json
  locales/zh-TW/models.json
  src/app/(main)/settings/provider/(detail)/azure/page.tsx
  src/app/(main)/settings/provider/(detail)/bedrock/page.tsx
  src/app/(main)/settings/provider/(detail)/cloudflare/page.tsx
  src/app/(main)/settings/provider/(detail)/github/page.tsx
  src/app/(main)/settings/provider/(detail)/huggingface/page.tsx
  src/app/(main)/settings/provider/(detail)/wenxin/page.tsx
  src/app/(main)/settings/provider/features/ProviderConfig/index.tsx
  src/components/FormInput/FormInput.tsx
  src/components/FormInput/FormPassword.tsx
  src/components/FormInput/index.ts
  src/config/modelProviders/deepseek.ts
  src/locales/default/modelProvider.ts
Labels: 🐛 Bug, size:XL

#5560 💄 style: Add new stepfun model
  src/config/aiModels/stepfun.ts
  src/config/modelProviders/stepfun.ts
Labels: Model Provider, size:M

#5569 🐛 fix: fix tts in new provider model
  src/services/_header.ts
Labels: size:S

#5564 💄 style: Add HuggingFace Model: DeepSeek R1
  src/config/aiModels/huggingface.ts
  src/config/modelProviders/huggingface.ts
Labels: size:S

#5571 🐛 fix: fix form input in provider
  package.json
  src/components/FormInput/FormInput.test.tsx
  src/components/FormInput/FormInput.tsx
  src/components/FormInput/FormPassword.tsx
Labels: 🐛 Bug, size:M

#5566 💄 style: fix model fetch match tag error & add Hunyuan model fetch support
  src/config/aiModels/hunyuan.ts
  src/config/aiModels/qwen.ts
  src/config/modelProviders/hunyuan.ts
  src/libs/agent-runtime/deepseek/index.ts
  src/libs/agent-runtime/hunyuan/index.ts
  src/libs/agent-runtime/qwen/index.ts
  src/libs/agent-runtime/stepfun/index.ts
Labels: 💄 Design, size:L

#5585 🐛 fix: fix ollama Browser Request failed in PG mode
  src/config/modelProviders/ollama.ts
Labels: 🐛 Bug, ollama, size:XS

#5584 💄 style: add `parallel_tool_calls` support for Qwen
  src/libs/agent-runtime/qwen/index.ts
Labels: 💄 Design, size:XS

#5582 💄 style: fix tag version and add provider changelog
  docs/changelog/2025-01-22-new-ai-provider.mdx
  docs/changelog/2025-01-22-new-ai-provider.zh-CN.mdx
  docs/changelog/index.json
  docs/self-hosting/advanced/auth/next-auth/casdoor.mdx
  docs/self-hosting/advanced/auth/next-auth/casdoor.zh-CN.mdx
  docs/self-hosting/advanced/knowledge-base.mdx
  docs/self-hosting/advanced/knowledge-base.zh-CN.mdx
  docs/self-hosting/advanced/observability/langfuse.mdx
  docs/self-hosting/server-database.mdx
  locales/ar/changelog.json
  locales/ar/models.json
  locales/bg-BG/changelog.json
  locales/bg-BG/models.json
  locales/de-DE/changelog.json
  locales/de-DE/models.json
  locales/en-US/changelog.json
  locales/en-US/models.json
  locales/es-ES/changelog.json
  locales/es-ES/models.json
  locales/fa-IR/changelog.json
  locales/fa-IR/models.json
  locales/fr-FR/changelog.json
  locales/fr-FR/models.json
  locales/it-IT/changelog.json
  locales/it-IT/models.json
  locales/ja-JP/changelog.json
  locales/ja-JP/models.json
  locales/ko-KR/changelog.json
  locales/ko-KR/models.json
  locales/nl-NL/changelog.json
  locales/nl-NL/models.json
  locales/pl-PL/changelog.json
  locales/pl-PL/models.json
  locales/pt-BR/changelog.json
  locales/pt-BR/models.json
  locales/ru-RU/changelog.json
  locales/ru-RU/models.json
  locales/tr-TR/changelog.json
  locales/tr-TR/models.json
  locales/vi-VN/changelog.json
  locales/vi-VN/models.json
  locales/zh-CN/changelog.json
  locales/zh-CN/models.json
  locales/zh-TW/changelog.json
  locales/zh-TW/models.json
  src/app/@modal/(.)changelog/modal/features/Pagination.tsx
  src/locales/default/changelog.ts
  src/server/services/changelog/index.test.ts
  src/server/services/changelog/index.ts
Labels: 📝 Documentation, size:XL

#5599 💄 style: improve model pricing with CNY
  src/app/(main)/settings/provider/features/ModelList/ModelItem.tsx
  src/const/currency.ts
  src/const/discover.ts
  src/utils/format.test.ts
  src/utils/format.ts
Labels: 💄 Design, size:M

#5577 📝 docs: add domain configuration scheme documentation based on Casdoor authentication method
  docs/self-hosting/server-database/docker-compose.zh-CN.mdx
Labels: 📝 Documentation, size:L

#5602 💄 style: improve thinking style
  locales/ar/chat.json
  locales/ar/components.json
  locales/bg-BG/chat.json
  locales/bg-BG/components.json
  locales/de-DE/chat.json
  locales/de-DE/components.json
  locales/en-US/chat.json
  locales/en-US/components.json
  locales/es-ES/chat.json
  locales/es-ES/components.json
  locales/fa-IR/chat.json
  locales/fa-IR/components.json
  locales/fr-FR/chat.json
  locales/fr-FR/components.json
  locales/it-IT/chat.json
  locales/it-IT/components.json
  locales/ja-JP/chat.json
  locales/ja-JP/components.json
  locales/ko-KR/chat.json
  locales/ko-KR/components.json
  locales/nl-NL/chat.json
  locales/nl-NL/components.json
  locales/pl-PL/chat.json
  locales/pl-PL/components.json
  locales/pt-BR/chat.json
  locales/pt-BR/components.json
  locales/ru-RU/chat.json
  locales/ru-RU/components.json
  locales/tr-TR/chat.json
  locales/tr-TR/components.json
  locales/vi-VN/chat.json
  locales/vi-VN/components.json
  locales/zh-CN/chat.json
  locales/zh-CN/components.json
  locales/zh-TW/chat.json
  locales/zh-TW/components.json
  src/components/Thinking/index.tsx
  src/features/Conversation/Messages/Assistant/Reasoning/index.tsx
  src/locales/default/chat.ts
  src/locales/default/components.ts
Labels: size:L

#5247 🔨 chore: local docker-compose setup.sh compatible mac osx
  docker-compose/local/setup.sh
Labels: 🐛 Bug, size:S

#5481 ✨ feat: Support Doubao Models
  src/app/(main)/settings/provider/(detail)/doubao/page.tsx
  src/app/(main)/settings/provider/features/ModelList/ModelConfigModal/index.tsx
  src/config/aiModels/doubao.ts
  src/config/aiModels/index.ts
  src/config/llm.ts
  src/config/modelProviders/doubao.ts
  src/config/modelProviders/index.ts
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/doubao/index.ts
  src/libs/agent-runtime/index.ts
  src/libs/agent-runtime/types/type.ts
  src/server/globalConfig/index.ts
  src/services/chat.ts
  src/types/aiProvider.ts
  src/types/user/settings/keyVaults.ts
Labels: 🌠 Feature Request, size:L

#5603 ♻️ refactor: useMobileWorkspace use nqus to replace useQuery
  package.json
  src/app/(main)/_layout/Mobile/index.tsx
  src/app/(main)/chat/_layout/Mobile.tsx
  src/app/(main)/files/(content)/_layout/Mobile.tsx
  src/app/(main)/repos/[id]/_layout/Mobile.tsx
  src/components/DataStyleModal/index.tsx
  src/features/InitClientDB/EnableModal.tsx
  src/hooks/useShowMobileWorkspace.ts
  src/hooks/useWorkspaceModal.tsx
  src/middleware.ts
Labels: size:M

#5604 ♻️ refactor: remove use query
  src/app/(main)/discover/features/StoreSearchBar.tsx
  src/app/(main)/discover/features/useNav.tsx
  src/app/(main)/discover/search/_layout/Mobile/Header.tsx
  src/app/(main)/profile/@category/features/CategoryContent.tsx
  src/app/(main)/settings/@category/features/CategoryContent.tsx
  src/app/@modal/chat/(.)settings/modal/features/CategoryContent.tsx
  src/app/@modal/chat/(.)settings/modal/layout.tsx
  src/app/@modal/chat/(.)settings/modal/page.tsx
  src/components/withSuspense.tsx
  src/features/AgentSetting/AgentTTS/index.tsx
  src/hooks/useActiveTabKey.ts
  src/hooks/useChatSettingsTab.ts
  src/hooks/useDiscoverTab.ts
  src/hooks/useQuery.test.ts
  src/hooks/useQuery.ts
  src/hooks/useQueryRoute.test.ts
  src/hooks/useQueryRoute.ts
  src/hooks/useSettingsTab.ts
  src/layout/GlobalProvider/ReactScan.tsx
Labels: size:L

#5607 🐛 fix: fix changelog locale not showing English
  src/server/services/changelog/index.ts
Labels: 🐛 Bug, size:XS

#5611 🐛 fix: pin `@clerk/nextjs@6.10.2` to avoid build error
  package.json
Labels: 🐛 Bug, size:XS

#5632 🐛 fix: support litellm reasoning streaming
  src/libs/agent-runtime/utils/streams/openai.test.ts
  src/libs/agent-runtime/utils/streams/openai.ts
Labels: 🐛 Bug, size:L
