Repository lobehub/lobe-chat, pull requests merged in 2025-05, with the labels that each got.

#7659 💄 style: Fix style issues
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatInput/Mobile/Files/FileItem/File.tsx
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatInput/Mobile/Files/FileItem/Image.tsx
  src/app/[variants]/(main)/chat/(workspace)/_layout/Desktop/TopicPanel.tsx
  src/app/[variants]/(main)/settings/provider/features/ProviderConfig/Checker.tsx
Labels: 💄 Design, size:M

#7665 💄 style: add windows control and tray
  apps/desktop/build/favicon.ico
  apps/desktop/build/icon-beta.ico
  apps/desktop/build/icon-nightly.ico
  apps/desktop/build/icon.ico
  apps/desktop/electron-builder.js
  apps/desktop/resources/error.html
  apps/desktop/resources/tray-icon.png
  apps/desktop/src/main/controllers/BrowserWindowsCtr.ts
  apps/desktop/src/main/controllers/TrayMenuCtr.ts
  apps/desktop/src/main/core/App.ts
  apps/desktop/src/main/core/Browser.ts
  apps/desktop/src/main/core/BrowserManager.ts
  apps/desktop/src/main/core/Tray.ts
  apps/desktop/src/main/core/TrayManager.ts
  apps/desktop/src/main/types/ipcClientEvent.ts
  packages/electron-client-ipc/src/events/index.ts
  packages/electron-client-ipc/src/events/system.ts
  packages/electron-client-ipc/src/events/tray.ts
  packages/electron-client-ipc/src/types/index.ts
  packages/electron-client-ipc/src/types/tray.ts
  src/features/ElectronTitlebar/WinControl/index.tsx
  src/features/ElectronTitlebar/const.ts
  src/features/ElectronTitlebar/index.tsx
  src/services/electron/system.ts
Labels: 💄 Design, size:XL, Build Desktop

#7675 🐛 fix: fix quit with reopen window
  apps/desktop/src/main/core/Browser.ts
  apps/desktop/src/main/core/BrowserManager.ts
  package.json
  src/app/[variants]/(main)/settings/provider/(detail)/ollama/CheckError.tsx
  src/features/OllamaSetupGuide/Desktop.tsx
  src/store/tool/slices/store/action.ts
  src/tools/local-files/Render/RenameLocalFile/index.tsx
  src/tools/local-files/Render/index.tsx
Labels: 🐛 Bug, size:L, Build Desktop

#7680 ✅ test: fix tests
  package.json
  src/libs/mcp/__tests__/__snapshots__/index.test.ts.snap
Labels: size:XS

#7684 💄 style: add write file tool to local-file plugin
  apps/desktop/src/main/controllers/LocalFileCtr.ts
  package.json
  packages/electron-client-ipc/src/events/localFile.ts
  packages/electron-client-ipc/src/types/localFile.ts
  src/features/Conversation/components/MarkdownElements/LocalFile/Render/index.tsx
  src/features/LocalFile/LocalFile.tsx
  src/features/LocalFile/LocalFolder.tsx
  src/features/LocalFile/index.tsx
  src/services/electron/localFileService.ts
  src/store/chat/slices/builtinTool/actions/localFile.ts
  src/store/electron/selectors/desktopState.ts
  src/store/electron/selectors/index.ts
  src/tools/local-files/Render/ListFiles/index.tsx
  src/tools/local-files/Render/RenameLocalFile/index.tsx
  src/tools/local-files/Render/RunCommand/index.tsx
  src/tools/local-files/Render/WriteFile/index.tsx
  src/tools/local-files/Render/index.tsx
  src/tools/local-files/index.ts
  src/tools/local-files/systemRole.ts
Labels: 💄 Design, size:L

#7677 ♻️ refactor: Support Provider Output Performance Statistics for OpenAI Compatible Providers with Custom Stream
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
  src/libs/agent-runtime/utils/streams/qwen.test.ts
  src/libs/agent-runtime/utils/streams/qwen.ts
  src/libs/agent-runtime/utils/streams/spark.test.ts
  src/libs/agent-runtime/utils/streams/spark.ts
Labels: ⚡️ Performance, size:M

#7694 💄 style: fix init state of loading
  src/app/(backend)/webapi/assistant/[id]/route.ts
  src/app/(backend)/webapi/assistant/store/route.ts
  src/app/(backend)/webapi/plugin/store/route.ts
  src/features/ElectronTitlebar/index.tsx
  src/server/modules/AssistantStore/index.ts
  src/server/routers/edge/index.ts
  src/server/routers/edge/market/index.ts
  src/services/__tests__/assistant.test.ts
  src/services/__tests__/tool.test.ts
  src/services/_url.ts
  src/services/assistant.ts
  src/services/tool.ts
  src/store/electron/initialState.ts
Labels: 💄 Design, size:L

#7660 💄 style: Show Aliyun Bailian tokens usage tracking
  src/libs/agent-runtime/qwen/index.ts
  src/libs/agent-runtime/utils/streams/qwen.test.ts
  src/libs/agent-runtime/utils/streams/qwen.ts
Labels: 💄 Design, size:L

#7573 ♻️ refactor: Remove doubao Provider
  src/app/[variants]/(main)/settings/provider/(detail)/doubao/page.tsx
  src/config/aiModels/doubao.ts
  src/config/aiModels/hunyuan.ts
  src/config/aiModels/index.ts
  src/config/aiModels/novita.ts
  src/config/aiModels/qwen.ts
  src/config/aiModels/siliconcloud.ts
  src/config/aiModels/volcengine.ts
  src/config/llm.ts
  src/config/modelProviders/doubao.ts
  src/config/modelProviders/index.ts
  src/libs/agent-runtime/runtimeMap.ts
  src/libs/agent-runtime/types/type.ts
  src/libs/agent-runtime/volcengine/index.ts
  src/server/globalConfig/index.ts
  src/services/chat.ts
  src/types/aiModel.ts
  src/types/aiProvider.ts
  src/types/user/settings/keyVaults.ts
Labels: Model Provider, size:L

#7707 🐛 fix: fix electron state init on window
  src/store/electron/actions/app.ts
Labels: 🐛 Bug, Build Desktop

#7717 💄 style: add Xiaohongshu crawler rules
  packages/web-crawler/src/urlRules.ts
Labels: size:XS

#7737 📝 docs: Update Dokploy Deplyment Documents
  docs/self-hosting/server-database/dokploy.mdx
  docs/self-hosting/server-database/dokploy.zh-CN.mdx
Labels: 📝 Documentation, size:L

#7718 🔨 chore: fix typo in docker compose
  docker-compose/local/docker-compose.yml
Labels: size:XS

#7730 💄 style: Add new gemini & Mistral models
  src/config/aiModels/google.ts
  src/config/aiModels/mistral.ts
  src/config/aiModels/vertexai.ts
  src/config/modelProviders/vertexai.ts
Labels: Gemini, size:L

#7723 💄style: Improve the shortcut key prompt panel
  src/features/HotkeyHelperPanel/index.tsx
Labels: 💄 Design, size:M

#7740 🐛 fix: fix changelog issue on desktop app
  locales/ar/hotkey.json
  locales/ar/models.json
  locales/ar/providers.json
  locales/bg-BG/hotkey.json
  locales/bg-BG/models.json
  locales/bg-BG/providers.json
  locales/de-DE/hotkey.json
  locales/de-DE/models.json
  locales/de-DE/providers.json
  locales/en-US/hotkey.json
  locales/en-US/models.json
  locales/en-US/providers.json
  locales/es-ES/hotkey.json
  locales/es-ES/models.json
  locales/es-ES/providers.json
  locales/fa-IR/hotkey.json
  locales/fa-IR/models.json
  locales/fa-IR/providers.json
  locales/fr-FR/hotkey.json
  locales/fr-FR/models.json
  locales/fr-FR/providers.json
  locales/it-IT/hotkey.json
  locales/it-IT/models.json
  locales/it-IT/providers.json
  locales/ja-JP/hotkey.json
  locales/ja-JP/models.json
  locales/ja-JP/providers.json
  locales/ko-KR/hotkey.json
  locales/ko-KR/models.json
  locales/ko-KR/providers.json
  locales/nl-NL/hotkey.json
  locales/nl-NL/models.json
  locales/nl-NL/providers.json
  locales/pl-PL/hotkey.json
  locales/pl-PL/models.json
  locales/pl-PL/providers.json
  locales/pt-BR/hotkey.json
  locales/pt-BR/models.json
  locales/pt-BR/providers.json
  locales/ru-RU/hotkey.json
  locales/ru-RU/models.json
  locales/ru-RU/providers.json
  locales/tr-TR/hotkey.json
  locales/tr-TR/models.json
  locales/tr-TR/providers.json
  locales/vi-VN/hotkey.json
  locales/vi-VN/models.json
  locales/vi-VN/providers.json
  locales/zh-CN/hotkey.json
  locales/zh-CN/models.json
  locales/zh-CN/providers.json
  locales/zh-TW/hotkey.json
  locales/zh-TW/models.json
  locales/zh-TW/providers.json
  src/const/hotkeys.ts
  src/const/url.ts
  src/features/User/UserPanel/useMenu.tsx
  src/locales/default/hotkey.ts
  src/types/hotkey.ts
Labels: 🐛 Bug, size:XL

#7741 🐛 fix: fix desktop upload image on macOS
  apps/desktop/src/main/controllers/__tests__/BrowserWindowsCtr.test.ts
  apps/desktop/src/main/controllers/__tests__/DevtoolsCtr.test.ts
  apps/desktop/src/main/controllers/__tests__/MenuCtr.test.ts
  apps/desktop/src/main/controllers/__tests__/ShortcutCtr.test.ts
  apps/desktop/src/main/controllers/__tests__/TrayMenuCtr.test.ts
  apps/desktop/src/main/controllers/__tests__/UpdaterCtr.test.ts
  apps/desktop/src/main/services/fileSrv.ts
  apps/desktop/vitest.config.ts
  packages/electron-server-ipc/package.json
  packages/electron-server-ipc/src/ipcClient.ts
  packages/electron-server-ipc/src/ipcServer.test.ts
  packages/electron-server-ipc/src/ipcServer.ts
  vitest.config.ts
Labels: 🐛 Bug, size:XXL, Build Desktop

#7746 💄 style: add qwen3 for ollama
  src/config/aiModels/ollama.ts
  src/libs/langchain/loaders/epub/index.ts
  src/server/routers/async/file.ts
  src/server/routers/lambda/file.ts
  src/server/routers/lambda/importer.ts
  src/server/routers/lambda/message.ts
  src/server/routers/lambda/ragEval.ts
  src/server/routers/lambda/user.ts
  src/server/services/file/index.ts
  src/server/utils/tempFileManager.ts
Labels: 💄 Design, ollama, size:M

#7757 🔨 chore: fix tests
  package.json
  src/libs/mcp/__tests__/__snapshots__/index.test.ts.snap
Labels: size:XS

#7501 💄 style: add reasoning tokens and token usage statistics for Google Gemini
  src/config/aiModels/vertexai.ts
  src/libs/agent-runtime/google/index.ts
  src/libs/agent-runtime/utils/streams/google-ai.test.ts
  src/libs/agent-runtime/utils/streams/google-ai.ts
  src/libs/agent-runtime/utils/streams/protocol.ts
  src/libs/agent-runtime/utils/streams/vertex-ai.test.ts
  src/libs/agent-runtime/utils/streams/vertex-ai.ts
Labels: Gemini, size:L

#7751 ✨ feat: support upload files direct into context
  docs/development/database-schema.dbml
  package.json
  packages/file-loaders/package.json
  packages/file-loaders/src/loadFile.ts
  packages/file-loaders/src/loaders/docx/index.ts
  packages/file-loaders/src/loaders/excel/index.ts
  packages/file-loaders/src/loaders/pdf/__snapshots__/index.test.ts.snap
  packages/file-loaders/src/loaders/pdf/index.ts
  packages/file-loaders/src/loaders/pptx/index.ts
  packages/file-loaders/src/loaders/text/index.test.ts
  packages/file-loaders/src/loaders/text/index.ts
  packages/file-loaders/test/__snapshots__/loaders.test.ts.snap
  packages/file-loaders/test/loaders.test.ts
  packages/file-loaders/test/setup.ts
  packages/file-loaders/vitest.config.ts
  src/const/file.ts
  src/database/client/migrations.json
  src/database/migrations/0022_add_documents.sql
  src/database/migrations/meta/0022_snapshot.json
  src/database/migrations/meta/_journal.json
  src/database/models/_template.ts
  src/database/models/document.ts
  src/database/models/message.ts
  src/database/repositories/tableViewer/index.test.ts
  src/database/schemas/document.ts
  src/database/schemas/index.ts
  src/database/schemas/relations.ts
  src/database/schemas/topic.ts
  src/database/utils/idGenerator.ts
  src/features/ChatInput/Desktop/FilePreview/FileItem/Content.tsx
  src/features/ChatInput/Desktop/FilePreview/FileItem/index.tsx
  src/features/ChatInput/Desktop/FilePreview/FileItem/style.ts
  src/features/ChatInput/components/UploadDetail/UploadStatus.tsx
  src/features/Conversation/Actions/Error.tsx
  src/libs/trpc/lambda/context.ts
  src/prompts/files/file.ts
  src/server/routers/lambda/document.ts
  src/server/routers/lambda/index.ts
  src/server/services/document/index.ts
  src/server/services/mcp/index.ts
  src/services/rag.ts
  src/store/chat/slices/aiChat/actions/__tests__/rag.test.ts
  src/store/chat/slices/aiChat/actions/rag.ts
  src/store/file/slices/chat/action.ts
  src/types/document/index.ts
  src/types/message/chat.ts
Labels: 🌠 Feature Request, files, size:XL, Build Desktop

#7716 🔨 chore: update pnpm version
  package.json
Labels: size:XS, Build Docker

#7772 👷 build: fix docker build
  package.json
Labels: size:XS, Build Docker

#7657 💄 style: add Qwen3 models for the infiniai provider
  src/config/aiModels/infiniai.ts
  src/libs/agent-runtime/infiniai/index.ts
Labels: size:L

#7773 ♻️ refactor: upgrade anthropic sdk
  package.json
  src/libs/agent-runtime/anthropic/index.ts
Labels: size:S

#7776 🐛 fix: remove mcp client cache
  src/server/services/mcp/index.ts
Labels: size:M, Build Desktop

#7738 🐛 fix: fix nothing return when reset the client db
  src/database/client/db.ts
Labels: size:M

#7780 🐛 fix: fix window close issue and release Window/Linux beta
  .github/workflows/desktop-pr-build.yml
  .github/workflows/release-desktop-beta.yml
  apps/desktop/package.json
  apps/desktop/src/main/core/BrowserManager.ts
  src/features/ElectronTitlebar/WinControl/index.tsx
Labels: 🐛 Bug, size:M, Build Desktop

#7786 👷 build: update build workflow
  .github/workflows/release-desktop-beta.yml
  apps/desktop/package.json
Labels: size:S, Build Desktop

#7788 🐛 fix: fix macOS fisrt time open when downloaded
  apps/desktop/electron-builder.js
Labels: 🐛 Bug, size:S, Build Desktop

#7794 🐛 fix: fix streamable http url valid and refactor local files to local system
  locales/ar/models.json
  locales/ar/plugin.json
  locales/bg-BG/models.json
  locales/bg-BG/plugin.json
  locales/de-DE/models.json
  locales/de-DE/plugin.json
  locales/en-US/models.json
  locales/en-US/plugin.json
  locales/es-ES/models.json
  locales/es-ES/plugin.json
  locales/fa-IR/models.json
  locales/fa-IR/plugin.json
  locales/fr-FR/models.json
  locales/fr-FR/plugin.json
  locales/it-IT/models.json
  locales/it-IT/plugin.json
  locales/ja-JP/models.json
  locales/ja-JP/plugin.json
  locales/ko-KR/models.json
  locales/ko-KR/plugin.json
  locales/nl-NL/models.json
  locales/nl-NL/plugin.json
  locales/pl-PL/models.json
  locales/pl-PL/plugin.json
  locales/pt-BR/models.json
  locales/pt-BR/plugin.json
  locales/ru-RU/models.json
  locales/ru-RU/plugin.json
  locales/tr-TR/models.json
  locales/tr-TR/plugin.json
  locales/vi-VN/models.json
  locales/vi-VN/plugin.json
  locales/zh-CN/models.json
  locales/zh-CN/plugin.json
  locales/zh-TW/models.json
  locales/zh-TW/plugin.json
  src/features/PluginDevModal/MCPManifestForm/index.tsx
  src/locales/default/plugin.ts
  src/store/chat/slices/builtinTool/actions/localFile.ts
  src/tools/index.ts
  src/tools/local-system/Render/ListFiles/Result.tsx
  src/tools/local-system/Render/ListFiles/index.tsx
  src/tools/local-system/Render/ReadLocalFile/ReadFileSkeleton.tsx
  src/tools/local-system/Render/ReadLocalFile/ReadFileView.tsx
  src/tools/local-system/Render/ReadLocalFile/index.tsx
  src/tools/local-system/Render/ReadLocalFile/style.ts
  src/tools/local-system/Render/RenameLocalFile/index.tsx
  src/tools/local-system/Render/RunCommand/index.tsx
  src/tools/local-system/Render/SearchFiles/Result.tsx
  src/tools/local-system/Render/SearchFiles/SearchQuery/SearchView.tsx
  src/tools/local-system/Render/SearchFiles/SearchQuery/index.tsx
  src/tools/local-system/Render/SearchFiles/index.tsx
  src/tools/local-system/Render/WriteFile/index.tsx
  src/tools/local-system/Render/index.tsx
  src/tools/local-system/components/FileItem.tsx
  src/tools/local-system/index.ts
  src/tools/local-system/systemRole.ts
  src/tools/local-system/type.ts
  src/tools/renders.ts
Labels: 🐛 Bug, size:M

#7800 🐛 fix: fix config import in desktop
  packages/file-loaders/package.json
  packages/file-loaders/test/setup.ts
  src/features/DataImporter/index.tsx
  src/server/routers/lambda/__tests__/importer.test.ts
  src/server/routers/lambda/importer.ts
  src/services/__tests__/upload.test.ts
  src/services/import/server.ts
  src/services/ragEval.ts
  src/services/upload.ts
  src/store/chat/slices/builtinTool/actions/dalle.test.ts
  src/store/file/slices/upload/action.ts
Labels: 🐛 Bug, size:L, Build Desktop

#7813 :bug: fix: Redirect unauthorized next-auth user to signin page
  src/middleware.ts
Labels: size:S

#7830 🔨 chore: disable signups for the default lobechat org in Casdoor
  docker-compose/local/init_data.json
Labels: size:XS

#7833 💄 style: improve smoothing on completion
  package.json
  src/components/Thinking/index.tsx
  src/features/ChatInput/ActionBar/Knowledge/index.tsx
  src/features/ChatInput/ActionBar/Tools/index.tsx
  src/features/Conversation/components/ChatItem/index.tsx
  src/features/Portal/Artifacts/Body/index.tsx
  src/features/Portal/Artifacts/Header.tsx
  src/features/Portal/FilePreview/Header.tsx
  src/features/Portal/Plugins/Header.tsx
  src/features/Portal/components/Header.tsx
  src/features/User/UserPanel/LangButton.tsx
  src/features/User/UserPanel/PanelContent.tsx
  src/features/User/UserPanel/ThemeButton.tsx
  src/store/chat/slices/aiChat/actions/generateAIChat.ts
  src/store/chat/slices/message/selectors.ts
  src/utils/fetch/__tests__/fetchSSE.test.ts
  src/utils/fetch/fetchSSE.ts
Labels: 💄 Design, size:L

#7839 💄 style: update electron style on windows
  apps/desktop/build/nsis-header.bmp
  apps/desktop/build/nsis-sidebar.bmp
  apps/desktop/electron-builder.js
  apps/desktop/src/main/core/App.ts
  apps/desktop/src/main/core/Browser.ts
  src/features/ElectronTitlebar/WinControl/index.tsx
  src/features/ElectronTitlebar/const.ts
Labels: size:M, Build Desktop

#7649 :sparkles: feat: add Qiniu Provider
  .env.example
  Dockerfile
  Dockerfile.database
  Dockerfile.pglite
  README.md
  README.zh-CN.md
  docs/self-hosting/environment-variables/model-provider.mdx
  docs/self-hosting/environment-variables/model-provider.zh-CN.mdx
  docs/usage/providers/qiniu.mdx
  docs/usage/providers/qiniu.zh-CN.mdx
  locales/ar/providers.json
  locales/bg-BG/providers.json
  locales/de-DE/providers.json
  locales/en-US/providers.json
  locales/es-ES/providers.json
  locales/fa-IR/providers.json
  locales/fr-FR/providers.json
  locales/it-IT/providers.json
  locales/ja-JP/providers.json
  locales/ko-KR/providers.json
  locales/nl-NL/providers.json
  locales/pl-PL/providers.json
  locales/pt-BR/providers.json
  locales/ru-RU/providers.json
  locales/tr-TR/providers.json
  locales/vi-VN/providers.json
  locales/zh-CN/providers.json
  locales/zh-TW/providers.json
  src/app/[variants]/(main)/settings/llm/ProviderList/providers.tsx
  src/app/[variants]/(main)/settings/llm/components/ProviderModelList/Option.tsx
  src/config/aiModels/index.ts
  src/config/aiModels/qiniu.ts
  src/config/llm.ts
  src/config/modelProviders/index.ts
  src/config/modelProviders/qiniu.ts
  src/libs/agent-runtime/qiniu/index.test.ts
  src/libs/agent-runtime/qiniu/index.ts
  src/libs/agent-runtime/runtimeMap.ts
  src/libs/agent-runtime/types/type.ts
  src/server/modules/AgentRuntime/index.test.ts
  src/store/user/slices/modelList/selectors/modelProvider.ts
  src/types/user/settings/keyVaults.ts
Labels: Model Provider, size:L

#7856 ✅ test: fix tests
  src/libs/model-runtime/ModelRuntime.test.ts
  src/libs/model-runtime/ModelRuntime.ts
  src/libs/model-runtime/index.ts
  src/store/electron/selectors/__tests__/desktopState.test.ts
Labels: size:S

#7855 🐛 fix: fix oidc redirect url
  src/libs/oidc-provider/config.ts
Labels: 🐛 Bug, size:XS

#7480 💄 style: update Spark X1 model list & fix build-in search params
  Dockerfile
  Dockerfile.database
  Dockerfile.pglite
  src/config/aiModels/spark.ts
  src/config/modelProviders/spark.ts
  src/libs/model-runtime/spark/index.test.ts
  src/libs/model-runtime/spark/index.ts
  src/libs/model-runtime/utils/streams/spark.test.ts
  src/libs/model-runtime/utils/streams/spark.ts
Labels: 💄 Design, size:L

#7860 🔨 chore: update desktop env
  .env.desktop
Labels: 🐛 Bug, size:XS

#7870 ♻️ refactor: clean code with new antd api
  package.json
  src/app/[variants]/(main)/chat/@session/features/SessionListContent/Modals/CreateGroupModal.tsx
  src/app/[variants]/(main)/chat/@session/features/SessionListContent/Modals/RenameGroupModal.tsx
  src/app/[variants]/(main)/chat/features/PageTitle/index.tsx
  src/app/[variants]/(main)/settings/llm/components/ProviderModelList/ModelConfigModal/index.tsx
  src/app/[variants]/(main)/settings/provider/features/ModelList/CreateNewModelModal/index.tsx
  src/app/[variants]/(main)/settings/provider/features/ModelList/ModelConfigModal/index.tsx
  src/features/ChatInput/ActionBar/STT/common.tsx
  src/features/PluginDevModal/index.tsx
Labels: size:M

#7778 🐛 fix: supported SenseNova v6 models correctly & update Gemini models
  src/config/aiModels/google.ts
  src/config/aiModels/groq.ts
  src/config/aiModels/novita.ts
  src/config/aiModels/sensenova.ts
  src/libs/model-runtime/google/index.ts
  src/libs/model-runtime/sensenova/index.ts
  src/libs/model-runtime/utils/sensenovaHelpers.ts
Labels: size:L

#7874 📝 docs: Update `docs/usage/providers/vllm.zh-CN.mdx`
  docs/usage/providers/vllm.zh-CN.mdx
Labels: 📝 Documentation, size:XS

#7883 🐛 fix: fix desktop open issue on linux like Fedora42
  apps/desktop/src/main/core/App.ts
  package.json
  src/features/InitClientDB/ErrorResult.tsx
Labels: 🐛 Bug, size:L, Build Desktop

#7906 💄 style: improve tools display
  locales/ar/models.json
  locales/ar/plugin.json
  locales/bg-BG/models.json
  locales/bg-BG/plugin.json
  locales/de-DE/models.json
  locales/de-DE/plugin.json
  locales/en-US/models.json
  locales/en-US/plugin.json
  locales/es-ES/models.json
  locales/es-ES/plugin.json
  locales/fa-IR/models.json
  locales/fa-IR/plugin.json
  locales/fr-FR/models.json
  locales/fr-FR/plugin.json
  locales/it-IT/models.json
  locales/it-IT/plugin.json
  locales/ja-JP/models.json
  locales/ja-JP/plugin.json
  locales/ko-KR/models.json
  locales/ko-KR/plugin.json
  locales/nl-NL/models.json
  locales/nl-NL/plugin.json
  locales/pl-PL/models.json
  locales/pl-PL/plugin.json
  locales/pt-BR/models.json
  locales/pt-BR/plugin.json
  locales/ru-RU/models.json
  locales/ru-RU/plugin.json
  locales/tr-TR/models.json
  locales/tr-TR/plugin.json
  locales/vi-VN/models.json
  locales/vi-VN/plugin.json
  locales/zh-CN/models.json
  locales/zh-CN/plugin.json
  locales/zh-TW/models.json
  locales/zh-TW/plugin.json
  src/features/Conversation/Messages/Assistant/Tool/Inspector/BuiltinPluginTitle.tsx
  src/features/Conversation/Messages/Assistant/Tool/Inspector/ToolTitle.tsx
  src/locales/default/plugin.ts
  src/tools/local-system/Render/ListFiles/Result.tsx
  src/tools/local-system/systemRole.ts
  src/utils/fetch/fetchSSE.ts
Labels: 💄 Design, size:XL

#7912 🐛 fix: bump @lobehub/ui to 2.1.7
  package.json
  src/app/[variants]/(main)/settings/provider/features/CreateNewProvider/index.tsx
Labels: dependencies, size:XS

#7747 🐛 fix: 'top_p' is not supported with o4-mini
  src/config/aiModels/novita.ts
  src/config/aiModels/openai.ts
  src/config/aiModels/siliconcloud.ts
  src/libs/model-runtime/azureai/index.ts
  src/libs/model-runtime/openai/__snapshots__/index.test.ts.snap
  src/libs/model-runtime/openai/index.ts
Labels: size:M

#7929 🐛 fix: lock zustand version to avoid type error
  package.json
Labels: 🐛 Bug, size:XS

#7939 ✨ feat: add claude 4 series
  src/config/aiModels/anthropic.ts
  src/const/models.ts
Labels: 🌠 Feature Request, size:M

#7918 🐛 fix: update agent config of client db will override old config
  src/database/models/__tests__/session.test.ts
  src/database/models/session.ts
  src/server/routers/lambda/session.ts
  src/server/services/agent/index.test.ts
  src/server/services/agent/index.ts
  src/services/session/client.ts
Labels: 🐛 Bug, size:L

#7686 💄 style: Support Gemini 2.5 thought reasoning
  src/config/aiModels/google.ts
  src/libs/model-runtime/google/index.ts
  src/libs/model-runtime/utils/streams/google-ai.ts
Labels: size:S

#7899 🐛 fix: user nickName & username selector in desktop
  src/store/user/slices/auth/selectors.test.ts
  src/store/user/slices/auth/selectors.ts
Labels: 🐛 Bug, size:M

#7948 🐛 fix(chat): handle mobile query param in settings URL
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatList/WelcomeChatItem/WelcomeMessage.tsx
Labels: 🐛 Bug, 📱 Mobile Device, size:XS

#7963 💄 style: improve thread flicker when first-time loading
  src/app/[variants]/(main)/chat/(workspace)/@topic/features/TopicListContent/ThreadList/index.tsx
  src/app/[variants]/(main)/chat/(workspace)/@topic/features/TopicListContent/TopicItem/index.tsx
  src/hooks/useFetchTopics.ts
  src/store/chat/slices/thread/action.ts
Labels: 💄 Design, size:M

#7957 🐛 fix(docs): rename and update Google Gemini documentation
  docs/usage/providers/google.mdx
  docs/usage/providers/google.zh-CN.mdx
Labels: 📝 Documentation, size:XS

#7967 💄 style: support share single message
  src/features/Conversation/Actions/Assistant.tsx
  src/features/Conversation/components/ChatItem/ActionsBar.tsx
  src/features/Conversation/components/ChatItem/ShareMessageModal/ShareImage/Preview.tsx
  src/features/Conversation/components/ChatItem/ShareMessageModal/ShareImage/index.tsx
  src/features/Conversation/components/ChatItem/ShareMessageModal/ShareImage/style.ts
  src/features/Conversation/components/ChatItem/ShareMessageModal/ShareImage/type.ts
  src/features/Conversation/components/ChatItem/ShareMessageModal/ShareText/Preview.tsx
  src/features/Conversation/components/ChatItem/ShareMessageModal/ShareText/index.tsx
  src/features/Conversation/components/ChatItem/ShareMessageModal/ShareText/template.test.ts
  src/features/Conversation/components/ChatItem/ShareMessageModal/ShareText/template.ts
  src/features/Conversation/components/ChatItem/ShareMessageModal/ShareText/type.ts
  src/features/Conversation/components/ChatItem/ShareMessageModal/index.tsx
  src/features/Conversation/components/ChatItem/ShareMessageModal/style.ts
  src/features/Conversation/hooks/useChatListActionsBar.tsx
Labels: 🌠 Feature Request, size:XL

#7952 💄 style: Fix a few typos in the model tooltips
  locales/en-US/components.json
Labels: 📝 Documentation, size:S

#7968 🐛 fix: fix draggable issue with agent header
  src/app/[variants]/(main)/chat/(workspace)/_layout/Desktop/ChatHeader/index.tsx
Labels: size:S

#7961 🐛 fix(DragUpload): resolve issue with pasting clipboard images in Safari
  src/components/DragUpload/useDragUpload.tsx
Labels: 🐛 Bug, size:S

#7973 🐛 fix: fix chat header in the desktop
  src/app/[variants]/(main)/chat/(workspace)/_layout/Desktop/ChatHeader/index.tsx
Labels: size:S

#7708 💄 style: Allow `SliderWithInput` to have no input limit
  src/features/AgentSetting/AgentChat/index.tsx
  src/features/AgentSetting/AgentModal/index.tsx
  src/features/ChatInput/ActionBar/History/Controls.tsx
Labels: 💄 Design, size:XS

#7970 🐛 fix: auto sync theme mode in desktop
  .cursor/rules/desktop-feature-implementation.mdc
  .cursor/rules/desktop-menu-configuration.mdc
  .cursor/rules/desktop-window-management.mdc
  apps/desktop/src/main/controllers/SystemCtr.ts
  packages/electron-client-ipc/src/events/index.ts
  packages/electron-client-ipc/src/events/system.ts
  packages/electron-client-ipc/src/types/system.ts
  src/features/ElectronTitlebar/hooks/useWatchThemeUpdate.ts
  src/features/ElectronTitlebar/index.tsx
  src/store/global/actions/general.ts
  src/styles/global.ts
Labels: size:XL, Build Desktop

#7979 💄 style: correct model name `SenseChat-5-1202`
  src/config/aiModels/sensenova.ts
Labels: 💄 Design, size:XS

#7947 💄 style: support adjust thinkingBudget in gemini 2.5 flash
  src/config/aiModels/google.ts
  src/libs/model-runtime/google/index.ts
  src/libs/model-runtime/types/chat.ts
Labels: 💄 Design, Gemini, size:XS

#7989 ⚡️ perf: use approximate way with tokenizer
  package.json
  src/utils/tokenizer/estimated.ts
  src/utils/tokenizer/index.ts
Labels: ⚡️ Performance, size:S

#7999 📝 docs: add some cursor rules & optimize codebase indexing
  .cursor/rules/backend-architecture.mdc
  .cursor/rules/cursor-ux-optimize.mdc
  .cursor/rules/define-database-model.mdc
  .cursor/rules/drizzle-schema-style-guide.mdc
  .cursor/rules/i18n/i18n-auto-attached.mdc
  .cursor/rules/i18n/i18n.mdc
  .cursor/rules/packages/lobe-ui.mdc
  .cursor/rules/packages/react-layout-kit.mdc
  .cursor/rules/project-introduce.mdc
  .cursor/rules/react-component.mdc
  .cursorindexingignore
Labels: 📝 Documentation, size:XL

#8006 💄 style: add fc ability to reasoner model
  src/config/aiModels/deepseek.ts
Labels: 💄 Design, size:XS

#7993 💄 style: Update Hunyuan models & deepseek-r1-0528
  src/config/aiModels/deepseek.ts
  src/config/aiModels/groq.ts
  src/config/aiModels/hunyuan.ts
  src/config/aiModels/novita.ts
  src/config/aiModels/openrouter.ts
  src/config/aiModels/siliconcloud.ts
  src/config/aiModels/volcengine.ts
  src/libs/model-runtime/novita/__snapshots__/index.test.ts.snap
Labels: size:XL

#7984 💄 style: `+` in the welcome message can be clicked to create an assistant
  locales/ar/welcome.json
  locales/bg-BG/welcome.json
  locales/de-DE/welcome.json
  locales/en-US/welcome.json
  locales/es-ES/welcome.json
  locales/fa-IR/welcome.json
  locales/fr-FR/welcome.json
  locales/it-IT/welcome.json
  locales/ja-JP/welcome.json
  locales/ko-KR/welcome.json
  locales/nl-NL/welcome.json
  locales/pl-PL/welcome.json
  locales/pt-BR/welcome.json
  locales/ru-RU/welcome.json
  locales/tr-TR/welcome.json
  locales/vi-VN/welcome.json
  locales/zh-CN/welcome.json
  locales/zh-TW/welcome.json
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatList/WelcomeChatItem/InboxWelcome/AddButton.tsx
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatList/WelcomeChatItem/InboxWelcome/index.tsx
  src/locales/default/welcome.ts
Labels: 💄 Design, size:M
