Repository lobehub/lobe-chat, pull requests merged in 2025-09, with the labels that each got.

#8903 💄 style: Support new provider Nebius
  .env.example
  Dockerfile
  Dockerfile.database
  Dockerfile.pglite
  packages/model-bank/package.json
  packages/model-bank/src/aiModels/index.ts
  packages/model-bank/src/aiModels/nebius.ts
  packages/model-bank/src/aiModels/openrouter.ts
  packages/model-runtime/src/index.ts
  packages/model-runtime/src/nebius/index.ts
  packages/model-runtime/src/runtimeMap.ts
  packages/model-runtime/src/types/type.ts
  packages/types/src/user/settings/keyVaults.ts
  src/config/llm.ts
  src/config/modelProviders/index.ts
  src/config/modelProviders/nebius.ts
Labels: 🌠 Feature Request, Model Provider, size:XXL

#9013 💄 style: adjust ControlsForm component to adapt to mobile phone display
  src/features/ChatInput/ActionBar/Model/ControlsForm.tsx
Labels: 📱 Mobile Device, size:M

#9016 🐛 fix(ai-image): save config.imageUrl with fullUrl instead of key
  .vscode/settings.json
  packages/model-bank/src/standard-parameters/index.ts
  src/server/routers/lambda/__tests__/image.test.ts
  src/server/routers/lambda/image.ts
  src/server/services/file/impls/local.test.ts
  src/server/services/file/impls/local.ts
  src/server/services/file/impls/s3.test.ts
  src/server/services/file/impls/s3.ts
  src/server/services/file/impls/utils.test.ts
  src/server/services/file/impls/utils.ts
Labels: 🐛 Bug, size:L

#7969 💄 style: add upload hint for non-visual model
  src/components/DragUpload/useDragUpload.test.tsx
  src/components/DragUpload/useDragUpload.tsx
  src/locales/default/chat.ts
Labels: size:L

#8608 🔨 chore: add docker compose to setup local services for development
  .env.development
  .npmrc
  docker-compose.development.yml
  docker-compose/local/.gitignore
  docker-compose/local/init_data.json
  docs/development/basic/work-with-server-side-database.mdx
  docs/development/basic/work-with-server-side-database.zh-CN.mdx
  docs/self-hosting/advanced/s3/cloudflare-r2.mdx
  docs/self-hosting/advanced/s3/cloudflare-r2.zh-CN.mdx
  package.json
Labels: size:XXL, lgtm

#9053 fix: fix socks5 proxy not work problem
  apps/desktop/package.json
  apps/desktop/src/main/modules/networkProxy/dispatcher.ts
Labels: 🐛 Bug, size:S

#9046 ✨ feat: refactor to speed up send message in server mode
  packages/const/src/index.ts
  packages/const/src/session.ts
  packages/database/src/models/__tests__/message.test.ts
  packages/database/src/models/message.ts
  packages/database/src/models/topic.ts
  packages/types/src/aiChat.ts
  packages/types/src/index.ts
  packages/types/src/message/base.ts
  packages/types/src/message/chat.ts
  packages/types/src/message/index.ts
  packages/types/src/message/rag.ts
  packages/utils/src/index.ts
  packages/utils/src/object.test.ts
  src/server/routers/lambda/__tests__/message.test.ts
  src/server/routers/lambda/aiChat.test.ts
  src/server/routers/lambda/aiChat.ts
  src/server/routers/lambda/index.ts
  src/server/routers/lambda/message.ts
  src/server/services/aiChat/index.test.ts
  src/server/services/aiChat/index.ts
  src/services/aiChat.ts
  src/services/message/_deprecated.ts
  src/services/message/client.ts
  src/services/message/server.ts
  src/services/message/type.ts
  src/store/chat/slices/aiChat/actions/generateAIChat.ts
  src/store/chat/slices/aiChat/actions/generateAIChatV2.ts
  src/store/chat/slices/aiChat/actions/index.ts
  src/store/chat/slices/message/action.ts
  src/store/chat/slices/message/reducer.ts
  src/store/chat/slices/topic/reducer.ts
Labels: size:XXL

#9066 🔨 chore: fix webpack build OOM
  next.config.ts
Labels: size:XS

#9079 📝 docs: update README
  README.md
Labels: size:XS

#9067 🐛 fix(modelProvider): add lmstudio to provider whitelist to enable fetchOnClient toggle
  src/store/aiInfra/slices/aiProvider/selectors.ts
  src/store/user/slices/modelList/selectors/modelConfig.ts
Labels: 🐛 Bug, Model Provider, size:XS

#9054 🐛 fix: Support base64 image from markdown image syntax
  packages/model-runtime/src/utils/streams/openai/openai.test.ts
  packages/model-runtime/src/utils/streams/openai/openai.ts
Labels: 🐛 Bug, size:L, lgtm

#9075 💄 style: Update the price of the o3 model in OpenRouter
  packages/model-bank/src/aiModels/openrouter.ts
Labels: Model Provider, size:XS

#9074 ✅ test: add more tests
  packages/database/src/models/__tests__/drizzleMigration.test.ts
  packages/database/src/models/__tests__/file.test.ts
  packages/database/src/models/__tests__/session.test.ts
  packages/database/src/server/models/__tests__/user.test.ts
  src/store/chat/slices/aiChat/actions/__tests__/generateAIChatV2.test.ts
Labels: size:XL

#8188 ♻️ Refactor: Make LobeNextAuthDBAdapter Edge Compatible
  packages/database/src/server/models/__tests__/nextauth.test.ts
  packages/utils/src/server/__tests__/auth.test.ts
  packages/utils/src/server/auth.ts
  src/app/(backend)/api/auth/adapter/route.ts
  src/app/(backend)/api/webhooks/logto/route.ts
  src/config/auth.ts
  src/libs/next-auth/adapter/index.ts
  src/libs/next-auth/auth.config.ts
  src/libs/next-auth/edge.ts
  src/libs/next-auth/index.ts
  src/libs/trpc/edge/context.ts
  src/libs/trpc/lambda/context.ts
  src/middleware.ts
  src/server/routers/lambda/user.test.ts
  src/server/routers/lambda/user.ts
  src/server/services/nextAuthUser/index.test.ts
  src/server/services/nextAuthUser/index.ts
  src/server/services/nextAuthUser/utils.ts
Labels: size:XXL

#9086 👷 build: Revert "♻️ refactor: make LobeNextAuthDBAdapter Edge Compatible"
  packages/database/src/server/models/__tests__/nextauth.test.ts
  packages/utils/src/server/__tests__/auth.test.ts
  packages/utils/src/server/auth.ts
  src/app/(backend)/api/auth/adapter/route.ts
  src/app/(backend)/api/webhooks/logto/route.ts
  src/config/auth.ts
  src/libs/next-auth/adapter/index.ts
  src/libs/next-auth/adapter/utils.ts
  src/libs/next-auth/auth.config.ts
  src/libs/next-auth/edge.ts
  src/libs/next-auth/index.ts
  src/libs/trpc/edge/context.ts
  src/libs/trpc/lambda/context.ts
  src/middleware.ts
  src/server/routers/lambda/user.test.ts
  src/server/routers/lambda/user.ts
  src/server/services/nextAuthUser/index.test.ts
  src/server/services/nextAuthUser/index.ts
Labels: size:XXL

#9090 🔨 chore: rename example development
  .env.example.development
Labels: size:XS

#9088 ♻️ refactor: make LobeNextAuthDBAdapter Edge Compatible
  packages/database/src/server/models/__tests__/nextauth.test.ts
  packages/utils/src/server/__tests__/auth.test.ts
  packages/utils/src/server/auth.ts
  src/app/(backend)/api/auth/adapter/route.ts
  src/app/(backend)/api/webhooks/logto/route.ts
  src/config/auth.ts
  src/libs/next-auth/adapter/index.ts
  src/libs/next-auth/auth.config.ts
  src/libs/next-auth/edge.ts
  src/libs/next-auth/index.ts
  src/libs/trpc/edge/context.ts
  src/libs/trpc/lambda/context.ts
  src/middleware.ts
  src/server/routers/lambda/user.test.ts
  src/server/routers/lambda/user.ts
  src/server/services/nextAuthUser/index.test.ts
  src/server/services/nextAuthUser/index.ts
  src/server/services/nextAuthUser/utils.ts
Labels: 🐛 Bug, size:XXL

#9109 🐛 fix: fix mobile header title to loog not ellipsis
  src/app/[variants]/(main)/chat/(workspace)/_layout/Mobile/ChatHeader/ChatHeaderTitle.tsx
Labels: size:S

#9107 ♻️ refactor: refactor to use trpc client link chain
  src/libs/trpc/client/lambda.ts
Labels: size:L

#9085 ♻️ refactor: remove edge runtime
  src/app/(backend)/webapi/chat/[provider]/route.ts
  src/app/(backend)/webapi/chat/anthropic/route.test.ts
  src/app/(backend)/webapi/chat/anthropic/route.ts
  src/app/(backend)/webapi/chat/google/route.test.ts
  src/app/(backend)/webapi/chat/google/route.ts
  src/app/(backend)/webapi/chat/groq/route.test.ts
  src/app/(backend)/webapi/chat/groq/route.ts
  src/app/(backend)/webapi/chat/openai/route.test.ts
  src/app/(backend)/webapi/chat/openai/route.ts
  src/app/(backend)/webapi/chat/vertexai/route.ts
Labels: size:L

#9124 ✅ test: refactor to improve utils tests and add more tests
  packages/const/src/hotkeys.ts
  packages/const/src/index.ts
  packages/const/src/trace.ts
  packages/database/src/client/db.test.ts
  packages/electron-server-ipc/src/ipcClient.test.ts
  packages/file-loaders/src/loadFile.test.ts
  packages/file-loaders/src/utils/isTextReadableFile.test.ts
  packages/file-loaders/src/utils/parser-utils.test.ts
  packages/model-runtime/src/utils/streams/anthropic.ts
  packages/model-runtime/src/utils/streams/openai/openai.ts
  packages/model-runtime/src/utils/streams/openai/responsesStream.ts
  packages/model-runtime/src/utils/streams/protocol.ts
  packages/types/src/index.ts
  packages/types/src/message/base.ts
  packages/types/src/openai/chat.ts
  packages/utils/package.json
  packages/utils/src/_deprecated/parseModels.test.ts
  packages/utils/src/_deprecated/parseModels.ts
  packages/utils/src/client/topic.test.ts
  packages/utils/src/client/topic.ts
  packages/utils/src/electron/desktopRemoteRPCFetch.ts
  packages/utils/src/fetch/fetchSSE.ts
  packages/utils/src/fetch/parseError.ts
  packages/utils/src/format.test.ts
  packages/utils/src/toolManifest.ts
  packages/utils/src/trace.ts
  packages/utils/vitest.config.mts
  packages/web-crawler/src/__tests__/urlRules.test.ts
  packages/web-crawler/src/crawImpl/__tests__/exa.test.ts
  packages/web-crawler/src/crawImpl/__tests__/firecrawl.test.ts
  packages/web-crawler/src/crawImpl/__tests__/naive.test.ts
  packages/web-crawler/src/crawImpl/__tests__/tavily.test.ts
  packages/web-crawler/src/utils/__tests__/errorType.test.ts
  packages/web-crawler/vitest.config.mts
  src/components/Thinking/index.tsx
Labels: size:XXL

#9084 feat(desktop): support mac intel chip
  .github/scripts/pr-comment.js
  .github/workflows/desktop-pr-build.yml
  .github/workflows/release-desktop-beta.yml
  apps/desktop/electron-builder.js
  scripts/electronWorkflow/mergeMacReleaseFiles.ts
Labels: size:L, Build Desktop

#9128 ✅ test: add model runtime tests
  packages/const/src/settings/hotkey.ts
  packages/const/src/user.ts
  packages/model-runtime/package.json
  packages/model-runtime/src/ai21/index.test.ts
  packages/model-runtime/src/ai360/index.test.ts
  packages/model-runtime/src/akashchat/index.test.ts
  packages/model-runtime/src/anthropic/index.test.ts
  packages/model-runtime/src/baichuan/index.test.ts
  packages/model-runtime/src/bedrock/index.test.ts
  packages/model-runtime/src/bfl/createImage.test.ts
  packages/model-runtime/src/bfl/index.test.ts
  packages/model-runtime/src/cloudflare/index.test.ts
  packages/model-runtime/src/cohere/index.test.ts
  packages/model-runtime/src/deepseek/index.test.ts
  packages/model-runtime/src/fireworksai/index.test.ts
  packages/model-runtime/src/giteeai/index.test.ts
  packages/model-runtime/src/github/index.test.ts
  packages/model-runtime/src/google/createImage.test.ts
  packages/model-runtime/src/google/index.test.ts
  packages/model-runtime/src/groq/index.test.ts
  packages/model-runtime/src/huggingface/index.test.ts
  packages/model-runtime/src/hunyuan/index.test.ts
  packages/model-runtime/src/internlm/index.test.ts
  packages/model-runtime/src/jina/index.test.ts
  packages/model-runtime/src/lmstudio/index.test.ts
  packages/model-runtime/src/minimax/index.test.ts
  packages/model-runtime/src/mistral/index.test.ts
  packages/model-runtime/src/modelscope/index.test.ts
  packages/model-runtime/src/moonshot/index.test.ts
  packages/model-runtime/src/nebius/index.test.ts
  packages/model-runtime/src/novita/index.test.ts
  packages/model-runtime/src/nvidia/index.test.ts
  packages/model-runtime/src/openrouter/__snapshots__/index.test.ts.snap
  packages/model-runtime/src/openrouter/index.test.ts
  packages/model-runtime/src/perplexity/index.test.ts
  packages/model-runtime/src/ppio/index.test.ts
  packages/model-runtime/src/qwen/index.test.ts
  packages/model-runtime/src/sambanova/index.test.ts
  packages/model-runtime/src/search1api/index.test.ts
  packages/model-runtime/src/sensenova/index.test.ts
  packages/model-runtime/src/spark/index.test.ts
  packages/model-runtime/src/stepfun/index.test.ts
  packages/model-runtime/src/taichu/index.test.ts
  packages/model-runtime/src/tencentcloud/index.test.ts
  packages/model-runtime/src/togetherai/index.test.ts
  packages/model-runtime/src/upstage/index.test.ts
  packages/model-runtime/src/utils/openaiCompatibleFactory/index.test.ts
  packages/model-runtime/src/utils/streams/openai/responsesStream.test.ts
  packages/model-runtime/src/wenxin/index.test.ts
  packages/model-runtime/src/xai/index.test.ts
  packages/model-runtime/src/zeroone/index.test.ts
  packages/model-runtime/src/zhipu/index.test.ts
  packages/model-runtime/vitest.config.mts
  packages/utils/src/index.ts
  src/libs/traces/index.ts
  src/server/modules/ModelRuntime/trace.ts
Labels: size:L

#9133 ♻️ refactor: refactor to remove edge runtime and add more tests
  packages/const/package.json
  packages/const/src/analytics.ts
  packages/const/src/desktop.ts
  packages/const/src/discover.ts
  packages/const/src/guide.ts
  packages/const/src/index.ts
  packages/const/src/settings/common.ts
  packages/const/src/settings/genUserLLMConfig.test.ts
  packages/const/src/settings/genUserLLMConfig.ts
  packages/const/src/settings/index.ts
  packages/const/src/settings/knowledge.ts
  packages/const/src/settings/llm.ts
  packages/const/src/settings/sync.ts
  packages/const/src/settings/systemAgent.ts
  packages/const/src/settings/tts.ts
  packages/const/src/url.ts
  packages/model-runtime/src/higress/index.ts
  packages/types/src/discover/index.ts
  packages/types/src/index.ts
  packages/types/src/tool/index.ts
  packages/types/src/tool/tool.ts
  packages/types/src/user/settings/index.ts
  packages/utils/vitest.config.mts
  src/app/(backend)/webapi/models/[provider]/pull/route.ts
  src/app/(backend)/webapi/models/[provider]/route.ts
  src/app/(backend)/webapi/text-to-image/[provider]/route.ts
  src/app/(backend)/webapi/trace/route.ts
Labels: size:M

#9141 🐛fix: update back navigation logic for provider settings in mobile view
  src/app/[variants]/(main)/settings/_layout/Mobile/Header.tsx
Labels: 🐛 Bug, 📱 Mobile Device, size:XS

#9163 🔨 chore: Branching input component for incoming group chat
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatInput/Desktop/ClassicChat.tsx
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatInput/Desktop/GroupChat.tsx
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatInput/Desktop/index.tsx
Labels: size:L

#9160 ✨ feat(image): implement model selection memory functionality
  .cursor/rules/react-component.mdc
  src/app/[variants]/(main)/image/@menu/features/ConfigPanel/components/ImageConfigSkeleton.tsx
  src/app/[variants]/(main)/image/@menu/features/ConfigPanel/index.tsx
  src/hooks/useFetchAiImageConfig.ts
  src/store/aiInfra/slices/aiModel/selectors.test.ts
  src/store/aiInfra/slices/aiProvider/__tests__/action.test.ts
  src/store/aiInfra/slices/aiProvider/action.ts
  src/store/aiInfra/slices/aiProvider/initialState.ts
  src/store/aiInfra/slices/aiProvider/selectors.ts
  src/store/global/initialState.ts
  src/store/global/selectors/systemStatus.ts
  src/store/image/slices/generationConfig/action.test.ts
  src/store/image/slices/generationConfig/action.ts
  src/store/image/slices/generationConfig/initialState.ts
  src/store/image/utils/aspectRatio.test.ts
  src/store/image/utils/aspectRatio.ts
Labels: 🌠 Feature Request, size:XXL

#9178 🐛 fix: fix Assistant List error message
  src/server/modules/AssistantStore/index.test.ts
  src/server/modules/AssistantStore/index.ts
  src/services/discover.ts
Labels: size:S

#9192 chore(mobile): optimized chatlist & auto scroll
  apps/mobile/src/features/chat/AutoScroll.tsx
  apps/mobile/src/features/chat/ChatList/index.tsx
Labels: size:M

#9065 💄 style: Add CometAPI model provider and chat models
  packages/model-bank/package.json
  packages/model-bank/src/aiModels/cometapi.ts
  packages/model-bank/src/aiModels/index.ts
  packages/model-runtime/src/cometapi/index.ts
  packages/model-runtime/src/index.ts
  packages/model-runtime/src/runtimeMap.ts
  packages/model-runtime/src/types/type.ts
  packages/types/src/user/settings/keyVaults.ts
  src/config/llm.ts
  src/config/modelProviders/cometapi.ts
  src/config/modelProviders/index.ts
Labels: Model Provider, size:L

#9170 💄 style: Update model configs
  packages/model-bank/src/aiModels/deepseek.ts
  packages/model-bank/src/aiModels/google.ts
  packages/model-bank/src/aiModels/groq.ts
  packages/model-bank/src/aiModels/modelscope.ts
  packages/model-bank/src/aiModels/novita.ts
  packages/model-bank/src/aiModels/qwen.ts
  packages/model-bank/src/aiModels/siliconcloud.ts
  packages/model-bank/src/aiModels/volcengine.ts
  packages/model-runtime/src/utils/modelParse.ts
Labels: 🐛 Bug, 💄 Design, size:L

#9102 🔨 chore(model-runtime): openai stream error not inherited correctly
  packages/model-runtime/src/core/streams/openai/openai.test.ts
  packages/model-runtime/src/core/streams/openai/openai.ts
  packages/model-runtime/src/core/streams/openai/responsesStream.ts
Labels: 🐛 Bug, size:S

#9214 🐛fix: update check model and mark deprecated models
  packages/model-bank/src/aiModels/xai.ts
  src/config/modelProviders/qwen.ts
  src/config/modelProviders/siliconcloud.ts
Labels: 🐛 Bug, size:S

#9180 🐛 fix: Google stream error unable to abort request
  packages/model-runtime/src/core/openaiCompatibleFactory/index.test.ts
  packages/model-runtime/src/core/streams/google-ai.test.ts
  packages/model-runtime/src/core/streams/google-ai.ts
  packages/model-runtime/src/core/streams/openai/openai.test.ts
  packages/model-runtime/src/core/streams/protocol.test.ts
  packages/model-runtime/src/core/streams/protocol.ts
  packages/model-runtime/src/providers/google/index.test.ts
  packages/model-runtime/src/providers/google/index.ts
Labels: 🐛 Bug, size:L, lgtm

#9250 👷 build: fix electron build
  package.json
Labels: size:XS

#9258 fix(mobile): input multiple line issue
  apps/mobile/src/features/chat/ChatInput/index.tsx
  apps/mobile/src/features/chat/ChatInput/style.ts
Labels: 🐛 Bug, 📱 Mobile Device, size:XS

#9259 fix(mobile): app crash
  apps/mobile/babel.config.js
  apps/mobile/package.json
  apps/mobile/pnpm-lock.yaml
  apps/mobile/src/utils/tokenizer/client.ts
Labels: 📱 Mobile Device, size:S

#9261 ⚡️ perf: fix search agent issue
  .gitignore
  docs/development/database-schema.dbml
  packages/database/migrations/0031_add_agent_index.sql
  packages/database/migrations/meta/0031_snapshot.json
  packages/database/migrations/meta/_journal.json
  packages/database/src/core/migrations.json
  packages/database/src/models/session.ts
  packages/database/src/schemas/agent.ts
Labels: ⚡️ Performance, 🐛 Bug, size:M

#9173 💄 style: Enable toggling search on/off via search button click & historyCount button
  src/features/ChatInput/ActionBar/History/Controls.tsx
  src/features/ChatInput/ActionBar/History/index.tsx
  src/features/ChatInput/ActionBar/Search/index.tsx
  src/features/ChatInput/ActionBar/components/Action.tsx
Labels: 💄 Design, size:M

#9276 🐛 fix: fix azure ai runtime error
  docs/development/database-schema.dbml
  next.config.ts
  package.json
  packages/const/src/layoutTokens.ts
  packages/database/migrations/0031_add_agent_index.sql
  packages/database/migrations/0032_improve_agents_field.sql
  packages/database/migrations/meta/0032_snapshot.json
  packages/database/migrations/meta/_journal.json
  packages/database/src/core/migrations.json
  packages/database/src/schemas/agent.ts
  packages/database/src/server/models/__tests__/adapter.test.ts
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/(backend)/webapi/chat/azureai/route.test.ts
  src/app/(backend)/webapi/chat/azureai/route.ts
  src/app/[variants]/(main)/chat/(workspace)/_layout/Desktop/ChatHeader/index.tsx
  src/app/[variants]/global-error.tsx
  src/components/Error/index.tsx
  src/components/Error/sentryCaptureException.ts
  src/instrumentation.ts
Labels: azure, size:L

#8883 ✨ feat: support Vercel AI Gateway provider
  .env.example
  Dockerfile
  Dockerfile.database
  Dockerfile.pglite
  docs/self-hosting/environment-variables/model-provider.mdx
  docs/self-hosting/environment-variables/model-provider.zh-CN.mdx
  docs/usage/providers/vercel-ai-gateway.mdx
  docs/usage/providers/vercel-ai-gateway.zh-CN.mdx
  packages/model-bank/package.json
  packages/model-bank/src/aiModels/index.ts
  packages/model-bank/src/aiModels/vercelaigateway.ts
  packages/model-runtime/src/const/modelProvider.ts
  packages/model-runtime/src/providers/vercelaigateway/index.ts
  packages/model-runtime/src/runtimeMap.ts
  packages/types/src/user/settings/keyVaults.ts
  src/config/modelProviders/index.ts
  src/config/modelProviders/vercelaigateway.ts
  src/envs/llm.ts
Labels: 🌠 Feature Request, size:XXL

#9283 ♻️ refactor: improve db sql performance
  docs/development/database-schema.dbml
  packages/database/migrations/0031_add_agent_index.sql
  packages/database/migrations/0032_improve_agents_field.sql
  packages/database/migrations/0033_modern_mercury.sql
  packages/database/migrations/meta/0033_snapshot.json
  packages/database/migrations/meta/_journal.json
  packages/database/src/core/migrations.json
  packages/database/src/schemas/message.ts
  packages/database/src/schemas/rag.ts
  packages/database/src/schemas/session.ts
  packages/database/src/schemas/topic.ts
Labels: ⚡️ Performance, size:L

#9289 fix: app submit bug
  apps/mobile/app/(discover)/assistant/detail/index.tsx
  apps/mobile/app/(main)/setting/providers/[id]/index.tsx
  apps/mobile/app/(main)/setting/providers/[id]/styles.ts
  apps/mobile/app/playground/components/button.tsx
  apps/mobile/docs/model-switch-refactor-design.md
  apps/mobile/src/components/ActionIcon/index.tsx
  apps/mobile/src/components/Button/demos/disabled.tsx
  apps/mobile/src/components/Button/demos/index.ts
  apps/mobile/src/components/Button/demos/loading.tsx
  apps/mobile/src/components/Button/demos/shape.tsx
  apps/mobile/src/components/Button/demos/states.tsx
  apps/mobile/src/components/Button/demos/variant-color.tsx
  apps/mobile/src/components/Button/index.tsx
  apps/mobile/src/components/Button/style.ts
  apps/mobile/src/components/Markdown/markdown.tsx
  apps/mobile/src/const/branding.ts
  apps/mobile/src/const/common.ts
  apps/mobile/src/const/meta.ts
  apps/mobile/src/features/SideBar/components/Footer/index.tsx
  apps/mobile/src/features/SideBar/components/Header/index.tsx
  apps/mobile/src/features/chat/ChatBubble/style.ts
  apps/mobile/src/features/chat/ChatHeader/index.tsx
  apps/mobile/src/features/chat/ChatHeader/style.ts
  apps/mobile/src/features/chat/ChatInput/components/IconBtn/index.tsx
  apps/mobile/src/features/chat/ChatInput/components/IconBtn/styles.ts
  apps/mobile/src/features/chat/ChatInput/components/ModelSwitch/ModelSwitchButton/index.tsx
  apps/mobile/src/features/chat/ChatInput/components/ModelSwitch/ModelSwitchButton/styles.ts
  apps/mobile/src/features/chat/ChatInput/components/ModelSwitch/index.tsx
  apps/mobile/src/features/chat/ChatInput/index.tsx
  apps/mobile/src/features/chat/ChatInput/style.ts
  apps/mobile/src/features/chat/WelcomeChatBubble/style.ts
  apps/mobile/src/features/chat/WelcomeMessage/OpeningQuestions.style.ts
  apps/mobile/src/features/chat/WelcomeMessage/index.tsx
  apps/mobile/src/features/chat/WelcomeMessage/style.ts
  apps/mobile/src/features/chat/actions/NewChatBtn/index.tsx
  apps/mobile/src/features/chat/actions/SenderBtn/StopLoadingIcon/index.tsx
  apps/mobile/src/features/chat/actions/SenderBtn/StopLoadingIcon/style.ts
  apps/mobile/src/features/chat/actions/SenderBtn/index.tsx
  apps/mobile/src/features/chat/actions/ToogleTopic/index.tsx
  apps/mobile/src/features/setting/providers/ConfigurationSection/Checker.tsx
  apps/mobile/src/theme/algorithm/dark/color.ts
  apps/mobile/src/theme/algorithm/light/color.ts
  apps/mobile/src/theme/algorithm/shared/generateColorPalette.ts
  apps/mobile/src/theme/alias.ts
  apps/mobile/src/theme/interface/alias.ts
  apps/mobile/src/theme/interface/maps/colors.ts
  apps/mobile/src/theme/interface/presetColors.ts
Labels: 🐛 Bug, 📱 Mobile Device, size:XL

#9295 🐛 fix: improve db migrations sql
  packages/database/migrations/0031_add_agent_index.sql
  packages/database/src/core/migrations.json
Labels: 🐛 Bug, size:S

#9277 🐛 fix: add qwen provider support for image-edit model
  packages/model-runtime/src/core/RouterRuntime/baseRuntimeMap.ts
  packages/model-runtime/src/providers/newapi/index.ts
  packages/model-runtime/src/providers/qwen/createImage.test.ts
  packages/model-runtime/src/providers/qwen/createImage.ts
Labels: 🐛 Bug, size:L

#9319 ✨ feat: Add scroll support for pinned assistants using ScrollShadow
  src/app/[variants]/(main)/_layout/Desktop/SideBar/PinList/index.tsx
  src/app/[variants]/(main)/_layout/Desktop/SideBar/index.tsx
Labels: 🌠 Feature Request, size:M

#9063 🔨 chore: fix `nextjs@15.5.x` runtime warning
  next.config.ts
  package.json
  packages/utils/src/toolManifest.ts
  src/app/(backend)/webapi/chat/vertexai/route.ts
Labels: size:S, Build Docker

#9355 📝 docs: renamed license to LobeHub Community License
  LICENSE
Labels: 📝 Documentation, size:XS

#9278 💄 style: extend custom provider runtime options
  packages/types/src/aiProvider.ts
  src/app/[variants]/(main)/settings/provider/features/CreateNewProvider/index.tsx
  src/app/[variants]/(main)/settings/provider/features/ProviderConfig/UpdateProviderInfo/SettingModal.tsx
  src/app/[variants]/(main)/settings/provider/features/customProviderSdkOptions.ts
Labels: 🌠 Feature Request, size:M, codex

#8761 ✨ feat: support google video understanding
  packages/context-engine/src/processors/MessageContent.ts
  packages/context-engine/src/processors/__tests__/MessageContent.test.ts
  packages/database/src/models/message.ts
  packages/model-bank/src/aiModels/google.ts
  packages/model-runtime/src/providers/google/index.ts
  packages/model-runtime/src/types/chat.ts
  packages/prompts/src/prompts/files/index.test.ts
  packages/prompts/src/prompts/files/index.ts
  packages/prompts/src/prompts/files/video.ts
  packages/types/src/agent/index.ts
  packages/types/src/message/chat.ts
  packages/types/src/message/index.ts
  packages/types/src/message/video.ts
  packages/utils/src/client/index.ts
  packages/utils/src/client/videoValidation.test.ts
  packages/utils/src/client/videoValidation.ts
  packages/utils/src/parseModels.ts
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatInput/useSend.ts
  src/components/ModelSelect/index.tsx
  src/features/ChatInput/ActionBar/Upload/ClientMode.tsx
  src/features/ChatInput/ActionBar/Upload/ServerMode.tsx
  src/features/ChatInput/components/UploadDetail/UploadStatus.tsx
  src/features/Conversation/Messages/Assistant/index.tsx
  src/features/Conversation/Messages/User/VideoFileListViewer.tsx
  src/features/Conversation/Messages/User/index.tsx
  src/hooks/useModelSupportVideo.ts
  src/locales/default/chat.ts
  src/locales/default/components.ts
  src/services/chat/contextEngineering.test.ts
  src/services/chat/contextEngineering.ts
  src/services/chat/helper.ts
  src/services/upload.ts
  src/store/aiInfra/slices/aiModel/selectors.ts
  src/store/chat/slices/aiChat/actions/generateAIChatV2.ts
  src/store/chat/slices/message/action.ts
Labels: size:XL

#9361 🐛 fix: fix missing provider in server message
  src/server/routers/lambda/aiChat.ts
Labels: size:XS

#9293 💄 style: Added `AUTH_MICROSOFT_ENTRA_ID_BASE_URL` routing
  .devcontainer/devcontainer.json
  docs/self-hosting/environment-variables/auth.mdx
  src/libs/next-auth/sso-providers/microsoft-entra-id-helper.ts
Labels: 🌠 Feature Request, 📝 Documentation, size:S

#9408 💄 style: Enhanced Nvidia NIM chat experience
  packages/model-bank/src/aiModels/nvidia.ts
  packages/model-bank/src/aiModels/ollama.ts
  packages/model-runtime/src/providers/akashchat/index.ts
  packages/model-runtime/src/providers/nvidia/index.ts
Labels: 💄 Design, size:M

#9417 🐛 fix: slove setting proxy page with style error
  src/app/[variants]/(main)/settings/proxy/index.tsx
Labels: 🐛 Bug, size:XS, Build Desktop

#9422 👷 build: fix `UNABLE_TO_GET_ISSUER_CERT_LOCALLY` error with docker image
  Dockerfile
  Dockerfile.database
  Dockerfile.pglite
Labels: size:S

#9414 🐛 fix: resolve qwen-image-edit imageUrls conversion issue
  packages/model-runtime/src/providers/qwen/createImage.test.ts
  packages/model-runtime/src/providers/qwen/createImage.ts
Labels: 🐛 Bug, size:L

#9435 ✨ feat: Add new provider Ollama Cloud
  packages/model-bank/package.json
  packages/model-bank/src/aiModels/index.ts
  packages/model-bank/src/aiModels/ollama.ts
  packages/model-bank/src/aiModels/ollamacloud.ts
  packages/model-bank/src/const/modelProvider.ts
  packages/model-runtime/src/index.ts
  packages/model-runtime/src/providers/ollamacloud/index.ts
  packages/model-runtime/src/runtimeMap.ts
  packages/types/src/user/settings/keyVaults.ts
  src/app/[variants]/(main)/settings/llm/ProviderList/providers.tsx
  src/config/modelProviders/index.ts
  src/config/modelProviders/ollamacloud.ts
  src/envs/llm.ts
  src/server/globalConfig/index.ts
  src/server/modules/ModelRuntime/index.ts
Labels: ollama, size:L

#9444 ⚡️ perf: fix battery usage
  apps/desktop/src/main/core/browser/Browser.ts
Labels: ⚡️ Performance, size:XS

#9441 🐛 fix: can not input empty group name
  src/app/[variants]/(main)/chat/@session/features/SessionListContent/Modals/ConfigGroupModal/GroupItem.tsx
  src/app/[variants]/(main)/chat/@session/features/SessionListContent/Modals/CreateGroupModal.tsx
Labels: 🐛 Bug, size:XS

#9448 🐛 fix: refactor tools-engine and fix search token count
  package.json
  packages/context-engine/src/index.ts
  packages/context-engine/src/tools/ToolsEngine.ts
  packages/context-engine/src/tools/__tests__/ToolsEngine.test.ts
  packages/context-engine/src/tools/__tests__/generateToolName.test.ts
  packages/context-engine/src/tools/__tests__/utils.test.ts
  packages/context-engine/src/tools/index.ts
  packages/context-engine/src/tools/types.ts
  packages/context-engine/src/tools/utils.ts
  src/features/ChatInput/ActionBar/Token/TokenTag.tsx
  src/helpers/getSearchConfig.test.ts
  src/helpers/getSearchConfig.ts
  src/helpers/isCanUseFC.ts
  src/helpers/toolEngineering/index.test.ts
  src/helpers/toolEngineering/index.ts
  src/services/chat/chat.test.ts
  src/services/chat/contextEngineering.test.ts
  src/services/chat/contextEngineering.ts
  src/services/chat/helper.ts
  src/services/chat/index.ts
  src/store/tool/selectors/tool.test.ts
  src/store/tool/selectors/tool.ts
Labels: size:XXL

#9464 👷 build: Add `virtual` column to agent table
  docs/development/database-schema.dbml
  packages/database/migrations/0035_add_virtual.sql
  packages/database/migrations/meta/0035_snapshot.json
  packages/database/migrations/meta/_journal.json
  packages/database/src/core/migrations.json
  packages/database/src/schemas/agent.ts
Labels: 🌠 Feature Request, size:S, lgtm

#9471 chore: performance issues
  apps/mobile/app/(main)/setting/providers/index.tsx
  apps/mobile/app/discover/assistant/index.tsx
  apps/mobile/package.json
  apps/mobile/pnpm-lock.yaml
  apps/mobile/src/features/SideBar/components/SessionList/SessionItem.tsx
  apps/mobile/src/features/SideBar/components/SessionList/index.tsx
  apps/mobile/src/features/chat/AutoScroll.tsx
  apps/mobile/src/features/chat/BackBottom/index.tsx
  apps/mobile/src/features/chat/MessageActions/index.tsx
  apps/mobile/src/features/discover/assistant/components/AgentCard/index.tsx
Labels: size:L

#9473 🔨 chore: add auto close issues workflow
  .github/scripts/lock-closed-issues.js
  .github/workflows/lock-closed-issues.yml
Labels: size:L

#9478 🔨 chore: fix types
  package.json
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatHydration/index.tsx
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ThreadHydration.tsx
  src/features/AgentSetting/StoreUpdater.tsx
  src/features/ChatInput/StoreUpdater.tsx
  src/layout/AuthProvider/Clerk/UserUpdater.tsx
  src/layout/AuthProvider/NextAuth/UserUpdater.tsx
  src/store/user/slices/auth/initialState.ts
Labels: size:M

#9476 ✨ feat: add Claude Sonnet 4.5 model to AI chat models
  packages/const/src/models.ts
  packages/model-bank/src/aiModels/anthropic.ts
  packages/model-bank/src/aiModels/openrouter.ts
  packages/model-runtime/src/providers/anthropic/index.ts
Labels: 🌠 Feature Request, size:M

#9477 🐛 fix: fix frontend random API key support
  packages/const/src/index.ts
  packages/utils/src/client/apiKeyManager.test.ts
  packages/utils/src/client/apiKeyManager.ts
  packages/utils/src/client/index.ts
  packages/utils/src/index.ts
  packages/utils/src/toolManifest.ts
  src/services/_auth.ts
  src/services/chat/contextEngineering.ts
Labels: 🐛 Bug, size:L
