Repository lobehub/lobe-chat, pull requests merged in 2025-03, with the labels that each got.

#6616 ✅ test: fix tests
  src/database/server/models/__tests__/message.test.ts
Labels: size:XS

#6618 💄 style: add `gpt-4.5-preview` for OpenAI
  src/config/aiModels/openai.ts
Labels: 💄 Design, size:M

#6628 👷 build: fix docker build failed
  .env.example
  Dockerfile
  Dockerfile.database
  Dockerfile.pglite
  README.md
  README.zh-CN.md
  next.config.ts
Labels: size:L, Build Docker

#6634 🐛 fix: improve some crawl case
  locales/ar/models.json
  locales/ar/plugin.json
  locales/bg-BG/models.json
  locales/bg-BG/plugin.json
  locales/de-DE/models.json
  locales/de-DE/plugin.json
  locales/en-US/models.json
  locales/en-US/plugin.json
  locales/es-ES/models.json
  locales/es-ES/plugin.json
  locales/fa-IR/models.json
  locales/fa-IR/plugin.json
  locales/fr-FR/models.json
  locales/fr-FR/plugin.json
  locales/it-IT/models.json
  locales/it-IT/plugin.json
  locales/ja-JP/models.json
  locales/ja-JP/plugin.json
  locales/ko-KR/models.json
  locales/ko-KR/plugin.json
  locales/nl-NL/models.json
  locales/nl-NL/plugin.json
  locales/pl-PL/models.json
  locales/pl-PL/plugin.json
  locales/pt-BR/models.json
  locales/pt-BR/plugin.json
  locales/ru-RU/models.json
  locales/ru-RU/plugin.json
  locales/tr-TR/models.json
  locales/tr-TR/plugin.json
  locales/vi-VN/models.json
  locales/vi-VN/plugin.json
  locales/zh-CN/models.json
  locales/zh-CN/plugin.json
  locales/zh-TW/models.json
  locales/zh-TW/plugin.json
  packages/web-crawler/src/crawler.ts
  packages/web-crawler/src/type.ts
  packages/web-crawler/src/urlRules.ts
  packages/web-crawler/src/utils/appUrlRules.ts
  src/locales/default/plugin.ts
  src/server/routers/tools/search.ts
  src/store/chat/slices/builtinTool/actions/searXNG.ts
  src/tools/web-browsing/Portal/PageContent/index.tsx
  src/tools/web-browsing/const.ts
Labels: 🐛 Bug, size:M

#6646 🔨 chore: upgrade anthropic SDK
  package.json
  src/libs/agent-runtime/utils/anthropicHelpers.ts
Labels: size:XS

#6627 :memo: docs: Add env to enable NextAuth
  docs/self-hosting/advanced/auth.mdx
  docs/self-hosting/advanced/auth.zh-CN.mdx
Labels: 📝 Documentation, size:S

#6653 🐛 fix: fix search web-browsing display bug
  src/store/tool/slices/builtin/selectors.test.ts
  src/store/tool/slices/builtin/selectors.ts
Labels: 🐛 Bug, size:S

#6133 ✨ feat: add new model provider PPIO
  .env.example
  Dockerfile
  Dockerfile.database
  README.md
  README.zh-CN.md
  docs/self-hosting/environment-variables/model-provider.mdx
  docs/self-hosting/environment-variables/model-provider.zh-CN.mdx
  docs/usage/providers/ppio.mdx
  docs/usage/providers/ppio.zh-CN.mdx
  locales/en-US/providers.json
  locales/zh-CN/providers.json
  src/app/[variants]/(main)/settings/llm/ProviderList/providers.tsx
  src/config/aiModels/index.ts
  src/config/aiModels/ppio.ts
  src/config/llm.ts
  src/config/modelProviders/index.ts
  src/config/modelProviders/ppio.ts
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/ppio/__snapshots__/index.test.ts.snap
  src/libs/agent-runtime/ppio/fixtures/models.json
  src/libs/agent-runtime/ppio/index.test.ts
  src/libs/agent-runtime/ppio/index.ts
  src/libs/agent-runtime/ppio/type.ts
  src/libs/agent-runtime/types/type.ts
  src/types/user/settings/keyVaults.ts
Labels: 🌠 Feature Request, Model Provider, size:XXL

#6662 🐛 fix: Fix page crash with crawler error
  packages/web-crawler/README.md
  packages/web-crawler/README.zh-CN.md
  packages/web-crawler/src/__test__/crawler.test.ts
  packages/web-crawler/src/crawler.ts
  packages/web-crawler/src/type.ts
  packages/web-crawler/src/urlRules.ts
  src/tools/web-browsing/Portal/PageContent/index.tsx
  src/tools/web-browsing/Render/PageContent/Result.tsx
  src/tools/web-browsing/Render/PageContent/index.tsx
  src/types/tool/crawler.ts
Labels: 🐛 Bug, size:L

#6617 💄 style: add build-in web search support for Wenxin & Hunyuan
  src/config/aiModels/wenxin.ts
  src/libs/agent-runtime/hunyuan/index.test.ts
  src/libs/agent-runtime/hunyuan/index.ts
  src/libs/agent-runtime/qwen/index.ts
  src/libs/agent-runtime/utils/streams/openai.ts
  src/libs/agent-runtime/utils/streams/protocol.ts
  src/libs/agent-runtime/wenxin/index.test.ts
  src/libs/agent-runtime/wenxin/index.ts
Labels: 🌠 Feature Request, size:L

#6669 🐛 fix: improve url rules
  packages/web-crawler/src/crawImpl/jina.ts
  packages/web-crawler/src/urlRules.ts
Labels: 🐛 Bug, size:S

#6690 👷 build: add `ENABLE_PROXY_DNS` env
  scripts/serverLauncher/startServer.js
Labels: size:S

#6701 📝 docs: Update provider docs
  docs/usage/providers/azureai.mdx
  docs/usage/providers/azureai.zh-CN.mdx
  docs/usage/providers/deepseek.mdx
  docs/usage/providers/deepseek.zh-CN.mdx
  docs/usage/providers/jina.mdx
  docs/usage/providers/jina.zh-CN.mdx
  docs/usage/providers/lmstudio.mdx
  docs/usage/providers/lmstudio.zh-CN.mdx
  docs/usage/providers/nvidia.mdx
  docs/usage/providers/nvidia.zh-CN.mdx
  docs/usage/providers/ppio.mdx
  docs/usage/providers/ppio.zh-CN.mdx
  docs/usage/providers/sambanova.mdx
  docs/usage/providers/sambanova.zh-CN.mdx
  docs/usage/providers/tencentcloud.mdx
  docs/usage/providers/tencentcloud.zh-CN.mdx
  docs/usage/providers/vertexai.mdx
  docs/usage/providers/vertexai.zh-CN.mdx
  docs/usage/providers/vllm.mdx
  docs/usage/providers/vllm.zh-CN.mdx
  docs/usage/providers/volcengine.mdx
  docs/usage/providers/volcengine.zh-CN.mdx
  src/config/modelProviders/ppio.ts
Labels: 📝 Documentation, size:XXL

#6702 💄 style: fix provider order
  README.md
  README.zh-CN.md
  src/config/modelProviders/index.ts
Labels: 💄 Design, size:M

#6712 🐛 fix: fix custom ai provider sdk type
  locales/ar/modelProvider.json
  locales/bg-BG/modelProvider.json
  locales/de-DE/modelProvider.json
  locales/en-US/modelProvider.json
  locales/es-ES/modelProvider.json
  locales/fa-IR/modelProvider.json
  locales/fr-FR/modelProvider.json
  locales/it-IT/modelProvider.json
  locales/ja-JP/modelProvider.json
  locales/ko-KR/modelProvider.json
  locales/nl-NL/modelProvider.json
  locales/pl-PL/modelProvider.json
  locales/pt-BR/modelProvider.json
  locales/ru-RU/modelProvider.json
  locales/tr-TR/modelProvider.json
  locales/vi-VN/modelProvider.json
  locales/zh-CN/modelProvider.json
  locales/zh-TW/modelProvider.json
  src/app/[variants]/(main)/settings/provider/features/CreateNewProvider/index.tsx
  src/app/[variants]/(main)/settings/provider/features/ProviderConfig/UpdateProviderInfo/SettingModal.tsx
  src/app/[variants]/(main)/settings/provider/features/ProviderConfig/index.tsx
  src/features/Conversation/Extras/Usage/UsageDetail/ModelCard.tsx
  src/features/Conversation/Extras/Usage/UsageDetail/index.tsx
  src/locales/default/modelProvider.ts
Labels: 🐛 Bug, size:L

#6284 ♻️ refactor: refactor agent runtime to better code format
  src/app/(backend)/webapi/chat/[provider]/route.test.ts
  src/libs/agent-runtime/AgentRuntime.test.ts
  src/libs/agent-runtime/AgentRuntime.ts
  src/libs/agent-runtime/azureOpenai/index.test.ts
  src/libs/agent-runtime/azureOpenai/index.ts
  src/libs/agent-runtime/runtimeMap.ts
  src/libs/agent-runtime/vertexai/index.ts
  src/server/modules/AgentRuntime/index.ts
  src/services/chat.ts
Labels: size:XL

#6708 💄 style: improve openrouter models info
  src/database/server/models/aiModel.ts
  src/libs/agent-runtime/openrouter/__snapshots__/index.test.ts.snap
  src/libs/agent-runtime/openrouter/index.ts
  src/libs/agent-runtime/openrouter/type.ts
  src/types/llm.ts
Labels: 🐛 Bug, size:M

#6317 💄 style: add epub file chunk split support
  package.json
  src/database/client/migrations.json
  src/libs/langchain/loaders/epub/__tests__/__snapshots__/index.test.ts.snap
  src/libs/langchain/loaders/epub/__tests__/demo.epub
  src/libs/langchain/loaders/epub/__tests__/index.test.ts
  src/libs/langchain/loaders/epub/index.ts
  src/libs/langchain/loaders/index.ts
  src/libs/langchain/types.ts
  src/server/utils/tempFileManager.ts
Labels: 🌠 Feature Request, files, size:L

#6734 🐛 fix: fix litellm streaming usage issue
  locales/ar/chat.json
  locales/ar/models.json
  locales/bg-BG/chat.json
  locales/bg-BG/models.json
  locales/de-DE/chat.json
  locales/de-DE/models.json
  locales/en-US/chat.json
  locales/en-US/models.json
  locales/es-ES/chat.json
  locales/es-ES/models.json
  locales/fa-IR/chat.json
  locales/fa-IR/models.json
  locales/fr-FR/chat.json
  locales/fr-FR/models.json
  locales/it-IT/chat.json
  locales/it-IT/models.json
  locales/ja-JP/chat.json
  locales/ja-JP/models.json
  locales/ko-KR/chat.json
  locales/ko-KR/models.json
  locales/nl-NL/chat.json
  locales/nl-NL/models.json
  locales/pl-PL/chat.json
  locales/pl-PL/models.json
  locales/pt-BR/chat.json
  locales/pt-BR/models.json
  locales/ru-RU/chat.json
  locales/ru-RU/models.json
  locales/tr-TR/chat.json
  locales/tr-TR/models.json
  locales/vi-VN/chat.json
  locales/vi-VN/models.json
  locales/zh-CN/chat.json
  locales/zh-CN/models.json
  locales/zh-TW/chat.json
  locales/zh-TW/models.json
  src/config/aiModels/perplexity.ts
  src/features/Conversation/Extras/Usage/UsageDetail/ModelCard.tsx
  src/features/Conversation/Extras/Usage/UsageDetail/index.tsx
  src/features/Conversation/Extras/Usage/UsageDetail/tokens.test.ts
  src/features/Conversation/Extras/Usage/UsageDetail/tokens.ts
  src/libs/agent-runtime/baichuan/index.test.ts
  src/libs/agent-runtime/groq/index.test.ts
  src/libs/agent-runtime/mistral/index.test.ts
  src/libs/agent-runtime/perplexity/index.test.ts
  src/libs/agent-runtime/providerTestUtils.ts
  src/libs/agent-runtime/togetherai/index.test.ts
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.test.ts
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
  src/libs/agent-runtime/utils/streams/anthropic.test.ts
  src/libs/agent-runtime/utils/streams/anthropic.ts
  src/libs/agent-runtime/utils/streams/openai.test.ts
  src/libs/agent-runtime/utils/streams/openai.ts
  src/libs/agent-runtime/utils/usageConverter.test.ts
  src/libs/agent-runtime/utils/usageConverter.ts
  src/libs/agent-runtime/zeroone/index.test.ts
  src/locales/default/chat.ts
  src/types/message/base.ts
  src/utils/filter.test.ts
  src/utils/filter.ts
Labels: 🐛 Bug, size:L

#6722 📝 docs: update docs for providers
  docs/usage/providers/ppio.mdx
  docs/usage/providers/ppio.zh-CN.mdx
  src/config/modelProviders/ppio.ts
Labels: 📝 Documentation, size:S

#6679 💄 style: Add Gemini 2.0 Flash model variations
  locales/ar/models.json
  locales/bg-BG/models.json
  locales/de-DE/models.json
  locales/en-US/models.json
  locales/es-ES/models.json
  locales/fa-IR/models.json
  locales/fr-FR/models.json
  locales/it-IT/models.json
  locales/ja-JP/models.json
  locales/ko-KR/models.json
  locales/nl-NL/models.json
  locales/pl-PL/models.json
  locales/pt-BR/models.json
  locales/ru-RU/models.json
  locales/tr-TR/models.json
  locales/vi-VN/models.json
  locales/zh-CN/models.json
  locales/zh-TW/models.json
  src/config/aiModels/google.ts
Labels: Gemini, size:L

#6779 🐛fix: ignore epub2 compile error
  next.config.ts
Labels: 🐛 Bug, size:XS

#6783 💄 style: Add Qwen QwQ model
  src/config/aiModels/google.ts
  src/config/aiModels/groq.ts
  src/config/aiModels/novita.ts
  src/config/aiModels/siliconcloud.ts
Labels: size:M

#6784 ♻️ refactor: refactor the agent runtime
  locales/ar/models.json
  locales/bg-BG/models.json
  locales/de-DE/models.json
  locales/en-US/models.json
  locales/es-ES/models.json
  locales/fa-IR/models.json
  locales/fr-FR/models.json
  locales/it-IT/models.json
  locales/ja-JP/models.json
  locales/ko-KR/models.json
  locales/nl-NL/models.json
  locales/pl-PL/models.json
  locales/pt-BR/models.json
  locales/ru-RU/models.json
  locales/tr-TR/models.json
  locales/vi-VN/models.json
  locales/zh-CN/models.json
  locales/zh-TW/models.json
  package.json
  src/libs/agent-runtime/UniformRuntime/index.ts
  src/libs/agent-runtime/anthropic/handleAnthropicError.ts
  src/libs/agent-runtime/anthropic/index.test.ts
  src/libs/agent-runtime/anthropic/index.ts
  src/libs/agent-runtime/azureai/index.ts
  src/libs/agent-runtime/github/index.ts
  src/libs/agent-runtime/index.ts
  src/libs/agent-runtime/openai/index.ts
  src/libs/agent-runtime/types/type.ts
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
  src/libs/agent-runtime/utils/openaiHelpers.ts
Labels: size:XL

#6434 :lipstick: style: Add login ui for next-auth
  src/app/[variants]/(auth)/next-auth/signin/AuthSignInBox.tsx
  src/app/[variants]/(auth)/next-auth/signin/page.tsx
  src/app/[variants]/(main)/profile/(home)/features/SSOProvidersList/index.tsx
  src/components/NextAuth/AuthIcons.tsx
  src/libs/next-auth/auth.config.ts
  src/middleware.ts
Labels: 💄 Design, size:L

#6828 🐛 fix: fix some relative bug
  packages/web-crawler/package.json
  packages/web-crawler/src/crawImpl/browserless.ts
  packages/web-crawler/src/urlRules.ts
  src/features/Conversation/Extras/Usage/UsageDetail/ModelCard.tsx
  src/features/Conversation/Extras/Usage/UsageDetail/index.tsx
  src/libs/agent-runtime/mistral/index.test.ts
  src/libs/agent-runtime/mistral/index.ts
  src/libs/agent-runtime/utils/debugStream.ts
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
  src/services/chat.ts
  src/store/agent/index.ts
  src/store/agent/slices/chat/selectors/chatConfig.ts
  src/store/agent/store.ts
  src/store/aiInfra/index.ts
  src/store/aiInfra/store.ts
  src/store/chat/slices/aiChat/actions/generateAIChat.ts
  src/store/chat/slices/aiChat/actions/helpers.ts
  src/store/session/index.ts
  src/store/session/store.ts
  src/store/tool/index.ts
  src/store/tool/store.ts
  src/store/user/store.ts
  src/types/agent/chatConfig.ts
  src/types/agent/index.ts
Labels: size:L

#6714 🔨 chore: Casdoor re-init in on-click deployment
  docker-compose/setup.sh
Labels: 🐛 Bug, size:M

#6497 💄 style(chat): auto send message from URL
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatInput/Desktop/Footer/MessageFromUrl.tsx
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatInput/Desktop/Footer/index.tsx
Labels: 🌠 Feature Request, size:L

#6309 📝 docs: Add `NEXT_PUBLIC_ENABLE_NEXT_AUTH` to clerk example
  docs/self-hosting/advanced/auth/clerk.mdx
Labels: 📝 Documentation, size:XS

#6672 ⚡️ perf: Improve the performance of `refreshModelProviderList`.
  src/store/user/slices/modelList/action.ts
Labels: ⚡️ Performance, size:M

#6831 🐛 fix: fix context cache control and model builtin search switch
  locales/ar/components.json
  locales/ar/models.json
  locales/bg-BG/components.json
  locales/bg-BG/models.json
  locales/de-DE/components.json
  locales/de-DE/models.json
  locales/en-US/components.json
  locales/en-US/models.json
  locales/es-ES/components.json
  locales/es-ES/models.json
  locales/fa-IR/components.json
  locales/fa-IR/models.json
  locales/fr-FR/components.json
  locales/fr-FR/models.json
  locales/it-IT/components.json
  locales/it-IT/models.json
  locales/ja-JP/components.json
  locales/ja-JP/models.json
  locales/ko-KR/components.json
  locales/ko-KR/models.json
  locales/nl-NL/components.json
  locales/nl-NL/models.json
  locales/pl-PL/components.json
  locales/pl-PL/models.json
  locales/pt-BR/components.json
  locales/pt-BR/models.json
  locales/ru-RU/components.json
  locales/ru-RU/models.json
  locales/tr-TR/components.json
  locales/tr-TR/models.json
  locales/vi-VN/components.json
  locales/vi-VN/models.json
  locales/zh-CN/components.json
  locales/zh-CN/models.json
  locales/zh-TW/components.json
  locales/zh-TW/models.json
  package.json
  packages/web-crawler/package.json
  packages/web-crawler/src/crawImpl/__tests__/browserless.test.ts
  packages/web-crawler/src/crawImpl/browserless.ts
  packages/web-crawler/src/crawImpl/naive.ts
  packages/web-crawler/src/utils/__snapshots__/htmlToMarkdown.test.ts.snap
  packages/web-crawler/src/utils/htmlToMarkdown.ts
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatList/WelcomeChatItem/InboxWelcome/AgentsSuggest.tsx
  src/config/modelProviders/openai.ts
  src/database/client/db.ts
  src/features/Conversation/components/MarkdownElements/LobeArtifact/Render/index.tsx
  src/features/ModelSwitchPanel/index.tsx
  src/libs/agent-runtime/anthropic/index.ts
  src/locales/default/components.ts
  src/services/__tests__/chat.test.ts
  src/services/chat.ts
  src/utils/fetch/__tests__/fetchSSE.test.ts
  src/utils/fetch/fetchSSE.ts
Labels: size:M, Build Docker

#6842 ✨ feat: support no-fc models like deepseek r1 with online search
  docs/self-hosting/advanced/auth/clerk.zh-CN.mdx
  docs/self-hosting/server-database/vercel.zh-CN.mdx
  locales/ar/chat.json
  locales/bg-BG/chat.json
  locales/de-DE/chat.json
  locales/en-US/chat.json
  locales/es-ES/chat.json
  locales/fa-IR/chat.json
  locales/fr-FR/chat.json
  locales/it-IT/chat.json
  locales/ja-JP/chat.json
  locales/ko-KR/chat.json
  locales/nl-NL/chat.json
  locales/pl-PL/chat.json
  locales/pt-BR/chat.json
  locales/ru-RU/chat.json
  locales/tr-TR/chat.json
  locales/vi-VN/chat.json
  locales/zh-CN/chat.json
  locales/zh-TW/chat.json
  packages/web-crawler/src/crawler.ts
  src/app/(backend)/webapi/chat/[provider]/route.test.ts
  src/app/(backend)/webapi/chat/[provider]/route.ts
  src/components/CircleLoader/index.tsx
  src/config/tools.ts
  src/const/settings/agent.ts
  src/features/ChatInput/ActionBar/Search/FCSearchModel.tsx
  src/features/ChatInput/ActionBar/Search/FunctionCallingModelSelect/index.tsx
  src/features/ChatInput/ActionBar/Search/SwitchPanel.tsx
  src/features/Conversation/Extras/Usage/UsageDetail/ModelCard.tsx
  src/features/Conversation/Extras/Usage/UsageDetail/pricing.ts
  src/features/Conversation/Extras/Usage/UsageDetail/tokens.test.ts
  src/features/Conversation/Extras/Usage/UsageDetail/tokens.ts
  src/features/Conversation/Messages/Assistant/IntentUnderstanding.tsx
  src/features/Conversation/Messages/Assistant/Tool/Inspector/ToolTitle.tsx
  src/features/Conversation/Messages/Assistant/index.tsx
  src/features/ModelSwitchPanel/index.tsx
  src/hooks/useAgentEnableSearch.ts
  src/locales/default/chat.ts
  src/server/routers/tools/search.ts
  src/services/__tests__/chat.test.ts
  src/services/chat.ts
  src/services/session/type.ts
  src/store/agent/slices/chat/selectors/__snapshots__/agent.test.ts.snap
  src/store/agent/slices/chat/selectors/chatConfig.ts
  src/store/chat/slices/aiChat/actions/__tests__/generateAIChat.test.ts
  src/store/chat/slices/aiChat/actions/generateAIChat.ts
  src/store/chat/slices/aiChat/initialState.ts
  src/store/chat/slices/aiChat/selectors.ts
  src/store/chat/slices/message/action.ts
  src/store/chat/slices/plugin/action.ts
  src/store/user/slices/settings/selectors/__snapshots__/settings.test.ts.snap
  src/types/agent/chatConfig.ts
  src/types/openai/chat.ts
Labels: 🌠 Feature Request, size:L

#6856 🔨 chore: typo fixed for zh-CN
  locales/zh-CN/chat.json
  src/locales/default/chat.ts
Labels: size:XS

#6859 🐛 fix: fix anthropic max tokens
  locales/ar/chat.json
  locales/bg-BG/chat.json
  locales/de-DE/chat.json
  locales/en-US/chat.json
  locales/es-ES/chat.json
  locales/fa-IR/chat.json
  locales/fr-FR/chat.json
  locales/it-IT/chat.json
  locales/ja-JP/chat.json
  locales/ko-KR/chat.json
  locales/nl-NL/chat.json
  locales/pl-PL/chat.json
  locales/pt-BR/chat.json
  locales/ru-RU/chat.json
  locales/tr-TR/chat.json
  locales/vi-VN/chat.json
  locales/zh-CN/chat.json
  locales/zh-TW/chat.json
  src/libs/agent-runtime/anthropic/index.test.ts
  src/libs/agent-runtime/anthropic/index.ts
  src/locales/default/chat.ts
Labels: 🐛 Bug, size:L

#6876 💄 style(spelling): correct "broswer" to "browser" across codebase
  locales/fa-IR/setting.json
  locales/zh-CN/setting.json
  locales/zh-TW/setting.json
  src/config/modelProviders/index.ts
  src/locales/default/setting.ts
  src/store/aiInfra/slices/aiProvider/selectors.ts
  src/store/user/slices/modelList/selectors/modelConfig.test.ts
  src/store/user/slices/modelList/selectors/modelConfig.ts
Labels: size:S

#6886 ♻️ refactor: refactor user plugins model name
  packages/web-crawler/src/crawImpl/naive.ts
  packages/web-crawler/src/urlRules.ts
  src/database/schemas/user.ts
  src/database/server/models/__tests__/plugin.test.ts
  src/database/server/models/plugin.ts
  src/services/plugin/client.test.ts
Labels: plugin, size:L

#6864 💄 style: Support OpenRouter custom BaseURL
  src/config/modelProviders/openrouter.ts
  src/libs/agent-runtime/openrouter/index.test.ts
Labels: 💄 Design, size:S

#6844 🐛 fix: refactor the theme implement
  src/app/[variants]/(main)/(mobile)/me/(home)/features/Header.tsx
  src/app/[variants]/(main)/settings/common/features/Theme/index.tsx
  src/const/settings/common.ts
  src/features/User/UserPanel/ThemeButton.tsx
  src/layout/GlobalProvider/AppTheme.tsx
  src/services/user/_deprecated.test.ts
  src/services/user/client.test.ts
  src/store/global/action.test.ts
  src/store/global/actions/__tests__/general.test.ts
  src/store/global/actions/general.ts
  src/store/global/initialState.ts
  src/store/global/selectors/systemStatus.test.ts
  src/store/global/selectors/systemStatus.ts
  src/store/user/slices/settings/action.test.ts
  src/store/user/slices/settings/action.ts
  src/store/user/slices/settings/selectors/general.test.ts
  src/store/user/slices/settings/selectors/general.ts
  src/types/user/settings/general.ts
Labels: size:XL

#6893 🐛 fix: Link jump in mobile terminal data statistics
  src/app/[variants]/(main)/profile/stats/Client.tsx
  src/app/[variants]/(main)/profile/stats/features/AssistantsRank.tsx
  src/app/[variants]/(main)/profile/stats/features/TopicsRank.tsx
Labels: size:S

#6926 🐛 fix: fix theme flicking
  src/layout/GlobalProvider/AppTheme.tsx
Labels: 🐛 Bug, size:S

#4609 🐛 fix: the agent setting `-edit_agent` not work
  src/features/AgentSetting/AgentMeta/index.tsx
Labels: 🐛 Bug, size:S

#6937 ⚡️ perf: fix improve topic relative performance
  src/database/client/migrations.json
  src/database/migrations/0016_add_message_index.sql
  src/database/migrations/meta/0016_snapshot.json
  src/database/migrations/meta/_journal.json
  src/database/schemas/message.ts
  src/tools/web-browsing/Render/PageContent/index.tsx
  src/tools/web-browsing/Render/Search/SearchResult/SearchResultItem.tsx
Labels: ⚡️ Performance, size:S

#6950 🔨 chore: visualize db schema with dbdocs
  .github/workflows/sync-database-schema.yml
  .npmrc
  docs/developer/database-schema.dbml
  package.json
  scripts/dbmlWorkflow/index.ts
  src/database/client/migrations.json
Labels: size:XL

#6956 ✨ feat: support gemini image output in chat
  locales/ar/models.json
  locales/bg-BG/models.json
  locales/de-DE/models.json
  locales/en-US/models.json
  locales/es-ES/models.json
  locales/fa-IR/models.json
  locales/fr-FR/models.json
  locales/it-IT/models.json
  locales/ja-JP/models.json
  locales/ko-KR/models.json
  locales/nl-NL/models.json
  locales/pl-PL/models.json
  locales/pt-BR/models.json
  locales/ru-RU/models.json
  locales/tr-TR/models.json
  locales/vi-VN/models.json
  locales/zh-CN/models.json
  locales/zh-TW/models.json
  src/config/aiModels/google.ts
  src/database/server/models/message.ts
  src/features/AlertBanner/CloudBanner.tsx
  src/features/Conversation/Messages/Assistant/index.tsx
  src/features/Conversation/Messages/User/index.tsx
  src/libs/agent-runtime/google/index.ts
  src/libs/agent-runtime/utils/streams/google-ai.test.ts
  src/libs/agent-runtime/utils/streams/google-ai.ts
  src/libs/agent-runtime/utils/streams/protocol.ts
  src/services/chat.ts
  src/services/file/client.ts
  src/services/message/server.ts
  src/services/message/type.ts
  src/services/upload.ts
  src/store/chat/slices/aiChat/actions/generateAIChat.ts
  src/store/chat/slices/message/action.ts
  src/store/file/slices/upload/action.ts
  src/store/file/store.ts
  src/types/files/upload.ts
  src/types/message/base.ts
  src/types/message/chat.ts
  src/types/message/image.ts
  src/types/message/index.ts
  src/utils/fetch/fetchSSE.ts
Labels: Gemini, size:L

#6970 🐛 fix: fix google gemini output relative issue
  locales/ar/components.json
  locales/ar/models.json
  locales/bg-BG/components.json
  locales/bg-BG/models.json
  locales/de-DE/components.json
  locales/de-DE/models.json
  locales/en-US/components.json
  locales/en-US/models.json
  locales/es-ES/components.json
  locales/es-ES/models.json
  locales/fa-IR/components.json
  locales/fa-IR/models.json
  locales/fr-FR/components.json
  locales/fr-FR/models.json
  locales/it-IT/components.json
  locales/it-IT/models.json
  locales/ja-JP/components.json
  locales/ja-JP/models.json
  locales/ko-KR/components.json
  locales/ko-KR/models.json
  locales/nl-NL/components.json
  locales/nl-NL/models.json
  locales/pl-PL/components.json
  locales/pl-PL/models.json
  locales/pt-BR/components.json
  locales/pt-BR/models.json
  locales/ru-RU/components.json
  locales/ru-RU/models.json
  locales/tr-TR/components.json
  locales/tr-TR/models.json
  locales/vi-VN/components.json
  locales/vi-VN/models.json
  locales/zh-CN/components.json
  locales/zh-CN/models.json
  locales/zh-TW/components.json
  locales/zh-TW/models.json
  src/components/ModelSelect/index.tsx
  src/config/aiModels/google.ts
  src/config/modelProviders/vertexai.ts
  src/libs/agent-runtime/google/index.ts
  src/libs/agent-runtime/utils/streams/google-ai.test.ts
  src/libs/agent-runtime/utils/streams/google-ai.ts
  src/libs/agent-runtime/utils/streams/index.ts
  src/locales/default/components.ts
  src/types/aiModel.ts
Labels: 🐛 Bug, size:M

#6967 💄 style: Update Vertex AI models
  src/config/aiModels/vertexai.ts
Labels: 💄 Design, size:M

#6984 🐛 fix: fix claude 3.5+ models context max output
  src/libs/agent-runtime/anthropic/index.test.ts
  src/libs/agent-runtime/anthropic/index.ts
Labels: 🐛 Bug, size:S

#7001 🔨 chore: Update github issue template
  .github/ISSUE_TEMPLATE/1_bug_report.yml
  .github/ISSUE_TEMPLATE/1_bug_report_cn.yml
  .github/ISSUE_TEMPLATE/2_feature_request.yml
  .github/ISSUE_TEMPLATE/2_feature_request_cn.yml
Labels: size:S

#6995 💄 style: update Wenxin & Hunyuan model list
  src/config/aiModels/hunyuan.ts
  src/config/aiModels/wenxin.ts
Labels: 💄 Design, size:L

#6275 💄 style: support screenshot to clipboard when sharing
  src/features/ShareModal/ShareImage/index.tsx
  src/hooks/useImgToClipboard.ts
  src/hooks/useScreenshot.ts
Labels: 🌠 Feature Request, size:L

#7022 :card_file_box: feat: update db schema to add `user_id` for data export
  docs/developer/database-schema.dbml
  package.json
  src/database/client/db.ts
  src/database/client/migrations.json
  src/database/migrations/0017_add_user_id_to_tables.sql
  src/database/migrations/meta/0017_snapshot.json
  src/database/migrations/meta/_journal.json
  src/database/models/__tests__/_test_template.ts
  src/database/models/__tests__/_util.ts
  src/database/models/__tests__/agent.test.ts
  src/database/models/__tests__/aiModel.test.ts
  src/database/models/__tests__/aiProvider.test.ts
  src/database/models/__tests__/asyncTask.test.ts
  src/database/models/__tests__/chunk.test.ts
  src/database/models/__tests__/file.test.ts
  src/database/models/__tests__/fixtures/embedding.ts
  src/database/models/__tests__/knowledgeBase.test.ts
  src/database/models/__tests__/message.test.ts
  src/database/models/__tests__/plugin.test.ts
  src/database/models/__tests__/session.test.ts
  src/database/models/__tests__/sessionGroup.test.ts
  src/database/models/__tests__/topic.test.ts
  src/database/repositories/dataImporter/index.ts
  src/database/schemas/file.ts
  src/database/schemas/message.ts
  src/database/schemas/relations.ts
  src/database/server/models/__tests__/nextauth.test.ts
  src/database/server/models/__tests__/user.test.ts
  src/database/server/models/chunk.ts
  src/database/server/models/file.ts
  src/database/server/models/message.ts
  src/database/server/models/session.ts
  src/database/server/models/user.test.ts
  src/services/file/client.test.ts
  src/services/message/client.test.ts
  src/services/session/client.test.ts
  src/types/message/base.ts
  vitest.server.config.ts
Labels: size:XXL, Build Docker

#7007 🐛 fix: Allow historyCount to be set to 0
  src/store/agent/slices/chat/selectors/chatConfig.ts
Labels: 🐛 Bug, size:XS

#6717 📝 docs: fix usage doc for PPIO
  README.md
  docs/usage/providers/ppio.zh-CN.mdx
  locales/en-US/providers.json
  locales/zh-CN/providers.json
  src/config/modelProviders/index.ts
Labels: 📝 Documentation, size:S

#7016 ✨ feat: add Cohere provider support
  Dockerfile
  Dockerfile.database
  Dockerfile.pglite
  src/app/[variants]/(main)/settings/llm/ProviderList/providers.tsx
  src/config/aiModels/cohere.ts
  src/config/aiModels/index.ts
  src/config/llm.ts
  src/config/modelProviders/cohere.ts
  src/config/modelProviders/index.ts
  src/libs/agent-runtime/cohere/index.ts
  src/libs/agent-runtime/runtimeMap.ts
  src/libs/agent-runtime/types/type.ts
  src/types/user/settings/keyVaults.ts
Labels: 🌠 Feature Request, Model Provider, size:L

#7036 ✨ feat: add search1api crawler implementation for WeChat Sogou links
  packages/web-crawler/README.md
  packages/web-crawler/README.zh-CN.md
  packages/web-crawler/src/crawImpl/__tests__/search1api.test.ts
  packages/web-crawler/src/crawImpl/index.ts
  packages/web-crawler/src/crawImpl/naive.ts
  packages/web-crawler/src/crawImpl/search1api.ts
  packages/web-crawler/src/crawler.ts
  packages/web-crawler/src/type.ts
  packages/web-crawler/src/urlRules.ts
  packages/web-crawler/src/utils/withTimeout.ts
Labels: 🌠 Feature Request, size:L

#7050 📝 docs: add proxy URL configurations for Moonshot and Volcengine APIs
  docs/self-hosting/environment-variables/model-provider.mdx
  docs/self-hosting/environment-variables/model-provider.zh-CN.mdx
Labels: 📝 Documentation, size:M

#7069 💄 style: Update shiki to v3
  package.json
Labels: 💄 Design, size:XS

#7064 🔨 chore: Update devcontainer.json
  .devcontainer/devcontainer.json
Labels: size:XS

#7012 ✨ feat: support infini-ai provider
  .env.example
  Dockerfile
  Dockerfile.database
  Dockerfile.pglite
  README.md
  README.zh-CN.md
  docs/self-hosting/environment-variables/model-provider.mdx
  docs/self-hosting/environment-variables/model-provider.zh-CN.mdx
  docs/usage/providers/infiniai.mdx
  docs/usage/providers/infiniai.zh-CN.mdx
  locales/ar/models.json
  locales/ar/providers.json
  locales/bg-BG/models.json
  locales/bg-BG/providers.json
  locales/de-DE/models.json
  locales/de-DE/providers.json
  locales/en-US/models.json
  locales/en-US/providers.json
  locales/es-ES/models.json
  locales/es-ES/providers.json
  locales/fa-IR/models.json
  locales/fa-IR/providers.json
  locales/fr-FR/models.json
  locales/fr-FR/providers.json
  locales/it-IT/models.json
  locales/it-IT/providers.json
  locales/ja-JP/models.json
  locales/ja-JP/providers.json
  locales/ko-KR/models.json
  locales/ko-KR/providers.json
  locales/nl-NL/models.json
  locales/nl-NL/providers.json
  locales/pl-PL/models.json
  locales/pl-PL/providers.json
  locales/pt-BR/models.json
  locales/pt-BR/providers.json
  locales/ru-RU/models.json
  locales/ru-RU/providers.json
  locales/tr-TR/models.json
  locales/tr-TR/providers.json
  locales/vi-VN/models.json
  locales/vi-VN/providers.json
  locales/zh-CN/models.json
  locales/zh-CN/providers.json
  locales/zh-TW/models.json
  locales/zh-TW/providers.json
  src/app/[variants]/(main)/settings/llm/ProviderList/providers.tsx
  src/config/aiModels/index.ts
  src/config/aiModels/infiniai.ts
  src/config/llm.ts
  src/config/modelProviders/index.ts
  src/config/modelProviders/infiniai.ts
  src/libs/agent-runtime/infiniai/index.ts
  src/libs/agent-runtime/runtimeMap.ts
  src/libs/agent-runtime/types/type.ts
  src/types/user/settings/keyVaults.ts
Labels: Model Provider, size:L

#6376 ✨ feat: add Search1API provider with web search DeepSeek models
  Dockerfile
  Dockerfile.database
  src/app/[variants]/(main)/settings/llm/ProviderList/providers.tsx
  src/config/aiModels/index.ts
  src/config/aiModels/search1api.ts
  src/config/llm.ts
  src/config/modelProviders/index.ts
  src/config/modelProviders/search1api.ts
  src/libs/agent-runtime/search1api/index.ts
  src/libs/agent-runtime/types/type.ts
  src/types/user/settings/keyVaults.ts
Labels: 🌠 Feature Request, size:L

#7062 ⚡️ perf: enable smoothing for all providers
  package.json
  packages/web-crawler/src/utils/htmlToMarkdown.test.ts
  src/database/models/__tests__/knowledgeBase.test.ts
  src/libs/agent-runtime/ai21/index.test.ts
  src/libs/agent-runtime/ai360/index.test.ts
  src/libs/agent-runtime/anthropic/index.ts
  src/libs/agent-runtime/deepseek/index.test.ts
  src/libs/agent-runtime/fireworksai/index.test.ts
  src/libs/agent-runtime/giteeai/index.test.ts
  src/libs/agent-runtime/github/index.test.ts
  src/libs/agent-runtime/internlm/index.test.ts
  src/libs/agent-runtime/lmstudio/index.test.ts
  src/libs/agent-runtime/moonshot/index.test.ts
  src/libs/agent-runtime/novita/index.test.ts
  src/libs/agent-runtime/ollama/index.test.ts
  src/libs/agent-runtime/openrouter/index.test.ts
  src/libs/agent-runtime/ppio/index.test.ts
  src/libs/agent-runtime/providerTestUtils.ts
  src/libs/agent-runtime/qwen/index.test.ts
  src/libs/agent-runtime/sensenova/index.test.ts
  src/libs/agent-runtime/spark/index.test.ts
  src/libs/agent-runtime/stepfun/index.test.ts
  src/libs/agent-runtime/taichu/index.test.ts
  src/libs/agent-runtime/upstage/index.test.ts
  src/libs/agent-runtime/utils/openaiCompatibleFactory/index.test.ts
  src/libs/agent-runtime/xai/index.test.ts
  src/services/chat.ts
  src/utils/fetch/__tests__/parseToolCalls.test.ts
  src/utils/server/jwt.test.ts
  vitest.server.config.ts
Labels: ⚡️ Performance, size:XXL

#7085 💄 style: fix `deepseek-r1-70b-online` search tag missing from Search1API
  src/config/aiModels/search1api.ts
Labels: 💄 Design, size:XS

#7095 📝 docs: fix the display problem caused by merging
  docs/self-hosting/environment-variables/model-provider.mdx
  docs/self-hosting/environment-variables/model-provider.zh-CN.mdx
Labels: 📝 Documentation, size:M

#7094 🐛 fix: update input and output prices
  src/config/aiModels/qwen.ts
  src/config/aiModels/volcengine.ts
Labels: 🐛 Bug, size:S

#7083 🐛 fix: checkModel change clears other configs
  src/app/[variants]/(main)/settings/provider/features/ProviderConfig/Checker.tsx
Labels: 🐛 Bug, size:XS

#7087 💄 style: Clear previous model check result
  src/app/[variants]/(main)/settings/provider/features/ProviderConfig/Checker.tsx
Labels: 💄 Design, size:XS

#7105 🐛 fix: upgrade next to 15.2.3 to fix CVE-2025-29927
  package.json
  packages/web-crawler/src/utils/html/yingchao.html
  packages/web-crawler/src/utils/htmlToMarkdown.test.ts
  src/app/(backend)/webapi/plugin/store/route.ts
Labels: 🐛 Bug, size:S

#6585 🐛 fix: fix wechat login error with next-auth
  src/libs/next-auth/sso-providers/wechat.ts
Labels: 🐛 Bug, size:S

#7114 🐛 fix: set max_completion_tokens to undefined for Azure OpenAI
  src/libs/agent-runtime/azureOpenai/index.ts
Labels: 🐛 Bug, size:XS

#7124 🔨 chore: upgrade antd version
  package.json
Labels: size:XS

#6996 ♻️ refactor: Add reject pattern for browserless to boost crawl performance
  packages/web-crawler/src/crawImpl/browserless.ts
Labels: ⚡️ Performance, size:XS

#7123 💄 style: add `hunyuan-t1-latest` from Hunyuan
  src/config/aiModels/hunyuan.ts
  src/libs/agent-runtime/hunyuan/index.ts
Labels: 💄 Design, size:M

#7141 ♻️ refactor: upgrade styles for Drawer
  src/app/[variants]/(main)/settings/_layout/Desktop/Header.tsx
Labels: size:S

#7153 💄 style: Add Gemini 2.5 Pro Experimental model
  locales/ar/models.json
  locales/bg-BG/models.json
  locales/de-DE/models.json
  locales/en-US/models.json
  locales/es-ES/models.json
  locales/fa-IR/models.json
  locales/fr-FR/models.json
  locales/it-IT/models.json
  locales/ja-JP/models.json
  locales/ko-KR/models.json
  locales/nl-NL/models.json
  locales/pl-PL/models.json
  locales/pt-BR/models.json
  locales/ru-RU/models.json
  locales/tr-TR/models.json
  locales/vi-VN/models.json
  locales/zh-CN/models.json
  locales/zh-TW/models.json
  src/config/aiModels/google.ts
Labels: Gemini, size:L

#7081 ✨ feat: add Xinference provider support
  Dockerfile
  Dockerfile.database
  Dockerfile.pglite
  src/app/[variants]/(main)/settings/llm/ProviderList/providers.tsx
  src/config/aiModels/index.ts
  src/config/aiModels/xinference.ts
  src/config/llm.ts
  src/config/modelProviders/index.ts
  src/config/modelProviders/xinference.ts
  src/libs/agent-runtime/runtimeMap.ts
  src/libs/agent-runtime/types/type.ts
  src/libs/agent-runtime/xinference/index.ts
  src/types/user/settings/keyVaults.ts
Labels: 🌠 Feature Request, Model Provider, size:L

#7149 💄 style: improve editing scroll experience
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatList/ChatItem/index.tsx
  src/features/Conversation/components/ChatItem/ActionsBar.tsx
  src/features/Conversation/components/ChatItem/index.tsx
  src/features/Conversation/components/VirtualizedList/VirtuosoContext.ts
  src/features/Conversation/components/VirtualizedList/index.tsx
  src/features/Portal/Thread/Chat/ChatItem.tsx
Labels: 💄 Design, size:M

#7056 ✨ feat: add reasoning content selector and update AutoScroll component
  src/features/Conversation/components/AutoScroll.tsx
  src/store/chat/slices/message/selectors.test.ts
  src/store/chat/slices/message/selectors.ts
Labels: 🌠 Feature Request, size:M

#7072 💄 style: Update siliconcloud models
  src/config/aiModels/google.ts
  src/config/aiModels/novita.ts
  src/config/aiModels/siliconcloud.ts
  src/config/aiModels/volcengine.ts
Labels: 💄 Design, size:L

#7156 🐛 fix: Update 'gemini-2.5-pro-exp-03-25' maxOutput and contextWindowTokens
  src/config/aiModels/google.ts
Labels: 🐛 Bug, size:XS

#7155 🐛 fix: fix anthropic import issue
  package.json
Labels: 🐛 Bug, size:S

#7164 💄 style: Update models info
  src/config/aiModels/google.ts
  src/config/aiModels/qwen.ts
  src/config/aiModels/siliconcloud.ts
  src/config/aiModels/vertexai.ts
  src/config/aiModels/volcengine.ts
Labels: 💄 Design, size:L

#7204 📝 docs: update copyright date
  README.md
  README.zh-CN.md
Labels: 📝 Documentation, size:XS

#7182 💄 style: Add tencentcloud deepseek-v3-0324
  src/config/aiModels/tencentcloud.ts
Labels: 🌠 Feature Request, size:S

#7140 💄 style: support for parsing `imageOutput`
  docs/self-hosting/advanced/model-list.mdx
  docs/self-hosting/advanced/model-list.zh-CN.mdx
  src/utils/parseModels.test.ts
  src/utils/parseModels.ts
Labels: 🌠 Feature Request, size:M

#7197 💄 style: update models for siliconcloud & infiniai
  docs/usage/providers/infiniai.zh-CN.mdx
  locales/ar/models.json
  locales/ar/providers.json
  locales/bg-BG/models.json
  locales/bg-BG/providers.json
  locales/de-DE/models.json
  locales/de-DE/providers.json
  locales/en-US/models.json
  locales/en-US/providers.json
  locales/es-ES/models.json
  locales/es-ES/providers.json
  locales/fa-IR/models.json
  locales/fa-IR/providers.json
  locales/fr-FR/models.json
  locales/fr-FR/providers.json
  locales/it-IT/models.json
  locales/it-IT/providers.json
  locales/ja-JP/models.json
  locales/ja-JP/providers.json
  locales/ko-KR/models.json
  locales/ko-KR/providers.json
  locales/nl-NL/models.json
  locales/nl-NL/providers.json
  locales/pl-PL/models.json
  locales/pl-PL/providers.json
  locales/pt-BR/models.json
  locales/pt-BR/providers.json
  locales/ru-RU/models.json
  locales/ru-RU/providers.json
  locales/tr-TR/models.json
  locales/tr-TR/providers.json
  locales/vi-VN/models.json
  locales/vi-VN/providers.json
  locales/zh-CN/models.json
  locales/zh-CN/providers.json
  locales/zh-TW/models.json
  locales/zh-TW/providers.json
  src/config/aiModels/infiniai.ts
  src/config/aiModels/siliconcloud.ts
  src/libs/agent-runtime/infiniai/index.ts
  src/utils/format.ts
Labels: 💄 Design, 📝 Documentation, size:XXL

#7175 🐛 fix: Add the FEATURE_FLAGS variable in the dockerfile
  Dockerfile
  Dockerfile.database
  Dockerfile.pglite
Labels: 🐛 Bug, size:S

#7213 💄 style: Supports OpenAI's latest voice model gpt-4o-mini-tts
  locales/ar/models.json
  locales/bg-BG/models.json
  locales/de-DE/models.json
  locales/en-US/models.json
  locales/es-ES/models.json
  locales/fa-IR/models.json
  locales/fr-FR/models.json
  locales/it-IT/models.json
  locales/ja-JP/models.json
  locales/ko-KR/models.json
  locales/nl-NL/models.json
  locales/pl-PL/models.json
  locales/pt-BR/models.json
  locales/ru-RU/models.json
  locales/tr-TR/models.json
  locales/vi-VN/models.json
  locales/zh-CN/models.json
  locales/zh-TW/models.json
  src/app/[variants]/(main)/settings/tts/features/const.tsx
  src/config/aiModels/openai.ts
  src/types/user/settings/tts.ts
Labels: 🌠 Feature Request, size:M

#7219 🐛 fix: fix export button and clean orphan agent
  locales/ar/common.json
  locales/bg-BG/common.json
  locales/de-DE/common.json
  locales/en-US/common.json
  locales/es-ES/common.json
  locales/fa-IR/common.json
  locales/fr-FR/common.json
  locales/it-IT/common.json
  locales/ja-JP/common.json
  locales/ko-KR/common.json
  locales/nl-NL/common.json
  locales/pl-PL/common.json
  locales/pt-BR/common.json
  locales/ru-RU/common.json
  locales/tr-TR/common.json
  locales/vi-VN/common.json
  locales/zh-CN/common.json
  locales/zh-CN/models.json
  locales/zh-TW/common.json
  src/app/[variants]/(main)/(mobile)/me/data/features/Category.tsx
  src/app/[variants]/(main)/settings/storage/Advanced.tsx
  src/database/models/__tests__/session.test.ts
  src/database/server/models/session.ts
  src/features/User/UserPanel/useMenu.tsx
  src/locales/default/common.ts
Labels: 🐛 Bug, size:L

#7220 🐛 fix: fix decrypt error with imported pg data
  src/database/server/models/aiProvider.ts
Labels: 🐛 Bug, size:S

#7237 📝 docs: update example model names in documentation
  docs/self-hosting/environment-variables/model-provider.mdx
  docs/self-hosting/environment-variables/model-provider.zh-CN.mdx
Labels: 📝 Documentation, size:XS

#7246 🔨 chore: add electron server ipc
  packages/electron-server-ipc/README.md
  packages/electron-server-ipc/package.json
  packages/electron-server-ipc/src/const.ts
  packages/electron-server-ipc/src/index.ts
  packages/electron-server-ipc/src/ipcClient.test.ts
  packages/electron-server-ipc/src/ipcClient.ts
  packages/electron-server-ipc/src/ipcServer.ts
  packages/electron-server-ipc/src/types/event.ts
  packages/electron-server-ipc/src/types/index.ts
Labels: size:XL

#7224 💄 style: update branding
  src/components/Branding/ProductLogo/index.tsx
Labels: 💄 Design, size:XS

#7245 ♻️ refactor: refactor db core
  scripts/migrateServerDB/index.ts
  src/database/core/db-adaptor.ts
  src/database/core/dbForTest.ts
  src/database/core/web-server.ts
  src/database/models/__tests__/_test_template.ts
  src/database/models/__tests__/_util.ts
  src/database/models/__tests__/session.test.ts
  src/database/repositories/dataImporter/deprecated/__tests__/index.test.ts
  src/database/server/index.ts
  src/database/server/models/__tests__/nextauth.test.ts
  src/database/server/models/__tests__/user.test.ts
Labels: size:M
