Repository lobehub/lobe-chat, pull requests merged in 2025-10, with the labels that each got.

#9474 ♻️ refactor: refactor a `ssrf-safe-fetch` module
  package.json
  packages/ssrf-safe-fetch/index.test.ts
  packages/ssrf-safe-fetch/index.ts
  packages/ssrf-safe-fetch/package.json
  packages/ssrf-safe-fetch/vitest.config.mts
  src/app/(backend)/webapi/proxy/route.ts
Labels: 🐛 Bug, size:L

#9481 🐛 fix: OllamaCloud error
  packages/model-bank/src/aiModels/aihubmix.ts
  packages/model-bank/src/aiModels/anthropic.ts
  packages/model-bank/src/aiModels/novita.ts
  packages/model-bank/src/aiModels/qwen.ts
  packages/model-bank/src/aiModels/zhipu.ts
  packages/model-runtime/src/providers/anthropic/index.test.ts
  packages/model-runtime/src/providers/novita/index.ts
  packages/model-runtime/src/providers/novita/type.ts
  packages/model-runtime/src/providers/ollamacloud/index.ts
  packages/model-runtime/src/providers/openrouter/index.ts
  src/config/modelProviders/anthropic.ts
  src/config/modelProviders/ollamacloud.ts
  src/config/modelProviders/zhipu.ts
Labels: ollama, size:XL

#9507 💄 style: fix chat Minimap overflow
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatMinimap/index.tsx
  src/features/Conversation/components/WideScreenContainer/index.tsx
Labels: 🐛 Bug, size:M

#9511 🔨 chore: improve github workflow
  .github/workflows/claude-translator.yml
  .github/workflows/issue-auto-comments.yml
  .github/workflows/issue-close-require.yml
  packages/utils/package.json
Labels: size:S

#9528 💄 style: nano banana support `aspect_ratio`
  packages/model-bank/src/aiModels/google.ts
  packages/model-runtime/src/providers/google/createImage.ts
Labels: 💄 Design, size:M

#9529 💄 style: Allow switching model `type`
  packages/database/src/repositories/aiInfra/index.ts
  packages/model-bank/src/types/aiModel.ts
  src/app/[variants]/(main)/settings/provider/features/ModelList/CreateNewModelModal/Form.tsx
  src/locales/default/modelProvider.ts
  src/store/aiInfra/slices/aiProvider/action.ts
Labels: 💄 Design, size:M

#9561 🐛 fix: type not preserved when model is sorted
  packages/database/src/models/__tests__/aiModel.test.ts
  packages/database/src/models/aiModel.ts
  packages/model-bank/src/types/aiModel.ts
  packages/model-runtime/src/providers/google/index.ts
  src/app/[variants]/(main)/settings/provider/features/ModelList/SortModelModal/index.tsx
  src/server/routers/lambda/aiModel.ts
Labels: 🐛 Bug, size:M

#9568 💄 style: add promptfoo to improve prompts quality
  package.json
  packages/prompts/.gitignore
  packages/prompts/CLAUDE.md
  packages/prompts/README.md
  packages/prompts/package.json
  packages/prompts/promptfoo/emoji-picker/eval.yaml
  packages/prompts/promptfoo/emoji-picker/prompt.ts
  packages/prompts/promptfoo/knowledge-qa/eval.yaml
  packages/prompts/promptfoo/knowledge-qa/prompt.ts
  packages/prompts/promptfoo/language-detection/eval.yaml
  packages/prompts/promptfoo/language-detection/prompt.ts
  packages/prompts/promptfoo/summary-title/eval.yaml
  packages/prompts/promptfoo/summary-title/prompt.ts
  packages/prompts/promptfoo/translate/eval.yaml
  packages/prompts/promptfoo/translate/prompt.ts
  packages/prompts/promptfooconfig.yaml
  packages/prompts/src/chains/__tests__/__snapshots__/answerWithContext.test.ts.snap
  packages/prompts/src/chains/__tests__/__snapshots__/pickEmoji.test.ts.snap
  packages/prompts/src/chains/__tests__/__snapshots__/summaryTitle.test.ts.snap
  packages/prompts/src/chains/__tests__/__snapshots__/translate.test.ts.snap
  packages/prompts/src/chains/__tests__/answerWithContext.test.ts
  packages/prompts/src/chains/__tests__/pickEmoji.test.ts
  packages/prompts/src/chains/__tests__/summaryTitle.test.ts
  packages/prompts/src/chains/__tests__/translate.test.ts
  packages/prompts/src/chains/answerWithContext.ts
  packages/prompts/src/chains/pickEmoji.ts
  packages/prompts/src/chains/summaryTitle.ts
  packages/prompts/src/chains/translate.ts
Labels: size:XXL

#9491 🐛 fix(database): prevent empty array insertion in aiModel batch operations
  packages/database/src/models/__tests__/aiModel.test.ts
  packages/database/src/models/aiModel.ts
Labels: 🐛 Bug, size:M

#9543 🔨 chore: add group-messages database schema
  docs/development/database-schema.dbml
  packages/database/migrations/0036_add_group_messages.sql
  packages/database/migrations/meta/0036_snapshot.json
  packages/database/migrations/meta/_journal.json
  packages/database/package.json
  packages/database/src/core/migrations.json
  packages/database/src/repositories/tableViewer/index.test.ts
  packages/database/src/schemas/_helpers.ts
  packages/database/src/schemas/message.ts
  packages/database/src/schemas/relations.ts
  packages/database/src/utils/idGenerator.ts
Labels: size:L

#9576 👷 build: fix docker build
  package.json
Labels: size:XS

#9581 📝 docs: update Zustand import syntax for v5 compatibility
  docs/development/basic/feature-development-frontend.zh-CN.mdx
Labels: 📝 Documentation, size:XS, lgtm

#9582 📝 docs: update app directory structure documentation
  docs/development/basic/folder-structure.mdx
  docs/development/basic/folder-structure.zh-CN.mdx
Labels: 📝 Documentation, size:L

#9589 ✨ feat: huanyuan text-to-image 3
  locales/ar/models.json
  locales/bg-BG/models.json
  locales/de-DE/models.json
  locales/en-US/models.json
  locales/es-ES/models.json
  locales/fa-IR/models.json
  locales/fr-FR/models.json
  locales/it-IT/models.json
  locales/ja-JP/models.json
  locales/ko-KR/models.json
  locales/nl-NL/models.json
  locales/pl-PL/models.json
  locales/pt-BR/models.json
  locales/ru-RU/models.json
  locales/tr-TR/models.json
  locales/vi-VN/models.json
  locales/zh-CN/models.json
  locales/zh-TW/models.json
  packages/model-bank/src/aiModels/fal.ts
  packages/model-runtime/src/providers/fal/index.ts
  src/app/[variants]/(main)/image/@menu/components/SizeSelect/index.tsx
  src/server/modules/EdgeConfig/index.ts
  src/server/modules/EdgeConfig/types.ts
Labels: 🌠 Feature Request, size:L

#9592 💄 style(image): optimize UX and fix fal pricing
  packages/model-bank/src/aiModels/fal.ts
  src/app/[variants]/(main)/image/@menu/features/ConfigPanel/components/ImageConfigSkeleton.tsx
Labels: 💄 Design, size:M

#9597 💄 style: improve Korean translate
  .i18nrc.js
  locales/ko-KR/auth.json
  locales/ko-KR/changelog.json
  locales/ko-KR/chat.json
  locales/ko-KR/clerk.json
  locales/ko-KR/color.json
  locales/ko-KR/common.json
  locales/ko-KR/components.json
  locales/ko-KR/discover.json
  locales/ko-KR/editor.json
  locales/ko-KR/file.json
  locales/ko-KR/hotkey.json
  locales/ko-KR/image.json
  locales/ko-KR/knowledgeBase.json
  locales/ko-KR/market.json
  locales/ko-KR/metadata.json
  locales/ko-KR/migration.json
  locales/ko-KR/modelProvider.json
  locales/ko-KR/oauth.json
  locales/ko-KR/plugin.json
  locales/ko-KR/portal.json
  locales/ko-KR/providers.json
  locales/ko-KR/ragEval.json
  locales/ko-KR/setting.json
  locales/ko-KR/subscription.json
  locales/ko-KR/thread.json
  locales/ko-KR/tool.json
  locales/ko-KR/welcome.json
  packages/prompts/promptfoo/summary-title/eval.yaml
Labels: 💄 Design, size:XXL

#9594 💄 style: Add GPT-5 pro model
  packages/model-bank/src/aiModels/aihubmix.ts
  packages/model-bank/src/aiModels/nvidia.ts
  packages/model-bank/src/aiModels/openai.ts
  packages/model-runtime/src/const/models.ts
  packages/model-runtime/src/providers/openai/index.ts
  packages/model-runtime/src/providers/openrouter/index.ts
  packages/model-runtime/src/providers/openrouter/type.ts
  packages/model-runtime/src/providers/vercelaigateway/index.ts
  packages/model-runtime/src/utils/modelParse.ts
Labels: Model Provider, size:L
