Repository lobehub/lobe-chat, pull requests merged in 2025-07, with the labels that each got.

#8331 ⚡️ build: integrate tsgo to validate ts
  apps/desktop/package.json
  package.json
  scripts/migrateServerDB/index.ts
  src/app/[variants]/(main)/chat/(workspace)/@conversation/features/ChatInput/Mobile/index.tsx
  src/server/modules/ContentChunk/index.ts
  src/tools/local-system/Render/index.tsx
Labels: size:S

#8338 📝 docs: add some cursor rules
  .cursor/rules/backend-architecture.mdc
  .cursor/rules/code-review.mdc
  .cursor/rules/cursor-rules.mdc
  .cursor/rules/cursor-ux-optimize.mdc
  .cursor/rules/cursor-ux.mdc
  .cursor/rules/debug.mdc
  .cursor/rules/i18n/i18n.mdc
  .cursor/rules/packages/lobe-ui.mdc
  .cursor/rules/packages/react-layout-kit.mdc
  .cursor/rules/react-component.mdc
  .cursor/rules/rules-attach.mdc
  .cursor/rules/system-role.mdc
  .cursor/rules/testing-guide.mdc
  .cursor/rules/typescript.mdc
  .cursor/rules/zustand-action-patterns.mdc
  .cursor/rules/zustand-slice-organization.mdc
Labels: 📝 Documentation, size:XXL

#8340 💄 style: files hello pages should scroll
  src/app/[variants]/(main)/files/(content)/NotSupportClient.tsx
Labels: 🐛 Bug, size:XS

#8339 🐛 fix: change the wrong github checkmodel name
  src/config/modelProviders/github.ts
Labels: 🐛 Bug, size:XS

#8354 🐛 fix: pin `officeparser@5.1.1` to fix server error
  package.json
  packages/file-loaders/package.json
Labels: size:XS

#8374 🔨 chore: remove async router max duration limit
  src/app/(backend)/trpc/async/[trpc]/route.ts
  src/server/routers/async/caller.ts
Labels: size:S

#8365 🐛 fix: fix locale hydration error in SSR
  README.md
  README.zh-CN.md
  docs/usage/features/desktop.mdx
  docs/usage/features/desktop.zh-CN.mdx
  docs/usage/features/mcp-market.mdx
  docs/usage/features/mcp-market.zh-CN.mdx
  docs/usage/features/mcp.mdx
  docs/usage/features/mcp.zh-CN.mdx
  docs/usage/features/search.mdx
  docs/usage/features/search.zh-CN.mdx
  package.json
  src/layout/GlobalProvider/Locale.tsx
  src/locales/create.ts
  src/utils/locale.ts
Labels: size:XL

#8352 💄 style: implement data analytics event tracking framework
  package.json
  src/app/[variants]/(main)/chat/(workspace)/_layout/Desktop/index.tsx
  src/app/[variants]/(main)/chat/(workspace)/_layout/Mobile/index.tsx
  src/app/[variants]/(main)/chat/@session/features/SessionListContent/List/index.tsx
  src/components/Analytics/LobeAnalyticsProvider.tsx
  src/components/Analytics/LobeAnalyticsProviderWrapper.tsx
  src/components/Analytics/MainInterfaceTracker.tsx
  src/components/Analytics/index.tsx
  src/const/analytics.ts
  src/features/AgentSetting/store/action.ts
  src/features/ChatInput/useSend.ts
  src/features/User/UserLoginOrSignup/Community.tsx
  src/layout/GlobalProvider/index.tsx
  src/libs/analytics/index.ts
  src/server/services/user/index.test.ts
  src/server/services/user/index.ts
  src/store/session/slices/session/action.ts
  src/store/user/slices/common/action.ts
  tests/setup.ts
Labels: 🌠 Feature Request, size:L

#8378 👷 build: pin minio version
  docker-compose/local/docker-compose.yml
  docker-compose/local/logto/docker-compose.yml
  docker-compose/local/zitadel/docker-compose.yml
  docker-compose/production/logto/docker-compose.yml
  docker-compose/production/zitadel/docker-compose.yml
  docs/self-hosting/server-database/docker-compose.mdx
Labels: size:S

#8379 💄 style: add `grok-4-0709` model from xAI
  src/config/aiModels/xai.ts
  src/libs/model-runtime/xai/index.ts
Labels: size:M

#8313 💄 style: add google search grounding for Vertex AI
  src/config/aiModels/vertexai.ts
  src/libs/model-runtime/utils/streams/google-ai.test.ts
  src/libs/model-runtime/utils/streams/google-ai.ts
  src/libs/model-runtime/utils/streams/vertex-ai.ts
Labels: 🌠 Feature Request, size:M

#6698 🔨 chore: Add Codecov Bundle Analysis
  .github/workflows/bundle-analysis.yml
  codecov.yml
  next.config.ts
  package.json
Labels: 🌠 Feature Request, size:M

#8384 🔨 chore: revert "Add Codecov Bundle Analysis"
  .github/workflows/bundle-analysis.yml
  codecov.yml
  next.config.ts
  package.json
Labels: size:M

#7472 💄 style: integrate Amazon Cognito for user authentication
  src/libs/next-auth/sso-providers/cognito.ts
  src/libs/next-auth/sso-providers/index.ts
Labels: 🌠 Feature Request, size:S

#8390 🐛 fix: Grok-4 reasoning model universal matching
  src/config/aiModels/xai.ts
  src/libs/model-runtime/xai/index.ts
Labels: size:S

#8174 💄 style: Support new Doubao thinking models
  locales/ar/chat.json
  locales/ar/models.json
  locales/bg-BG/chat.json
  locales/bg-BG/models.json
  locales/de-DE/chat.json
  locales/de-DE/models.json
  locales/en-US/chat.json
  locales/en-US/models.json
  locales/es-ES/chat.json
  locales/es-ES/models.json
  locales/fa-IR/chat.json
  locales/fa-IR/models.json
  locales/fr-FR/chat.json
  locales/fr-FR/models.json
  locales/it-IT/chat.json
  locales/it-IT/models.json
  locales/ja-JP/chat.json
  locales/ja-JP/models.json
  locales/ko-KR/chat.json
  locales/ko-KR/models.json
  locales/nl-NL/chat.json
  locales/nl-NL/models.json
  locales/pl-PL/chat.json
  locales/pl-PL/models.json
  locales/pt-BR/chat.json
  locales/pt-BR/models.json
  locales/ru-RU/chat.json
  locales/ru-RU/models.json
  locales/tr-TR/chat.json
  locales/tr-TR/models.json
  locales/vi-VN/chat.json
  locales/vi-VN/models.json
  locales/zh-CN/chat.json
  locales/zh-TW/chat.json
  src/config/aiModels/google.ts
  src/config/aiModels/openai.ts
  src/config/aiModels/volcengine.ts
  src/features/ChatInput/ActionBar/Model/ControlsForm.tsx
  src/features/ChatInput/ActionBar/Model/ThinkingSlider.tsx
  src/libs/model-runtime/volcengine/index.ts
  src/locales/default/chat.ts
  src/services/chat.ts
  src/types/agent/chatConfig.ts
  src/types/aiModel.ts
Labels: size:L

#8402 🐛 fix: Revert "💄 style: Open new topic by tap Just Chat again"
  src/app/[variants]/(main)/chat/@session/features/SessionListContent/Inbox/index.tsx
  src/store/chat/slices/message/selectors.ts
Labels: 🐛 Bug, size:S

#8401 💄 style: Add Kimi K2 model
  src/config/aiModels/moonshot.ts
Labels: size:S

#8407 🔨 chore: fix lint
  package.json
Labels: size:XS

#8386 🐛 fix: add vision support to Grok 4
  src/config/aiModels/xai.ts
Labels: 🌠 Feature Request, vision, size:XS

#8278 💄 style: Support Hunyuan A13B thinking model
  src/config/aiModels/google.ts
  src/config/aiModels/groq.ts
  src/config/aiModels/hunyuan.ts
  src/config/aiModels/novita.ts
  src/config/aiModels/qwen.ts
  src/config/aiModels/siliconcloud.ts
  src/config/aiModels/zhipu.ts
  src/config/modelProviders/zhipu.ts
  src/libs/model-runtime/hunyuan/index.ts
Labels: size:XL

#8414 🔨 chore: fix settings in desktop
  apps/desktop/src/main/appBrowsers.ts
Labels: size:XS

#8423 💄 style: fix discover translation
  src/app/[variants]/(main)/discover/(list)/(home)/page.tsx
Labels: 🐛 Bug, size:XS

#8431 ⚡️ perf: improve memory usage in desktop
  apps/desktop/src/main/appBrowsers.ts
  apps/desktop/src/main/core/BrowserManager.ts
Labels: ⚡️ Performance, size:XS, Build Desktop

#8441 🐛 fix: fix page error when url is not defined in web search plugin
  src/tools/web-browsing/Render/PageContent/index.tsx
Labels: size:XS

#8479 🐛 fix: fix webapi proxy with clerk
  src/app/(backend)/middleware/auth/index.ts
  src/const/auth.ts
  src/libs/oidc-provider/jwt.ts
  src/libs/trpc/lambda/context.ts
Labels: 🐛 Bug, size:M

#8486 ✨ feat: add zhipu cogview4
  locales/ar/models.json
  locales/bg-BG/models.json
  locales/de-DE/models.json
  locales/en-US/models.json
  locales/es-ES/models.json
  locales/fa-IR/models.json
  locales/fr-FR/models.json
  locales/it-IT/models.json
  locales/ja-JP/models.json
  locales/ko-KR/models.json
  locales/nl-NL/models.json
  locales/pl-PL/models.json
  locales/pt-BR/models.json
  locales/ru-RU/models.json
  locales/tr-TR/models.json
  locales/vi-VN/models.json
  locales/zh-CN/models.json
  locales/zh-TW/models.json
  src/config/aiModels/zhipu.ts
Labels: 🌠 Feature Request, size:M

#8508 💄 style: fix lobehub provider /chat in desktop
  src/config/aiModels/index.ts
  src/config/aiModels/lobehub.ts
  src/config/modelProviders/index.ts
  src/config/modelProviders/lobehub.ts
  src/features/ModelSwitchPanel/index.tsx
  src/libs/model-runtime/types/type.ts
Labels: size:M

#8511 🔨 chore: fix model runtime test issue
  src/libs/model-runtime/ModelRuntime.test.ts
Labels: size:XS

#8514 💄 style: modal list header sticky style
  src/app/[variants]/(main)/settings/provider/features/ModelList/ModelTitle/index.tsx
Labels: 💄 Design, size:XS

#8510 🐛 fix(groq): Enable streaming for tool calls and add Kimi K2 model
  src/config/aiModels/groq.ts
  src/libs/model-runtime/groq/index.test.ts
  src/libs/model-runtime/groq/index.ts
Labels: 🌠 Feature Request, size:M

#8526 👷 build: add default app url for docker image to avoid building error
  Dockerfile.pglite
Labels: size:XS

#8528 ♻️ refactor: add badge and improve document
  apps/desktop/README.md
  apps/desktop/README.zh-CN.md
  apps/desktop/package.json
  apps/desktop/resources/tray-dark.png
  apps/desktop/resources/tray-icon.png
  apps/desktop/resources/tray-light.png
  apps/desktop/resources/tray.png
  apps/desktop/src/main/const/env.ts
  apps/desktop/src/main/core/TrayManager.ts
  locales/ar/subscription.json
  locales/bg-BG/subscription.json
  locales/de-DE/subscription.json
  locales/en-US/subscription.json
  locales/es-ES/subscription.json
  locales/fa-IR/subscription.json
  locales/fr-FR/subscription.json
  locales/it-IT/subscription.json
  locales/ja-JP/subscription.json
  locales/ko-KR/subscription.json
  locales/nl-NL/subscription.json
  locales/pl-PL/subscription.json
  locales/pt-BR/subscription.json
  locales/ru-RU/subscription.json
  locales/tr-TR/subscription.json
  locales/vi-VN/subscription.json
  locales/zh-CN/subscription.json
  locales/zh-TW/subscription.json
  packages/electron-client-ipc/README.md
  packages/electron-client-ipc/README.zh-CN.md
  packages/electron-server-ipc/README.md
  packages/electron-server-ipc/README.zh-CN.md
  packages/file-loaders/README.md
  packages/file-loaders/README.zh-CN.md
  src/app/[variants]/(main)/chat/(workspace)/_layout/Desktop/ChatHeader/HeaderAction.tsx
  src/app/[variants]/(main)/chat/(workspace)/features/SettingButton.tsx
  src/app/[variants]/(main)/chat/(workspace)/features/ShareButton/index.tsx
  src/app/[variants]/(main)/chat/@session/_layout/Desktop/SessionHeader.tsx
  src/features/PlanIcon/index.tsx
  src/features/User/PlanTag.tsx
  src/locales/default/index.ts
  src/locales/default/subscription.ts
  src/types/subscription.ts
Labels: 💄 Design, 📝 Documentation, size:XXL

#8545 💄 style: Add cached token count to usage of GoogleAI and VertexAI
  src/libs/model-runtime/utils/streams/google-ai.test.ts
  src/libs/model-runtime/utils/streams/google-ai.ts
  src/libs/model-runtime/utils/streams/vertex-ai.ts
Labels: size:M

#8439 💄 style: Fix win electron style
  apps/desktop/build/icon-beta.ico
  apps/desktop/build/icon-dev.ico
  apps/desktop/build/icon-nightly.ico
  apps/desktop/build/icon.ico
  apps/desktop/electron.vite.config.ts
  apps/desktop/package.json
  apps/desktop/src/main/appBrowsers.ts
  apps/desktop/src/main/const/env.ts
  apps/desktop/src/main/const/store.ts
  apps/desktop/src/main/const/theme.ts
  apps/desktop/src/main/controllers/NotificationCtr.ts
  apps/desktop/src/main/controllers/SystemCtr.ts
  apps/desktop/src/main/controllers/index.ts
  apps/desktop/src/main/core/App.ts
  apps/desktop/src/main/core/browser/Browser.ts
  apps/desktop/src/main/core/browser/BrowserManager.ts
  apps/desktop/src/main/core/infrastructure/I18nManager.ts
  apps/desktop/src/main/core/infrastructure/IoCContainer.ts
  apps/desktop/src/main/core/infrastructure/StaticFileServerManager.ts
  apps/desktop/src/main/core/infrastructure/StoreManager.ts
  apps/desktop/src/main/core/infrastructure/UpdaterManager.ts
  apps/desktop/src/main/core/ui/MenuManager.ts
  apps/desktop/src/main/core/ui/ShortcutManager.ts
  apps/desktop/src/main/core/ui/Tray.ts
  apps/desktop/src/main/core/ui/TrayManager.ts
  apps/desktop/src/main/types/store.ts
  src/app/[variants]/(main)/chat/(workspace)/features/AgentSettings/index.tsx
  src/features/ElectronTitlebar/WinControl/index.tsx
  src/features/ElectronTitlebar/hooks/useWatchThemeUpdate.ts
  src/features/PluginDevModal/index.tsx
Labels: 💄 Design, size:XL, Build Desktop

#8443 💄 style: fix sub topic width in md responsive
  src/app/[variants]/(main)/chat/(workspace)/_layout/Desktop/Portal.tsx
Labels: 🐛 Bug, size:XS

#8572 🐛 fix: fix update hotkey invalid when input mod in desktop
  apps/desktop/src/main/core/ui/ShortcutManager.ts
  apps/desktop/src/main/core/ui/__tests__/ShortcutManager.test.ts
Labels: 🐛 Bug, size:XL, Build Desktop

#8576 🔨 chore: add react scan debugger and bump deps
  package.json
  src/app/[variants]/layout.tsx
  src/layout/GlobalProvider/ReactScan.tsx
  src/layout/GlobalProvider/index.tsx
Labels: size:S

#8539 💄 style: Add Gemini 2.5 Flash-Lite GA model
  src/config/aiModels/google.ts
  src/config/aiModels/vertexai.ts
Labels: size:M

#8585 💄 style: fix setting window layout when in desktop was disappear
  src/app/[variants]/(main)/settings/_layout/Desktop/index.tsx
Labels: 💄 Design, size:XS

#8535 ✨ feat: Implement API Key management functionality
  src/app/[variants]/(main)/profile/apikey/Client.tsx
  src/app/[variants]/(main)/profile/apikey/features/ApiKeyDatePicker/index.tsx
  src/app/[variants]/(main)/profile/apikey/features/ApiKeyDisplay/index.tsx
  src/app/[variants]/(main)/profile/apikey/features/ApiKeyModal/index.tsx
  src/app/[variants]/(main)/profile/apikey/features/EditableCell/index.tsx
  src/app/[variants]/(main)/profile/apikey/features/index.ts
  src/app/[variants]/(main)/profile/apikey/page.tsx
  src/app/[variants]/(main)/profile/hooks/useCategory.tsx
  src/config/featureFlags/schema.ts
  src/database/migrations/0029_add_apikey_manage.sql
  src/database/migrations/meta/0029_snapshot.json
  src/database/migrations/meta/_journal.json
  src/database/models/apiKey.ts
  src/database/schemas/apiKey.ts
  src/database/schemas/index.ts
  src/database/schemas/rbac.ts
  src/locales/default/auth.ts
  src/server/routers/lambda/apiKey.ts
  src/server/routers/lambda/index.ts
  src/store/global/initialState.ts
  src/store/serverConfig/selectors.test.ts
  src/types/apiKey.ts
  src/utils/apiKey.ts
Labels: 🌠 Feature Request, size:XXL

#8574 💄 style: support more Text2Image from Qwen
  src/config/aiModels/qwen.ts
  src/libs/model-runtime/qwen/createImage.ts
Labels: 💄 Design, size:L

#8595 ♻️ refactor: refactor jose-JWT to xor obfuscation
  package.json
  src/app/(backend)/middleware/auth/index.test.ts
  src/app/(backend)/middleware/auth/index.ts
  src/app/(backend)/webapi/chat/[provider]/route.test.ts
  src/app/(backend)/webapi/plugin/gateway/route.ts
  src/const/auth.ts
  src/libs/model-runtime/ModelRuntime.test.ts
  src/libs/trpc/async/context.ts
  src/libs/trpc/edge/context.ts
  src/libs/trpc/edge/middleware/jwtPayload.test.ts
  src/libs/trpc/edge/middleware/jwtPayload.ts
  src/libs/trpc/lambda/context.ts
  src/libs/trpc/lambda/middleware/keyVaults.ts
  src/server/modules/AgentRuntime/index.test.ts
  src/server/modules/AgentRuntime/index.ts
  src/server/routers/async/caller.ts
  src/server/routers/tools/search.test.ts
  src/server/services/chunk/index.ts
  src/services/_auth.ts
  src/utils/client/xor-obfuscation.test.ts
  src/utils/client/xor-obfuscation.ts
  src/utils/jwt.test.ts
  src/utils/jwt.ts
  src/utils/server/jwt.test.ts
  src/utils/server/jwt.ts
  src/utils/server/xor.test.ts
  src/utils/server/xor.ts
Labels: size:XL

#8573 💄 style: add more OpenAI SDK Text2Image providers
  src/config/aiModels/giteeai.ts
  src/config/aiModels/siliconcloud.ts
  src/config/aiModels/stepfun.ts
  src/config/aiModels/volcengine.ts
  src/config/aiModels/wenxin.ts
  src/config/aiModels/xai.ts
Labels: 🌠 Feature Request, size:XL

#8600 ♻️ refactor: reorder AppTheme and Locale components in GlobalLayout
  src/layout/GlobalProvider/index.tsx
Labels: size:S

#8426 💄 style: Open new topic by tap Just Chat again
  src/app/[variants]/(main)/chat/@session/features/SessionListContent/Inbox/index.tsx
  src/store/chat/slices/message/selectors.ts
Labels: 💄 Design, size:S

#8605 style: none login user access ai image page error
  src/app/[variants]/(main)/image/@topic/features/Topics/TopicList.tsx
  src/app/[variants]/(main)/image/features/PromptInput/index.tsx
  src/hooks/useFetchGenerationTopics.ts
  src/store/image/slices/generationTopic/action.test.ts
  src/store/image/slices/generationTopic/action.ts
Labels: 🐛 Bug, size:M

#8419 🐛 fix: moonshot assistant messages must not be empty
  src/config/aiModels/google.ts
  src/config/aiModels/groq.ts
  src/config/aiModels/hunyuan.ts
  src/config/aiModels/moonshot.ts
  src/config/aiModels/qwen.ts
  src/config/aiModels/siliconcloud.ts
  src/config/aiModels/stepfun.ts
  src/config/modelProviders/moonshot.ts
  src/libs/model-runtime/moonshot/index.ts
Labels: 🐛 Bug, size:L

#8615 🐛 fix: fix mcp calling missing array content
  apps/desktop/src/preload/routeInterceptor.ts
  src/server/services/mcp/index.test.ts
  src/server/services/mcp/index.ts
Labels: 🐛 Bug, size:L

#8619 💄 style: improve mcp plugin calling and display
  src/features/Conversation/Messages/Assistant/Tool/Inspector/BuiltinPluginTitle.tsx
  src/features/Conversation/Messages/Assistant/Tool/Inspector/PluginResultJSON.tsx
  src/features/Conversation/Messages/Assistant/Tool/Inspector/ToolTitle.tsx
  src/features/Conversation/Messages/Assistant/Tool/Inspector/index.tsx
  src/features/Conversation/Messages/Assistant/Tool/Render/Arguments/index.tsx
  src/features/Conversation/Messages/Assistant/Tool/Render/CustomRender.tsx
  src/features/Conversation/Messages/Assistant/Tool/index.tsx
  src/features/Conversation/Messages/Assistant/index.tsx
  src/features/Conversation/components/VirtualizedList/index.tsx
  src/store/chat/slices/aiChat/actions/generateAIChat.ts
  src/store/chat/slices/aiChat/initialState.ts
  src/store/chat/slices/message/selectors.ts
  src/store/chat/slices/plugin/action.ts
Labels: ⚡️ Performance, 💄 Design, size:L

#8620 🐛 fix: fix oidc oauth callback page 404
  src/app/[variants]/oauth/callback/layout.tsx
Labels: 🐛 Bug, size:S

#8612 💄 style: update Aliyun Bailian models
  src/config/aiModels/qwen.ts
  src/config/aiModels/siliconcloud.ts
  src/features/ChatInput/ActionBar/Model/ControlsForm.tsx
  src/libs/model-runtime/qwen/index.ts
  src/services/chat.ts
Labels: 💄 Design, size:L

#8569 💄 style: Support SenseNova V6.5 models
  src/config/aiModels/sensenova.ts
  src/libs/model-runtime/sensenova/index.ts
Labels: size:M
