Repository lobehub/lobe-chat, pull requests merged in 2025-06, with the labels that each got.

#7639 🔨 chore(setup.sh): Replace SED_COMMAND with SED_INPLACE_ARGS for improved compatibility across platforms on macOS
  docker-compose/setup.sh
Labels: size:M

#7719 💄 style: use default deployment name when parseModelString doesn't contain deployment name
  docs/self-hosting/advanced/model-list.mdx
  docs/self-hosting/advanced/model-list.zh-CN.mdx
  docs/self-hosting/environment-variables/model-provider.mdx
  docs/self-hosting/environment-variables/model-provider.zh-CN.mdx
  src/utils/parseModels.test.ts
  src/utils/parseModels.ts
Labels: size:M

#7980 💄 style: support `web_search` tool for MiniMax & Zhipu
  src/config/aiModels/minimax.ts
  src/config/aiModels/openai.ts
  src/libs/model-runtime/minimax/index.ts
  src/libs/model-runtime/openai/index.ts
  src/libs/model-runtime/utils/streams/openai.ts
  src/libs/model-runtime/zhipu/index.ts
Labels: 💄 Design, size:L

#8047 📝 docs: add some more cursor rules
  .cursor/rules/backend-architecture.mdc
  .cursor/rules/cursor-ux-optimize.mdc
  .cursor/rules/define-database-model.mdc
  .cursor/rules/drizzle-schema-style-guide.mdc
  .cursor/rules/i18n/i18n.mdc
  .cursor/rules/project-introduce.mdc
  .cursor/rules/system-role.mdc
  .cursor/rules/zustand-action-patterns.mdc
  .cursor/rules/zustand-slice-organization.mdc
Labels: 📝 Documentation, size:XL

#8044 🐛 fix: Update the clerk to enable or disable route protection based on configuration
  src/middleware.ts
Labels: 🐛 Bug, size:XS

#8041 📝 docs: update Qwen model provider in documentation
  docs/self-hosting/advanced/model-list.mdx
  docs/self-hosting/advanced/model-list.zh-CN.mdx
  docs/self-hosting/environment-variables/model-provider.mdx
  docs/self-hosting/environment-variables/model-provider.zh-CN.mdx
Labels: 📝 Documentation, size:S

#8055 🐛 fix (migration): Remove abandoned `reasoning_effort` & `doubao`
  src/database/client/migrations.json
  src/database/migrations/0023_remove_param_and_doubao.sql
  src/database/migrations/meta/0023_snapshot.json
  src/database/migrations/meta/_journal.json
Labels: size:S

#8033 ✨ feat: add more provider support for search & crawl
  packages/web-crawler/src/crawImpl/exa.ts
  packages/web-crawler/src/crawImpl/firecrawl.ts
  packages/web-crawler/src/crawImpl/index.ts
  packages/web-crawler/src/crawImpl/tavily.ts
  src/server/services/search/impls/bocha/index.ts
  src/server/services/search/impls/bocha/type.ts
  src/server/services/search/impls/exa/index.ts
  src/server/services/search/impls/exa/type.ts
  src/server/services/search/impls/firecrawl/index.ts
  src/server/services/search/impls/firecrawl/type.ts
  src/server/services/search/impls/index.ts
  src/server/services/search/impls/jina/index.ts
  src/server/services/search/impls/jina/type.ts
  src/server/services/search/impls/tavily/index.ts
  src/server/services/search/impls/tavily/type.ts
Labels: 🌠 Feature Request, size:XXL

#8072 💄 style: improve loading state
  src/features/ChatInput/ActionBar/Model/ControlsForm.tsx
  src/features/ChatInput/ActionBar/Model/index.tsx
  src/features/ChatInput/ActionBar/Search/Controls.tsx
  src/features/ChatInput/ActionBar/Search/FCSearchModel.tsx
  src/features/ChatInput/ActionBar/Search/index.tsx
  src/features/ModelSwitchPanel/index.tsx
  src/middleware.ts
Labels: 💄 Design, size:M

#8064 💄 style: Add Volcengine & OpenAI-like Provider (e.g. oneapi) model fetch support
  src/libs/model-runtime/google/index.ts
  src/libs/model-runtime/novita/__snapshots__/index.test.ts.snap
  src/libs/model-runtime/novita/index.ts
  src/libs/model-runtime/nvidia/index.ts
  src/libs/model-runtime/openai/__snapshots__/index.test.ts.snap
  src/libs/model-runtime/openai/index.ts
  src/libs/model-runtime/openrouter/__snapshots__/index.test.ts.snap
  src/libs/model-runtime/openrouter/index.ts
  src/libs/model-runtime/qwen/index.ts
  src/libs/model-runtime/siliconcloud/index.ts
  src/libs/model-runtime/utils/modelParse.test.ts
  src/libs/model-runtime/utils/modelParse.ts
  src/libs/model-runtime/volcengine/index.ts
  src/libs/model-runtime/zeroone/index.ts
  src/libs/model-runtime/zhipu/index.ts
Labels: size:XXL

#8090 💄 style: Support Vertex AI thought summaries
  src/libs/model-runtime/utils/streams/vertex-ai.ts
Labels: 💄 Design, size:S

#8060 ✨ feat: support placeholder variables in prompt
  locales/ar/setting.json
  locales/bg-BG/setting.json
  locales/de-DE/setting.json
  locales/en-US/setting.json
  locales/es-ES/setting.json
  locales/fa-IR/setting.json
  locales/fr-FR/setting.json
  locales/it-IT/setting.json
  locales/ja-JP/setting.json
  locales/ko-KR/setting.json
  locales/nl-NL/setting.json
  locales/pl-PL/setting.json
  locales/pt-BR/setting.json
  locales/ru-RU/setting.json
  locales/tr-TR/setting.json
  locales/vi-VN/setting.json
  locales/zh-CN/setting.json
  locales/zh-TW/setting.json
  src/locales/default/setting.ts
  src/services/chat.ts
  src/store/chat/slices/aiChat/actions/generateAIChat.ts
  src/store/user/slices/auth/selectors.test.ts
  src/store/user/slices/auth/selectors.ts
  src/utils/client/parserPlaceholder.test.ts
  src/utils/client/parserPlaceholder.ts
Labels: 🌠 Feature Request, size:XL

#8083 💄 style: Update Gemini & Qwen models
  src/config/aiModels/google.ts
  src/config/aiModels/hunyuan.ts
  src/config/aiModels/novita.ts
  src/config/aiModels/openrouter.ts
  src/config/aiModels/qwen.ts
  src/config/aiModels/siliconcloud.ts
Labels: size:L

#8100 💄 style: improve `{{username}}` placeholder variable
  src/store/user/slices/auth/selectors.test.ts
  src/store/user/slices/auth/selectors.ts
  src/utils/client/parserPlaceholder.test.ts
  src/utils/client/parserPlaceholder.ts
Labels: 💄 Design, size:L

#7960 💄 style(ModelSelect): add responsive layout for mobile devices
  src/components/ModelSelect/index.tsx
Labels: 💄 Design, 📱 Mobile Device, size:XS

#8101 👷 build: init rbac system table scheme and data structure
  src/database/migrations/0024_add_rbac_tables.sql
  src/database/migrations/meta/0024_snapshot.json
  src/database/migrations/meta/_journal.json
  src/database/schemas/index.ts
  src/database/schemas/rbac.ts
Labels: 🌠 Feature Request, size:L

#8075 💄 style: add support to azure openai embedding model
  src/libs/model-runtime/azureOpenai/index.ts
Labels: 🌠 Feature Request, azure, size:M

#8009 🐛 fix: fix client s3 getObject throw error
  src/services/file/ClientS3/index.test.ts
  src/services/file/ClientS3/index.ts
Labels: size:S

#8087 💄 style: Support OpenRouter Claude 4 reasoning
  src/config/aiModels/openrouter.ts
  src/libs/model-runtime/openrouter/index.ts
Labels: 💄 Design, size:L

#8124 🐛 fix: fix openai default Responses API issue
  src/services/__tests__/chat.test.ts
  src/store/aiInfra/slices/aiProvider/selectors.ts
Labels: 🐛 Bug, size:XS

#8121 ♻️ refactor: refactor `<think>` & `</think>` handling
  src/libs/model-runtime/perplexity/index.test.ts
  src/libs/model-runtime/utils/streams/ollama.test.ts
  src/libs/model-runtime/utils/streams/ollama.ts
  src/libs/model-runtime/utils/streams/openai/openai.test.ts
  src/libs/model-runtime/utils/streams/openai/openai.ts
  src/libs/model-runtime/utils/streams/protocol.ts
Labels: ollama, size:L

#8134 ♻️ refactor: refactor branding info
  src/app/[variants]/(main)/changelog/features/Hero.tsx
  src/app/[variants]/(main)/settings/about/index.tsx
  src/const/branding.ts
  src/const/guide.ts
  src/const/url.ts
  src/features/Follow/index.tsx
  src/features/User/UserPanel/useMenu.tsx
  src/server/ld.ts
Labels: size:M

#8074 ✨ feat: support google sso as auth provider
  docs/self-hosting/advanced/auth.mdx
  docs/self-hosting/advanced/auth/next-auth/google.mdx
  src/components/NextAuth/AuthIcons.tsx
  src/libs/next-auth/sso-providers/google.ts
  src/libs/next-auth/sso-providers/index.ts
Labels: 🌠 Feature Request, size:L

#8119 💄 style: update pplx abilities tags, support `vision`
  src/config/aiModels/perplexity.ts
Labels: 💄 Design, size:XS

#8122 🐛 fix: Update Gemini range of thinkingBudget
  src/libs/model-runtime/google/index.ts
Labels: Gemini, size:S

#7981 💄 style: Transition animation switch
  locales/ar/setting.json
  locales/bg-BG/setting.json
  locales/de-DE/setting.json
  locales/en-US/setting.json
  locales/es-ES/setting.json
  locales/fa-IR/setting.json
  locales/fr-FR/setting.json
  locales/it-IT/setting.json
  locales/ja-JP/setting.json
  locales/ko-KR/setting.json
  locales/nl-NL/setting.json
  locales/pl-PL/setting.json
  locales/pt-BR/setting.json
  locales/ru-RU/setting.json
  locales/tr-TR/setting.json
  locales/vi-VN/setting.json
  locales/zh-CN/setting.json
  locales/zh-TW/setting.json
  src/app/[variants]/(main)/settings/common/features/ChatAppearance/ChatTransitionPreview.tsx
  src/app/[variants]/(main)/settings/common/features/ChatAppearance/index.tsx
  src/components/Thinking/index.tsx
  src/config/modelProviders/anthropic.ts
  src/config/modelProviders/baichuan.ts
  src/config/modelProviders/google.ts
  src/config/modelProviders/lmstudio.ts
  src/config/modelProviders/minimax.ts
  src/config/modelProviders/moonshot.ts
  src/config/modelProviders/openai.ts
  src/config/modelProviders/perplexity.ts
  src/config/modelProviders/qwen.ts
  src/config/modelProviders/search1api.ts
  src/config/modelProviders/spark.ts
  src/config/modelProviders/stepfun.ts
  src/config/modelProviders/vertexai.ts
  src/config/modelProviders/volcengine.ts
  src/config/modelProviders/wenxin.ts
  src/const/settings/common.ts
  src/features/Conversation/Messages/Assistant/Reasoning/index.tsx
  src/features/Conversation/components/ChatItem/index.tsx
  src/features/Conversation/components/MarkdownElements/LobeThinking/Render.tsx
  src/features/Conversation/components/MarkdownElements/Thinking/Render.tsx
  src/locales/default/setting.ts
  src/services/chat.ts
  src/store/user/slices/settings/selectors/general.test.ts
  src/store/user/slices/settings/selectors/general.ts
  src/types/aiProvider.ts
  src/types/llm.ts
  src/types/user/settings/general.ts
  src/utils/fetch/__tests__/fetchSSE.test.ts
  src/utils/fetch/fetchSSE.ts
Labels: 🌠 Feature Request, size:L

#8153 🔧 chore: improve i18n workflow diff script
  package.json
  scripts/i18nWorkflow/genDefaultLocale.ts
  scripts/i18nWorkflow/genDiff.ts
  scripts/i18nWorkflow/utils.ts
Labels: size:M

#8160 🐛 fix(chat): Improve response animation merging logic
  src/services/chat.ts
Labels: size:S

#8131 💄 style: support `web_search_preview` & fix some bug form OpenAI Response API
  src/config/aiModels/openai.ts
  src/const/models.ts
  src/libs/model-runtime/openai/index.ts
  src/libs/model-runtime/types/chat.ts
  src/libs/model-runtime/utils/openaiCompatibleFactory/index.ts
  src/libs/model-runtime/utils/streams/openai/__snapshots__/responsesStream.test.ts.snap
  src/libs/model-runtime/utils/streams/openai/responsesStream.ts
Labels: 💄 Design, size:L

#8180 🐛 fix: Correctly handle `reasoning_effort`
  src/store/chat/slices/aiChat/actions/generateAIChat.ts
Labels: size:XS

#8133 🐛 fix: improve chat selectors and enhance topic handling logic
  src/store/chat/slices/aiChat/actions/generateAIChat.ts
  src/store/chat/slices/message/selectors.ts
Labels: size:S

#8199 🔨 chore(ci): improve i18n workflow
  .github/workflows/auto-i18n.yml
Labels: size:L

#8200 🔨 chore(ci): improve i18n workflow (#8199)
  .github/workflows/auto-i18n.yml
  locales/ar/models.json
  locales/bg-BG/models.json
  locales/de-DE/models.json
  locales/en-US/models.json
  locales/es-ES/models.json
  locales/fa-IR/models.json
  locales/fr-FR/models.json
  locales/it-IT/models.json
  locales/ja-JP/models.json
  locales/ko-KR/models.json
  locales/nl-NL/models.json
  locales/pl-PL/models.json
  locales/pt-BR/models.json
  locales/ru-RU/models.json
  locales/tr-TR/models.json
  locales/vi-VN/models.json
  locales/zh-CN/models.json
  locales/zh-TW/models.json
Labels: size:XL

#8212 📝 docs: improve README.md
  README.md
Labels: 📝 Documentation, size:XS

#8209 💄 style: Add MiniMax-M1 model
  src/config/aiModels/minimax.ts
  src/config/aiModels/novita.ts
  src/config/aiModels/siliconcloud.ts
Labels: size:M

#8213 💄 style: Add Gemini 2.5 Pro, Flash GA models and 2.5 Flash-Lite Preview
  src/config/aiModels/google.ts
  src/config/aiModels/vertexai.ts
Labels: Gemini, size:L

#8228 🔨 chore: improve dev speed
  src/app/[variants]/layout.tsx
Labels: size:XS

#8221 🐛 fix: Correctly pass `reasoning.summary`
  src/config/aiModels/google.ts
  src/config/aiModels/groq.ts
  src/config/aiModels/xai.ts
  src/libs/model-runtime/openai/index.ts
  src/libs/model-runtime/utils/openaiCompatibleFactory/index.ts
Labels: size:M

#8172 ✨ feat: add Brave & Google PSE & Kagi as build-in Search Provider
  docs/self-hosting/advanced/online-search.mdx
  docs/self-hosting/advanced/online-search.zh-CN.mdx
  src/server/services/search/impls/anspire/index.ts
  src/server/services/search/impls/anspire/type.ts
  src/server/services/search/impls/brave/index.ts
  src/server/services/search/impls/brave/type.ts
  src/server/services/search/impls/google/index.ts
  src/server/services/search/impls/google/type.ts
  src/server/services/search/impls/index.ts
  src/server/services/search/impls/kagi/index.ts
  src/server/services/search/impls/kagi/type.ts
Labels: 🌠 Feature Request, size:XL

#8235 ✨ feat: add v0 (Vercel) provider support
  Dockerfile
  Dockerfile.database
  Dockerfile.pglite
  src/app/[variants]/(main)/settings/llm/ProviderList/providers.tsx
  src/config/aiModels/index.ts
  src/config/aiModels/v0.ts
  src/config/llm.ts
  src/config/modelProviders/index.ts
  src/config/modelProviders/v0.ts
  src/libs/model-runtime/runtimeMap.ts
  src/libs/model-runtime/types/type.ts
  src/libs/model-runtime/utils/modelParse.ts
  src/libs/model-runtime/v0/index.ts
  src/types/user/settings/keyVaults.ts
Labels: 🌠 Feature Request, Model Provider, size:L

#8240 💄 style: fix `MiniMax-M1` reasoning tag missing
  src/config/aiModels/minimax.ts
Labels: 💄 Design, size:M

#8248 📝 docs: add Vercel OSS Program Badge
  README.md
Labels: 📝 Documentation, size:XS

#8224 💄 style: Optimized Gemini thinkingBudget configuration
  src/config/aiModels/google.ts
  src/features/ChatInput/ActionBar/Model/ControlsForm.tsx
  src/features/ChatInput/ActionBar/Model/ThinkingBudgetSlider.tsx
  src/libs/model-runtime/google/index.ts
  src/libs/model-runtime/types/chat.ts
  src/services/chat.ts
  src/types/agent/chatConfig.ts
  src/types/aiModel.ts
Labels: Gemini, size:L

#8280 🐛 fix: fix desktop chunk issue
  src/app/[variants]/layout.tsx
  src/server/routers/async/caller.ts
  src/server/routers/async/index.ts
  src/server/routers/lambda/ragEval.ts
  src/server/services/chunk/index.ts
Labels: 🐛 Bug, size:L

#8270 🐛 fix(mermaid): firefox mermaid show error
  package.json
Labels: 🐛 Bug, size:XS

#8303 🐛 fix: pin `antd@5.26.2` to fix build error
  package.json
Labels: size:XS
